// Mocks generated by Mockito 5.4.6 from annotations
// in ieca_mobile/test/widget/screens/page_screen.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:ieca_mobile/object_box.dart' as _i3;
import 'package:ieca_mobile/objectbox.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStore_0 extends _i1.SmartFake implements _i2.Store {
  _FakeStore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ObjectBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectBox extends _i1.Mock implements _i3.ObjectBox {
  MockObjectBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Store get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _FakeStore_0(this, Invocation.getter(#store)),
          )
          as _i2.Store);

  @override
  set store(_i2.Store? _store) => super.noSuchMethod(
    Invocation.setter(#store, _store),
    returnValueForMissingStub: null,
  );
}
