import 'package:ieca_mobile/enums/hymns_content_code.dart';
import 'package:ieca_mobile/models/_import.dart';
import 'package:ieca_mobile/seeders/_import.dart';

class UmHymnsOkulikutilila {
  static List<HymnsContent> list = [
    HymnsContent(id: 2356, position: 1, content: "A Suku yange, enju, ndo tumãle. \nVonjo yutima nunga etambo liove \nNdi ku fendela, ndi likutilila. \nA Suku yange, kala lame hu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_178, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2357, position: 2, content: "Njimbe onumbi yocipango cove. \nÑuame lesanju oku o songuila \nSi lingi vali evi via tatama. \nA Suku yange, ndo songuile hu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_178, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2358, position: 3, content: "Ñape owuya wocisola cove. \nNjupe owesi lokalendewuya. \nÑuate kesunga loku sokolola \nEvi viocili haivio ka vi pui.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_178, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2359, position: 4, content: "Nyihe ombembua yove ya supoka. \nYi lue vutima ndono ka yi takata. \nNava kokuove cosi o mangela, \nA Suku yange, ci lingiwe ño.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_178, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2360, position: 1, content: "Kokuove tu likutilila, a Suku; \nNda lika wetu ka tu tela cimue. \nPuãi nda ocinyi cove ci tu songuila, \nOco tu amako ciwa lekolelo.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_179, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2361, position: 2, content: "Eci tu sakalala levi via puiya, \nPamue ongusu yetu yosi ya pua, \nUnene wove wiye, u tu kuatise, \nLohenda yove yi tu vindikiye.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_179, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2362, position: 3, content: "Ove ukuaku muisa evi viomuenyo, \nTekula lavio ovitima vietu. \nTu ikise evi vi tu longa olongunge \nVioku tu kunamisa kuwa wove.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_179, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2363, position: 4, content: "Ove angunja yovitima viomanu, \nWaya ohenda vovitima vietu; \nKulamo vali ekolelo lesunga, \nHa tu lombola noke lonjolela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_179, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2364, position: 1, content: "A Suku Usovoli, \nA Suku Ucikolo, \nComanu vosi vana \nVa kuete ekolelo; \nCina kua lulikile \nOngongo lokalunga, \nOve o kasi ale, \nKu suli, wenda hu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_180, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2365, position: 2, content: "Etu tumanu vaño; \nTua soka ño ndowangu. \nKomele u yova ciwa. \nPuãi noke u keluiwa; \nHaico oloneke vietu \nVi pita ndolonjoi.\nTu muise olondunge; \nTu ku limbuke ocili.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_180, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2366, position: 3, content: "A Suku, akandu etu \nNdaño ovoyombeki, \nA limbukiwa love, \nA tu kokela ohali. \nTu lomba ohenda yove. \nA Suku, tu popele. \nKuatisa omanu vove; \nKa va ka linyelise.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_180, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2367, position: 1, content: "Ku ka mitahãle, a Yesu, \nNdo njevelele. \nVakuetu wa va kovonga; \nNdo ñovonge ame.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_181, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2368, content: "A Yesu, a Yesu, \nNdo njevelele. \nVakuetu wa va kovonga; \nNdo ñovonge ame.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_181, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2369, position: 2, content: "Ku ka mitahãle, a Yesu, \nNdo muise eyovo. \nNdo ngecele akandu ange, \nNdo mopele ame.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_181, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2370, position: 3, content: "Ku ka mitahãle, a Yesu, \nKu ka mukule. \nKayisa utima wange, \nNdo sakule ame.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_181, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2371, position: 1, content: "A Yesu, ndimeke; \nNdo songuile. \nUtanya u soka nduteke; \nTe nda ove o ngendisa. \nNdo songuile. \nA Yesu, ndimeke.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_182, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2372, position: 2, content: "A Yesu, nda huka; \nOve o minda. \nKondaka yove njevako, \nNdimeme, Ove Ungombo. \nOve o minda, \nA Yesu, nda huka.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_182, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2373, position: 3, content: "A Yesu, ndisuke; \nNda sekuka. \nNdo numbuluile lohenda \nOvina akandu a nyolela. \nNda sekuka, \nA Yesu, ndimeke.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_182, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2374, position: 4, content: "A Yesu, hũ sole; \nNdo ñuatise. \nUpeke, ahuku lusuke \nKa vi ka nepe kokuove. \nNdo ñuatise \nA Yesu, hũ sole.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_182, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2375, position: 1, content: "Nda limbuka esanju, a Ñala, \nOve o muisa ocali. \nUkuesanju lia kanguka, \nNdo sanjuise, lame le. \nLame le. Lame le. \nNdo sanjuise, lame le.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_183, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2376, position: 2, content: "Ku ka njanduluke,a Tate, \nNdukuakandu ocili. \nSi siluila ocali cove, \nNdinge ohenda, lame le. \nLame le. Lame le. \nNdinge ohenda, lame le.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_183, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2377, position: 3, content: "Ku ka mitahãle, a Yesu, \nHu kolela.Hu sole. \nNda livela eyovo liove, \nNdo njovole,lame le. \nLame le. Lame le. \nNdo njovole, lame le.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_183, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2378, position: 4, content: "Ku ka siepo,a Spiritu, \nOmo ñasi lupeke. \nOve muele Uyelisi. \nNdo njelise, lame le. \nLame le. Lame le. \nNdo njelise, lame le.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_183, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2379, position: 1, content: "Popia lutima wange, \nA Ñala, lohenda. \nPopia locali, huti, \nKu kasi ulika. \nSituluile kutima; \nNjeve ondaka yove, \nOco ndi ku sivaya \nLutima wange wosi.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_184, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2380, content: "Popia loku loñola \nKutima levando: \n«Nda ku pesila osonde \nOku ku yovola» \nPopia oloneke viosi, \nPopia locisola; \nLoku loñola vetui: \n«Okuete Upopeli»!", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_184, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2381, position: 2, content: "Popia loku loñola, \nLocisola huti. \nOve o yula ayonjo, \nNda o ñolela ame. \nPopia oloneke viosi, \nA Ñala lohenda; \nSi yevi ondaka yiti, \nKu kasi ulika.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_184, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2382, position: 3, content: "Popia komãla vove, \nLoku va songuila; \nLoku va longisavo, \nOku lomba kokuove. \nLoku eca ongusu yavo \nKupange wove u kola, \nTe eteke Ñala yetu \nO keya lulamba.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_184, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2383, position: 1, content: "Ndimeke, a Suku, nda loña \nVonjila ya sanjavala. \nOvaka vove va niule; \nVa songuile.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_185, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2384, position: 2, content: "Ndaño nda linga via senga, \nNda putua tupu kutima, \nOvaka vove va fina \nVa songuile.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_185, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2385, position: 3, content: "Ndaño nda ambata ca lela, \nNdaño nda ambata ci lema, \nOvaka vove va pama \nVa songuile.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_185, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2386, position: 4, content: "Ndaño nda sanga epese, \nNdaño nda suka epako, \nOvaka vove vohenda \nVa songuile.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_185, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2387, position: 5, content: "Nda nyehua ca lua ndaño fa, \nMitila kilu kulamba, \nOvaka vove a Suku \nVa songuile.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_185, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2388, position: 1, content: "Anjovoli ndo songuile, \nSanga ha nyelela ño. \nNdo songuile locisola; \nOve lika hũ kolela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_186, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2389, content: "A Yesu, a Ñala, \nNdo songuile locisola. \nSituluile onjila yove. \nSi endelamo lekolelo.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_186, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2390, position: 2, content: "Ndaño nãla olohali \nOve Ulolo, Upopeli \nNdi ku kuama, si yokoka, \nMomo ove ombetatela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_186, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2391, position: 3, content: "Nda kesanju, nda kesumuo, \nNgamamako ohele mbu, \nToke nyiñila kesanju \nLina li tumãla hũ.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_186, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2392, position: 1, content: "Mbindulule, a Yesu, \nNjimba ovaso kokuove. \nVokalunga kohali, \nNdi tapula lepandi. \nOwato wange ekolelo. \nMbindule, a Yesu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_187, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2393, position: 2, content: "Kovakimba ayonjo, \nMuise ongusu a Yesu. \nMomo nda ku ñuatisa, \nMbomba ndeci Petulu. \nTulumula akimba; \nOco nule utima.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_187, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2394, position: 3, content: "Kulo eci nundako, \nEci nula omuenyo. \nEci mbanja lusumba, \nOlui luna luokufa. \nNdo sapuile, a Yesu, huti, \nAmilo, hũ pitiya.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_187, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2395, position: 1, content: "Ola yoku lombela,  \nNda tu liongolola,\nLukukui wutima,  \nYesu o tu yeva. \nHaeye o tu songuila  \nHa tu lombi lika \nEvi via tu kambela,  \nSuku ha tu vi iha.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_188, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2396, content: "Ola ya fina. Ola ya fina. \nYi vokiya ekolelo. \nYi lembavo utima.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_188, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2397, position: 2, content: "Ola yoku lombela,  \nYesu o kokela, \nLesanju kutima  \nHa yevelela. \nNda tua yandulukiwa \nLoku suvalisua, \nEye o tu lembeleka  \nKuenda o tu teyuila.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_188, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2398, position: 3, content: "Ola yoku lombela  \nCa tu posokela, \nOku sapuila Yesu  \nEvi tua kamba. \nCosi tu ci pingila  \nEye o tu ciha, \nNda co sungulukila  \nKuenje ci tu kuatisa.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_188, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2399, position: 4, content: "Ola yoku lombela  \nYi tu sumuluisa; \nNdaño upongo lohali  \nVi tu limbisa \nNdovihemba via fina  \nVi kuatisa etimba, \nHaico oku lombela  \nKu kuatisa utima.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_188, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2400, position: 1, content: "Owola yoku lombela \nNdi sole cimue yi mepa, \nYi njivalisa oluali \nLakandu aluo, lohele; \nYi mitilisa kopolo \nYa Suku yange yokilu; \nYi sõsã cimue ya piãla \nOwola yoku lombela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_189, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2401, position: 2, content: "Kowola yoku lombela \nTu lete omangu yohenda, \nYa nyiliwa losonde yu \nWa tu fila kakandu osi; \nLa kuosi, posi lo kilu \nKuli onembele ya Suku. \nKuenda Espiritu o tu iha \nKowola yoku lombela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_189, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2402, position: 3, content: "Owola yoku lombela \nYi tu londisa komunda. \nNda cina Mose a vanjele \nOfeka yina Kanana; \nEtimba ndula nduwalo, \nMalala toke kovailu, \nLosimbu ngenda manduila \nOwola yoku lombela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_189, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2403, position: 1, content: "Omuenyo wa Suku vutima \nU koka ekolelo liocili, \nLi tela oku yula oluali, \nOlio tu sanga kokua’e.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_190, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2404, content: "A Suku o kola, tu yevelele \nlohenda, \nTu muise onima yocili \nYovina ka vi pui.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_190, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2405, position: 2, content: "Omuenyo wa Suku vutima \nU koka elavoko lia fina; \nLi lete ofeka yokilu, \nOlio tu sanga kokua’e.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_190, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2406, position: 3, content: "Omuenyo wa Suku vutima \nU koka ocisola ca piãla; \nCi imula ohele lusumba, \nOco tu sanga kokua’e.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_190, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2407, position: 4, content: "Onima ya piãla ka yi pui \nYi kasi vomuenyo wa Suku. \nTu sandi lombili lepandi \nOvina viaye ka vi pui.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_190, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2408, position: 1, content: "Ndo songuile, a Yehova, \nEci mita kovakango \nNda pekengua, nyihe ongusu \nNdo nyimule olohele.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_191, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2409, content: "Ñuate peka, Ñuate peka,  \nOco ngende lekolelo.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_191, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2410, position: 2, content: "Ndo ndekise ono yina \nYeca ovava omuenyo ko pui. \nNdise a Suku, mana yove; \nYi tekule utima wange.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_191, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2411, position: 3, content: "Kuosi mita njimbe onumbi, \nSanga mambukila kuvi. \nNdo ndingile otevele, \nO neyuile kovanyali.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_191, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2412, position: 1, content: "Popia, a Cime, ukuenje o yeva; \nNdi tayilili ondaka. \nNjongola oku yi yeva; \nYi tukula, a Cime. \nÑasi loku lavoka \nEci ove o mbanguisa.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_192, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2413, position: 2, content: "Nukule londuko, a Cime, \nNdimbuke ondaka yove. \nPopia, oco njayuleko \nLohandokua ya piãla. \nKuosi o songuila, a Cime, \nHaiko ame njilila.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_192, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2414, position: 3, content: "Situluile ciwa ondaka; \nSi ka tunde lahuku. \nPopia a Cime, momo o ci \nÑasi longeva love. \nVutima nda sukila \nSumuluise, a Cime.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_192, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2415, position: 4, content: "Popia, a Cime, ndo ñuatise, \nOco hu lamelele, \nLoku pokola kondaka \nYosi o handeleka. \nNdo njevise, a Cime, \nCosi o vangula lame.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_192, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2416, position: 1, content: "Tu songuile, a Suku, a tate; \nLika lietu tu nyelela. \nOve muele ukuonene, \nOñuatisi yiñi sio. \nNda o kasi kumue letu \nTu amamako, ohele mbu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_193, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2417, position: 2, content: "Anjovoli, ndo tu ecele \nOlukonyo luetu luosi. \nOmo wa kala voluali \nWa kuliha ayonjo etu, \nOvopongo lovasumuo \nWa molavo evalo liaco.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_193, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2418, position: 3, content: "A Spiritu tu pasule; \nEnju vovitima vietu; \nMu tumãle ongusu yove \nHa tu yuli ayonjo osi. \nTu yulise kuevi viosi \nVi tu tepulula ombembua.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_193, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2419, position: 1, content: "A Suku, tu nolele omanu \nVa sia iholo via tatama, \nVa tuwa lika esunguluko \nKovisimilo lovilinga.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_194, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2420, position: 2, content: "A Suku, nola va pua evelo, \nVa eca ongangu ya posoka, \nOco tu pame kesunga liove \nKuenda oku kuata olondunge.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_194, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2421, position: 3, content: "A Suku, nola vakuacili. \nVa kuete epandi locisola, \nVa sunguluka, vakuesumbilo, \nVa imba uvangi wevi viwa.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_194, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2422, position: 4, content: "A Suku, nola vakuotõi, \nVa tamalãlã levi vivi. \nOvo omanu tu va sukila \nPokati kolofeka viosi.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_194, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2423, position: 1, content: "Owola kowola \nNda sukila Yesu, \nEye ukuahenda, \nO nyiha ongusu", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_195, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2424, content: "Yesu ame ndo sukila, \nKo kuahe ndeyilila. \nO sumuluisa ndopo, \nNdo sukila.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_195, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2425, position: 2, content: "Owola kowola \nÑala kolomati, \nAyonjo ka a nela, \nNdo ñale ocituke.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_195, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2426, position: 3, content: "Owola kowola \nNdo ndongise ame, \nOco ndi telise \nOlohuminyo via’e.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_195, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2427, position: 4, content: "Owola kowola \nO ndingisa omolahe, \nEye ongusu yange, \nEye ombindikiyo.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_195, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2428, position: 1, content: "A Yesu, ove Uno yuhayele, \nWa lilundika oku vela kuetu, \nHaive wa tu talela ohali ya lua, \nNdo tu kuatise kolongembia vietu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_196, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2429, position: 2, content: "Eci wa kala kulo kilu lieve, \nWa muisa ekayo olombeyi via lua. \nLopo unene wove locisola \nViye, vi tu nenele ekayo liove.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_196, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2430, position: 3, content: "Lava va vela, lava va sakola \nVosi va litumbike peka liove. \nOvaka ovasakuli a limbukise \nOvaka vove a tu tomiwila.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_196, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2431, position: 4, content: "Poku leñela kuetu tu kuatise \nOku liyeka peka liove, a Yesu. \nOco ovina viosi vi tu vala \nVi tu longise ocisola cove.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_196, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2432, position: 5, content: "Eci tu lisiosuila oku vela, \nKa tu ka ivale  kuna kuovitima. \nTe tu livela oku kaya olumue, \nNdaño katimba, ndaño kovitima.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_196, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2433, position: 1, content: "Ocinyi coluali Yesu; \nTuila komanu vove. \nNdo tupe upeke wosi, \nTuila vitima vietu \nHa tu leta! Ha tu leta! \nOco tu felevela, \nOco tu felevela.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_197, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2434, position: 2, content: "Vekalasoko lioluali, \nOmo a viala Satana, \nMu tuile ondaka yiwa, \nOcali ci tue lombembua; \nOve a Cinyi! Ove a Cinyi, \nYula ocinyi coluali, \nYula ocinyi coluali.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_197, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2435, position: 3, content: "Owelema wovakandu \nWa sitika ocisola, \nOcinyi condaka yiwa \nCi tu viale, Upopeli \nMolehisa, molehisa, \nOcinyi cove a Njovoli, \nOcinyi cove a Njovoli.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_197, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2436, position: 4, content: "Acinyi comanu, lomuenyo! \nNdo tu tuile lunene! \nEnju ndo tu situluile \nKunene wa Yehova! \nA Cinyi cetu! A Cinyi cetu! \nOve Umihi wo kilu, \nOve Umihi wo kilu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_197, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2437, position: 1, content: "Wa yongola oku popela vakuele \nVa ka vilikiya ndati ku Yesu. \nTe nda ove wenda oku va sapuila \nKuende oku longaisa", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_198, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2438, content: "Kuende oku popela, \nKuende oku Longaisa \nOlomunga viaco \nO vi yongola, \nSuku puãi o pondola.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_198, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2439, position: 2, content: "Wa yongola oku popela vakuele \nSanga va ka mola okufa lakandu. \nVa ka tava ndati te va ka yeva; \nKuende oku sapula.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_198, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2440, position: 3, content: "Wa yongola vakuele va popelua? \nUlongisi kepo te otumiwa. \nKoku yevelela kuli omuenyo, \nSuku o vaiha eyovo.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_198, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2441, position: 4, content: "Cime cetu tu sanjuka oku u vumba, \nNdeci ko nahulu ca sonehiwa. \nVa posoka va sapula esapulo, \nLina liesumuluho.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_198, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2442, position: 1, content: "Acisola ca kanguka. \nAnjolela yokovailu, \nNdo tumãle kumue letu; \nSumuluisa itima vietu.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_199, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2443, position: 2, content: "Ove, a Yesu, ukuahenda, \nHaive ukuacali ca lua. \nMolehisa uwa wove, \nLoku tu sanjuisa ocili.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_199, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2444, position: 3, content: "Anjovoli, ndo pasule \nOvitima vi suñila. \nVi yelisa, vi posuisa, \nVi litepe lowelema.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_199, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2445, position: 4, content: "Olopandu lesivayo \nOvangelo va ku imbila. \nLetu haico tu panduila \nOcisola cove ca lua.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_199, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2446, position: 5, content: "Malusula, a Yehova, \nOcilulikilo cove, \nCi pue oku kamba kuosi, \nOve hu ci sanjukila.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_199, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2447, position: 6, content: "Tu yukinye ekolelo \nToke tu pitila kilu. \nOko tu ku sivayaila \nLovitima via kanguka.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_199, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2448, position: 1, content: "Ñoka lolohuminyo vi Upopeli; \nNjimbila asivayo Upopeli wange; \nOcisola caye ciñolisa ño; \nYesu eye lika oñolisa.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_200, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2449, content: "Ñoka, ñoka, \nÑoka lolohuminyo via Yesu \nUsongui. \nÑoka, ñoka, \nMba, Yesu eye oñolisa", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_200, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2450, position: 2, content: "Omo liolohuminyo si sumi mbu, \nNdaño sumuisiwa latande. \nVonduko ya Yesu nalavayaño; \nYesu eye lika oñolisa.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_200, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2451, position: 3, content: "Ñoka lolohuminyo otembo yosi; \nNjelisiwa losonde y’Upopeli. \nLa Yesu ndilisanja otembo yosi; \nYesu eye lika oñolisa.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_200, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2452, position: 1, content: "Ku ka taluke loku linga eci wa panga \nSanga onyelisa ocinyi cove. \nEsumbilo liove lialua! Linga eci ciwa! \nTuila ocinyi kuosi okasi.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_201, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2453, content: "Tuila ocinyi kuosi okasi, \nTuila ocinyi kuosi okasi, \nÑala Yesu eye oku songuila ciwa; \nTuila ocinyi kuosi okasi.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_201, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2454, position: 2, content: "Ndaño ilu lia sitika sito lalende \nYesu eye oliyelisa. \nImba ocisungo eci lutima wove \nTuila ocinyi kuosi okasi.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_201, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2455, position: 3, content: "Epandi liove liosi liocili okuetu, \nIvaluka ocinyi lomele. \nEsunga liove olio liuku songuila; \nTuila ocinyi kuosi okasi.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_201, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2456, position: 1, content: "Ndi lomba kokuove,  \nA Ñala yange; \nOve o lete cosi, covutima. \nNdeya oku fendela, \nNdi pinga esumuluho; \nEnju ndo sumuluise;  \nEnju a Ñala.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_202, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2457, position: 2, content: "Ndi lomba kokuove,  \nA Ñala yange; \nNdi pinga ongecelo, ya akandu. \nKala a Ñala yange, \nOtevele yange; \nEca locali cove, \nOngecelo.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_202, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2458, position: 3, content: "Ndi lomba kokuove,  \nA Ñala yange; \nOve uñuatisi, kolohali. \nEnju a ndembeleki, \nKolisa utima wange; \nOco sika litepe, \nLove a Ñala.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_202, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2459, position: 4, content: "Yeva a Ñala yange,  \nElombelo eli; \nLioku likekemba halio liolopandu. \nAmitakati yange, \nSoma Njovoli yange; \nVocisola cove a Ñala,  \nÑalemo hũ.", hymnsNumber: UmHymnsNumberSeeder.OKU_LIKUTILILA_202, typeStanza: HymnsContentCode.VERSE),

  ];
}