import 'package:ieca_mobile/_import.dart';

class UmHymnsEkoleloLelembeleko{
  static List<HymnsContent> list = [
    HymnsContent(id: 2583, position: 1, content: "Ove a Yesu, wa nalela\nOlohali kekulusu.\nNjivaluise upongo wove.\nNdimbukise ohenda yove.\nYi mbokiye ocipango\nCoku litumbika ocili.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_232, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2584, position: 2, content: "Cosi ndinga ka ci tela\nOku muisa epopelo.\nNdaño nda pesela cosi;\nNdaño ombili yange ya lua;\nSi limuisa laco eyovo;\nOve lika Upopeli.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_232, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2585, position: 3, content: "Lacimue nda ku nenela;\nNda liyeka ño kokuove.\nÑasi epele, ndo mbualise.\nNda pua esunga, sunguluise.\nOku viha kuange kua lua;\nNdo njelise, sanga fa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_232, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2586, position: 4, content: "Ndimbukise kekulusu\nUvi wovakandu ange,\nHaiko ndimbukile unene\nWocisola ca mopela.\nOcisola caco, a Yesu,\nCi yukise utima wange.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_232, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2587, position: 1, content: "Ndo ñuatise a Suku yange\nOku yulako.\nOvayonjo valua cimue\nOngusu yitito.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_233, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2588, content: "A Suku yange,\nNdo nyiheko ongusu,\nLonduko yove,\nNdembuise ayonjo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_233, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2589, position: 2, content: "Si kolela ongusu yange\nSanga ñonyoha.\nNjimba ovaso konjovoli,\nEye oñolaisa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_233, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2590, position: 3, content: "Ndo tundise ovisimilo\nVi linga osõi.\nHa si yuka lonjolela\nYina yi koka utõi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_233, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2591, position: 4, content: "Vamue nda va njola epembe\nSi ka yeveko.\nSokolola cime cange,\nHaico vo lingavo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_233, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2592, position: 1, content: "A Yesu, ndo ñuatise,\nOco hu vumbe ciwa.\nNdo ñaile ocituke,\nA Cime cocisola.\nNda ove o kasi lame\nLacimue njokokela.\nNda ove o songuila\nLakumue mambukila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_234, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2593, position: 2, content: "Ndo ñaile ocituke\nMomo oluali luvi;\nAyonjo aluo a lua\nA sole oku njonja.\nAnyali vange va lua\nVa ñuala ocingonja.\nA Cime, ndo ngohele,\nHu lingi otevele.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_234, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2594, position: 3, content: "A Cime, ndo njevise\nOndaka yove yiwa.\nYi imule ocileñi\nCesanda lokayengu.\nNdongise olondunge;\nMbokiye ekolelo.\nAndavululi yange,\nNdo ñuale locisola.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_234, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2595, position: 4, content: "A Yesu, wa lisila\nLa vosi va ku vumba,\nOkuti kumue love\nVa kala hũ kulamba.\nA Cime, ndi livela\nEpandi lioku amako.\nNdo ñaile ocituke,\nAkamba liange liwa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_234, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2596, position: 1, content: "Ndaño ehunguhungu liayonjo\nLi tuñunya utima wange,\nNdi lupukila kupopeli,\nSi salamela vavava aye.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_235, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2597, content: "O mbundisa. O mbundisa.\nVemi liavava aye ohenda ya lua.\nO mbundisa. O mbundisa.\nVemi liavava aye ohenda ya lua.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_235, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2598, position: 2, content: "Ndaño ohali ya lua yi mbeta,\nHaimo njivaluka Yesu.\nKa njanduluka; o ñolisa,\nSi talavaya upange waye.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_235, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2599, position: 3, content: "Ndaño ndi suvukiwa lomanu,\nHaimo lopo si  konyoha.\nMomo Yehova o mbetatela,\nO ndembeleka lohenda yahe.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_235, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2600, position: 1, content: "Ndeci ovava olondui a pita pita,\nHa va likongela oku va lunga,\nOmbembua ya Suku haico ya tuwa,\nYi pita pita ño, yi lua vutima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_236, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2601, content: "Va kolela Suku va sumuluha.\nVa sanga epuyuko\nKuenda Ombembua.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_236, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2602, position: 2, content: "Peka lia Yehova vosi va koka,\nLomue o va lingisa ha va yokoka.\nKa va lisiõsiõla; ka va luluma;\nKa va kuata ohele. Va tula utima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_236, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2603, position: 3, content: "Cosi ci va veta ci va kuatisa,\nVa pandula Suku wa ci tumisa.\nVo kolela ocili, ndaño va sumua,\nOmo va limbuka u wa va sola.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_236, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2604, position: 1, content: "Ci kale kombembua, ci kale kupongo,\nKelau pamue kolohali.\nHu imbila ovaso, a Ñala yange,\nLoku ku kolela vutima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_237, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2605, content: "Hu imbila ovaso.\nA Yesu, hu imbila ovaso.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_237, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2606, position: 2, content: "Satana o saluisa lovina vi pita,\nCimosi ci njivaluisa.\nCokuti wa mbanja kukukui wange,\nOsonde yove ya mopela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_237, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2607, position: 3, content: "Manduila ca piãla omo wa ngecela\nAkandu a nonguisile.\nWa ñuatela ohenda ya piãla enene.\nManduila ocili vutima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_237, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2608, position: 4, content: "Cove oku songuila vonjila yokilu.\nCange oku ku kakatela.\nOco ngamameko toke mitila\nLombembua lesanju vutima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_237, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2609, position: 1, content: "Ame ñasi kumue lene,\nOyo ondaka ya Yesu\nYekoliso locisola\nWa usikile osimbu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_238, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2610, position: 2, content: "Ñasi lene wakuopange\nWoku kula ondaka.\nNdaño wa kavi kolisiko,\nWu ka ungula lesanju.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_238, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2611, position: 3, content: "Ñasi lene eci wendi\nLowelema wongongo.\nNdu kolisi vovitima;\nNundisamo usumba.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_238, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2612, position: 4, content: "Ñasi lene eci u piti\nVocimbota cokufa.\nNdi yelisa onjila yene\nLocinyei cokovailu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_238, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2613, position: 1, content: "Kulo koluali ku li ohali,\nÑuete usumba. Ñuete osõi.\nSiti, ci tava oku popelua.\nNgenda ku Yesu nava kokua'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_239, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2614, content: "Ame njolela nda ndu kolela.\nKa nakumula, ngenda kokua'e.\nOco ndu vumba si ka yokoka.\nNgenda ku Yesu, nava kokua'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_239, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2615, position: 2, content: "Ku Ñala Yesu ku li esanju,\nSanga ombembua, sanga utoi.\nNda wa nambula oco nda koka.\nNgenda ku Yesu, nava kokua'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_239, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2616, position: 3, content: "Ku Ñala Yesu ku li eyovo,\nKu li omuenyo una ko pui.\nSi sumi vali; ñuata ombili.\nNgenda ku Yesu, nava kokua'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_239, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2617, position: 1, content: "Kulo nda wa soki oku konyoha\nHoti, ohali yaco ya lua enene,\nTendi asumuluho ene, akuetu,\nKuenje wu komohi ohenda ya Suku.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_240, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2618, content: "Tendi asumuluho, tendi ya!\nMosi, vali, tendi lutate\nTendi osi, osi akuetu\nKuenje wu komohi ohenda ya Suku.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_240, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2619, position: 2, content: "Nda wa lemui locitele cohele,\nEkulusu lio lemi enene,\nTendi asumuluho ene, tendi ya!\nHa wu kuata utima woku sivaya.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_240, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2620, position: 3, content: "Nda vakuele wu va lete lukuasi\nSokololi wene ndomo wa piãla,\nOwo ko landiwa lolombongo mbu,\nKo nyaniwa; ko nyoleha; wenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_240, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2621, position: 4, content: "Ndaño kuiya ongongo, kali lepandi.\nYesu u kuatisi nda wu kolela.\nIvaluki ndomo a likuminya,\nHati Ñasi lene; siu yanduluka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_240, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2622, position: 1, content: "Kuoha ngenda nda la\nYesu ha koka,\nKuoha o songuila oko njilila.\nKuoha njila ndeye keko nyelela.\nKuoha o songuila o mbetatela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_241, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2623, content: "Kuoha ño ngenda la'e, si luluma mbu.\nKuoha o songuila ngenda ha koka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_241, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2624, position: 2, content: "Ndaño o songuila kuna\nKua wunda,\nSiko tupu haimo eye o ñuatisa.\nVamue mbi va siapo\nHaimo ndu kuama.\nNgenda kumue laye, eye Osoma.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_241, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2625, position: 3, content: "Kuoha ngenda la'e si kala ulika.\nNdaño nda fa,\nHaimo mola omuenyo.\nKilu ha pasuka: Yesu haiko a li.\nÑala laye olotembo ka vi pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_241, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2626, position: 1, content: "Cipi ci konyuisa vali\nAva va kolela Yesu?\nCipi ci lingisa usumba\nAva va kolela Yesu?", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_242, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2627, content: "Akuetu, likolisi.\nKu kuete ohuminyo\nYa kola, yi telisa\nAva va kolela Yesu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_242, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2628, position: 2, content: "Ndaño vimue vi sumuisa\nAva va kolela Yesu,\nElavoko li kuatisa\nAva va kolela Yesu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_242, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2629, position: 3, content: "Ndaño okufa ka ku nyoli\nAva va kolela Yesu.\nOcisola ci popela\nAva va kolela Yesu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_242, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2630, position: 1, content: "Nda kolela Ñala Yesu,\nNda kolela ohenda yaye.\nNdaño onjila yi sitika\nO songuila, ngenda la'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_243, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2631, content: "Nda kolela, nda sanjuka\nO nekula, si lambuka.\nKuosi ngenda, ngenda la'e.\nNda kolela ohenda ya'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_243, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2632, position: 2, content: "Nda kolela Ñala Yesu.\nO nyimula ohele yosi.\nOloneke viange viosi\nNdi kolela unene wa'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_243, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2633, position: 3, content: "Nda kolela Ñala Yesu.\nOnjimbaimba onumbi yiwa.\nNda kutanya, nda kuteke,\nNgenda ciwa, ngenda la'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_243, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2634, position: 4, content: "Nda kolela Ñala Yesu.\nEye Ekamba lia velapo.\nNda ndu vumba locisola\nO mosuisa luwa wa'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_243, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2635, position: 1, content: "Nda komoha ohenda ya Suku\nNdomo a ndingisa omolaye.\nNdaño si sesamela cimue pua\nHaimo Eye o muisa epopelo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_244, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2636, content: "Momo u ndo kolela ndu wi\nKuenje ñuliha okuti o tela\nOku lava omuenyo wange\nToke eteke lia'e linene.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_244, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2637, position: 2, content: "Nda komoha upange we Spiritu\nNdomo a ndekisa uvi wange.\nNoke wa situlula Ukristu\nKuenje nda tava lonjolela", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_244, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2638, position: 3, content: "Nda limbuka unene wekulusu;\nWa loñolola cosi caño.\nCilo onumbi ya mua muele pe,\nOcinyi calio ci songuila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_244, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2639, position: 4, content: "Nda komoha ondaka ya posoka\nYa likuminya Ñala Yesu,\nHati, Ha tiuka vali lulamba\nHa si upilila omanu vange.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_244, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2640, position: 1, content: "Osonge ndeci yi laika\nHa yi sandi ovava a talala,\nHaico ame ndi livela\nOvava ana utima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_245, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2641, position: 2, content: "Eteke lipi ndi mola\nUnene wove, a Suku?\nEteke lipi njolela\nOhenda yove locali?", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_245, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2642, position: 3, content: "Otima, ku ka lulume;\nKu ka lisakalaise ño.\nKolela Suku ukuamuenyo,\nOco o sange epuyuko.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_245, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2643, position: 4, content: "Yehova eye Onekui,\nO nyiha cosi sukila\nOtima, o lambukila nye?\nEteku lieli vonjo ya'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_245, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2644, position: 5, content: "Omanu nda va fuanguila\nHa vati. Ka puluka mbu,\nÑolela Suku Ukueyovo;\nOcili caye ka ci pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_245, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2645, position: 1, content: "Nda yeva Yesu wa ñovonga.\nWa linga hati, Enju\nWa kava loku tungayala;\nPuyuka, amolange.\nNdeya ku Yesu yu nda sanga\nOmangu ya mosoka.\nNda tula utima, nda sanjuka;\nSi tungayala vali.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_246, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2646, position: 2, content: "Nda yeva Yesu wa ñovonga.\nWa linga hati, Enju.\nOvava omuenyo ko pui ya!\nPetama oco o nyue.\nNdeya ku Yesu yu nda sanga\nOvava a ñavuluisa;\nA imula enyona liange liosi;\nUtima wa petuka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_246, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2647, position: 3, content: "Nda yeva Yesu wa ñovonga.\nWa linga hati, Enju.\nAme ndicinyi, amolange;\nKu ka pupute vali.\nNdeya ku Yesu yu nda sanga\nOvaso a patuluka.\nKaliye ngenda lekolelo\nToke ungende u pua.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_246, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2648, position: 1, content: "Ungombo wange Yehova;\nO muisa via ñamba.\nVisenge viwa o songuila\nKovava a yela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2649, position: 2, content: "O numbuluila utima;\nVesunga o ngendisa,\nLovolonjila via miuha\nLonduko ya'e yiwa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2650, position: 3, content: "Ndaño vekungu liokufa;\nSi yokokela uvi.\nOmbueti yaye lomango\nVi ndembeleka ocili.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2651, position: 4, content: "Omesa yange o yi njalela;\nNdaño va suvuka.\nLulela kutue ombuaveka;\nVokopo mua supa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2652, position: 5, content: "Ohenda yaye yi ñuama;\nToke omuenyo u muako.\nKovailu, konjo ya Suku,\nHa tumala ño hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_247, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2653, position: 1, content: "Yesu eye Usongui wange;\nSi nyelela nda ndu kuama.\nNda onjila ya natama\nNdi kolela ongusu yaye.\nNda onjila yi nyelela\nEye o njimba ciwa onumbi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_248, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2654, content: "Vowelema eye o nuila\nLocinyi condaka yaye,\nVowelema eye o nuila\nLocinyi condaka yaye.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_248, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2655, position: 2, content: "Nda nyikiwa lovayonjo\nO pamisa utima wange.\nNda nda lemua lovitele\nO muyuisila pulembo.\nNda nda sumua lolohali\nNjeva elembeleko liaye.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_248, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2656, content: "Nda nda suka eye o muisa\nEvi viosi via ñambela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_248, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2657, position: 3, content: "Yesu eye Usongui wange\nHaeye Undipo, ka ndueyisa.\nOcisola ca'e ka ci pui,\nHaico ka ci tepuluka.\nO songuila toke kilu,\nOko a mongiyila onjo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_248, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2658, content: "Kuenje ha imba ovisungo\nSi panduila ohenda yaye.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_248, typeStanza: HymnsContentCode.CHOIR),

    HymnsContent(id: 2659, position: 1, content: "Yesu eye ekamba lietu,\nWa tu ecela akandu.\nKuenje kumue longecelo\nO tu muisa cosi ciwa.\nVia lua via tu tatamisa;\nVi tu sakalaisa ño,\nMomo olonjanja via lua\nKa tua vi lombelele.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_249, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2660, position: 2, content: "Nda ayonjo a ku kuete,\nKu li cimue ci vala,\nKu ka konyohe lombili;\nLomba muele ku Yesu.\nKupi vali kuli ekamba\nCosi o tu ambatisako?\nEci ongusu yi tokoka\nYesu o tu kuatisa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_249, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2661, position: 3, content: "Nda wa ambata ocilemo,\nNda wa kuata usumba.\nOcikolo cetu ceci:\nOku lomba ku Yesu.\nNdaño va tu yola epembe\nYesu o tu lembeleka.\nEye lika Upopeli,\nO tu muisa esanju.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_249, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2662, position: 1, content: "Konele ya'e, nda salama, nda koka.\nNdaño kahunguhungu ohali.\nÑolela Suku, kokua'e nda tiamela,\nAme ndimola'e o sole ocili.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_250, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2663, content: "Konele ya'e, konele ya'e,\nU o njupako helie?\nKonele ya'e nda salamako;\nKua mosokela cimue.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_250, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2664, position: 2, content: "Konele ya'e, oko sanga ocikolo\nNdaño koluali ka kuli o ndemba,\nNda salamako momo Suku o sole,\nÑasiko ciwa, kua mosokela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_250, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2665, position: 3, content: "Konele ya'e kua niamela enene\nOko nilila te ohali yi pua.\nCi pi ca viha ci tela oku sanga?\nNula utima momo nda koka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_250, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2666, position: 1, content: "Evi violuali via huvika enene;\nCilo njongola evi viokovailu;\nKuenje eci natelela eviho liange\nNjevite elaleko liocisola.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_251, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2667, position: 2, content: "Ndimbuka ondaka yonjovoli yange.\nEye o mayula leka lia tomiwa.\nOsonde yaye oyo yi njelisa;\nOkufa kuaye oko ku njovola.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_251, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2668, position: 3, content: "Ocili, a Yesu, ove usunga liange;\nWa lituikile akandu ange osi.\nCove olosongo, cange ekolowa:\nCove okufa, cange omuenyo ko pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_251, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2669, position: 4, content: "A Ñala yange, ndinge embombe liove;\nÑale lutima woku felevela,\nOco nyiñile noke lonjolela\nVonjo wa yi mongiyila kimbo liove.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_251, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2670, position: 1, content: "Hu kolela, a Yesu.\nKu ka njanduluke.\nNda pia, nda nyelela,\nEnju ndo mopele.\nKupi vali sanga\nOhenda ndeyi yove?\nNdukuakandu tupu\nWa nulila omuenyo!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_252, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2671, content: "Nda ku limbukila\nKocisola cove,\nOco hu pandola\nOloneke viosi\nHu kolela a Yesu.\nKu ka njanduluke.\nNda pia, nda nyelela,\nEnju ndo mopele.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_252, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2672, position: 2, content: "Hu kolela, a Yesu.\nOlondaka Viove\nNda vi yeva, puãi\nka via ndombolokele.\nEci Espiritu o vi ndomboluila\nNyihe olondunge,\nSi vi patekela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_252, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2673, position: 3, content: "Hu kolela, a Yesu.\nSi tatãla vali.\nU iya kokuove ove ku u pukula.\nOhuminyo yove\nYa posoka enene.\nA Yesu, nda have,\nNda sia pulukile.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_252, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2674, position: 1, content: "Yesu nda tu sola loku kuamelela\nO tu yelisila onjila.\nNda tu pandikisa loku pokoyola\nKumue letu eye o kala.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_253, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2675, content: "Kuameleli\nOku kuama Yesu.\nU koleli ocili\nHa wu moli esanju.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_253, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2676, position: 2, content: "Ndaño tuoku endela vowelema wa lua\nOcipala ca'e ci tu tuila.\nCi tu imula usumba, ci tu endisa ciwa;\nKuenda ci tu tulisa utima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_253, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2677, position: 3, content: "Cosi ci valula ovitima vietu\nO ci lete ka cu limbi mbu.\nNda tu pumba ukuasi, nda tu \nmola epese,\nTu ka mola ca piãla kilu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_253, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2678, position: 1, content: "Ombonge yetu Yehova,\nEye ocikolo ca pama.\nNdaño anyãli va lova\nYehova o tu yulisa.\nSatana ukuatutu,\nUnyoli witima,\nO kasi lupombo,\nEsuvu lia'e lia lua;\nWa piãla cimue keviho.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_254, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2679, position: 2, content: "Nda tua lituna losiata\nNda oco tua patuluka.\nPuãi ku li U o tu ohela;\nTu kuete U ka teliwa.\nOnduko ya'e Yesu.\nTu wimbila ovaso.\nEye o tu songuila\nKovita viutima;\nOnjuli yina ya piãla!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_254, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2680, position: 3, content: "Ndaño oluali lue yuka\nLeliapu lovakuenje va'e.\nKa tu va yokokela pua;\nYehova lika Onene.\nNdaño tu pundiwa;\nNdaño tu pondiwa,\nHaimo imuenyo vietu\nViamale via Suku,\nOmbiali  yina yenda hu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_254, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2681, position: 1, content: "Momo Suku o tu sole\nTua kolapo.\nWa tu ecela akandu osi,\nTua kolapo.\nWa tu fila omolaye,\nYa tokala osonde yaye.\nKua kolapo okuokuo  kuaye.\nTua kolapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_255, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2682, position: 2, content: "Ndaño wa lua upongo wetu\nTua kolapo.\nLia posoka eyovo lietu,\nTua kolapo.\nNda tu sanjukila Yesu\nLoku tumbangiya Suku\nEye o tu imbila owanji.\nTua kolapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_255, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2683, position: 3, content: "Yesu eye tua imba ondunge\nTua kolapo.\nNdaño ohali, o tu ohela,\nTua kolapo.\nEye o kasi kumue letu,\nO tu lava locisola,\nO tu imula usuke wetu,\nTua kolapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_255, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2684, position: 4, content: "Nda kuiya eci, nda kuiya oco\nTua kolapo.\nCosi tu panduila Suku,\nTua kolapo.\nNdaño ukuasi ka tu kuete\nKa ci tu vindula ohele\nOmo Suku o ci lete\nTua kolapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_255, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2685, position: 1, content: "Yerusalai yokilu,\nYepuiti kuenda uwale,\nOku yi sokolola,\nUtima u sulila.\nSi li ocili, si li\nEsanju tu sangako\nLulamba una wa lua,\nOtembo ka yi pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_256, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2686, position: 2, content: "Volokololo vimbo\nMua vota lovisungo\nViangelo, lolombangi\nVana va fila etavo.\nOhali yavo ya pua,\nVa tunga hu la Soma\nVofeka yonjolela,\nLulamba ka u pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_256, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2687, position: 3, content: "Omanu vovo Siono\nVa pua ohele yosi;\nVa imbaimba atumbangiyo,\nLisungo vionjolela.\nOvo lusongui wavo\nVa mala oku yaka,\nVa wala evi via yela\nOtembo ka yi pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_256, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2688, position: 4, content: "Afeka yonjolela,\nYakuepata lia Suku,\nAfeka ya posoka,\nTu ku livela cimue.\nA Yesu, tu pitiye\nKofeka yepuyuko,\nHa tu kala la Suku\nOtembo ka yi pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_256, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2689, position: 1, content: "Metuila ovaso ange kolomunda.\nVi njivaluisa\nNdomo Yehova\nA ndingila ocikolo,\nCoku tilila.\nU wa lulika ilu kuenda ongongo\nEye Yehova. Oñuatisi yange.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_257, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2690, position: 2, content: "Eye ka tava okuti omai yove,\nYi lilondoka.\nU o ku lava lava ka suñila;\nKa ku ivalako.\nOndavululi yava Isareli\nKa yanduluka ava vo kolela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_257, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2691, position: 3, content: "Eye ulembo wovonjila yove,\nOmbindikiyo.\nKa ku li utanya\nu ku kakula vali,\nNdaño osãi.\nYehova o ku teyuila kuvi wosi\nKuenda o vindikiya\nOmuenyo wove.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_257, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2692, position: 4, content: "Nda poku tunda njimba pi ovaso,\nTe ku Yehova.\nNda poku iñila\nEye Utati wange,\nSi sumi vali.\nUkuaku ndava oloneke viosi\nTunde kosimbu\nTa kotembo yosi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_257, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2693, position: 1, content: "Va sole Suku va linga\nNdomunda Siono;\nKa va sondoloka vali,\nVa tumãla ño hu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_258, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2694, position: 2, content: "Ndeci olomunda via ñuala\nImbo lia Siono.\nHaico ongusu ya Suku\nYa ñuala omanu va’e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_258, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2695, position: 3, content: "Kilu kombala ya Suku,\nOko tu ka koka\nHaiko tu muila epuyuko\nLiocili, li enda hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_258, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2696, position: 4, content: "A Suku, ndo tu songuile,\nToke tu pitila,\nKofeka yove ya piãla\nYohenda lulamba.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_258, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2697, position: 1, content: "Ka kuli vali onduko sio,\nTe yove, a Yesu, o kola.\nO tela oku ecela akandu.\nO muisa ombembua ya Suku.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_259, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2698, position: 2, content: "Ka kuli vali onduko sio,\nEci utima u mbala.\nOve o mbeluisa ocali\nOngongo yosi lohali.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_259, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2699, position: 3, content: "Ka kuli vali onduko sio.\nEci ndi tula omuenyo.\nO sindikila kokufa,\nNyiñila love kulamba.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_259, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2700, position: 4, content: "Ka kuli vali onduko sio\nNdi tumbangiya yenda hũ;\nYa Yesu lika, oyo fu,\nYa Ñala yange, Upopeli.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_259, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2701, position: 1, content: "Tu ku sole, a Suku, a Tate\nOcisola cove ca lua.\nTu ku sole; ove lika\nUkuamuenyo wenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_260, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2702, position: 2, content: "Tu ku sole, wa tu avela\nCosi ca tu posokela.\nTu ku sole; ove lika\nUkuahenda yenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_260, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2703, position: 3, content: "Tu ku sole; O tu lete\nKuenje o tu endisa ciwa.\nTu ku sole; ove lika\nUkuonene wenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_260, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2704, position: 4, content: "Tu ku sole, tua limbuka\nEkemãlo liove lia lua.\nTu ku sole; Ove lika\nUkuolamba wenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_260, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2705, position: 1, content: "Yesu ocili, eye Fu.\nKomuenyo wange wosi.\nOngusu ñasi layo ya'e,\nNda haeye nda si kasi\nEci ndi sumua eye yu,\nLu o sanjuisa ndeye sio.\nKa ku li mbu wa lisoka la'e.\nEkamba!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_261, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2706, position: 2, content: "Yesu ocili, eye Fu,\nEkamba kolohali.\nOhele locinjoko mbu;\nNda koka, si fukila.\nEye o ndava, ka si ño;\nOhenda ya'e ka yi pui mbu.\nKa ku li mbu wa lisoka la'e,\nEkamba!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_261, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2707, position: 3, content: "Yesu ocili, eye Fu,\nEkamba lia kolelua.\nEye ka njanduluka mbu.\nO mbetatela ciwa.\nNda handa muele nda ndu kuãi.\nNgambata ekulusu lia'e.\nKa ku li mbu wa lisoka la'e.\nEkamba!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_261, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2708, position: 4, content: "Yesu ocili eye Fu,\nSi tava kumue wiñi.\nNdu kuama; ndu kolela hũ\nKungende wange wosi.\nMola omuenyo kumue la'e,\nUna ka u pui, wenda hũ.\nKa ku li mbu wa lisoka la'e,\nEkamba!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_261, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2709, position: 1, content: "Yesu o tu songuila\nToke tu pitila.\nNdaño ku li atateko,\nHaimo puãi ka tu tokoka,\nYesu o tu songuila\nToke tu pitila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_262, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2710, position: 2, content: "Nda tu mola upongo,\nNda tu mola ongongo,\nTu kolela Usongui wetu,\nTua amamako lekolelo.\nYesu o tu songuila\nToke tu pitila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_262, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2711, position: 3, content: "Ndaño upange wa lua,\nNdaño ekavo lia lua,\nHaimo lumue ka tu u lembui\nMomo Yesu o tu ohela.\nEye o tu songuila\nToke tu pitila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_262, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2712, position: 4, content: "Ka tu ka yokoki,\nKa tu ka konyohi.\nVolonjila vietu viosi\nYesu o tu endisa ciwa.\nEye o tu songuila\nToke tu pitila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_262, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2713, position: 1, content: "Yehova ukuangusu,\nEye tu kolela.\nNdaño anyali va lua\nEtu tu va yula.\nSatana a tamalãle ño,\nSatata a tamalãle ño,\nSuku haimo wa velapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_263, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2714, position: 2, content: "Yehova ocilala.\nKa tu pukula mbu.\nWa tu lingisa va'e.\nO tu iha ongusu.\nAnyali va tamalale ño,\nAnyali va tamalale ño,\nSuku haimo wa velapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_263, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2715, position: 3, content: "Yehova ocikolo\nCava vo kolela,\nO tu tata ciwa,\nO tu imula usuke.\nOluali lu tamalãle ño,\nOluali lu tamalãle ño,\nSuku haimo wa velapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_263, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2716, position: 4, content: "Yehova Ungombo,\nCa tu kambela o ci.\nEye ombindikiyo,\nOnati, Onekui.\nOkufa ku tamalãle ño,\nOkufa ku tamalãle ño,\nSuku haimo wa velapo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_263, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2717, position: 1, content: "Utima wange u kavulukila\nKolondui vi talala,\nVi tunda tunda kono\nYocali ca Suku yetu.\nKu kasi u o muisa\nOngusu yovutima,\nKua mosokela cimue\nKolondui viekavuluko.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_264, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2718, content: "Kolondui viekavuluko!\nKolondui viekavuluko!\nKua mosokela cimue\nKolondui viekavuluko.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_264, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2719, position: 2, content: "Njitika ciwa ekuamo lietavo\nSi lupukila onima,\nYa likuminya Suku\nLa vosi vakuekolelo.\nÑolela Ñala Yesu,\nWa linga Onati yange.\nKungende wange wosi\nO njelisila onjila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_264, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2720, content: "O njelisila onjila.\nO njelisila onjila.\nKungende wange wosi\nO njelisila onjila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_264, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2721, position: 3, content: "Onjalu yange yi pita kovaso,\nYi njimba onumbi yiwa.\nNdu kuama. Ndu kolela\nLayimue ohele ñuete.\nOhali ya lua tupu,\nNgamako lekolelo.\nO mbetatela ciwa\nMitila lonjolela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_264, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2722, content: "Mitila lonjolela.\nMitila lonjolela.\nO mbetatela ciwa.\nMitila lonjolela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_264, typeStanza: HymnsContentCode.CHOIR),

    HymnsContent(id: 2723, position: 1, content: "Nda nda kava lolohali\nNdi tilila pi?\nYesu wa mañinya hati,\nPuyuka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2724, position: 2, content: "Nda njongola Yesu Usongui\nNdu limbukila pi?\nVanja amome olohali\nVio sila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2725, position: 3, content: "Ekolowa he liosoma\nLili kutue wa'e?\nEkolowa liolosongo\nOlio lia'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2726, position: 4, content: "Nda ndu sanga, ha siu kuama\nNdi ka sanga nye?\nAsuelela lovopange\nLohali.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2727, position: 5, content: "Nda ndu kuama lekolelo\nO ka muisa nye?\nO ka muisa omuenyo ko pui\nKuwa wa'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_265, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2728, position: 1, content: "A Suku yetu, a Pakisi,\nTu ku imbila ovaso.\nOve Upopeli kohali,\nHaive Ucitililo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2729, position: 2, content: "Kokuove vakuekolelo\nVa muila epuyuko.\nOkuokuo kuove kua pama;\nOve Umbindikiyo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2730, position: 3, content: "Osimbu kua lulikile\nOluali pamue ilu.\nHaiko wa kala kulamba,\nHaive enda hu, ku pui.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2731, position: 4, content: "Anyamo a pita ño ndolui,\nAmbata oloneke.\nA pita lombili ndonjoi\nYa tu limba omele.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2732, position: 5, content: "A Suku Yetu a Pakisi,\nTu ku imbila ovaso.\nO tu popela kohali,\nO linga ocikolo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_266, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2733, position: 1, content: "Nda imbila ovaso ku Suku,\nHaeye ndo kolela.\nU wa lulika oluali,\nEye Ombindikiyo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_267, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2734, position: 2, content: "Ovolu wa ñolisila\nVonjila yomuenyo.\nO ndava ndava lohenda,\nKa njanduluka mbu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_267, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2735, position: 3, content: "Yehova o mbetatela;\nO kala lame hũ;\nKutanya kuenda kuteke\nKa pekelako mbu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_267, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2736, position: 4, content: "O mopela kolohali;\nO muisa ongusu.\nOhenda yaye ka yi pui,\nÑolela unene wa'e.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_267, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2737, position: 1, content: "Okuete osapi ya hela\nEye Suku.\nNda umue ukuavo wa kaile\nLosapi yaco, ndaño ame,\nNda nda pumba,\nNda nda pumba.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_268, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2738, position: 2, content: "Kovaso ngenda si leteko,\nNdo kuliha.\nSuku ka pongoloka mbu,\nO nambula olohele viosi\nNula utima,\nNula utima.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_268, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2739, position: 3, content: "Osapi yoloneke viange,\nOyi kuete.\nEteke eteke usumba mbu,\nOsimbu yosi peka liahe\nNda puyuka,\nNda puyuka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_268, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2740, position: 4, content: "Ñuata lika ekolelo\nKatoke fa.\nLeteke liange liesulilo,\nKepito lina liokilu,\nO njikuila,\nO njikuila.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_268, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2741, position: 1, content: "A Mola a Suku, Suku Isietu,\nNdaño ka tua ku kulihile.\nTu ku limbuka kocisola\nLoku kolela ondaka yove.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_269, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2742, position: 2, content: "Eci wa kala kilu lieve,\nWa linga Omunu haive Suku.\nPongoluisavo ipango vietu\nOco tu tuwe ndomo Ove.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_269, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2743, position: 3, content: "Uwale wolofeka viosi,\nNdaño ukuasi lolondunge,\nViosi vi kuete efulilo,\nPuãi Ove ku fulila vali.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_269, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2744, position: 4, content: "Ndaño tua linga olonoño,\nLoku kuliha ovina viosi.\nPuãi tu limbuka okuti cosi\nCi tunda muele peka liove.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_269, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2745, position: 1, content: "Uwe Lionahulu Ove;\nO neyuila ocili,\nYesu, ovava losonde\nVia ku tunda konele,\nVia sukuile akandu\nHa vi nyiha ongusu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_270, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2746, position: 2, content: "Ndaño nalavaya hũ,\nSi yovoka laco mbu;\nOvina viosi, nda ndi vi,\nNda mopela lavio pi?\nViosi ka vi  mondola,\nOve lika o nela.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_270, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2747, position: 3, content: "Peka ka pa kuete sio;\nÑuata  komindikiso,\nNdukuepele, mbualise;\nNdukuekavo ñolise;\nNdukuosumba, mbundise;\nKa ndingile otevele.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_270, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2748, position: 4, content: "Eci ñasi lomuenyo\nEci ndala veyambo,\nEci ndonda kovailu,\nMbanja omangu ya Suku,\nUwe Lionahulu Ove\nOka nyiha uwale.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_270, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2749, position: 1, content: "Hu kokela, a Suku,\nOcipepi,\nNdaño ndukuelamba,\nNala ohali;\nUtanya luteke,\nNjimba ocisungo eci,\nHu kokela, a Suku,\nOcipepi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_271, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2750, position: 2, content: "Ndaño nda suvala\nNda pua esanju;\nNgenda lowelema\nUtanya mbu,\nPokati kuteke\nKu tuila ocinyi,\nHu kokela, a Suku,\nOcipepi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_271, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2751, position: 3, content: "Ndekise onjila\nYenda kilu,\nMitise lombembua,\nOnguele sio;\nOco ungende wosi\nNgende londaka eyi:\nHu kokela, a Suku,\nOcipepi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_271, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2752, position: 1, content: "Okuendela vocinyi cahe,\nNda kakungu, nda kolomunda,\nKristu hati si ku yanduluka,", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_272, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2753, content: "Ñasi love otembo yosi.\nAcinyi catua! A cinyi catua!\nNjukise lulamba wokilu\nLasivayo ngamako,\nHu sivaya a cime cange!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_272, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2754, position: 2, content: "Nda ñualiwa layonjo alua,\nHaimo lumue mbanja ku Yesu.\nEye ocinyi ka ci takata.\nPonele yahe nda koka.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_272, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2755, position: 3, content: "Ocinyi ca Yesu ci songuila,\nToke mitila  kulamba wahe.\nÑasi laye ocituke.\nHu sivaya wa njovola.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_272, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2756, position: 1, content: "A Ñala okalunga ka tema,\nAkimba a pukuka;\nKilu kua sitikua lalende,\nKa kuli upopeli!\nKa ciku vindula ohele?\nOpekelako ño,\nOsimbu tu vomba vovava,\nTu laika oku fa we!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_273, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2757, content: "Akimba a pokola kokuange,\nUhi ño!\nCi kale okalunga katema,\nOnyeño yomanu\nKuenda olondele,\nOvava ka a tela oku vombisa,\nOwato mu endela Cime cene,\nVosi va pokola kokuange,\nUhi ño! Uhi ño!\nVosi va pokola kokuange\nUhi! Uhi ño!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_273, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2758, position: 2, content: "A Ñala esumuo lia lua\nCilo ñuete vutima;\nOhele yi ñuete enene,\nPasuka ndo mopele!\nKa kandu a soka ndetande,\nHelie o mopela?\nKuenje nda fa ocili a Cime!\nYayulako oku mbiala!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_273, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2759, position: 3, content: "A Ñala usumba wapua\nWa tulumula ofela!\nLutima wa tulumuhavo\nKo kuata vali ohele.\nKala vokuange a Cime,\nKu ka sie ño vali,\nLesanju mitila kesinya\nHa si puyuka love.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_273, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2760, position: 1, content: "Etavo liange lia tunga\nKu Yesu Ohanda yesunga,\nSi ka tungile keseke\nLioluali lulo luveke.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_274, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2761, content: "Nda tunga onjo yutima\nKu Yesu Ohanda yesunga,\nKu Yesu Ohonda yesunga.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_274, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2762, position: 2, content: "Si lete opolo ya Yesu,\nPuãi si konyoha ngamako.\nOfela yosi yesanda\nKa yi tela oku hungisa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_274, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2763, position: 3, content: "Ñuete ohuminyo yi kola,\nYosonde yahe ya peseka.\nVetande liosi liayonjo\nYi numalisa, ñola ngo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_274, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2764, position: 4, content: "Eci Yesu eya, o sanga\nNdu wa tungiwa kohanda,\nKokuahe lika ñolela\nKeseke liaño si tava.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_274, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2765, position: 1, content: "Ca fina ndati akuetu,\nNda locisola calua,\nVamanji lekolelo lialua\nVafendela Cime cavo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_275, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2766, position: 2, content: "Ndaño vakualuali,\nVa mola ombembua yavo.\nVa yeva ndunguendu uwa,\nEkolelo liavo liwa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_275, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2767, position: 3, content: "Tu muise a Yesu\nTunde ko Siono,\nSpiritu Sandu linena\nEtokekiso eli.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_275, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2768, position: 1, content: "Ndingende mulo voluali;\nNda lungila ofeka yokilu,\nKuna kua fina enene;\nNjevite ko ongeva.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_276, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2769, content: "Ofeka yina ya fina\nOku yi vanjela komunda;\nNdete okalunga kanene\nHa yoka toke kesinya.\nNdetevo ulamba wenda hu,\nWokilu kuna kua fina!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_276, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2770, position: 2, content: "Ñala Yesu ondavandava.\nOmbanguisa evi viomuenyo.\nO ñuata peka, peka liae.\nNda koka, mitila kilu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_276, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2771, position: 3, content: "Njevite elemba liwa,\nLitundilila kulamba,\nLioloneleho vienda hu,\nKuenda viapako apepa.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_276, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2772, position: 4, content: "Ovisungo viovangelo\nVi kasi vofela yokilu;\nViava va yula ale osimbu;\nVa imba epopelo liavo.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_276, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2773, position: 1, content: "Nda yeva ondaka\nYesu a linga hati,\nAmolange wa suka\nÑolele ame nduhuasi.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_277, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2774, content: "Yesu wa feta\nWa fetela ame.\nCosi nda levalele\nKaliye ca pua pe.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_277, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2775, position: 2, content: "Ocili nda sanga\nOsonde ya Yesu;\nYi yelisa ovitima\nVia liña lakandu.", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_277, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2776, position: 3, content: "Lopula wokufa\nHa mola ohenda ya'e;\nEci ndi ci kolela;\nYesu wa fetela ame!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_277, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2777, position: 4, content: "Leteke mitila\nKomangu ya Tate;\nNjimba ocisungo eci:\nYesu wa fetela ame!", hymnsNumber: UmHymnsNumberSeeder.EKOLELO_LELEMBELEKO_277, typeStanza: HymnsContentCode.VERSE),
  ];
}