import 'package:ieca_mobile/_import.dart';

class UmHymnsOlopanduKuSuku {
  static List<HymnsContent> list = [
    HymnsContent(id: 2892, position: 1, content: "Tueya, a Suku, lesumbilo lia lua,\nOku panduila eci ca posoka.\nCa lingiwila vakuafeka yilo\nPoku sovuiwa ku ekongelo lietu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2893, position: 2, content: "Onepa yaco yiwa yokaliye,\nYa tu yikuila onjila ya posoka.\nKovaso tu enda kuli onima ya lua\nYu tu vetiya oku kuata epandi.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2894, position: 3, content: "Tu ku sivaya omo wa katuile,\nAva va kũ la lava va tapela.\nTua sanjukila upange wavo uwa!\nTu ohele, a Suku, oku wamisako.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2895, position: 4, content: "Nda asovoli, nda vakapiñala,\nVosi tu va panduila epandi liavo.\nLomo va litumbika locisola\nKupange woku sumuluisa omanu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2896, position: 5, content: "Kuenje, a Tate, tu likutilila,\nOkuti o tu iha onjongole ya lua;\nYoku liamuila lavakuetu vosi,\nEci ohenda yove ya tu muisa", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_304, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2897, position: 1, content: "Suku yokilu loposi\nLotukalunga le tuosi,\nA tumbangiyiwe kuosi;\nUkuacali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_305, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2898, position: 2, content: "Wa tu ĩha utanya, lofela,\nLalende  a nena ombela,\nLokulia le wa tu avela;\nUkuacali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_305, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2899, position: 3, content: "Ca piãla wa eca Omõla'e\nWongunga, una a sole,\nHa tu fila, tuakuahole;\nUkuacali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_305, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2900, position: 4, content: "Ongusu yoku lundula\nAyonjo a tu landula.\nO tu yiha, tua pandula,\nUkuacali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_305, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2901, position: 1, content: "Tu panduila, a Suku,\nOvilimbu vinene\nViocisola ca piãla\nWa kuatela omanu.\nLepopelo linene\nLia moleha ku Yesu.\nMomo cosi, a Suku,\nWa tu avela ocali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_306, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2902, position: 2, content: "Tu panduila, a Suku,\nUhayele wetimba\nLolondunge wa tu iha\nVioku sima viocili.\nLekolelo tu kuete\nLioku kuama esunga,\nMomo cosi, a Suku,\nWa  tu avela ocali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_306, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2903, position: 3, content: "Tu panduila, a Suku,\nVakuangangu ye lipua,\nLolonõi viekolelo\nVia vayela okufa,\nLalongisi vosimbu\nVa tu sila etavo,\nMomo cosi, a Suku,\nWa tu avela ocali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_306, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2904, position: 4, content: "Tu panduila, a Suku,\nAsapulo osimbu\nLelavoko tu kuete\nLevi vi li kovaso.\nVosi tu ihe ongusu\nYoku tunga ofeka\nMomo cosi, a Suku,\nWa tu avela ocali.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_306, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2905, position: 1, content: "Tu vanja konyima \nKuenje tua limbuka\nOhenda ya lua ya tu lingiwila;\nKuosi tua pita, \nWa tu endisa ciwa;\nA Suku yetu \nTu ku imbila olopandu. (2x)", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_307, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2906, position: 2, content: "Tu vanja kovaso \nKuenje tua kolela\nOkuti o tu amisako locisola.\nKovaso tu enda, \nNdaño ku li itangi,\nKa vi tu yokokisa, \nOve O tu songuila. (2x)", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_307, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2907, position: 3, content: "Tu vanjavo kilu \nKuna Kristu a kasi,\nHa tuolohela kocimaho cetu;\nVonjila yina a tu vanguluila,\nOmo tu endela \nLekolelo lolopandu. (2x)", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_307, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2908, position: 4, content: "A Yesu Usongui, \nHave Vufulilo;\nHẽla letaili \nKuenda otembo yosi;\nOve Unjovoli, \nHave Usoma yetu. \nUnene wove \nU tu muise eyulo lia lua. (2x)", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_307, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2909, position: 1, content: "Omo Suku wa tu avela\nOmbanjale ya posoka\nYeteke lilo liokaliye,\nTu imbi olopandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2910, position: 2, content: "Omo wa tu muisa ongusu\nYoku linga upange wetu,\nLomo a tu iha akamba etu,\nTu imbi olopandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2911, position: 3, content: "Omo wa tu kapa itima\nVioku sola esunga liaye,\nLoku suvuka eci cĩvi,\nTu imbi olopandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2912, position: 4, content: "Omo wa tu avela via lua\nVia posoka, ka vi kumi,\nVi tu kokaila esumbilo,\nTu imbi olopandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2913, position: 5, content: "Omo a tu ihaiha otulo,\nHa tu kavoloka  ciwa,\nOco atimba a kolepo,\nTu imbi olopandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2914, position: 6, content: "Omo a tuma Omolaye,\nHa tu moli la'e eyovo,\nOco litima via yelisua\nTu imbi olopandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_308, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2915, position: 1, content: "Acisola, locisola wa loka,\nAcisola locisola wa fa.\nHaka! Otokua eyi wa tala,\nUtima wange wa pongoloka\nOcisola cange ca yula.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_309, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2916, position: 2, content: "Acisola locisola wa kuama,\nAme kua muililile ocisola.\nHaka! ocisola wa ndingila\nOco kocisola a Yesu\nWa tala kekulusu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_309, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2917, position: 3, content: "Acisola locisola wa ecela,\nToke muele wa sumuluisa.\nUna wapia ove wa amela\nKokuove wa yula opopeli\nNdeyavo a Ñala.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_309, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2918, position: 4, content: "Acisola eci kacipui\nOkuti vovoko ove o ñuata\nCa ñuala ohulukayi ya asanju\nO Tava kaliye Upopeli\nWa li sepuisa locisola.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_309, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2919, position: 1, content: "Nda solele oku enda lehungu,\nNda lingaile ovina nda panga;\nSia tavele okuti Ukristu\nO mopela kahuku lesanda.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2920, position: 2, content: "Vowelema nda kala lusumba,\nKuosi ngenda si lete ocinyi.\nElavoko la limue nda kuata,\nKuenje siti, nda nongua lakandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2921, position: 3, content: "Ocinjoko ca ñuata enene.\nNoke puãi nda yeva ondaka,\nYiti, Yesu, Pakisi o kola,\nO popela omunu ukuakandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2922, position: 4, content: "Oco noke nda tava ku Yesu.\nNda sanjuka; nda sanjuka enene.\nNumbangiya ño hu Onjovoli\nWa mopela ndimunu ukuakandu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2923, position: 5, content: "Ñasi ciwa, ocinyi ca nuila;\nOwelema wa imuha olumue.\nNdi sapuila vakuetu okuti\nVakuakandu va sanga eyovo.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_310, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2924, position: 1, content: "Tuakuaku lima ovapia\nTu kula ombuto,\nPuãi u o yi tundisa\nTe Suku Yehova.\nHaeye o tu ihaiha ombela\nLutanya lofela\nHa vi kolisa ombuto\nKatoke yi yela.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_311, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2925, content: "Evi viosi viwa\nVi tunda ku Suku.\nTua pandula, tua pandula,\nUkuacali cetu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_311, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2926, position: 2, content: "Ovina viosi kilu\nLoposi upange wa'e,\nOviti oloneleho,\nEkumbi kuenda osai.\nOlondui lolomunda,\nOmanu linyama,\nSuku wa vi lulika\nLunene wa'e wa lua.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_311, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2927, position: 3, content: "Tu panduila omuenyo;\nTu panduila ongusu;\nTu panduila okulia;\nKa tua sukile mbu.\nLacimue tu ci kuete\nHa tu ko fetela,\nTe tu litelekala\nKokua'e lovitima.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_311, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2928, position: 1, content: "A Cime, a Suku, \nLevumbo hũ komoha;\nOluali luosi lua lulikiwa Love.\nNdete owiñi; njevite ocileñi;\nUnu wove u moleha kuoha.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_312, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2929, content: "Lutima hu sivaya, Ove O kola;\nOve O kola; Ove O kola;\nLutima hu sivaya, Ove O kola;\nOve O kola;Ove O kola!", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_312, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2930, position: 2, content: "Ovisenge vi komohisa ca lua;\nNjevite olonjila \nVi kasi loku imba.\nVolomunda unene wove wa lua;\nLocileñi covava ovolondui.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_312, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2931, position: 3, content: "Sokolola Suku wa eca Omolaye\nOco a fila okufa kua tila.\nWa tambula uvi wange lesanju;\nWa njupa akandu \nAnge eci a fila.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_312, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2932, position: 4, content: "Kristu iya lonjuvungo yocili\nÑekamavo levumbo liocili.\nNgenda laye \nLesanju eli ka li pui\nSi sapula ku Suku O kola.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_312, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2933, position: 1, content: "Itima vietu via sanjuka,\nTua wila vonjila yokilu.\nOcinyi cayo ca tu tuila,\nTua wila vonjila yokilu.\nItangi tupu tuamamako,\nTua kolela Usongui wetu,\nKumue lahe tu pitila.\nTua wila vonjila yokilu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_313, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2934, content: "Akuetu, tu imbi lonjolela:\nTulongende vielavoko.\nUngende wetu u puila kesanju,\nTua wila vonjila yokilu", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_313, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2935, position: 2, content: "Usongui wetu haeye Yesu,\nTua wila vonjila yokilu.\nLacimue tu ci yokokela\nTua wila vonjila yokilu.\nVekalasoko liovakandu\nTua nyelile, tua sumuile.\nCilo puãi tu popolola.\nTua wila vonjila yokilu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_313, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2936, position: 3, content: "Ohando yetu haeye Yesu,\nTua wila vonjila yokilu.\nLacimue ci tu konyohisa\nTua wila vonjila yokilu.\nEhunguhungu liovayonjo,\nLovatande olohali,\nVi tu veta puãi tu yula\nTua wila vonjila yokilu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_313, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2937, position: 4, content: "Okuetu, love, linga ongende,\nNdo wile vonjila yokilu.\nLiweka oku tungayala,\nNdo wile vonjila yokilu.\nLakumue vali ku li eyovo.\nTava ndopo kelaleko,\nKu ka tutuvale vali:\nNdo wile vonjila yokilu.", hymnsNumber: UmHymnsNumberSeeder.OLOPANDU_KU_SUKU_313, typeStanza: HymnsContentCode.VERSE),
  ];
}