import 'package:ieca_mobile/_import.dart';

class UmHymnsEfendeloLesivayo{
  static List<HymnsContent> list = [
    HymnsContent(id: 1618, position: 1, content: "O kola, o kola, o kola,  \nA Yehova a Suku. \nCilo kua ca isungo  \nVietu viu ku tumbangiya. \nO kola, o kola, o kola,  \nOve ukuahenda; \nOve lika Suku  \nKilu kuenda posi.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_5, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1619, position: 2, content: "O kola, o kola, o kola, \nVakuetavo vosi \nVa sivaya onduko  \nYove loku ku fendela. \nHaico ovangelo  \nVosi va ku vumba; \nWa kaile, o kasi,  \nLopo enda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_5, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1620, position: 3, content: "O kola, o kola, o kola,  \nOve ukuonene; \nOlongole vietu  \nVia sitika ulamba wove. \nNdaño tua kualufa,  \nWa tu muisa omuenyo \nTu ku tumbangiya,  \nA Suku, ove Fu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_5, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1621, position: 1, content: "Sivayi hũ Suku, \nUna wa tu tumisa Omola'e. \nYesu eye ocali coviali. \nSivayi hũ Suku.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_6, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1622, position: 2, content: "O ka tu pisa helie? \nYesu wa fila yu wa pinduka. \nCilo o kasi kondio ya Suku \nO ka tu pisa helie?", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_6, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1623, position: 3, content: "Yesu wa tu yovola. \nHelie o tu timbuiya ongecelo? \nHelie o tu vetela evelo? \nYesu wa tu yovola.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_6, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1624, position: 4, content: "Etu tu ka yula. \nYesu wa tu tundila olunda. \nUnyali wetu Yesu wo yula. \nLetu tu ka yula.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_6, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1625, position: 1, content: "Sivayi! Suku, wa tu ihile Yesu, \nWa tu fila akandu, wa londa kilu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_7, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1626, content: "Aleluia! Ulamba wahe \nAleluia! Amen! \nAleluia! Ulamba wahe, \nSivayi Suku.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_7, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1627, position: 2, content: "Sivayi Suku, wa tu iha Espiritu \nHa tu muisa esunga vitima vietu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_7, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1628, position: 3, content: "Sivayi Suku, ka sivayi Espiritu \nImbili esivayo ku Yesu Kristu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_7, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1629, position: 1, content: "A Suku yocili, a Suku Tõlo, \nTu kasi kovaso ove, o kola. \nWa tu vindikiya tunde kosiahũlũ. \nTu ku sambiliya litima via lipua.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_8, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1630, position: 2, content: "Ovina via fina wa vi lulika, \nVi tu komohisa eteke keteke. \nNda vievi vinene, nda vievi vitito, \nViosi wa vi tunga luloño wa piãla.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_8, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1631, position: 3, content: "A Suku yohenda, o tu lemãila \nKusumba wovina vi laika oku iya. \nOmo wa posuisa owangu woposi, \nOmanu ca piãla, nda va ku kolela.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_8, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1632, position: 4, content: "Tumãla vomanu, ka tua kolele, \nPuãi Suku Isietu wa kola ocili. \nA Suku, etali tua ku imba ovaso. \nNdo tu sumuluise lunene wokilu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_8, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1633, position: 1, content: "Fendeli Suku, amanu vosi; \nU tumbangiyi lesumbilo. \nLimbuki ndomo unene waye\nWa piãla olohõlo viosi.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1634, position: 2, content: "Uloño waye ko pondoka. \nWa tu lulika leve liaño. \nNoke eci akandu a tu nyola, \nLohenda ya'e wa tu popela.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1635, position: 3, content: "Tu iñili vovitali viaye \nLetumbangiyo lolopandu. \nTu imbili Suku esivayo. \nTu kemalisi onduko yaye.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1636, position: 4, content: "Uviali waye ko fulila. \nEsunga liaye lia pua evelo. \nIlulikilo viosi vi pua; \nOhenda yaye puãi ka yi pui.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_9, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1637, position: 1, content: "Fendeli Soma yetu, \nO li kocalo caye, \nYevi ovisungo viovangelo \nVioku u tumbangiya. \nAmanu, sambiliyi \nYesu Onjovoli yetu. \nWimbili olopandu via lua \nLoku u sivaya.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_10, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1638, position: 2, content: "Fendeli Ukuahenda \nTali ovaka aye. \nAmome aco a tu ivaluise \nOlohali viaye. \nKomindikiso yaye \nTua mola ocinyi ca tua, \nCi yula owelema wosi \nHa wi imuha olumue.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_10, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1639, position: 3, content: "Fendeli Ukuamuenyo, \nOkufa kuo tokoka. \nWa tukulula eyovo liaye \nKuosi ku li omanu. \nA kufa unene wove \nWa taka voku yula; \nUsumba wa tu lingisile \nCilo wa pua pe.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_10, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1640, position: 4, content: "Fendeli Ukuambembua; \nImula uyaki wosi. \nOmbembua yaye yi piñala \nKonya lokesuvu. \nUviali waye ko pui, \nO viala locisola. \nOnduko yaye yi kemãla \nPosi kuenda kilu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_10, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1641, position: 1, content: "A Suku Isietu, tu ku tumbangiya. \nTua nena ulambu wolohutililo. \nTu weca kokuove ha tu ku fendela. \nOnduko yove tu yi sivaya ño hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_11, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1642, position: 2, content: "Tu vumba Yehova yavakuasiahũlũ. \nPokati kayonjo o tu teyowaila. \nKotembo yohali eye o tu kuatisa. \nOnduko yove tui sivaya ño hu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_11, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1643, position: 3, content: "Tu likutilila lutima umuamue \nKokuove, a Suku, Unekui yocili. \nLokuokuo kua pama ndo tu songowaile. \nOnduko yove tu yi sivaya ño hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_11, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1644, position: 1, content: "A Tate, a Suku, Utungi \nWovina viosi vi kasi, \nEsunga liove lia lova, \nLohenda yove ukuasi.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_12, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1645, position: 2, content: "A Yesu Kristu, wa fila \nOmanu vosi voluali, \nWa tu pelela onjila \nYi tu pulula ohali.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_12, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1646, position: 3, content: "Ove a Spiritu, wa lemba \nItima viosi vionguele, \nWa imula upika wakandu; \nWa tu lingisa omãla va'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_12, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1647, position: 4, content: "A Tate, a Yesu, a Spiritu \nOve ukuolamba wenda hu; \nUnene wove wa piãla; \nCu ku sengisa ka ciko.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_12, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1648, position: 1, content: "Suku Usovoli \nO li vonembele; \nTu sivayi Usovoli. \nWa tu situluila \nEkemãlo liaye; \nTu limbuki ulamba waye. \nTu sivayi lesumbilo \nUsovoli wetu, \nO li vonembele.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_13, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1649, position: 2, content: "Suku Upopeli \nO li vonembele; \nTu sivayi Upopeli. \nTu imbi olopandu \nKu wa tu upa ohele; \nTu panduili eyovo liaye. \nTu sivayi lesumbilo \nUpopeli wetu, \nO li vonembele.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_13, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1650, position: 3, content: "Suku Oñuatisi \nO li vonembele, \nTu sivayi Oñuatisi. \nA Spiritu Sandu, \nKala kumue letu; \nOku tu enda tu songuile. \nTu sivayi lesumbilo \nOñuatisi yetu, \nO li vonembele.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_13, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1651, position: 1, content: "A Yehova, ove Uno \nYovasumuluho osi. \nTu li loku nena ilumba \nViesivayo liovitima. \nTu panduila epopelo \nTua li muila kekulusu, \nKuna Yesu a tu fila, \nHa tu moli omuenyo.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1652, position: 2, content: "Eye wa tu situluila \nOcipango cove ciwa, \nCina ci nenela esanju \nVosi va ci sole ocili. \nO tu muisa ukuasi wove, \nUna kopui wovitima; \nNoke iya o tu tuala \nKimbo liove ka li pui.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1653, position: 3, content: "Wa tu nola, ha tu moli \nUwa wove ka wimuha, \nUna wa tu molehela \nKocipala comõlove. \nTu panduila, a Suku yetu, \nNdomo wa tu sumuluisa. \nTu sivaya onduko yove \nOlotembo ka vi pui.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_14, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1654, position: 1, content: "Tumbangiyi Suku yetu; \nU neneli ulambu wene. \nYevalisi kolofeka \nEkemãlo lia Yehova. \nU sivayi. U sivayi. \nUkuonene wenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1655, position: 2, content: "U panduili olohenda\nA lingile vakuasimbu. \nNdaño etali o tu lava \nLocisola ca'e ka ci pui. \nU sivayi. U sivayi; \nUkuahenda yenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1656, position: 3, content: "Eye Onekui yovitima; \nWa kuliha ekambo lietu. \nO tu kuete leka liaye, \nO tu imula olohele \nU sivayi. U sivayi; \nUkuangusu yenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1657, position: 4, content: "Tuakuatimba a nyolaiha \nNdoneleho yovusenge. \nPuãi lohenda ya Yehova \nTu tumãla hũ lomuenyo \nU sivayi. U sivayi; \nUkueyovo lienda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_15, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1658, position: 1, content: "Nda yolela eci \nVa mañinya vati: \nHa tu endi konjo ya Tate. \nEwa! Olomai viange \nVi loña kombundi \nYa Suku la Siono ya'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_16, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1659, position: 2, content: "Siono, imbo lia'e, \nLia tunga lulambi: \nOko kua lunga olofeka. \nVa sivaya Suku \nLunene wa'e wa lua. \nVo sole va sumuluha.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_16, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1660, position: 3, content: "Ku kale ombembua, \nKimbo lia Yehova \nLokonjo ya'e yefendelo. \nOko tu ka sanga \nUsitue wa piãla.\nUtima wange u soleko.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_16, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1661, position: 1, content: "Enju, Ano yolohenda, \nHu imbe etumbangiyo. \nUkualondui viocisola \nVi sukola ovakandu. \nNdo ndongise ocisungo \nVa ci imbaimba kovailu. \nÑuete elolo liwa, liolio, \nEyovo liange vu Yesu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_17, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1662, position: 2, content: "Puwa waye nda levala, \nCosi ciwa nda mõla. \nOhenda yaye yi ndokaila \nEteke keteke ndowume. \nOve, u Yesu, womboka cimue; \nAme hu setukule. \nOcisola ndelienge, \nCi nokeke kokuove.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_17, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1663, position: 3, content: "Ndaño nala olongongo \nKu vana va suvuka; \nNda va nela olonjanjo \nOve o va sikuila. \nKovakango ovakandu, \nLopekungu liokufa. \nÑuete ongeva lokovailu, \nKuna ku pua asuẽlẽla.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_17, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1664, position: 1, content: "A Yesu, Undaka ka yi pui ya Suku, \nU Ñala yohenda lombembua, \nTu ku felevela, ndo tu yevelele; \nTu muise ekolelo lesanju.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_18, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1665, position: 2, content: "Ndo tu upe ulema, tu endise longusu; \nTu imule upeke wutima, \nTu ecele akandu; tu yele ocili.\nTu muise omuenyo wokilu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_18, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1666, position: 3, content: "Kolisa onjo yilo yefendelo liove; \nYi linge ombundi yokilu \nItima via kava vi sange epuyuko; \nVi vela vi sange oku kaya.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_18, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1667, position: 4, content: "Olonjo vitima laviovo vi kole, \nHa vi pui evihõ lesanda; \nVi yuke ombembua, vi pame kesunga; \nA Yesu, vi ku sesamele.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_18, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1668, position: 5, content: "A Tate, a Mõla, a Spiritu Sandu, \nWa piãla kunene lohenda, \nKokuove ku kale esivayo lulamba; \nU Suku Ukueyovo ka li pui.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_18, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1669, position: 1, content: "Ca posoka howa akuetu, \nYesu oku kolela, \nNdomo a tu popelele, \nOku ci sinyanyela.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_19, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1670, content: "Yesu, Yesu, ndu sole \nNdo kulĩha wa njika \nYesu, wa niamela cimue \nNda ndo sola capialã.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_19, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1671, position: 2, content: "Ca posoka cimue akuetu, \nNda tua ci limbuka ale. \nNdomo osonde yahe ocili, \nYa tu yelisile pe.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_19, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1672, position: 3, content: "Ca posoka oku kuliha, \nKa tu tẽla cimue puã, \nHaimo omuenyo kuenda owusa, \nO tuavela lombembua.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_19, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1673, position: 4, content: "Ndu kua ku sanjuka a Yesu, \nOmo nda ku kolela. \nOve ukamba, unjovoli,\nNda haveko nda ndafa!", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_19, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1674, position: 1, content: "Nda nda tẽlẽle oku kunda \nUnene wonjovoli yange \nPamue ekemãlo liaye. \nOco nda nda tenda esunga liaye, \nLoku yevalisa ohenda yahe \nYa nenela epopelo. (2x)", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_20, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1675, position: 2, content: "Nda nda sapula esivayo \nLionduko yaye ya kemãla \nKuosi kulo kilu lieve. \nNda ndo tumbangiya lisungo via lua, \nToke koloneke ka vi pui vali. \nNdu sivaya lonjolela. (2x)", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_20, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1676, position: 3, content: "Kulamba una wokovailu \nHo tumbangiya locileñi \nCa velapo covangelo. \nHo sivaya omo a mandulula, \nLomo a numbika komuenyo ko pui. \nKovakandu a njovola. (2x)", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_20, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1677, position: 1, content: "Okola, okola, okola eye Ñala; \nA tumbangiyiwe eye Ñala! \nOkola, okola, okola eye Ñala \nUfendeli afeka yosi! \nImbi asivayo, aco olonjuli, \nKu wa kemala Yesu imbi, \nOkola, okola, okola eye Ñala, \nYi tumbangiyiwe onduko ya'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1678, position: 2, content: "Ñala Yesu, eye ukuesunga; \nVu viali waye muli esunga! \nÑala Yesu, eye ukuesunga, \nEsunga liya lusoma Waye! \nKusoma Waye u kola, \nKuli ulamba lunene Waye. \nÑala Yesu, eye Ukuesunga \nEsunga liya lusoma Waye.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1679, position: 3, content: "Unu, unu, unu eye Ñala; \nWeyuka ombembua kuenda ocisola! \nUnu, unu, unu eye Ñala; \nNdeci etu, viosi wa setekiwa! \nOcitililo, Ono yocali, \nKomanu vaye Suku usovoli \nUnu, unu, unu eye Ñala \nWeyuka ombembua locisola.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1680, position: 4, content: "Ukuahenda eye muẽle Ñala \nCosi wa kuliha, cosi ca vala \nUkuahenda eye muẽle Ñala \nOlongembia vietu wa ambata. \nNdaño lokufa viosi wa ecele \nEye wa lieca kekulusu \nUkuahenda eye muele Ñala \nOlongembia vietu wa ambata.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_21, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1681, position: 1, content: "Tu sivaya Ñala yetu; \nTu pesela cosi cetu; \nTu tumbika atimba etu, \nTuti, cosi ca'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1682, position: 2, content: "Tua yolela ondaka yaye; \nYi kolisa ovitima. \nLacimue ci tu lingisa \nNda tu endaenda la'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1683, position: 3, content: "Tu koleli Cime cetu; \nTu endi la'e ka tu ekelela. \nO li pi o tu tepisa \nKocisola ca'e?", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1684, position: 4, content: "Akuetu, tu lameleli; \nEye lika o tu songuila.\nO tu upisa ovisolela \nNda tu kala la'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1685, position: 5, content: "Noke tu sondolokela; \nKuna muele kua posoka. \nLacimue ci tu somboka; \nTu sanjuka la'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_22, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1686, position: 1, content: "Lovitima vi yela, \nTu sivayi Yehova,", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1687, content: "Ukuahenda yenda hũ; \nKa yi pongoloka mbu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1688, position: 2, content: "Yu wa yala oluali; \nYu wa miha ekumbi.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1689, position: 3, content: "Olombungululu via'e; \nWa vi tunga kuenda osãi.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1690, position: 4, content: "Wa lingaile ovikomo; \nEye unene, eye Fũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1691, position: 5, content: "Leka liaye lia pama; \nWa popela omanu va'e", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1692, position: 6, content: "Letu nda tu u kolela; \nHaico muele a tu ohela.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_23, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1693, position: 1, content: "Ndete ono ya posoka; \nYi sukula cosi pe, \nEspiritu lia mañinya, \nHati, O yelisua lie.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_24, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1694, content: "Ndi sivaya! Ndi sivaya! \nNdi sivaya Ñala Yesu \nU sivayi amanu vosi. \nU yelisa lie losonde ya'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_24, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1695, position: 2, content: "Ndaño owelema wa lua \nCi saluisa ci li pi? \nOnjongole yange yeyi, \nNda o kala lame hu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_24, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1696, position: 3, content: "Oco ondalu ye Spiritu \nYi sanyisa utima fĩ. \nNdu sivaya, si puyuka. \nNumbangiya onduko ya'e.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_24, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1697, position: 4, content: "Yesu Kristu ndu sivaya; \nWa ñovonga, ngenda la'e. \nWa ngecela ovakandu \nYu nda yela muele lie.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_24, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1698, position: 1, content: "Ocisola Cove ca tu sandiliya, \nPandu, pandu a Suku ndi litumbika; \nA Ñala tava olopandu viukuekandu, \nUlambu lesivayo, ngeca kokuove.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_25, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1699, position: 2, content: "Tava a Ñala Yesu, epingilo lilo. \nNda hongua kutima, hame levĩho. \nEci onduko yove, ha yi kemanya \nNduisa usoma Wove. Enju omindise.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_25, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1700, position: 3, content: "Mbokiye onjogole, yocisola ciwa, \nOco ndu ku vumbe lesunguluko. \nOku kuata imuenyo, vi endele vocinyi; \nSole omãla vove, enju omindise.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_25, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1701, position: 4, content: "Ndomo ñasi a Ñala, njiya kokuove; \nVoluali luvi, si tiukila mbu. \nEci ha mola, Ocipala Cove, \nA Ñala ha ku vumba, kulamba wove.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_25, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1702, position: 1, content: "Suku eye Usovoli; \nOsoma yenda hũ. \nEye wa sovola oluali;\nOsoma yenda hũ. \nEye wa sovola okalunga; \nOsoma yenda hũ. \nEye wa sovola ekumbi; \nOsoma yenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_26, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1703, content: "Ululi, ululi, ululi, ululi! \nOsoma yenda hũ. \nUlu, ulu, ulu, ulu! \nOsoma yenda hũ \nO kola, o kola, o kola, o kola! \nOsoma yenda hũ.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_26, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1704, position: 2, content: "Suku eye Usovoli. \nEye wa sovola ombela. \nEye wa sovola ofela. \nEye wa sovola oviti.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_26, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1705, position: 3, content: "Suku eye Usovoli. \nEye wa sovola omuenyo. \nEye wa sovola omunu. \nEye wa sovola okulia.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_26, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1706, position: 4, content: "Wa tuma Ñala Yesu. \nEye Upopeli womanu. \nKuenda Espiritu Sandu. \nEye Uyelisi witima.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_26, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1707, position: 1, content: "Ku Suku kovailu, \nNgeca olopandu \nLesivayo. \nWa eca omolahe, \nWa fa kekulusu. \nHa yovola omanu, \nSivayi Suku.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_27, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1708, position: 2, content: "Tu sivayi Ñala, \nOnjovoli yetu, \nÑala Yesu! \nWa eca etimba lia'e \nKondinga ekandu, \nWo yuluila epito \nLiokovailu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_27, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1709, position: 3, content: "Ku Suku Oñuatisi \nYesu a tumisa \nTu usivayi \nKristu Ocisola, \nHaye Ulongisi; \nMitakati yetu. \nSivayi Suku.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_27, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1710, position: 1, content: "Yesu ndu pandula; \nNdu wimbila uvangi \nLolopandu. \nVa suka, va pumba, \nVa konua, va sumua, \nYesu wa popela \nKolohali.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_28, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1711, position: 2, content: "Yesu ndu pandula; \nNdu wimbila uvangi \nLalombelo. \nAva va nyelela, \nApika vokufa, \nYesu wa yovuila \nKekulusu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_28, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1712, position: 3, content: "Yesu ndu pandula; \nNdu wimbila uvangi \nNdukuenje wa'e. \nNdinga upange wa'e. \nNãla ohali la'e; \nNdi kuama lepandi \nÑala yange.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_28, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1713, position: 4, content: "Yesu ndu panduila; \nNdu wimbila uvangi\nLelavoko. \nVosi vo kolela, \nVa yela  kutima, \nKokuaye va mola \nEpinduko.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_28, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1714, position: 1, content: "Tu imbi vosi lonjolela; \nAleluya! \nTu imbi olopandu via lua; \nAleluya! \nLovileñi lovitima \nTu sivayi Suku yetu. \nOcisola caye ca lua. \nAleluya!", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_29, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1715, position: 2, content: "Ovitima vi sanjuke; \nAleluya! \nTumbangiyi Onjovoli; \nAleluya! \nYesu eye usongui wetu, \nHaye oñuatisi yetu; \nUkuahenda ya kanguka. \nAleluya!", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_29, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1716, position: 3, content: "Esivayo ka li ka pue; \nAleluya! \nNdaño kulo, ndaño kilu, \nAleluya! \nTulombangui viepopelo; \nTuakuandaka ya posoka; \nTu yi yevalisi kuosi; \nAleluya!", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_29, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1717, position: 1, content: "Yi pepa onduko ya Yesu \nKovatui ukuetavo. \nYi lembeleka utima, \nYi imula ocinjoko.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_30, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1718, position: 2, content: "Onduko ya'e otevele, \nHayo ocikolo. \nOnduko yaco ndi sole, \nOyo onjumbatiyo,", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_30, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1719, position: 3, content: "Oyo ombolo kelambu, \nIhemba kovovei; \nKekavo yi kavuluisa; \nYi imula olonjaya.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_30, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1720, position: 4, content: "A Yesu, Ove Ungombo \nUkamba, Uprofeto, \nUsoma, haive Ucitunda, \nNdi ku tumbangiya.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_30, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1721, position: 5, content: "Si oku vumba ciwa mbu, \nUtima wa pola. \nPuãi eci hu sanga kilu \nHu pandula ocili.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_30, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1722, position: 1, content: "Ku Suku tu eca ulamba lonjolela, \nOmolove waecavo kokuetu; \nOcali ca eciwa kukuekandu uvi \nOku njuluila epito lio kilu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_31, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1723, content: "Yoleli, yoleli, enjui vosi imbi, \nKu Yesu Upopeli,  \nKu Yesu Onjovoli; \nKu Suku tu eca ulamba omo \nOmolaye wa wecavo ko kuetu.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_31, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1724, position: 2, content: "Ocali cocili ca Ñala Yeso, \nLoku fa, osonde wa tu yi pesila. \nOnjo kilu, lolosandu vocinyi, \nWa tu yi landela, ondando wa yi feta.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_31, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1725, position: 3, content: "Loku kuama ongangu yocisola, \nTu ka linga ocipango ca Tate;\nWosi o okolela ku Upopeli waye,  \nO ko molã, wa tumalã laye kulamba.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_31, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1726, position: 1, content: "Sivayi onduko ya Yesu. \nAngelo kemanyi \nOmola a Suku enda hu; \nLulamba U vialeki.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_32, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1727, position: 2, content: "Ene epata lia noliwa, \nLia Tate enda hu. \nYesu usovoli Weyovo, \nLulamba U vialeki.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_32, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1728, position: 3, content: "Ene Wa ecelui locisola, \nVu ka yula ocili; \nKu Suku - Omunu, Ukueyulo \nLulamba U vialeki.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_32, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1729, position: 4, content: "Ene apata, lalimi \nSumbili  Soma yilu, \nWa tepa tepa alienge avĩ, \nLulamba u vialeki.", hymnsNumber: UmHymnsNumberSeeder.EFENDELO_LESIVAYO_32, typeStanza: HymnsContentCode.VERSE),
  ];
}