import 'package:ieca_mobile/_import.dart';

class UmHymnsUvangiLupange {
  static List<HymnsContent> list = [
    HymnsContent(id: 2778, position: 1, content: "Evi via Yesu njongola.\nEvi via Yesu mbangula.\nNdaño via lua si tẽla,\nVi pepa; ka vi kumi puã.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_278, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2779, content: "Haimo sia tẽlẽle.\nHaimo sia tẽlẽle.\nEvi via Yesu njongola.\nVi pepa ka vi kumi pua.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_278, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2780, position: 2, content: "Ndi lisikama la Yesu,\nNdi lipasola laye hũ.\nMbangola laye kulika,\nNdi kuete laye ongeva.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_278, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2781, position: 3, content: "Eci ndu muila komangu,\nYina yulamba kovailu.\nNongeka vali lesanju,\nKolombangulo vi enda hũ.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_278, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2782, position: 1, content: "Nda o yongola esumuluho\nKuama volomãi via Yesu.\nO ku muisa esanju lia lua;\nKuama volomai via Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_279, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2783, content: "Linga ondonge ya'e,\nU kuama lekolelo.\nLikakatela la'e.\nKuama volomai via Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_279, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2784, position: 2, content: "Nda o yongola epuyuko\nKuama volomãi via Yesu.\nNda wa konua o ku kolisa.\nKuama volomãi via Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_279, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2785, position: 3, content: "Nda o yongola ekolowa\nKuama volomãi via Yesu.\nKa tikule omindikiso,\nKuama volomãi via Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_279, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2786, position: 4, content: "Nda o yongola viokovailu\nKuama volomãi via Yesu.\nEye lika Ongavi yaco.\nKuama volomãi via Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_279, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2787, position: 1, content: "Lingi olomunga viosoma yohenda;\nSandeki ondaka yeyovo.\nAva va nyelela vakango va tiuke,\nVa iñile vepata liomuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_280, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2788, content: "Lingi olomunga viosoma yohenda\nKuendi lekolelo lepandi.\nOco olosuke vi yeve lesanju\nElaleko liwa liomuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_280, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2789, position: 2, content: "Lingi olomunga viosoma yohenda,\nLekisi ocinyi cocili.\nVowelema uvĩ wesanda lioluali\nMolehi ndimihi viomuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_280, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2790, position: 3, content: "Lingi olomunga viosoma yohenda,\nIliki ofeka yulamba.\nOco olongende via kava lesumuo\nVi wile vonjila yomuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_280, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2791, position: 4, content: "Lingi olomunga viosoma yohenda,\nSapuli ocali ca Suku,\nYevalisi kuosi ohenda ya piãla\nYo muisi onima yomuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_280, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2792, position: 1, content: "Ukua Kristu wosi Yesu u sukila;\nCi yongola muele olohõlo viosi\nKuenda esunguluko liokupange waye.\nKu ka sime hutu, Ukuetu. Ove muele!", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_281, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2793, content: "Vumba Yesu ocili.\nKapelako oku linga upange wa'e.\nVumba Yesu ocili.\nKu ka sime hutu, Ukuetu.\nOve muele.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_281, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2794, position: 2, content: "Okangusu kove ndaño ka ka luile,\nHaimo ka kuatisa ava va nyelela.\nKu ka tepuluke. Kolisako ño.\nKu ka sime huti. Ukuetu. Ove muẽle!", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_281, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2795, position: 3, content: "Evumbo liocili oku sandiliya\nAva va konyoha, ha va pongoloka.\nKua lua kua yela ale, lalongisi mbu\nOku vumba Cime cove Yesu Kristu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_281, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2796, position: 4, content: "Vumba Yesu Kristu loku lembeleka\nVakuetavo vosi va tala ohali.\nKuata ocisola ci vala tupu,\nOco upongo kuenda ohali vi va pita.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_281, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2797, position: 1, content: "Ohenda ya Suku Tate\nYi tuila ño voluali.\nEye hati, Akuetavo,\nKa taimi, ndolovela.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_282, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2798, content: "Tu taimisi olovela\nViovitima akuetu,\nSanga umue o nyelela\nVowelema wakandu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_282, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2799, position: 2, content: "Vowelema wovakandu\nVa lua va nyelelamo.\nVamue omanu va livela\nOku sanga Onjila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_282, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2800, position: 3, content: "Tu kuatise, a Spiritu,\nOku taima ocili.\nSanga tu songuila vamue\nKu Yesu Upopeli.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_282, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2801, position: 1, content: "Umue wa linga ukuavo ohenda;\nWa molehisa ukamba wocili;\nWa imbila omanu ocisungo cokilu\nCa va kokela utõi lekolelo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2802, content: "Ove hẽ? Wa linga nye?\nOve hẽ? Wa linga nye?", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_283, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2803, position: 2, content: "Umue wa likuminya esunga;\nWa sanjukila ondaka yomuenyo;\nWa tamalãla lovina vieviho;\nWa litumbika kusoma wa Suku.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2804, position: 3, content: "Umue wa huka lovina viocili;\nWa limba kuevi vi nyola utima;\nWa pambukila konjila yakandu;\nWa lipumbisa onima yomuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2805, position: 4, content: "Umue wa muisa omanu esanju;\nWa linga umihi wocinyi cokilu;\nWa lombolola ohenda ya Yesu,\nLomo a fila eyovo liomanu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2806, content: "Ame hẽ? Nda linga nye?\nAme hẽ? Nda linga nye?", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_283, typeStanza: HymnsContentCode.CHOIR),

    HymnsContent(id: 2807, position: 1, content: "Amiko, akuohande,\nEne wa tavi ku Yesu.\nOtembo yeya yoku votoka,\nKua ca kupange wosoma yinene.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_284, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2808, content: "Amiko. Amiko.\nLomue ka ka lende.\nAmiko. Amiko.\nOcinyi ca tu tuila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_284, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2809, position: 2, content: "Amiko. Vosi tu  endi;\nKu li ovaima valua.\nAkuaku ungula, kuosi wu kasi.\nKo ka tatãli. Votoki lombili.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_284, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2810, position: 3, content: "Amiko loku lomba,\nVa lua omanu vo lete.\nLavakuopange vo livangeli,\nVo lavololi. Amiko lepandi.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_284, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2811, position: 4, content: "Amiko. Yayuliko;\nNdopo utanya u pita.\nOtembo yilo oyo yupange,\nNoke ku  keya otembo yonima.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_284, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2812, position: 1, content: "Sole oku sapula ondaka yokilu\nYina ya lombolola\nohenda ya Yesu.\nSole oku yi sapula; \nYa posoka ocili.\nOndaka yaco yiwa \nYomuenyo wa'e ko pui.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_285, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2813, content: "Sole oku sapula\nOndaka ya posoka\nYa tunda konahulu,\nYohenda ya Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_285, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2814, position: 2, content: "Sole oku longaisa \nVana ka va la yeva\nApika vovakandu \nSuku wa va yovola.\nSole oku longaisa \nNdaño vakuetavo;\nVosi va sanjukila \nOndaka yeyovo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_285, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2815, position: 3, content: "Sole oku pandola. \nNdukuaku yolela\nOndaka ya mopela,\nYa ñolisa utima.\nLopo ndu tumbangiya\nKulamba wokilu,\nHaiko ndi ka panduila \nOhenda ya Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_285, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2816, position: 1, content: "Tu sapuili ondaka komanu,\nHa va pongoluisa itima,\nOndaka yaco yiwa,\nYombembua ka yi pui. (2x)", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_286, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2817, content: "Owelema u linga ongula,\nNoke ongula yi linga utanya.\nUkristu Soma o viala hu\nOtembo ka yi pui.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_286, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2818, position: 2, content: "Tu imbi ovisungo komanu,\nVa tekela ku Suku yocili,\nHa va tamalãla luvi\nU nyola esunga liaye. (2x)", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_286, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2819, position: 3, content: "Tu sapuili omanu ha tuti,\nSoma yetu o li kovailu,\nWa tumile Kristu posi\nOku imba oluiya luaye. (2x)", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_286, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2820, position: 4, content: "Tu lekisi Kristu komanu,\nUna wa talele ohali,\nNdokuti oluali luosi\nLu tava ku Suku Tõlo. (2x)", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_286, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2821, position: 1, content: "Votoki yapa, amanu va Kristu.\nSandeki ondaka yesanju lia piãla.\nYesu wa nyola ongusu yokufa.\nWa pindukila eyovo liomanu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_287, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2822, content: "Imbi ocisungo cesanju lia piãla.\nYesu o viala. Yesu o viala.\nKua ca kupange wusoma wa Suku!\nYesu wa yula, o viala ño hũ.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_287, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2823, position: 2, content: "Kuendi lutõi, tamalali leviho.\nLingi olomunga viesunga lombembua.\nMalehi ovimaleho via Suku.\nKo ka lembuisi koleli Kesongo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_287, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2824, position: 3, content: "Kovaimbo ene lokofeka yosi\nYuli owelema lutanya wokilu.\nPokati kevi violuali via puiya,\nLingi olonungi viusoma wesunga.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_287, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2825, position: 4, content: "Omindikiso yokufa lepembe\nYa nena omuenyo lulamba wa piãla.\nVosi sivayi Onjuli ya piãla.\nKuendi; ko vumbi lombili lesanju.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_287, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2826, position: 1, content: "Kua yevala ondaka yiwa,\nYesu o popela.\nTu yi yevalisi kuosi.\nYesu o popela.\nYendelele, yi yevale\nOcipepi lokupãla.\nVosi tu yi imbila  uvangi;\nYesu o popela.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_288, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2827, position: 2, content: "Tu yevisi omanu vosi,\nYesu o popela.\nVakuakandu va ci yeve,\nYesu o popela.\nKovifuka viokalunga,\nKolomunda lokanyala,\nKu yevale oluiya luwa,\nYesu o popela.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_288, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2828, position: 3, content: "Yi landule va nyelela,\nYesu o popela.\nYi kolise va leñela,\nYesu o popela.\nKovitima vi tekãva\nLevi via pua elavoko\nKu yevala elembeleko,\nYesu o popela.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_288, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2829, position: 4, content: "Yi kundiwe lekolelo,\nYesu o popela.\nYi sapuiwe locisola,\nYesu o popela.\nYi lungole otumãla;\nYi laleke amalẽhe;\nYi sanjuise vo akulu:\nYesu o popela.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_288, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2830, position: 1, content: "Tuliki epandela lietu,\nLi molehe kolofeka.\nImbi uvangi wepopelo\nLia moleha kekulusu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_289, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2831, position: 2, content: "Tuliki epandela lietu,\nOco omanu va kulihe\nEpondolo liekulusu,\nHa va tava kuwa walio.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_289, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2832, position: 3, content: "Tuliki epandela lietu,\nVakuanumbi va limbuke.\nOcisola conjovoli\nLomo eye wa va fila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_289, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2833, position: 4, content: "Tuliki epandela lietu,\nLi lekise onjila yiwa.\nOco ava va nyelela\nVa wilemo, va popelue.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_289, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2834, position: 5, content: "Tuliki epandela lietu,\nHa tu yevalisa ciwa\nEkovongo liekulusu,\nKuosi kulo kilu lieve.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_289, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2835, position: 1, content: "Soma yetu weyile voluali,\nWa sanga omanu va pata;\nVa pata lupeke wutima,\nCilo va patuluka.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2836, content: "Ocili! Tua sumuluha.\nOcinyi ca tu tuila.\nTu tavi olumue kondaka yeyovo;\nTu lingi olombangi viayo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_290, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2837, position: 2, content: "Alongisi va iñila vofeka.\nOndaka ya Suku ka tu yi.\nVa sanga omanu va putua,\nVa putua kovitima.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2838, position: 3, content: "Va  kundila omanu eyovo;\nVa ilika onjila yomuenyo.\nVakuavo va yeva lesanju,\nVakuavo puãi va tima.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2839, position: 4, content: "Kaliye, akuetu, tua tava.\nTua sanga etavo liocili,\nEtavo li koka eyovo,\nEyovo liolofeka.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2840, position: 5, content: "Alongisi vofeka katuki;\nKa tuali ondaka komanu.\nVa sukila ondaka ya Yesu,\nOndaka yepopelo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_290, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2841, position: 1, content: "Ku li wa velapo vosi,\nEye Yesu.\nOcisola ca'e cocili;\nEye Yesu.\nVamue mbi va tu pembula,\nVamue vali va tu nyãle,\nEye puãi o tu lemaila,\nEye Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_291, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2842, position: 2, content: "Uwa waye tu u sanda,\nLomuenyo wa'e.\nTavi etali, ho tiameli\nKomuenyo wa'e.\nWa pesela osonde yaye,\nHa popela omanu vosi,\nPeka liaye va tambula.\nOmuenyo wa'e.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_291, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2843, position: 3, content: "Ovanyali va lembuisua,\nLunene wa'e.\nOvakandu a ka imuha,\nLunene wa'e.\nCosi ci tu posokela,\nO tu ciha lonjolela,\nO tu sondoluila kilu,\nLunene wa'e.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_291, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2844, position: 1, content: "Yuvula ayonjo, sanga o lueya.\nKolela Onjovoli, oco o yula.\nLiyaka lehungu kuenda oloñei.\nImba ovaso ku Yesu, o ku kuatisa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_292, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2845, content: "Lomba; Yesu o ku ohela\nKuenda o ku kolisa.\nOve nda wo kolela\nO ku kuatisa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_292, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2846, position: 2, content: "Liuvika keviho; tila ondingaĩvi.\nLingainga esunga, sumbila Suku\nSima violondunge; vangula ocili.\nImba ovaso ku Yesu, o ku kuatisa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_292, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2847, position: 3, content: "Kuata olupili; ku ka konyohe;\nYesu o kolisa u wo kolela.\nSuku eca onima kuava va yula.\nImba ovaso ku Yesu o ku kuatisa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_292, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2848, position: 1, content: "Oku kolela Ñala;\nAmiko. Amiko.\nEndandi vocisola ca’e.\nAmiko. Amiko.\nU panduili ohenda ya’e,\nSapuli ulamba wahe,\nVialeki ocali ca’e.\nAmiko. Amiko.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_293, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2849, position: 2, content: "Oku waya ondaka ya’e;\nAmiko. Amiko.\nLekulusu liahe peka.\nAmiko. Amiko.\nLekolelo lepandi;\nKoleli Cime cene,\nKo ka ci tokoki mbu.\nAmiko. Amiko.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_293, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2850, position: 3, content: "Onjila ya yikuka;\nAmiko. Amiko.\nPandikisi la Yesu.\nAmiko. Amiko.\nLocinyei cokovailu,\nLocali ca’e ca piãla,\nU ka tambuli ocimaho.\nAmiko. Amiko.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_293, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2851, position: 1, content: "Vati, oko o li oku enda\nKu li olohukumo.\nPuãi ulamba ka vo lete\nWa moleha kovaso.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_294, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2852, content: "Yesu eye Usongui wange;\nO ngendaisa lohenda.\nKa ci tava oku enda ulika;\nKumue la'e puãi mitila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_294, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2853, position: 2, content: "Vati, Ungende waco u vala,\nKo ku sumuluisa mbu.\nHaimo Yesu ndu kolela,\nNdici okuti o ndava.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_294, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2854, position: 3, content: "Lika liange mbi nokoka;\nNdukuangusu yitito;\nYesu puãi o tela cosi;\nKumue laye mitila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_294, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2855, position: 1, content: "Wayi ño ombuto\nYina yolondaka,\nWayi ño omele loñolosi le.\nKolisiko upange;\nYesu o tu kuatisa,\nTu iya lonjolela\nPoku ungula kua'e.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_295, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2856, content: "Poku ungula kua'e.\nPoku ungula kua'e.\nTu iya lonjolela\nPoku ungula kua'e.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_295, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2857, position: 2, content: "Wayi ño kutanya.\nWayi ño kulembi,\nKo ka tili ombela\nPamue enyenye.\nEci upange u pua\nOco tu puyuka,\nTu iya lonjolela\nPoku ungula kua'e.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_295, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2858, position: 3, content: "Tu endi loku kula,\nNdaño lasuẽlelã,\nMuele o kuatisa\nOcili upange wa'e.\nOku lila ku pua,\nOco o tu tambula,\nTu iya lonjolela\nPoku ungula kua'e.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_295, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2859, position: 1, content: "Kihandeleko oku yovoka\nCi koka esanju ka li pondoka,\nTua pile lavio; tua fa tupu,\nWa tu yovola Eye Yesu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_296, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2860, content: "Tava, okuetu, tava etali,\nHu tambula omuenyo ocali.\nImba ovaso kekulusu,\nOko Yesu wa tu fila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_296, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2861, position: 2, content: "Cilo episo lia tu lomboka,\nKueya eyovo lia lomboloka.\nTu tumbangiya u wa tu fila.\nKepiso wa tu teyuila.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_296, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2862, position: 3, content: "Yu wa laleka, wa linga hati,\nEnjui kokuange, ene wa kavi;\nYa fina cimue ondaka oyo,\nYoku lalekua komuenyo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_296, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2863, position: 4, content: "Oku tukuiwa omãla va Suku,\nTua sumuluha cimue akuetu.\nTunde kesumuo kuenda okufa,\nToke komuenyo ko pui puã.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_296, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2864, position: 1, content: "Ñale pekuluso lia'e\nPali ovava omuenyo.\nKuli ono yekolelo;\nKuna kongongota.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_297, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2865, content: "Sanjukila hu,\nKekuluso liahe.\nToke nula omuenyo;\nNda yovokelako.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_297, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2866, position: 2, content: "Pekuluso lia Yesu\nNda lulumilapo.\nNda sangelapo ocali;\nPa nyiha ocinyi.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_297, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2867, position: 3, content: "Njivaluise muele hu\nEkulusu liove.\nVundembo liawo, a Cime,\nMbundisemo ciwa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_297, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2868, position: 4, content: "Pekulusu lekolelo,\nNdavuluilapo.\nNoke, kulamba ngenda;\nNda yovoka, ngenda.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_297, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2869, position: 1, content: "Tu lingi upange,\nAkuopange wa'e;\nLa kuosi tu endela\nTu tiami kokua'e.\nO tu muisa ongusu\nLelungulo lia'e.\nKupange wosi wahe tu kuata.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_298, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2870, content: "Ha tu endi... kupange!\nHa tu vumbi Ñala.\nLelavoko, lepandi, lombili\nToke eci Ñala a tiuka.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_298, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2871, position: 2, content: "Tu lingi upange,\nEne wakuopange;\nVotoki lombili, sapuli komanu.\nEkulusu lia'e olio ulamba wetu,\nYesu oka tu iha onima yiwa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_298, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2872, position: 3, content: "Tu lingi upange,\nKuli upange walua,\nUsoma wowelema u ka nyoleha\nLunene wonduko ya Yehova.\nYesu oka tu iha onima yiwa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_298, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2873, position: 4, content: "Tu lingi upange\nU sanjuisa Ñala,\nEkolowa lieyulo eye oka tu iha.\nKomangu yulamba\nTu ka tumãla\nYesu oka tu iha onima yiwa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_298, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2874, position: 1, content: "Kuendi ño; kuendi ño,\nKasapuli ondaka.\nKuli valua ka vala yeva Yesu.\nKuendi ño lepandi: wa noliwili\nOku kuama ovisila\nVia Ñala yetu.\nKoleli Onjovoli;\nKo ka kuati usumba.\nKuendi ño, la Yesu. Kuendi ño.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_299, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2875, position: 2, content: "Kuendi ño; kuendi ño,\nLembimbiliya peka.\nYendelele ondaka\nYeyovo liomanu.\nNdaño kuli ovitangi\nKoleli Yesu.\nNdaño ohali yalua,\nKilu tu ka viala.\nKuatiko avamanji.\nLingi upange wahe.\nKuendi ño, usumba mbu.\nKuendi ño.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_299, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2876, position: 3, content: "Kuendi ño; kuendi ño,\nKundili omanu.\nVa kasi vovitatamela violuali.\nYesu wa va filavo kekulusu.\nUna wa pembuiwa\nHaye wa sepuiwa.\nSapuli epopelo.\nYesu ecela akandu\nKuendi ño, locisola.\nKuendi ño.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_299, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2877, position: 1, content: "Tu votokeli etavo,\nTu lingi olombangi.\nTu tuliki epandela,\nLia Yesu Osoma.\nEye otu songuila\nKatoke tu yula,\nToke anyali vetu\nVosi va tu lembua.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_300, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2878, position: 2, content: "Tu votokeli etavo,\nTu yevi olumbeta.\nMuele otu kovongela\nEteke lieyulo.\nTu votoki akuetu,\nAnyali va lova:\nUhande u wenguke,\nSuku o tu yulisa.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_300, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2879, position: 3, content: "Tu votokeli etavo,\nVosi tu koli ngo,\nOhali ndopo yi pua,\nMuele o ka tu yamba.\nTu wala akolowa\nKofeka yokilu.\nLa Yesu tu ka viala\nOtembo yenda hu.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_300, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2880, position: 1, content: "Nda mola ekamba eye Yesu\nWa neteka oku sola,\nWa ñoka locisola cahe,\nLacovo ca mandeka,\nKutima le wa njitika;\nCinepisa  kaciko,\nMomo ndu waye leye wange\nOtembo, kolotembo.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_301, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2881, position: 2, content: "Nda mola ekamba eye Yesu,\nWa fa oku mopela;\nHamuenyoko lika a nyiha\nPuãi wa li nelekala;\nLacimue ñuete nda cange\nNukowaila cuvangi;\nOngusu lomuenyo wange\nCosi calinga cahe.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_301, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2882, position: 3, content: "Nda mola ekamba eye Yesu,\nUkuahenda ukuacali,\nUsongui haye ondunguli;\nPakisi lupopeli.\nCina a sola ame ndoto,\nCi ka nepisako nye?\nOmuenyo pamue oku fa sio,\nNdu wahe otembo yosi.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_301, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2883, position: 1, content: "Wa tundile kovailu;\nYesu Upopeli.\nWa fila kekulusu,\nYesu Upopeli.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_302, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2884, content: "Sandeki ondaka eyi,\nWa tu nenela eyovo.\nWa tu muisa omuenyo\nYesu Upopeli.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_302, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2885, position: 2, content: "Tua si oku fa luvali;\nYesu Upopeli.\nWeya ha tu yovola;\nYesu Upopeli.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_302, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2886, position: 3, content: "Ohuminyo wa tu ihã;\nYesu Upopeli.\nHati, otava o yovoka;\nYesu Upopeli.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_302, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2887, position: 4, content: "Iya oku tu upilila;\nYesu Upopeli.\nO tu tuala konjo ya'e;\nYesu Upopeli.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_302, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 2888, position: 1, content: "Kupãla kumue kuli olofeka,\nKu kuete ava voku nyelela;\nHelie o katuka oku va longisa\nOku imba ovaso ku Yesu lika?", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_303, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2889, content: "Ya nyihiwile ongusu, (2x)\nKuendi kolofeka viosi ka longisi;\nLame ñasi lene  kumue.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_303, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 2890, position: 2, content: "Vanji olofeka, vo va ku laleki;\nWa sualali a Yesu katuki;\nWa kuetavo pasuki! Litokeki!\nEsapulo li Ondaka ka  tuali,", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_303, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 2891, position: 3, content: "Nye u nyelila? Suku yu wa pula,\nNye u nyelila? Lene u va pula;\nYesu wa fa oco va ka popelua,\nEyovo kuenda omuenyo o wiha.", hymnsNumber: UmHymnsNumberSeeder.UVANGI_LUPANGE_303, typeStanza: HymnsContentCode.VERSE),
  ];
}