import 'package:ieca_mobile/enums/hymns_content_code.dart';
import 'package:ieca_mobile/models/_import.dart';
import 'package:ieca_mobile/seeders/_import.dart';

class KmHymnsGeneral {
  static List<HymnsContent> list = [
    HymnsContent(id: 3900, position: 1, content: "Nzambi ietu, itaia kiá! Tu kuatekese ue Ni nguzu ié Tata ia henda ngó Ei’u Munène, Amén! Zá, Ngana, utume kiá Muxima iú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_1, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3901, position: 2, content: "Izé kiá, u Jezú, Suinisa xibulu jé! Ngana Nzambi, Benzela athu bhox’ N’ambate maka mé A bhane Nzumbi ié Phal’ende-nâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_1, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3902, position: 3, content: "E’ Nzambi Imoxi ngó, Tu bheze ‘jina dié Katé Jezú Uiza n’uzonda uê Hé u tu ambata kiá Ni tuii ku’bhata diê Mu kala-nê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_1, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3903, position: 1, content: "Mua mu ijiia, ximanenu Ngana Jezú, Kibamueniu; Mieniu iene tu i ba muene, Ietu ioso, iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_2, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3904, position: 2, content: "‘Jina dia tu toualela, Dia Jezú ua tu bangela; Kioso kiza, tu dielela O kusuina kuê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_2, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3905, position: 3, content: "Maka mê ma kubuluka Kioso kiambe k’aluluka Muanu uê ki u batuka, Ua kilunga kiê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_2, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3906, position: 4, content: "Ngana, tu ku nienganana, Tu jijila o kuxikana, Katé hinu tua kèmana Bu kinama kiê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_2, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3907, position: 5, content: "Diene ‘bata di tuandala, Bene ioso ia tokala: Mbote jiniá já kà kala Ima ietu kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_2, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3908, position: 1, content: "Ngana Nzambi Ukôla U Nzambi ia jinzambi, Selu mu kimene Tuimbila fuma ié. Eie u Nzambi ia kidi, Kana-ku Nzambi iengi; Tata, Mona, Nzambi, Ei’u Nzambi imoxi ngó.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_3, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3909, position: 2, content: "Ngana Nzambi Ukôla, Kuvunda kua ku sueka Katé akue ‘tuxi Ka mona fuma ié. E’ Mubangi uetu, Mubangi a ima ioso, Eie ua kexile, U kala, ua kalé.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_3, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3910, position: 3, content: "Ngana Nzambi Ukôla, Jianju ji ku imbila, Oso ala bulu A beza ‘jina dié; Etu uetu boxi, Tu tuana tué tua kidi. Tua te uetu dízui Mu diximanu dié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_3, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3911, position: 4, content: "Ngana Nzambi Ukôla, U Nzambi ia jinzambi, Selu mu kimene Tuimbila fuma ié. Eie u Nzambi ia kidi, Kana-ku Nzambi iengi; Tata, Mona, Nzumbi, Ei’u Nzambi imoxi ngó", hymnsNumber: KmHymnsNumberSeeder.GENERAL_3, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3912, position: 1, content: "Ngana Nzambi muène ukôla ngó, A diximane ‘jina dieniidi! Ngana ietu muène ukôla ngó, A mu fumanesa ku’atu oso. Banenu diximanu dia kidi, Kua Nzambi ietu imbenu kiá. Ngana Jezú muène ukôla ngô; A mu fumanese ku’atu oso.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_4, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3913, position: 2, content: "Ngana ietu o kuiuka kuê! Kua muène ki kuene o katungu. Ngana ietu o kuika kuê! Utuminu uê pal’etuoso. O kiandu kiê kiezala ni henda; Kutena kué, ó Ngana Jezú! Ngana ietu o kuiuka kuê! Utuminu uê pal’etuoso.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_4, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3914, position: 3, content: "Kidi, kidi, henda ia kalé! Uejiia ioso, uívua ue ioso; Kidi, kidi, henda iahi ngó! Kiambatele ituxi ia mundu. Sumbala ku dik’lusu dianeme, Hanji ua zolo jinguma jê. Kidi kiene, henda iahi ngó! Kiambatele ituxi ia mundu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_4, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3915, position: 4, content: "Henda, henda, henda ki ibué, Ia mu’izalesa utu ue uoso. Henda, henda, henda ia Jezú, Ima ioso ngó madiuanu. Tu’endese, Ngana, bu’oto ia ngiji, Tua kève ubulukilu uê; Henda, henda, henda ia Jezú, Ima ioso ngó madiuanu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_4, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3916, position: 5, content: "Uoso uevu ngonge ia Jezú, A lenguluke kubalumuka. Diela selu o ituxi ié, U sange ufolo kua Ngana, Imbenu nguzu, enu jifolo, Kua Nzambi ietu imbenu kiá! Ngana Jezú muene Ukôla ngó. A mu fumanese ku’atu oso!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_4, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3917, position: 1, content: "Ximana Nzambi Ua tu bhana Mon’ê Ua tu fuila ku k’lusu Uaii di’kua Tat’â.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_5, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3918, content: "Aleluia! Mubuludi! Aleluia! Amém. Aleluia! Ua tu kula; Ximana Nzambi!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_5, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3919, position: 2, content: "Tu ximane ue, Nzumbi Ikola iuná Uendesa Jezú ‘Te kia tu kula ue.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_5, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3920, position: 3, content: "Ximanenu ue, O Kambudi Jezú, Uambata o kalunga Ni kúfua kuê kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_5, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3921, position: 4, content: "Tu tanienu ue, Jezú ni anjo jê Anda kuiza kuambata O Ngeleja iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_5, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3922, position: 1, content: "Ngende katé bu diklusu diê, Nga mu fukama bu inama iê, Muene ua ng’ivu, ngadiama iê, Ngi ximana kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_6, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3923, content: "A ximane ‘jina diê, A ximane ’ jina diê; Ngejiia, ua ngi bulula kiá. Sai umbangi uê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_6, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3924, position: 2, content: "Nga mu diuana, muen’ió Jezú. Ua ngi loloka mu henda ngó. Nga tambula-bu ufolo iú, Ngi ximana kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_6, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3925, position: 1, content: "Ki ngi tala ku dik’lusu, Klusu dia jipaxi jê; Ngana Jezú ua ngi sungu Ku ubulukilu uê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_7, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3926, content: "Ngi ximana! Ngi ximana Ngi ximana ‘jina diê. Ngana Jezú ngi mu imbila, Ua ngi kula ni maniinga mê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_7, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3927, position: 2, content: "Njila iê iatolo kidi, Pulu iami nga i xie Jivondadi ni jihanji Jaii mu kizanga kié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_7, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3928, position: 3, content: "Nga di bana kiá kua Jezú Ioso nga ilumbila uê, Nzumbi Ikola ua tuluka Ua ngi be kidifua kiê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_7, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3929, position: 4, content: "Tubia tuê tua ngi zelesa, Ngala kiá mu henda iê, Ngi di bana ku mu imbila Fuma ia dijina diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_7, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3930, position: 5, content: "Aleluia! Ngana Jezú, Ua ngi tambulula kiá, Ua lolok’ituxi ioso, Ua ngi be dibesá diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_7, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3931, position: 1, content: "Ngolokela tua i vué, u bulula, Kristu ió! Tumbulenu fuma iê, u bulula, Kristu ió! Ku makang’endenu bá Mu ijidise ukunji iú, Atu oso evue kiá, U bulula Kristu ió.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_8, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3932, position: 2, content: "Mak’a fuama kuenda nâ, u bulula, Kristu ió! Ku maxokololo kiá, u bulula, Kristu ió! Sai-ku ua tu fuila kiâ, Pala atu ka fue di’ Uoso u xikana kiá, u bulula, Kristu ió!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_8, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3933, position: 3, content: "Njimbu iii iende kiá, u bulula, Kristu ió! O kitembu pe mukuá, u bulula, Kristu ió! Menia ma kalunga iá, Sai milundu ni mikau. Iende ni mababa kiá, u bulula, Kristu ió!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_8, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3934, position: 4, content: "Imba nguzu, suina kiá u bulula, Kristu ió! Ka landuke ‘buia jâ, u bulula Kristu ió! Imba uê kilendu kiê, Mbebu ia mu ‘lamba ngó Né mu bombo, kùfua kiá, u bulula, Kristu ió!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_8, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3935, position: 1, content: "Tanesa ‘jina dia Jezú, Kifuxi kioso kiá; A m’unde ni kitundu kiê, Ene-oso Ngana iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3936, position: 2, content: "Ni Izraele, muiji uê, A mu’ind’okulu kiá; Lelu a xikane ‘jina diê, Mexiia, Ngana iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3937, position: 3, content: "Akua ituxi eze phe Ku di bakula uá A dionde bu kinama kiê, A suue Ngana iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3938, position: 4, content: "Ku jixi, ku madimi mâ, Atu osololo kiá, Etaie utuminu uê, Muenexi, Ngana iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_9, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3939, position: 5, content: "Ni mundu ió bu kiandu kiê Ni atu boxi kiá, Ua a sumbu ni maniinga mê; A beze Ngana iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_9, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3940, position: 1, content: "Lelu, lelu, tu imbidienu, Diximanu dia Jezú; O ungana ni ujitu, Uá mu fuama muene ngó; Bulu, Boxi, jixi joso, Muene Ngana ubeka uê. Kibamueniu pe kia mundu Pange iâ dikamba diâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_10, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3941, position: 2, content: "Tuimbidienu, kia touala, Tumbulenu henda iê; Kioso kia tundu-ê ku diulu Kudibanga mutu box: Ua suku-Ku  uadiama, Ni ku pax’ia kùfua kuê, Kuma pe ua fukunuka, Kubulula ua Soko-ê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_10, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3942, position: 3, content: "Tuimba jinga, tu imbidienu, Tu bandienu akunji ê, O jisandu ni jianju A tanese ‘jina diê. Kolokota kuxikana, Hinu ki bua mueniu iú, Tua kà sanga ‘pange jetu A bixila kua Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_10, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3943, position: 1, content: "Tu imbetu fuma ia Jezú Ivenu, akuetu oso. Se mu dielela muene ngó, Jezú u mi bulula.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_11, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3944, content: "Tu mu tumaka ijila iê, Tu mu sambela jinga ue, N’a tu bane Nzumbi iê, Mu mixima ietu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_11, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3945, position: 2, content: "Jezú ua zola atu oso, Uandala a zediue: U loloka ituxi iâ Kabasa a i ambala.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_11, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3946, position: 3, content: "Tuala ni maka ma Jezú, Kikale tu m’ejiia: Tu kale jifiiele jê, Tu mu uabele muene.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_11, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3947, position: 4, content: "Tu zole Mubuludi ió Ni henda ietu ioso: Tu fule ima ioso kiá, I tena ku mu ‘ibila.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_11, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3948, position: 5, content: "Jezú ua fukunuka kiá, Ua bande eu ku diulu: Ene oso a luka maka mê, Kuniá a kà mu mona.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_11, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3949, position: 1, content: "Uoso ua bindama, ive-kiu kiá! Kià ku ixana Nzambi, tala, uemana, Ua ku tambuisa ujitu ua mueniu; Uoso uandala, ezé!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_12, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3950, content: "Uoso uandala! Uoso uandala! Itaienu kixanu’iki kia Nzambi; Tat’etu ia benda ua mi’manena; Uoso uandala, ezé!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_12, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3951, position: 2, content: "Uala ni diniota, menia iá-ue iá; Né kualé kitadi, zá u tambule. Kudi’uku kua kidi, menia ma mueniu Uoso uandala ezé!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_12, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3952, position: 3, content: "Ima ia makutu, ki kudia ngó, U i texil’ahi o kitadi kié? Ivua o mulongi, u die kiuaba. Uoso uandala, ezé!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_12, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3953, position: 4, content: "Mu jikuile ditui, tetuluka kiá; Maka mê eniâ ka sangunuka di, Xikana o kidi, nda u buluke; Uoso uandala, ezé.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_12, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3954, position: 1, content: "Kilunga kiá hâm’a ‘mbudi sai, Kieniê mu kibanga kiâ; Hé bu kala ni iú, kamoxi ngó, Ua di texila ku mukáu. Mu ikanga ngó, ku iama kiá, Ua kambe kunienga kabila kâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_13, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3955, position: 2, content: "«E’Mubidi, jimbudi jé, ji-jé? O makuinh’ivua n’ivua diê?» «Kilalu ngó, Mbudi iami ió, Muen’iú ua xiê mu akuá, Mikáu, milundu, ng’i niunga phe, Katé nga mu beka bu nangu diê.»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_13, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3956, position: 3, content: "Ngana, ki end’okio, ua ki mono, na’i? Jihonga já vuu ue, Usuku ku vunda kuahi ngó, Ki a bongo kambudi kê! Ua ivu ia didi, makang’aniá, Ia kumbama, ieje kudiua kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_13, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3957, position: 4, content: "«Maniinga pe, Ngana, ahi oso-á. A xala mu hoka ié? Inama ni maku ia tuil’a’i? Ua di xuua ku minia ue» «Ua jimbidile, muene ua ngi t’ú Ku mu endela kua di tex’oko.»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_13, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3958, position: 5, content: "Ku luiji phe, usuku ió, Kua nokena o muadi’â, Ku diulu evu-ku o nzongo iê: «O mbudi ng’e mono kiá!» Jianju jetaia, já tana ue, Ngan’etu ua bongo kilalu kié.»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_13, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3959, position: 1, content: "Mubidi uami Jehova, U ngi bana ioso; U ngi songuela o njila, Ku ngiji menia mê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3960, position: 2, content: "U ngi betula muxima, Ngendela mu uembu uê; Mu njila jê já kuiuka, Mu dijina dia mon’ê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3961, position: 3, content: "Né um dikolo dia kufua, Ngi bua uoma ni Jezú; Maka mê mbangala iami, Ma ngi konda, kidi kiê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3962, position: 4, content: "U ngi zalela o meza, Bu pholo ia ‘nguma jê, U ngi lunduluila o Nzumbi; Muxim’ami uizalé.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3963, position: 5, content: "Mu mbote iê nga kondama, Katé nga bixila nê, Hé nga kà kala ni Nzambi; Mu dibata diê diná.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3964, position: 6, content: "Ngalu mi dionda, jiphange, Mu  jihenda ja Jezú; Dibakudienu mikutu, Sata ia mueniu-kokuê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3965, position: 7, content: "Maka ma tata Jehova, Kene ni mahezu mê; Ivenu ku njimbu iii, Mu di bakule, Amem!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_14, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3966, position: 1, content: "Nzambi mua Kristu ua tu zola bá, Uate kikutu ua tumu Mon’ê, Iú ua tu fuila ku k’lusu diná! Talenu henda Iê, Talenu henda Iê, Talenu Henda Iê, Iú ua tu fuila ku k’lusu diná, Talenu Henda Iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3967, position: 2, content: "Zenu mu diuane henda ia Jezú! «Eme ngi njila, ngi kidi tat’é» Mueniu ki uabua ki kale kokuê; Lolenu Henda Iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3968, position: 3, content: "Ngana iú kinga iú ku’ixana ue, Xisa ufusa, itaia kokuê, Tambula mueniu muloloko ue, Nda u buluke kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3969, position: 4, content: "Sai kizuua phé, Jezú iú uizé, Ku’ambata Ng’leja, o dibanga diê, Polo ni polo tuà kala nê kiá, Ni kuimba fuma Iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_15, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3970, position: 5, content: "Tana-ku Ngana! Ukola! Amem! Tua ku tondela, tua ximana ue; Kiki tua bixila ku mbanza Iê, Kolenu Fuma lê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_15, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3971, position: 1, content: "Iza kiá, u Nzumbi ia Nzambi, U ng’imbise henda ié; ‘Zuua ioso ngene naiu, Ngi dixiba naiu kie? Ngi longese muimbu uobe Uala kuimba hule jé; Iá ku diulu a ximane Mubuludi ua Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_16, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3972, position: 2, content: "An’a Nzambi mu xahulu Kia toluele ‘nguma já; A zanguile kiditadi Mbangi ié, U Ngunza iâ ‘Tadi dia dikuatekesu, A di luka ‘jina diê. Kiene ue ngi banga jinga, Mbangi ia jimbote jé.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_16, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3973, position: 3, content: "Nga kexile mu iluezu Nga bolele mu ituxi Mon’ê pe mu ngi bulula Ua tudile mueniu uê, ‘Kongo diami dia ituxi Muene ua di jimuné, ‘Kongo diami dia jihenda Nuka dia kà buila pe.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_16, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3974, position: 4, content: "Mbudi ii’ia jimbidile Jezú ua ngi soto pe; Ua ng’ambata bu isuxi, Ua ngi tula m’onzo iê. Tambule muxima uami, Maku ni inama ue. Kondeka-iu, Ngana iami, Nuka dingi ngi ku xié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_16, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3975, position: 1, content: "Ize Nzambi, Nzumbi ia Mbote,\nDizui dia mueniu,\nTonesa mixima ietu,\nKuivua maka mé,", hymnsNumber: KmHymnsNumberSeeder.GENERAL_17, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3976, content: "Nzumbi ia Nzambi!\nUize ungana ué;\nTu’ivue, Ngana, tua ku diondo,\nBane henda ié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_17, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3977, position: 2, content: "Ize ku tu kuatekesa,\nTu bane mueniu,\nTu muikine mua vundu,\nU zelese-mu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_17, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3978, position: 3, content: "Ize Nzambi, Nzumbi Ia Mbote,\nKu tu tekula,\nTu longe o kidi kioso\nKi ban’ufolo.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_17, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3979, position: 4, content: "Ize Nzambi, Nzumbi ia Mbote,\nKu tu tenesa,\nU te ku mixima ietu\nO kidimbu kié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_17, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3980, position: 5, content: "Ize, tualu kinga baba,\nIze kindala,\nUike mu mixima ietu\nTubia tua henda.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_17, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3981, position: 1, content: "Ndokuenu, mua xikana,\nMakuenze ma Jezú,\nTuienu kiá ku polo,\nTu kuate ‘klusu diê,\nJinguma Jê javulu,\nNdoko, tua kà luê nâ,\nO komanande ietu\nUa tuamenena kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_18, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3982, position: 2, content: "Endenu mua xikana,\nDielelenu Jezú.\nMakuenze mê, suinenu,\nNdenu ni nguzu ié.\nKa kambe kukudila,\nTuemana ni ku samba,\nMu’axaxi ka iluezu\nU bânga njila iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_18, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3983, position: 3, content: "Enu oso mua xikana,\nMuala mu henda iê,\nNé mbe tua mono paxi\nKi tu buidienu di’.\nHinu sé dizubilu\nTuà mu ximana kuniá;\nMutololodi a ioso,\nIó Jezú Kristu ngó", hymnsNumber: KmHymnsNumberSeeder.GENERAL_18, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3984, position: 1, content: "Kana ki kuenié ukamba\nKal’ukamba ua Jezú.\nMuene ua tu tumu et’uoso\nKu di beka kiá kokuê.\nMuxima se ua ku neme,\nNi malamba ni ngongo,\nNdé kua Ngana, u mu ambele\nIoso kiá uala naiu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_19, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3985, position: 2, content: "Se ua buila, se ua tate\nNi jipaxi ni uoma;\nJezú muene disuamenu\nMu dielele muene ngó.\nSe makamba mé ma ku xia.\nNdé, ka muambele-kiu ue;\nMuene u ku bana uembu,\nUizala ni henda iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_19, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3986, position: 3, content: "Jezú dikamba dia kidi:\nKidi, tua ki mono kiá,\nKioso kiejile kuambata\nO itux’ietu ioso.\nManiing’ê ua ma texile,\nMixim’êtu n’i zedié;\nMuene u tu bana mueniu,\nMueniu sé ‘zubilu diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_19, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3987, position: 1, content: "Kua Jezú eme, ngi tanga ioso,\nI ngala naiu mu thul’umu;\nIoso i ngi banza mu mueniu uami,\nKi kale Muene u i’iukisa ngó.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_20, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3988, content: "Kua Jezú Kristu, Dikamba diami,\nNgi tanga ioso, i ngala naiu;\nIoso i ngi banza, mu mueniu uami,\nKi kale Muene, u i iukisa ngó.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_20, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3989, position: 2, content: "Kua Jezú, eme ngi tanga ioso,\nMuene Dikamba, kimbaka uê;\nKi u mu binga, u lenguluka,\nKu kuatekesa a tâte uê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_20, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3990, position: 3, content: "Kia ngi tatesa uê ku jinguma,\nJezú Mukudi u ngi langa uê;\nMukonda Kristu, Muene dizonda,\nDi tena ku ngi kuatekesa.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_20, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3991, position: 1, content: "Ngana, tu tunge, Usuku ueza kiá,\nKuma kua vundu...Kale Eie ngó,\nU ngi kudila, uoma ni u bue.\nIzá, Ngana, u tunge n’eme kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3992, position: 2, content: "Kindala muene kùfua kueza kiá;\nIma mu ngongo i jimbila ue;\nIoso ngi mona ia biluka kiá.\nNgà kà tunga ni Nzambi, kuabu kiá", hymnsNumber: KmHymnsNumberSeeder.GENERAL_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3993, position: 3, content: "Ditukuluile ko kuami, Jezú,\nMesene iami, Soba iami ue,\nDikuatekesu, Musonguedi ue,\nIzá, Ngana, u tunge n’eme kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3994, position: 4, content: "Kuoso ngi kala, Nzambi iú-ue-iú,\nNé-mbé kua vundu, uoma kana di’\nNé-mbé o mbila, mba kalunga ue;\nBuoso bua tungu Nzambi, kuabu kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_21, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3995, position: 5, content: "Kalunga, lelu ua ngi lémbua kiá.\nEie, u mbila, ua lémbua-ku ue,\nMukutu uami ua kà tunda ue;\nNga kà tunga ni Nzambi, kuabu kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_21, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3996, position: 1, content: "Enu ‘pulungu jê, mua bondalala,\nTata ia henda sai, uivua an’e;\nZenu bu inama iê, zenu kusamba,\nBuala kididi, diniohenu diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3997, position: 2, content: "Muene u betula ió ua toloka,\nUidika njila iê ió ua di tex’;\nUoso u diela ngó, mulonga ua bu;\nU tululula, u konda kisox’.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3998, position: 3, content: "Kudielelesa kuê kene kufula,\nKinga kimuanu kiê, Tat’etu ió:\nNé ua mu bingi pe, iú ua ku’imina,\nUa ku bakela, sai hinu dilau.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_22, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3999, position: 4, content: "Ua kambe Nzambi iê, ndé kà mu ibule,\nKi mu’iza hadi iê, U dielel’a’i?\nNgana se tuala nê, uebi ua kambe?\n‘Lamba dia uenji, uzonda, uê sai.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_22, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4001, position: 1, content: "Kisangela sai kuenda ni Jezú,\nNi mu kuivua jinga dizui diê;\nO kuzediua kuivua paze iê.\nKuenda jinga ni lúkuaku luê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4002, content: "J-e-z-ú J-e-z-ú\n(Henda ia Jezú, Henda ia Jezú)\nTambule mueniu uami iú,\nJ-e-z-ú J-e-z-ú\n(Henda ia Jezú, henda ia Jezú)\nNguzu nga i sange mua Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_23, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4003, position: 2, content: "O kuuaba kuenda jinga nê,\nNi mu kuivua jinga henda iê;\nJezú tuala nê, ua tu muika’ue,\nTuenda jinga ni lúkuaku luê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_23, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4004, position: 3, content: "Pata iabu kiá, tuala ni Jezú,\nNi tu muiva jinga Nzumbi iê,\nUoma uahi di, paze ieza kia,\nTuenda jinga ni Iúkuaku luê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_23, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4005, position: 1, content: "Kuniá, kuniá, ku jixi já makanga,\nMu itombe bui, akuetu iá buil’a\nNa’i, nanii kiá u sola ku ki banga,\nKuia ku a kula mu iluezu iâ?", hymnsNumber: KmHymnsNumberSeeder.GENERAL_24, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4006, content: "Ene oso, eme Ngana iâ,\nMu diulu ni mu ngongo kiá,\nNdenu pe ka jimbudienu maka mami,\nNgá kala bu mbandu ienu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_24, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4007, position: 2, content: "Talenu mielu ioso ia jikuka,\nAtu a bingi maka ma Jezú.\nMahamba mâ ene oso atumbuluka,\n‘Jina di kola dia Ngan’etu ngó.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_24, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4008, position: 3, content: "Makuenze mê! Ndokuetu, tu kuatienu,\nTu sambukise utuminu uê.\nOso ejiie sai-ku Kibamueniu,\nKolenu fuma ia dijina diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_24, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4009, position: 4, content: "Kizuua kiê, tamanu kiendela-ku,\nKuivua mu jixi o kikoue kiê:\nJihule jê ji kala mu tana-ku,\n«Tua banduluka ngó mu henda iê»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_24, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4010, position: 1, content: "Hadi jé javulu,\nKu jitanga kutené,\nNe ua didi kutené,\nEhelaju ngó Jezú,\nHadi jé javulu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_25, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4011, content: "Tala Klusu dia Jezú,\nDia dikiza henda ie\nI katula ituxi ie,\nJezú u bulula.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_25, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4012, position: 2, content: "Ne ua kalakala,\nSe ku nioha, hadi ngo,\nO jingongo ki jibue,\nO malamba ma kalê,\nNguzu ki bulula.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_25, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4013, position: 3, content: "Ne ua samba jinga,\nNi kusuina kuoso kia,\nNi kudionda kuoso kia,\nNe ua diela ioso kia,\nSota ku buluka.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_25, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4014, position: 4, content: "Jezú u bulula.\nItuxi iami iabu kiá,\nKiadi kia ngi zelesa,\nNgala kiá ni henda ie,\nJezú u bulula.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_25, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4015, position: 1, content: "Zenu ana-ndenge, zenu kua Jezú,\nIó uafuile ku dik’lusu pal’enu;\nO ana-ndenge, muene u’exana:\nZenu kua Jezú Kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_26, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4016, content: "Zenu, zenu, kua Muadi Jezú,\nZenu, zenu, kua Muadi Jezú,\nIó uafuile ku dik’lusu pal’enu;\nZenu kua Jezú kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_26, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4017, position: 2, content: "Ki mu laleke-pe, izenu lelu;\nKana-ku njila iengi iia ku diulu;\nO ana-ndenge, muene u’a zola:\nZenu kua Jezú kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_26, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4018, position: 3, content: "Zola ana-ndenge, Jezú ua ki ambe:\nUanda ku mi beka ku ixi iauaba;\nUanda ku mi bana mueniu ua bulu:\nZenu, kua Jezú kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_26, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4019, position: 4, content: "Ivua ki a m’ixana, Zenu kual’eme:\nKana-ku dingi ua mi zola kiki;\nHenda iê ki ieniê ni dizubilu:\nZenu kua Jezú kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_26, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4020, position: 1, content: "Sai kikalakalu kieie ngó, kidistá,\nA ku xindila-kiu pala eie ngó.\n«Zá! Uambele Kristu,» Tuma, Ngan’emiú\nAkalakadi-oso, ki kal’eie ngó.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_27, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4021, content: "Kuata ‘Kalakalu kiê\nSé dixinga, nguzu ioso, suina kiá!\nKuatekesa Ngana ié.\nOso ka ki tena ki kal’eie ngó!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_27, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4022, position: 3, content: "Muxikani uoso, kuila ua diela kiá.\nNgan’u mu xindila ‘kalakalu kiê;\nKi ua dixibe-phe, ku i banga nguaie\nUafika uamukuá u kalakala né?", hymnsNumber: KmHymnsNumberSeeder.GENERAL_27, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4023, position: 4, content: "‘Kalakalu ioso sai ni ‘lebu diê;\nNgana iú kutala kutumaka kué;\nKios’utala hadi, ki hadi ia ngó,\nFutu ié ku diulu, Ngana ua i bakié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_27, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4024, position: 5, content: "Ndumba a jimbila, ku a sota nguaie?\nA mesena a diela, u a dimuna nê?\nKristu ue na a zola; nde kà exame kiá.\nSe nguaie kuia-ku, ‘kokolo dié kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_27, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4025, position: 1, content: "Tuivua dizuidia dikola,\n«Nanii u kalakala ue?»\nA tu kase ku mulenga,\nTuia mu kumuna kiá,\nNgana uexana kindala\nFutu ietu koko sai;\nNanii uenda n’a mu ambela\n«Ngi tum’iami, Ngana, em’iú?»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_28, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4026, position: 2, content: "Ndé uidike aku’etuxi\nMubuludi uetu ió;\nNdé! uendese o tumbudi\nKaté kiá bu nangu diê.\nNdé ni maka, tululuisa\nOso a mona hadi iâ;\nNdé! uambele mundu uoso\nSai ku mueniu kua Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_28, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4027, position: 3, content: "Ka ku mone usemenii,\nEie a ku kase ue.\nMundu uia mu Kalunga,\nNgana ka mu ijiia phe.\nTala muene iú ku dionda,\nIvua ngó kixanu kiê;\nMu tangele kia kindala,\n«Ngi tum’iami, Ngana, em’iú».", hymnsNumber: KmHymnsNumberSeeder.GENERAL_28, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4028, position: 1, content: "Alu ngi kuatesa uoma\nMu kikoka kia Jezú,\nExi, muala ngó jingongo\nMaji ngenda ni Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_29, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4029, content: "O, Jezú, ng’endese, Ngana!\nTe bu buila mueniu iú;\nOxi ioso iala iluezu:\nU ng’endese, u Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_29, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4030, position: 2, content: "Exi, ualu tala hadi,\nUandu suka naiu kué?\nMaji ene ka ki’jiia\nKuma Ngana ngala nê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_29, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4031, position: 3, content: "‘Ndandu jami exi, «U kioua,\nUa di sebulula ngó;\nSai kizuua uandu diela,\nAnga u vutuka di’.»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_29, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4032, position: 4, content: "kidi kiene, ngi mubhuidi\nO kulueza kua kalé,\nMaji nganda ku tolola\nMu kutena kua Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_29, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4033, position: 5, content: "Enu akuetu, tua di kase:\nKuxikana kuetu sai;\nSulukenu ku musanza,\nKuma Ngana kuene kuaii.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_29, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4034, position: 1, content: "Kuua mu kimene, kuua ue mu muania\nKuua ue ni henda, kuua maka mê;\nKuua pe ni muanu, Ngana ua ku tumu.\nMuene u tu ehela kuongolola nê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_30, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4035, content: "Tuanda kuiza di’ni ibundu iê.\nTuiza ni ngalasa ni ibundu iê.\nTuanda kuiza di’ni ibundu iê.\nTuiza ni ngalasa ni ibundu iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_30, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4036, position: 2, content: "Kwa ue mu mvula, mu kilembeketa.\nKi tu lenge mbambi, né-mu hadi ngó;\nKidi mu katembu tuanda kuiza dingi\nNi kusanguluka, oso mua Jezú", hymnsNumber: KmHymnsNumberSeeder.GENERAL_30, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4037, position: 3, content: "Kuua ni kusamba, kuua ni kudila,\nNzumbi Ikola muene ni njianju jê,\nA ku endese jinge katé tembu iabu;\nN’uvutuke dingi ni ibundu iê", hymnsNumber: KmHymnsNumberSeeder.GENERAL_30, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4038, position: 1, content: "Kana kuitaia mu tendasá,\nUetaia uafu mubetu uenió:\nSai-ku dizonda bu mbandu ié,\nU lendesa mutu mu mvunda ié.\nBinga nguzu kua Ngana,\nIa ku bânga ni nguma;\nMuene u ku kudila,\nDizonda Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_31, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4039, position: 2, content: "Mubombi mu lenge, ku laleke ngó,\nUa vulu jindunge mudiangudi ió.\nBu nanga ilalu, mu junga iâ,\nXikola iaiiba, tunda-ku kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_31, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4040, position: 3, content: "Kana jindaka mu ‘kanu dié,\nNé ngó kubuma mu ifua ié;\nKala ni ujitu, ukumbu né;\nO uoma ua Nzambi dijinu dié", hymnsNumber: KmHymnsNumberSeeder.GENERAL_31, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4041, position: 4, content: "Uoso u lenda, sai-ku dilau;\nKikoue, kitundu, ku mbanza kuná:\nJijila ku samba, tala kua Jezú;\nUzonda ua muene, mukudidi ió.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_31, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4042, position: 1, content: "Tal’abidi a jimbudi\nAnju lang’ilunga iâ,\nAnju anga i tuluka,\nI bixila mbandu iâ:\nIeza ni kubenia kuoso\nUix, Ivenu, mundu uoso,\nLelu m’oxi’a Beleme\nMueza Mubuludi uê.\nLelu m’oxi’a Beleme\nMueza Mubuludi uê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_32, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4043, position: 2, content: "Ki mu kale phe ni pata,\nSai-ku kijimbuete kiê:\nMu kidilu kia jimgombe\nMuene muala muanza uê,\nNi kifuxi kia jianju\nKieza mu tondela Nzambi,\nExi, «Fuma ioso iê;\nLelu kueza uembu uê;\nNi mu’axaxi k’atu ê\nLelu kueza uembu uê».", hymnsNumber: KmHymnsNumberSeeder.GENERAL_32, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4044, position: 1, content: "Nzambi’iami kioso ngi um xinganeka,\nNi madianu a bange o maku mê.\nO jitetembua diulu n’inuminu,\nNi ima ioso ia diuanesa.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_33, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4045, position: 2, content: "Mueniu uami imbila-ze Nzambi iê,\nUkôla bá! Ukôla bá!\nMueniu uami imbila-ze Nzambi iê,\nUnene uê, Ukôla bá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_33, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4046, position: 3, content: "Kutala matutu’amixi ni iangu;\nKu’ivua tunjila mu isasa kuimba.\nNg’ila ngi tala mu makeni’anzongo\nNg’ivua tungiji t’u kunguluka.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_33, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4047, position: 4, content: "Kioso ngi banza kuila Nzambi muene,\nUa bele Mon’ê k ungi fuil’eme,\nPhata i ngi kuata kuila kidi muene\nUa bele mueniu uê mukonda diam’i.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_33, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4048, position: 5, content: "Kia kèza Kristu ni nzongo ié ia suína,\nUixi, tuietu ku’bhata Dina;\nKutana kuahi! Nga mu fukamena\nNgi mu tangela: Ngana Ukôla bá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_33, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4049, position: 1, content: "Zenu, muive mak’ambote\nA Jezú mu Beleme;\nKia mu vuala mona ndenge,\nMon’a Nzambi phe:\nO jianju já mu imbila,\n‘Te tubila tueza ue;\nA mu sange, a mu beza,\nEmba fuma iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_34, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4050, content: "Tangelenu mundu oso\nMak’ambote a Soba iâ:\nNgana Jezú, Mubuludi,\nA mu vuala kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_34, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4051, position: 2, content: "Mutu uala ni malamba,\nIvua hanji maka iâ:\nTala muelu ua jikuka,\nKristu ueza kiá.\nZá, bokoné ku ufolo\nSakidila mbote jê;\nLelu a mu vuala kidi,\nMubuludi uê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_34, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4052, position: 3, content: "Sakidila, sanguluka,\nU ximane ‘jina diê;\nPaze, paze sé ‘zubilu,\nO dilau dié. Balumuka, tu mu imbile,\nUeza kiá ni henda iê;\nMaku ê lelu a jikuka,\nKristu ‘kamba diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_34, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4053, position: 1, content: "Ng’lasa mu ngongo ioso sai,\nKuma Jezú Ueza kiá!\nIú ueza mu henda ié\nKukula o mundu uê\nKu ituxi ioso kiá,\nKu ituxi ioso kiá,\nKukula mundu uê ku ituxi iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_35, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4054, position: 2, content: "Ungana uê ua paze kiá\nIa soko o mundu uê;\nUandala ku’idikiza\nEn’oso a dielela\nMadiuanu a henda iê,\nMadiuanu a henda ié,\nMadiuanu avulu a henda iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_35, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4055, position: 3, content: "Ku’ehele dingi nguma iê\nKutolola mueniu uê.\nTanesa pe Ngana, u kuxi\nKuisa mu lumbu iê.\nMadiuanu a henda iê,\nMadiuanu a henda ié,\nMadiuanu avulu a henda iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_35, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4056, position: 1, content: "Ivenu njimbu ii iambote:\nNgana Jezú Kamba dié.\nUa sumbu ufolo uê ua\nkidi Ni maniing’a tulu iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_36, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4057, content: "Nanii ua tu bela mueniu uê?\nNgana Jezú ku k’lusu diê.\nUa bange kiê? Ua fuile pe.\nIú uala kué?\nMu henda iê Ku diulu iú tu diondela.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_36, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4058, position: 2, content: "Anju, sumbala ien’ukôla,\nIeju lembua kongo diê.\nKua bingi Mon’a Nzambi muene\nKuia ku dik’lusu diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_36, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4059, position: 3, content: "Pange, toloka kiá kindala,\nBeza Mubuludi uê:\nIú u ku tala ue ni henda,\nU olok’ituxi ié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_36, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4060, position: 1, content: "Ku dik’lusu dia Jezú Kuene kuala fixi,\nIa subaka meniia mê\nMa biluka ngiji.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_37, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4061, content: "K’lusu diê! K’lusu diê!\nBene bu ngi nanga,\n‘Té kia kèla,\n«Kuabu kiá,\nBandé kiá kokuami.»", hymnsNumber: KmHymnsNumberSeeder.GENERAL_37, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4062, position: 2, content: "Nga teketa hanji phe,\nMu kubixila-ku;\nUa ngi be tetembua iê,\nKu muikina mesu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_37, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4063, position: 3, content: "Bu dik’lusu dié, Jezú,\nNga ku lembalala;\nUa ng’ixana, ngeza kiá,\nU ngi tambulule.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_37, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4064, position: 4, content: "Uoma uami uabu kiá,\nMu ku mu xikana;\n‘Té nga tena kuia nê,\nKuná ku dibata.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_37, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4065, position: 1, content: "Ngi mateka kuimba kiá:\nTala kia ngi bange o sange:\nPulu iami iabu kiá.\nMu ku tena ngó kua sange.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_38, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4066, content: "O! tala henda iê!\nIa bulu mbungu jê!\nO, pange! Lenga bá!\nNda u diuane kiene o sange.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_38, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4067, position: 2, content: "Nga diuana henda iê\nIa ngi vuua ue mu Sange!\nKu ngi xika ioso kiá\nIa ngi kexile mu Sange!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_38, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4068, position: 3, content: "Ki ngi tena kuimba ngó\nKale ngi di tenda o Sange!\nZanga dia Siloua sai,\nDialu subajaka o Sange!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_38, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4069, position: 4, content: "Henda ia ngi kuata kiá,\nMu ku banza ngoho Sange!\nPulu iami iabue kiá,\nEme nga diuana o Sange!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_38, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4070, position: 5, content: "A ngi lolokele phe,\nMu ku di xikina o Sange!\nA ngi zelesele ue,\nMu ku di sukula o Sange!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_38, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4071, content: "Aleluia! Aleluia! Aleluia!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4072, position: 1, content: "Ua i lu kiabu ita iê,\nUa bânge ku dik’lusu diê,\nUa bana mueniu mundu uê,\nALELUIA!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4073, position: 2, content: "Uzonda uahi ua Jezú,\nUa kaie nguma ietu ió\nTanenu, Mubuludi iú,\nALELUIA!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4074, position: 3, content: "O atu mu ubika uâ,\nKu tueza tu jihule jê,\nKolenu o kikoue kiê,\nALELUIA!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4075, position: 4, content: "Mulonga sai dilemba diê,\nItuxi sai dibonzo diê,\nTu zela mu maniinga mê,\nALELUIA!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4076, position: 5, content: "Kalunga kabu usueia uê\nUa xitununa njila iê;\nTu kaiedienu hoka iê\nALELUIA!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4077, position: 6, content: "Ua tuama kiá ku mbanza iê,\nUa sange o kijingu kiê,\nImbenu diximanu diê,\nALELUIA!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_39, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4078, position: 1, content: "Tala mu mbila ié, o Mubuludi;\nUa tula mueniu uê, Ngana Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_40, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4079, content: "Ua fukunuka phe!\nKristu ua tolola nguma jê;\nO Kitombe kiene kia mu lembua ue\nNgana uaii bulu ni jianju jê:\nKafue di’! Kafue di’!\nAleluia kua Jezú!", hymnsNumber: KmHymnsNumberSeeder.GENERAL_40, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4080, position: 2, content: "Tala ku mbila iê, tadi dionene,\nA i kolesa ue, kidimbu kiâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_40, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4081, position: 3, content: "Muelu ua mbila iê, ua jikukile;\nKristu n’uzonda uê ua tundu kiá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_40, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4082, position: 1, content: "Tu dima, hé tu kuna,\nO mbutu tu i ta box',\nO mvula i tekela-ku,\nIa Ngana i tekela-ku,\nIa Ngana ietu pé;\nO mbundu ni kitembu\nHé kuia muania uê,\nImisa o idima, o atu ê n'adiâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_41, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4083, content: "'Mbote jetu joso\nJi tunda ku diulu,\nTanesa kiá Ngan'etu pé,\nO henda iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_41, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4084, position: 2, content: "Mubangi a ima ioso\nNi kunu ni kuná;\nNi kakitulu, muene,\nNi jetetembua kiá:\nIen'ioso u i tumina,\nTunjila tuê tudiê,\nKa kambe pé kudisa,\nNi etu tu an'ê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_41, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4085, position: 3, content: "Tua sakidila Tata,\nJimbote jê jiji,\nNi mueniu ni sauidi,\nNi kudia kuetu kiá:\nTambule maujitu\nTua ku bakuila nâ:\nKuma iene i ua bingi,\nMixima ietu, iê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_41, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4086, position: 1, content: "Ngiji sai i tua zukama;\nTua 'ivu kukunguluka;\nHonga ioio ia Kalunga,\n'Tabu diê tu bita kieb'?", hymnsNumber: KmHymnsNumberSeeder.GENERAL_42, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4087, content: "Hinu tuijiia ku sàmbua,\nO hungulule tu i zauka,\nAn'a ngene a kà bongoloka\nBu inama ia Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_42, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4088, position: 2, content: "Hong’iii i kuata uoma,\nAtu endi a i lenga;\nKana mutu ngó u xala,\nBene kiá bu 'lamba diâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_42, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4089, position: 3, content: "'Tabu didi dia kuvuua,\nKene dingi kuzaula\nAn'a ngene pe 'ka lémbua,\nBua bitile Ngana iâ.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_42, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4090, position: 4, content: "Kixi menia mê mazongo,\nNé  musanzu uê uakulu,\nKi ku kuata utalalu,\nUa kà diota sàmbua diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_42, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4091, position: 5, content: "'Sàmbua diodio dia jimbote,\nMbundu ia tu xitila-diu:\nHinu ki a ngi tuma kuiza,\nNgi zediua, 'kumbi diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_42, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4092, position: 1, content: "Mu ixi ia dibesá diê\nNgala ni 'mbote ia Jezú;\nJavulu ue jihenda jê,\nNgi xala jinga ni Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_43, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4093, content: "O 'mbote jê, kuuabha kuê,\nTala ku polo, kox'iná\nKu sàmbua dia jimbote jê,\nKindala nga kà tula ue,\nU ngi zaule, u Jezú,\nKu ixi ia jimbote jê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_43, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4094, position: 2, content: "O Mubuludi ngenda nê,\nNgi banza jinga mbote jê;\nU tu'inga ue mu henda iê\nKu ixi ia jimbote jê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_43, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4095, position: 3, content: "O hanji ia ngi kuata kiá,\nJezú, kumona polo iê;\nKutala o kubenia kuê,\nNi kuivua jinga dizui diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_43, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4096, position: 4, content: "Zelesa kiá muxima iú,\nUizale kiá ni Nzumbi iê;\nNgi tuka ni ifuxi iê\nKuimbila diximanu diê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_43, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4097, position: 1, content: "Dibhata dietu dia kala ni Nzambi\nUzonda uoso bhu maku mé ngó;\nKiadi ni muanu se phé u i sota\nKikale ngó phé kua Ngana Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_44, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4098, content: "Uembu ué bá, muanu ué bá!\nNgi bhé lukuaku lué, Ngana!\nNgala Dikanga dia dikulusu,\nNgi bhanga kiebhi phe, Jezú?", hymnsNumber: KmHymnsNumberSeeder.GENERAL_44, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4099, position: 2, content: "Dibhata dietu dia kala ni Tata,\nSe tu mu'ixana, u'itaia, taté!\nKavanza koso kaxala phe bhoxi,\nHé tua ka kàla ni muene, Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_44, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4100, position: 3, content: "Se tu dielela dilemba dia bhoxi,\n'Lemba dia kidi kabhila Jezú,\nKu muxié dikanga se ku mu'ijiia,\nTua tunga Bhulu ni Jezú Kristu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_44, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4101, position: 4, content: "Kizuua kioso ngi tula ku Zione,\nKuila ituxi iò loloke kiá,\nHé nga ka kala mu ndunda ia ngongo,\nJinguma joso phe janda kúbhua.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_44, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4102, position: 1, content: "Kuiza kua Kristu sai 'kumbi diê;\nMuene ua kiambe, kulekela kuê;\nKusanguluka kua ngeleja iê,\nKioso kia kèza Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_45, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4103, content: "Kristu iú uiza!\nMba kua kambe ngó;\nManii kizuua kiê.\nTua mu dielela kuvutuka kuê.\nMu bongolola atu ê.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_45, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4104, position: 2, content: "Ua tu dimuna, mu mbele iê,\nKukumbidila mutendelu uê;\nUoso ua tono kuzediua kuê,\nKioso kia kèza Kezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_45, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4105, position: 3, content: "Tua kà takana n'akuetu kiá,\nNi iá a tunda mu mbila jâ;\nMilonga ioso u i iukisa bá,\nKioso kia kèza Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_45, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4106, position: 4, content: "O jifiiele já kinga 'lau,\nA kà tambula ungana ua ió,\nUa iudikila ku uobe uenió,\nKioso kia kèza Kezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_45, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4107, position: 1, content: "Ngi dise ue, Jezú,\nO mbolo ié;\nKala mu Ngalilé\nM'okulu kiá;\nKuadile mundu ué\nNi'besa dié;\nEme ngi dise pe,\nO kidi kié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_46, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4108, position: 2, content: "Mbolo ia mueniu kiá,\nNgana Jezú,\nIene mu div'lu dié,\nNgi bane-iu.\nKi ngalu binga pe\nO maka ngó,\nNga bindamena ue\nO Nzumbi ié.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_46, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4109, position: 1, content: "Nguami kuxisa o Biblia\nMak'a Nzambi eniá\nUnvuama ua xikini\nMukanda ua kidi;\nMukengeji ua diulu,\nKitombe kiedi mué!\nIa dikiza o henda\nMubuludi Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_47, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4110, position: 2, content: "Nguami kuxisa o Biblia\nNjimbu ia henda ie\nAkua ituxi a sanga\nO muloloko ua;\nNga suina mu dielela\nNgejiia mueniu sai!\nKu diulu nga ka kala\nMu ximana Jezú.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_47, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4111, position: 3, content: "Nguami kuxisa o Biblia\nKidi, nguami, taté!\nIa ngi bana ufolo\nHadi jami jabue;\nIvuenu mundu uoso,\nNgonge ia mak'enia!\nIa tu bekela ng'lasa\nNi mueniu ki uabue", hymnsNumber: KmHymnsNumberSeeder.GENERAL_47, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4112, position: 1, content: "Henda ia Jezú iavulu.\nKufua ku muxi uaiiba\nKu ngi bana ufolo;\nHenda iê iavulu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_48, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4113, content: "Henda ia Jezú iavulu,\nHenda ia Jezú iavulu,\nKu i tanga, nga i tokoka;\nHenda iê iavulu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_48, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4114, position: 2, content: "Jezú ua muene malamba,\nUa bitile ni kalunga,\nEme, pala ki ngi fue di’;\nHenda iê iavulu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_48, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4115, position: 3, content: "Muxima uami uaxidi,\nJezú ua u sukula  kiá;\nNga zele ku maniinga mê:\nHenda iê iavulu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_48, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4116, position: 4, content: "M’onzo ia Nzambi muauaba\nKana-mu mutu uaiiba;\nIó ka tena kubokona:\nHenda iê iavulu.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_48, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 4117, position: 1, content: "Nzambi’iami kioso ngi um xinganeka,\nNi madianu a bange o maku mê.\nO jitetembua diulu n’inuminu,\nNi ima ioso ia diuanesa.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_49, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4118, content: "Mueniu uami imbila-ze Nzambi iê,\nUkôla bá! Ukôla bá!\nMueniu uami imbila-ze Nzambi iê,\nUnene uê, Ukôla bá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_49, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 4120, position: 2, content: "Kutala matutu’amixi ni iangu;\nKu’ivua tunjila mu isasa kuimba.\nNg’ila ngi tala mu makeni’anzongo\nNg’ivua tungiji t’u kunguluka.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_49, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4121, position: 3, content: "Kioso ngi banza kuila Nzambi muene,\nUa bele Mon’ê k ungi fuil’eme,\nPhata i ngi kuata kuila kidi muene\nUa bele mueniu uê mukonda diam’i.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_49, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 4122, position: 4, content: "Kia kèza Kristu ni nzongo ié ia suína,\nUixi, tuietu ku’bhata Dina;\nKutana kuahi! Nga mu fukamena\nNgi mu tangela: Ngana Ukôla bá.", hymnsNumber: KmHymnsNumberSeeder.GENERAL_49, typeStanza: HymnsContentCode.VERSE),
  ];
}