import 'package:ieca_mobile/db/_import.dart';
import 'package:ieca_mobile/enums/HymnsContentCode.dart';
import 'package:ieca_mobile/models/_import.dart';

class HymnsBirthOfJesus {
  static List<HymnsContent> list = [

    HymnsContent(id: 129, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 1, content: "Numa estrebaria rude\nDa cidade de Belém,\nOnde as gentes não pensavam\nEncontrar o Sumo Bem,\nNela a Virgem deu à luz\nO Menino, o bom Jesus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 130, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 2, content: "Ainda que o Senhor de tudo,\nNeste mundo veio nascer,\nFoi seu berço a manjedoura;\nLeite humano quis beber;\nEle tanto se humilhou\nNo caminho que trilhou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 131, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 3, content: "Para ser o bom modelo,\nCristo honrou e obedeceu\nA Maria, mãe bendita\nE sujeito à lei cresceu;\nAgradava em tudo a\nDeus A seu Pai, o Rei dos céus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 132, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 4, content: "Desejamos desde agora,\nConhecer o bom Jesus \nFome, sede, dor, tristezas,\nSofreu tanto e até a cruz,\nP'ra mostrar-nos compaixão\nE nos dar a salvação.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 133, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 1, content: "Pequena vila de Belém,\nTranquilamente jaz,\nCintila o estrelado céu,\nA gente dorme em paz,\nNas tuas ruas brilha\nA sempiterna luz.\nDe ti espera o mundo\nO Salvador, Jesus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 134, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 2, content: "Jesus recém-nascido!\nE lá no céu além,\nOs anjos velam com amor\nO Cristo de Belém.\nOh! Proclamai, estrelas,\nA noite de Natal.\nLouvai a Deus, bondoso Rei.\nQue dá a paz real.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 135, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 3, content: "Agora em silêncio\nO Dom celeste veio.\nAos corações assim\nDeus dá As bênçãos lá do céu.\nEle vem sem ser ouvido\nNo mundo pecador.\nNas meigas almas quer entrar\nJesus, o Salvador.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 136, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 4, content: "Menino Santo de Belém.\nRogamos-te descer;\nDas nossas almas tira o mal;\nEm nós vem já nascer.\nOs anjos nos trouxeram\nMensagem tão fiel.\nVem, faz em nós habitação,\nJesus, Emanuel.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 137, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 1, content: "Tu deixaste, Jesus,\nO Teu reino de luz\nE baixaste a este mundo tão vil.\nUm presépio em Belém,\nTu Jesus, Sumo Bem,\nEscolheste por berço infantil.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 138, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, content: "Vem, Jesus, habitar comigo,\nEm minha alma há lugar para Ti.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 139, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 2, content: "Alegraram-se os céus\nCom os Santos de Deus,\nSim, por teres nascido, Jesus,\nVindo aos filhos de Adão\nConceder salvação\nPela morte, em resgate na cruz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 140, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 3, content: "Tu vieste, Senhor,\nRevelar-nos amor\nE de todo o mal nos salvar;\nMas provaste do fel,\nDo motejo cruel,\nMorte enfim Te fizeram provar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 141, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 4, content: "Outra vez Tu virás,\nE por mim chamarás,\nRodeado dos anjos de Deus.\nOh, que gozo p’ra mim,\nSe disseres assim:\n«Um lugar te darei Eu nos céus»", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 142, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 1, content: "Ó santa luz brilhante, Tal como aos magos cintilaste Para guiá-los a Belém, Vem conduzir a nós também.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 143, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, content: "Ouçam, ouçam os louvores, Pelos anjos lá na glória. Cantam-nos a Boa Nova De paz e amor de Deus, Dada aos homens, De paz e amor de Deus, Dada aos homens.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 144, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 2, content: "Ó luz tal como brilhaste Lá na estalagem da Judea, Vem brilhar em nossos lares, P’ra que haja a Tua beleza.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 145, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 3, content: "Ó luz se nós brilharmos Tristonhos de corações, A Tua paz venha alegrar-nos, Mitigando todas as dores.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 146, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 4, content: "Ó luz brilhante de graça, Iluminaste a manjedoura Iluminaste a rude cruz, P’ra conceder-nos a salvação.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 147, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 1, content: "Oh! Vinde fiéis, triunfantes, alegres,\nSim, vinde a Belém,\nJá movidos de amor.\nNasceu vosso Rei,\nO Cristo prometido.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 148, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, content: "Oh! Vinde, adoremos\nOh! Vinde, adoremos\nOh! Vinde, adoremos a nosso Senhor!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 149, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 2, content: "Olhai admirados a Sua humilde.\nOs anjos O louvam Com grande fervor,\nPois veio connosco\nHabitar encarnado.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 150, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 3, content: "Por nós se humilhou Jesus, o adorável,\nTornando-se pobre,\nSujeito a dor,\nP'ra dar-nos de graça\nA vida sempiterna.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 151, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 4, content: "Nos céus, adorai-O, vós anjos em coro,\nE todos na terra\nLhe rendam louvor!\nA Deus honra e glória\nContentes rendamos", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 152, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 1, content: "Foi na gruta de Belém,\nOnde surge a maravilha,\nNo primeiro Natal!\nA criança foi deitada\nNuma pobre manjedoura,\nNo primeiro Natal!\nNo primeiro Natal!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 153, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 2, content: "Ali junto desta aldeia,\nOs pastores pastorearam,\nNo primeiro Natal!\nBrilhou a fulgente luz,\nLá, surgiram alguns anjos,\nNo primeiro Natal!\nNo primeiro Natal!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 154, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 3, content: "Já os anjos divulgaram\nO nascimento de Jesus,\nNo primeiro Natal!\nOs pastores foram à aldeia,\nAdoraram o menino,\nNo primeiro Natal!\nNo primeiro Natal!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 155, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 4, content: "A estrela fulgurante\nÉ que conduziu os magos,\nNo primeiro Natal!\nE com viva fé partiram,\nLá, chegaram com alegria,\nNo primeiro Natal!\nNo primeiro Natal!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 156, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 1, content: "Os enviados lá do céu\nAdoraram a Jeová.\nO seu filho enviou,\nVindo à terra com a paz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 157, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 2, content: "Ele é Rei de corações,\nEle é purificador,\nDa vida Ele é o sol,\nÉ da glória de Deus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 158, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 3, content: "Deixou o reino celestial,\nPara aqui se humilhar,\nE os homens salvar,\nPerdidos com o mal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 159, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 4, content: "Gratos pelo seu Natal,\nAlegria trouxe a nós.\nSua graça adorai,\nSempiterno Rei Jesus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 160, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 1, content: "Anjos da mais alta glória,\nVossas vozes levantai.\nCristo já nasceu! A história,\nAo mundo todo proclamai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 161, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, content: "Adoremos, Adoremos.\nAo recém-nascido rei.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 162, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 2, content: "Os pastores vigiando,\nSobre seu rebanho estão.\nDeus em Cristo habitando,\nEntre os homens, adoração.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 163, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 3, content: "Magos, vossas buscas todas,\nHoje mesmo abandonai;\nDas nações o desejado,\nEm casebre adorai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 164, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 4, content: "Os que a Cristo reverente\nEsperando vê-lo estão,\nEm seu trono de repente,\nContemplá-Lo poderão", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 165, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_41, position: 1, content: "Tocai, ó sininhos.\nCantai, ó crianças.\nPublicai a Boa-Nova\nDo Salvador que nos nasceu.\nAlegrai-vos todos,\nDessa imensa graça.\nAdorai com reverência,\nCristo, nosso Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 166, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_41, position: 2, content: "Tocai, ó sininhos.\nCantai, ó crianças.\nPara as nações inteiras,\nDa Boa-Nova alegrar-se\nE da melodia\nQue os anjos entoaram.\nQue anunciam a paz bendita,\nVinda à humanidade.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 167, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_41, position: 3, content: "Tocai, ó sininhos.\nCantai, ó crianças.\nIde juntos com os anjos,\nContemplai o milagre.\nJuntos com os magos,\nLevai oferendas,\nÀquele que deixou Sua glória,\nSalvação nos dá.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 168, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_42, position: 1, content: "Do tronco rude e forte\nDa estirpe de Jessé;\nVem o rebento novo,\nQue infunde nova fé,\nE nele Deus se apraz.\nNas trevas do Universo\nJesus a luz nos traz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 169, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_42, position: 2, content: "Tu eras um anelo\nDo povo de Israel.\nDa seiva do Rebento\nSe nutre agora o fiel.\nÓ Verbo Divinal!\nDe Deus Tu foste oferta,\nPerfeita do Natal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 170, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_42, position: 3, content: "Ele é o amigo certo\nDe pobres sem esperança;\nConhece suas faltas\nCuradas pela fé.\nJamais a morte atroz.\nEle lhes dá conforto\nPor uma libação.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 171, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 1, content: "Ah! Um anjo proclamou\nO primeiro Natal,\nÀ uns pobres pastores\nAo pé de Belém,\nLá nos campos a guardar\nOs rebanhos do mal,\nNuma noite tão fria\nE escura também.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 172, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, content: "Natal! Natal! Natal! Natal!\nÉ-nos nascido um Rei Divinal!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 173, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 2, content: "E de súbito no céu\nLinda estrela surgiu,\nNo Oriente brilhou\nCom estranho fulgor.\nE a Terra recebeu\nEssa luz que caiu,\nMuitas noites ainda\nEm exímio esplendor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 174, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 3, content: "Tendo visto a clara luz\nDessa estrela sem par, \nDo Oriente alguns Magos\nA foram seguir.\nÀ procura de um Rei\nQue devia chegar,\nAos Judeus e as velhas\nPromessas cumprir.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 175, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 4, content: "Essa estrela apareceu\nE os Magos guiou,\nNa estrada que para\nBelém os conduz;\nAfinal, sobre Belém\nEssa estrela parou,\nMesmo acima da casa em que\nEstava JESUS.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 176, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 5, content: "E os magos com afã,\nE com grande temor,\nDe joelhos entraram\nNaquele lugar.\nCom ofertas liberais\nE de muito valor;\nOuro, mirra e incenso\nVieram Lhe dar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 177, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 6, content: "E com eles vamos nós,\nCom sincero fervor;\nDar louvores a nosso\nSublime Senhor.\nQue, deixando os altos céus,\nA este mundo baixou.\nE, morrendo na cruz,\nNossas almas salvou.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 178, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_44, position: 1, content: "Noite de paz! Noite de amor!\nDormem todos em redor.\nEntre os astros que espargem a luz,\nProclamando o Menino Jesus;\nBrilha a estrela de paz!\nBrilha a estrela de paz!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 179, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_44, position: 2, content: "Noite de paz! Noite de amor!\nNas campinas aos pastores,\nLindos anjos mandados por Deus,\nAnunciam a nova dos céus;\nNasce o bom Salvador,\nNasce o bom Salvador!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 180, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_44, position: 3, content: "Noite de paz! Noite de amor!\nOh, que belo esplendor\nIlumina o Menino Jesus!\nNo presépio do mundo eis a luz,\nSol de eterno fulgor!\nSol de eterno fulgor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 181, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_45, position: 1, content: "Em linda noite ao mundo êxul,\nEm coro angelical;\nCom harpas de ouro o céu quis dar\nUm canto divinal.\nE toda a terra, então, ouviu\nPromessas imortais,\nCom bênçãos eternais.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 182, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_45, position: 2, content: "Pairando sobre a terra estão\nOs anjos a cantar;\nE sobre o mundo pecador\nDerramam luz sem par.\nAcima dos tormentos mil,\nAngústias do viver,\nProclamam vida perenal\nPois bênçãos vêm trazer.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 183, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_45, position: 3, content: "E vão-se os dias sem cessar,\nSegundo a voz de Deus;\nMas, sobre a terra as gerações\nCaminham rumos seus.\nE, quando enfim, reinar a paz\nDos salvos pelo amor,\nO coro imenso então será,\nE santo o seu louvor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 184, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 1, content: "Oh! vem; Oh! vem, Emanuel\nRemir o escravo, Israel,\nQue no exílio em pranto está.\nMessias, vem, tira-o de lá.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 185, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, content: "Exulta e folga, ó Israel,\nQue vem remir-te Emanuel", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 186, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 2, content: "Sabedoria lá dos céus,\nDas gentes enche os corações;\nVem vivifica os filhos teus;\nDo mal separa as nações.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 187, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 3, content: "Raia o dia da redenção!\nDo mundo as trevas vem dissipar;\nLouvando a Deus com grata emoção,\nOh! vinde todos O proclamar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 188, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 4, content: "Cristo entre homens se encarnou\nE Deus em Cristo a nós se revelou.\nOh! quão gloriosa encarnação,\nDe Deus glorioso Emanuel!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 189, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, position: 1, content: "Mal supõe aquela gente\nQue a Belém quer ir parar,\nQue uma luz tão refulgente\nVai ali brilhar.\nE por anjos anunciado,\nE os pastores logo vêem,\nQue esse Rei por Deus mandado\nNasce em Belém.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 190, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, content: "Vinde, ouvir a doce história,\nQue do oriente vem:\nO Messias, Rei da Glória,\nNasce em Belém.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 191, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, position: 2, content: "Mundo triste, oh! Desperta!\nTeus grilhões desfeitos são.\nTens a porta franca, aberta,\nSai da vil prisão!\nNão hesites duvidoso;\nEste dom do céu provém.\nCristo, o Todo-Poderoso.\nNasce em Belém.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 192, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, position: 3, content: "Ouve com feliz espanto.\nSurge da vergonha e dor.\nCesse, cesse todo o pranto;\nTens um Salvador.\nGlória a Deus vem promovendo\nMas aos homens só quer bem.\nPaz, eterna paz, trazendo,\nNasce em Belém.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 193, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 1, content: "Há uma estrela no céu;\nHá canções pelo ar;\nLuz divina desceu\nPara o homem guiar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 194, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, content: "E essa estrela brilhando\nMostra em seu fulgor\nQue em Belém é nascido\nJesus, o Senhor.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 195, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 2, content: "E os anjos dos céus\nDescem em multidão,\nProclamando de Deus \nPaz, amor e perdão.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 196, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 3, content: "Pela estrela guiados,\nSábios, reis e pastores\nDão louvores prostrados\nAo Senhor dos senhores.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 197, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 4, content: "Glória, glória ao Senhor\nQue até nós baixou.\nP’ra mostrar Seu amor\nEntre nós encarnou.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 198, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 1, content: "Sobre os campos de Belém\nDescem anjos a cantar;\nDo Senhor aos homens vêm\nBoas novas proclamar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 199, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, content: "Glória in excelsis Deo!\nGlória in excelsis Deo.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 200, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 2, content: "Glória a Deus, na terra paz\nEis o canto divinal.\nHoje Cristo aos homens traz\nLuz, amor, vida eternal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 201, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 3, content: "Ledos, os pastores vão\nVisitar o novo Rei;\nTributar-Lhe adoração\nComo sua humilde grei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 202, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 4, content: "Vinde à gruta e contemplai\nO Menino, o Redentor;\nDe joelhos, lhe prestai\nHonra, glória e louvor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 203, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_50, position: 1, content: "Povos, cantai! Jesus nasceu!\nÀ terra a luz desceu!\nA graça infinda ao mundo vem,\nA graça infinda ao mundo vem,\nNa gruta de Belém,\nNa gruta de Belém,\nJesus humilde ao mundo vem.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 204, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_50, position: 2, content: "Do eterno Deus o Salvador\nRevela o grande amor!\nNa manjedoura um leito tem,\nNa manjedoura um leito tem,\nNa gruta de Belém,\nNa gruta de Belém,\nJesus Cristo um leito tem.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 205, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_50, position: 3, content: "Vamos, ó crentes, recordar\nQue foi por nos amar,\nQue à terra veio o Sumo Bem,\nQue à terra veio o Sumo Bem,\nNa gruta de Belém,\nNa gruta de Belém,\nJesus o amado, o Sumo Bem.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 206, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 1, content: "Alerta, ó terra, entoa!\nO canto já ressoa;\nO mundo pecador\nTem grande sorte e boa.\nA nova se vos dá,\nE quão alegre soa:\nNasceu o redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 207, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, content: "Nasceu o Redentor!\nNasceu o Redentor!\nO Eterno Pai do céu\nSeu Filho ao mundo deu.\nAlerta, ó terra entoa\nA nova alegre e boa:\nNasceu o Redentor!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 208, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 2, content: "A noite já passou,\nA aurora já raiou;\nO negro e denso véu\nDe todo se rasgou.\nDos montes através\nO brado ressoou:\nNasceu o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 209, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 3, content: "Nasceu o Rei da paz,\nNum berço humilde jaz;\nNas asas desse amor\nConforto a todos traz;\nDizei em alta voz\nQue Cristo satisfaz;\nNasceu o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 210, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 4, content: "Oh, gozo divinal,\nAmor celestial,\nQuem pode te sondar Ou\nTer um outro igual.\nPossa eu, da morte réu,\nGozar ventura tal?\nNasceu o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 211, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 5, content: "Oh, povos, proclamai,\nNações, oh, jubilai,\nEis finda toda a dor,\nJamais se dá um ai;\nA Virgem deu à luz;\nA Deus glorificai!\nNasceu O Redentor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 212, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, position: 1, content: "Eis dos anjos a harmonia,\nCantam glória ao Novo Rei;\nPaz aos homens e alegria,\nPaz com Deus e suave Lei.\nOuçam povos exultantes,\nErgam salmos triunfantes,\nAclamando o Seu Senhor,\nNasceu Cristo, o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 213, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, content: "Toda a terra e altos céus\nCantem glória ao Homem-Deus!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 214, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, position: 2, content: "Cristo eternamente honrado,\nDo Seu trono se ausentou.\nCristo, entre homens encarnado,\nDeus connosco nos mostrou.\nQuão bondosa divindade!\nQuão gloriosa humanidade!\nSalve! Glória de Israel, \nluz do mundo Emanuel!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 215, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, position: 3, content: "Cante o povo resgatado;\n“Glória ao Príncipe da paz”.\nDeus em Cristo revelado,\nVida e luz ao mundo traz!\nNasce p’ra que renasçamos;\nVive para que vivamos, Rei,\nProfeta e Salvador!\nTodos louvem ao Senhor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 216, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 1, content: "Nós, três reis com dons p'ra ofertar,\nDo oriente ousamos viajar;\nTendo a estrela pura e bela\nPara nos guiar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 217, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, content: "Oh, estrela, ó astro condutor\nComo é belo o teu fugor!\nPara oeste nos conduz,\nCom tua forte e meiga luz.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 218, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 2, content: "Ouro, eu trago ao Rei que nasceu\nEm Belém, Senhor lá do céu;\nQuero honrá-Lo, coroá-Lo,\nTê-Lo por Deus meu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 219, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 3, content: "Eu, Insenso venho oferecer,\nPor tal culto aDeus pertencer;\nGrato adoro, ledo imploro\nTão augusto ser.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 220, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 4, content: "Mirra amargo, símbolo de dor\nVenho eu dar ao meu Salvador;\nOdiado, desprezado,\nVai ser meu Senhor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 221, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 5, content: "Mas glorioso, alfim, se erguerá;\nSobre a morte triunfará; \nAleluia! Aleluia!\nTudo cantará!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 222, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_54, position: 1, content: "Lá na manjedoura\nDa nobre Belém,\nJesus pequenino;\nUm berço não tem.\nMas dorme nas palhas,\nSeu rosto a brilhar,\nE os astros se curvam\nP'ra o virem beijar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 223, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_54, position: 2, content: "O gado fez bulha;\nJesus acordou;\nOlhou meigo em volta,\nPorém não chorou,\nEu amo-te muito,\nQuerido Jesus;\nDos Céus p'ra mim olha,\nDerrama em mim luz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 224, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_54, position: 3, content: "Oh! fica comigo,\nTe rogo Senhor,\nP'ra ter-Te bem perto,\nSentir Teu amor.\nOh! toma as crianças\nNos bons braços Teus.\nPrepara-nos todos\nPara a vida nos céus.", typeStanza: HymnsContentCode.VERSE),
    
  ];

}