import 'package:ieca_mobile/db/_import.dart';
import 'package:ieca_mobile/enums/HymnsContentCode.dart';
import 'package:ieca_mobile/models/_import.dart';

class HymnsFaithAndSecurity{
  static List<HymnsContent> list = [
    HymnsContent(id: 976, position: 1, content: "Rocha eterna, meu Jesus,\nQue por mim na amarga cruz\nFoi ferido em meu lugar,\nMorto para me salvar;\nNele quero me esconder\nPois me poderá valer.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_232, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 977, position: 2, content: "Minhas obras, bem o sei,\nNada valem ante a lei;\nSe chorasse sem cessar,\nTrabalhasse sem cansar,\nMeu afã seria em vão:\nSó em Cristo há salvação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_232, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 978, position: 3, content: "Nada trago a Ti, Senhor;\nConto só com o Teu amor.\nDe perdão indigno sou\nE sem Ti perdido estou,\nMas Teu sangue, ó Salvador,\nLava o pobre pecador.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_232, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 979, position: 4, content: "Quando a morte me chamar\nE contigo eu for morar,\nRocha eterna, meu Jesus,\nQue por mim na amarga cruz\nPadeceste em meu lugar,\nQuero sempre a Ti louvar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_232, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 980, position: 1, content: "Vem e dá-me auxilio ó meu Deus,\nA ser vencedor.\nPois as tentações me cercam,\nA força pouca é.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_233, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 981, position: 2, content: "Ó meu Deus,\nVenha me dar mais força\nCom o Teu Poder,\nCessem as tentações", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_233, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 982, position: 3, content: "Minha força não me basta,\nPois desistirei.\nDo Salvador só, espero\nMinha consolação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_233, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 983, position: 4, content: "De pesares vem livrar-me,\nSalvo quero estar.\nPara de alegria encher-me\nE firme eu me achar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_233, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 984, position: 5, content: "Se cercado de desprezo,\nNão ressentirei.\nDo meu Senhor lembrar-me:\nDesprezo igual sofreu.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_233, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 985, position: 1, content: "Eu tenho prometido\nSeguir-te até o fim,\nPois Tu, Senhor, prometes\nGuiar-me sempre a mim.\nEu sei que sou mui fraco,\nE o bem não sei fazer,\nMas pela Tua graça\nHei sempre de vencer.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_234, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 986, position: 2, content: "O mundo já venceste\nE as suas obras más,\nE sobre tudo reinas,\nÓ Príncipe da paz.\nNo céu e aqui na terra\nImpera o Teu poder,\nE pela Tua graça\nHei sempre de vencer.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_234, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 987, position: 3, content: "Cercado de inimigos\nAqui no mundo estou.\nAs tentações apertam\nPor onde quer que vá.\nMas Tu estás mais perto,\nPois vens em mim viver.\nE pela Tua graça\nHei sempre de vencer.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_234, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 988, position: 4, content: "A todos que te seguem\nE tomam sua cruz\nPrometes que contigo\nIrão morar, Jesus.\nDescansarão na glória\nContigo, ó Vencedor,\nPois pela Tua graça\nVenceram, Salvador.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_234, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 989, position: 1, content: "Quando a tempestade ruge,\nQuando vem o furacão,\nEm Jesus abrigo tenho\nSob a sua protecção.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_235, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 990, content: "Jesus Cristo me resguarda\nOnde o mal jamais me atinge;\nJesus Cristo me conserva\nSob a sua protecção.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_235, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 991, position: 2, content: "Mesmo que sofrer eu venha,\nDeus o permite para o bem.\nEm amor, e não em ira,\nO castigo seu nos vem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_235, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 992, position: 3, content: "Inimigos me perseguem,\nSatanás me quer vencer,\nMas Jesus é poderoso\nPara bem me defender.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_235, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 993, position: 4, content: "Minha cruz vou carregando\nNesta peregrinação;\nNas maiores tempestades\nCristo dá-me protecção.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_235, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 994, position: 1, content: "Corre como um rio a perfeita paz\nCom que Deus, ao crente, a alma satisfaz.\nÉ perfeita e cresce, meiga em seu poder;\nSempre mais profunda, inundando o ser.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_236, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 995, content: "No Senhor firmada, a alma crente traz\nA completa bênção de descanso e paz.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_236, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 996, position: 2, content: "No bendito abrigo da divina mão\nNão há inimigo, não se vê traição.\nVento de cuidado, sombra de pesar,\nNunca a santa calma podem perturbar", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_236, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 997, position: 3, content: "São os nossos dias, quer de gozo ou dor,\nRaios derramados pelo Sol de Amor.\nPondo a confiança plenamente n'Ele,\nNós o acharemos sempre, o Deus fiel.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_236, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 998, position: 1, content: "Se paz a mais doce me deres gozar,\nSe dor a mais forte sofrer,\nOh! Seja o que for, Tu me fazes saber\nQue feliz com Jesus sempre sou!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_237, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 999, content: "Sou feliz com Jesus!\nSou feliz com Jesus, meu Senhor!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_237, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1000, position: 2, content: "Embora me assalte o cruel Satanás,\nE ataque com vis tentações,\nOh! Certo eu estou, apesar de aflições,\nQue feliz eu serei com Jesus!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_237, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1001, position: 3, content: "Meu triste pecado, por meu Salvador,\nFoi pago de um modo cabal;\nValeu-me o Senhor, oh! Mercê sem igual!\nSou feliz! Graças dou a Jesus!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_237, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1002, position: 4, content: "A vinda, eu anseio, do meu Salvador;\nEm breve virá me levar\nAo céu, onde eu vou para sempre morar\nCom remidos na luz do Senhor!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_237, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1003, position: 1, content: "Eu estou convosco sempre,\nÉ a promessa de Jesus.\nDe amor e de consolo,\nQue outrora nos legou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_238, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1004, position: 2, content: "'Stou convosco, vós obreiros,\nQue a Palavra semeais.\nSe cansados, sede firmes,\nPois alegres colhereis.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_238, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1005, position: 3, content: "‘Stou convosco, caminhando,\nMesmo em trevas e pavor.\nVossos corações conforto,\nDissipando seu temor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_238, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1006, position: 4, content: "Batalhando perto estou \nP’ra da morte vos tirar.\nAs veredas clareando\nCom a luz celestial.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_238, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1007, position: 1, content: "Que segurança, Jesus é meu! \nTenho ante-gozo da glória do céu.\nCom Cristo herdeiro, Deus me comprou;\nDele nascido, o sangue me lavou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_239, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1008, content: "Conto esta história cantando assim,\nAo Salvador louvando sem fim,\nConto esta história cantando assim,\nAo Salvador louvando sem fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_239, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1009, position: 2, content: "Inteiramente me submeti;\nPerfeito gozo e transporte senti.\nAnjos descendo trazem dos céus\nEcos da graça, mercê de Deus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_239, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1010, position: 3, content: "Sempre submisso, só reina o amor.\nEu estou contente no meu Salvador.\nEsperançoso, vivo na luz.\nOh, que bondade e amor tem Jesus!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_239, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1011, position: 1, content: "Se da vida as vagas \nProcelosas são,\nSe com desalento \nJulgas tudo vão,\nConta as muitas bênçãos,\nDize-as duma vez,\nHás-de ver, surpreso,\nQuanto Deus já fez.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_240, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1012, content: "Conta as bênçãos, conta quantas são,\nRecebidas da divina mão;\nUma a uma, dize-as duma vez,\nHás-de ver, surpreso, quanto Deus já fez.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_240, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1013, position: 2, content: "Tens, acaso, mágoas, \nTriste é teu lidar?\nÉ a cruz pesada \nQue tens de levar?\nConta as muitas bênçãos, \nNão duvidarás,\nE em canção alegre \nOs dias passarás.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_240, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1014, position: 3, content: "Quando vires outros \nCom seu ouro e bens,\nLembra que tesouros \nPrometidos tens.\nNunca os bens da terra \nPoderão comprar\nA mansão celeste \nEm que tu vais morar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_240, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1015, position: 4, content: "Seja o teu conflito \nFraco ou forte cá,\nNão te desanimes, \nDeus por cima está;\nSeu divino auxílio, \nMinorando o mal,\nTe dará consolo \nE paz celestial.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_240, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1016, position: 1, content: "Onde quer que seja, com Jesus irei;\nEle é meu bendito Salvador e Rei.\nSeja para a guerra, para batalhar,\nSeja p'ra a campina para semear.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_241, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1017, content: "Onde quer, onde quer \nQue Deus me mandar,\nPerto do meu Salvador \nEu quero andar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_241, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1018, position: 2, content: "Onde quer que seja, seguirei Jesus,\nDiz o coração que vive em sua luz;\nPerto d'Ele sempre bem seguro vou,\nOnde quer que seja, pois, contente estou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_241, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1019, position: 3, content: "Seja, pois, para onde quer que me levar,\nAcharei com Ele ali meu doce lar.\nOnde quer que seja, sempre cantarei:\n‘Tu Senhor, comigo estás não temerei.’", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_241, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1020, position: 1, content: "O que fará desistir\nAqueles que confiam em Cristo?\nO que mais faz assustar,\nAqueles que confiam em Cristo?", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_242, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1021, content: "Perseverai irmãos,\nPois há um galardão.\nÉ pleno e perfeito,\nPara os que em Cristo esperam.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_242, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1022, position: 2, content: "Mesmo havendo dor, tristeza,\nHaja confiança em Cristo.\nA esperança nunca murcha\nHaja confiança em Cristo.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_242, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1023, position: 3, content: "Mesmo a morte não abala,\nAqueles que confiam  Cristo.\nA bondade de Deus salva\nAqueles que confiam Cristo.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_242, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1024, position: 1, content: "Confiando em meu Jesus,\nEle dá-me paz e luz.\nQuando vem a provação\nEle dá-me a Sua mão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_243, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1025, content: "Sempre n'Ele confiar,\nVencedores nos fará;\nAtravés da provação\nDá-nos força e direcção.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_243, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1026, position: 2, content: "Dá-nos o Consolador,\nQue nos enche de fervor,\nQue não deixa tropeçar\nQuando o tentador chegar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_243, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1027, position: 3, content: "E se n'Ele eu confiar,\nPoderei então cantar,\nQuando o temporal bater,\nVenha, sim, o que vier!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_243, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1028, position: 4, content: "Oh! enquanto aqui viver,\nConfiança eu hei-de ter;\nQuando a vida terminar\nLá na glória irei cantar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_243, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1029, position: 1, content: "Não sei porque de Deus o amor\nA mim se revelou;\nPorque razão o Salvador\nP'ra si me resgatou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_244, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1030, content: "Mas eu sei em quem tenho crido,\nE estou bem certo que é poderoso\nPara guardar o meu tesouro\nAté ao dia final.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_244, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1031, position: 2, content: "Ignoro como o Espírito\nConvence-nos do mal,\nRevela Cristo, Verbo Seu,\nConsolador real.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_244, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1032, position: 3, content: "Não sei o que de mal ou bem\nÉ destinado a mim,\nSe maus ou áureos dias vêm\nAté da vida o fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_244, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1033, position: 4, content: "E quando vem Jesus não sei,\nSe breve ou tarde vem,\nMas sei que meu Senhor virá\nNa glória que Ele tem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_244, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1034, position: 1, content: "Qual ave que buscando os céus,\nO mundo deixo, e seus troféus.\nMinha alma vem a Ti, Senhor.\nP'ra conhecer Teu terno amor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_245, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1035, position: 2, content: "Amor sublime, amor real,\nAmor eterno, sem igual:\nSobre uma cruz por mim morrer\nE me salvar por Seu poder.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_245, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1036, position: 3, content: "Teu amor, ó Deus, publicarei.\nA Tua graça, a Tua lei,\nO Teu poder e o Teu amor!\nMinha alma adora-te, Senhor!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_245, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1037, position: 1, content: "Ouvi o Salvador dizer:\n«Vem descansar em Mim,\nE nos meus braços podes ter\nConsolação sem fim.»\nEntão eu vim e lhe entreguei\nMeu triste coração.\nAbrigo, paz e gozo achei;\nAchei consolação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_246, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1038, position: 2, content: "Ouvi o Salvador dizer\n«De graça eu sempre dou\nAs águas vivas. Vem beber;\nDa vida a fonte eu sou».\nVim a Jesus e me prostrei\nÀs águas e bebi;\nJamais a sede sentirei,\nEstando sempre aqui.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_246, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1039, position: 3, content: "Ouvi o Salvador dizer:\n«A luz do mundo sou.\nOh, vinde a mim! pois quem vier\nTerá a luz que dou.»\nVim a Jesus e n'Ele achei\nO sol que brilha em mim,\nE nessa luz andarei\nAté da vida o fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_246, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1040, position: 1, content: "O Senhor é meu bom Pastor;\nNada me faltará.\nEm campos bons deitar-me faz,\nOnde águas brandas há.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1041, position: 2, content: "O Senhor nova graça dá\nAo débil coração,\nFazendo os tardos pés andar\nConforme a rectidão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1042, position: 3, content: "E quando pelas trevas já\nDa morte caminhar,\nNão temerei; Tu perto estás\nPara me consolar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1043, position: 4, content: "Feliz me fazes, apesar\nDos que a perder-me vêm,\nE de alegrias encherás\nA minha sorte bem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_247, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1044, position: 5, content: "Por dó, Senhor, e compaixão\nSempre me seguirás,\nE para sempre morarei\nOnde Tu morarás.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_247, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1045, position: 1, content: "Meu Jesus me guia sempre,\nQue mais posso desejar?\nDuvidar do meu Amado?\nDo meu Deus desconfiar?\nPaz perfeita, gozo infindo\nTenho, e Sua protecção;\nPois eu sei que por mim vela\nSeu bondoso coração!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_248, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1046, position: 2, content: "Meu Jesus me guia sempre,\nEnsinando-me a viver,\nConcedendo graça e força\nPara me desenvolver.\nPerecer jamais eu posso;\nPois quem pode resistir\nAo Deus forte, Pai eterno,\nQue minha alma quis remir?", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_248, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1047, position: 3, content: "Meu Jesus me guia sempre\nPelo Seu tão terno amor!\nVida santa, glória eterna,\nMe garante o Salvador.\nOh! mui breve vem o dia,\nO da grande redenção,\nQuando salva, transformada\nHá-de ser a criação!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_248, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1048, position: 1, content: "Quão bondoso amigo é Cristo!\nCarregou com a nossa dor,\nE nos manda que levemos\nOs cuidados ao Senhor.\nFalta ao coração dorido\nGozo, paz, consolação.\nIsso é porque não levamos\nTudo a Deus em oração.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_249, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1049, position: 2, content: "Tu estás fraco e carregado\nDe cuidados e temor?\nA Jesus, refúgio eterno,\nVai, com fé, teu mal expor.\nTeus amigos te desprezam?\nConta-lhe isso em oração.\nE com Seu amor tão terno\nPaz terás no coração.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_249, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1050, position: 3, content: "Cristo é verdadeiro amigo,\nDisto prova nos mostrou\nQuando para ver remido\nAo culpado, encarnou.\nDerramou Seu sangue puro\nNossa mancha p'ra lavar.\nGozo em vida e no futuro\nNele podemos alcançar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_249, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1051, position: 1, content: "Minha morada, Jesus assegura,\nPaz e conforto na luta feroz;\nDá-me teu braço, transporta-me à altura,\nOnde escutar poderei tua voz.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_250, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1052, content: "Vem dar-me paz, ó meu Jesus,\nDá-me teu braço, ó Cristo!\nVou perecendo longe da cruz,\nE eu em clamar insisto!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_250, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1053, position: 2, content: "Triste, procuro refúgio ao teu lado,\nVolta-me a paz, o descanso me vem;\nQuando na terra me achar desprezado\nGlória terei noutra pátria de além.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_250, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1054, position: 3, content: "Quando da morte cercar-me a tristeza,\nFinda a jornada do mundo cruel,\nCerto terei nesse dia a certeza\nDe ir-me alegrar sob imenso docel.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_250, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1055, position: 1, content: "Coisas mundanas\nCercam-me demais,\nDesejo agora bens celestiais; \nQuando propenso \nNalguma maldade, \nOuço o convite \nMeigo de amor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_251, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1056, position: 2, content: "Do meu Senhor\nEu reconheço a voz,\nEle me chama com a mão cravada. \nSeu sangue remidor \nMe purifica; \nSua morte é p'ra mim \nLibertadora.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_251, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1057, position: 3, content: "Ó meu Jesus,\nTu és minha justiça;\nPois carregaste\nTodo o meu pecado;\nTeus são os espinhos, minha é a coroa:\nP'ra Ti a morte \nE para mim a vida.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_251, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1058, position: 4, content: "Vem meu Senhor\nFaz-me meigo e manso;\nP'ra Ter um coração suplicador, \nPara eu entrar sim, \njubilosamente, \nNo lar que preparaste para mim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_251, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1059, position: 1, content: "Não me desampares,\nCristo em Ti confio.\nEstando eu perdido,\nVem Senhor salvar. \nEm quem encontrei, eu, \ncompaixão igual? \nMesmo pecador,\nPor mim o Senhor morreu. \nFoi no Teu amor que Te reconheci; \nGrato Te serei, Jesus, eternamente. \nNão me desampares, pois em Ti confio. \nEstou perdido, arrependido. \nVem me salvar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_252, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1060, position: 2, content: "Não me desampares,\nCristo em Ti confio.\nTua voz ouvi, mas\nEu não entendi. \nVem, Senhor, revele\nTua terna voz.\nDê-me inteligência para perceber.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_252, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1061, position: 3, content: "Cristo em Ti confio,\nSem mais duvidar, \nQuem a Ti chegar,\nPois, não rejeitarás. \nA Tua promessa\nSempre cumprirei; \nSem Ti, meu Jesus, eu salvo não seria.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_252, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1062, position: 1, content: "Em Jesus confiar, Sua lei observar, \nOh! que gozo, que bênção, que paz! \nSatisfeitos guardar tudo quanto ordenar \nAlegria perene nos traz.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_253, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1063, content: "Crer e observar \nTudo quanto ordenar; \nO fiel obedece \nAo que Cristo mandar!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_253, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1064, position: 2, content: "O inimigo falaz e a calúnia mordaz \nCristo pode desprestigiar; \nNem tristeza, nem dor, nem a intriga maior \nPoderão ao fiel abalar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_253, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1065, position: 3, content: "Que delícia de amor, comunhão com o Senhor \nTem o crente zeloso e leal; \nO seu rosto mirar, seus segredos privar, \nSeu consolo constante e real.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_253, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1066, position: 4, content: "Resolutos, Senhor, e com fé, zelo e ardor, \nOs teus passos queremos seguir; \nTeus preceitos guardar, o teu nome exaltar, \nSempre a tua vontade cumprir.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_253, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1067, position: 1, content: "Castelo forte é nosso Deus, \nEspada e bom escudo; \nCom Seu poder defende os seus \nEm todo o transe agudo. \nCom fúria pertinaz \nPersegue Satanás, \nCom ânimo cruel. \nAstuto e forte é ele. \nIgual não há na terra.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_254, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1068, position: 2, content: "A nossa força nada faz; \nO homem está perdido. \nMas nosso Deus socorro traz \nNo Filho escolhido. \nSabeis quem é Jesus, \nO qual venceu na cruz; \nSenhor dos altos céus; \nE, sendo o próprio Deus, \nTriunfa na batalha.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_254, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1069, position: 3, content: "Se nos quisessem devorar \nDemónios não contados, \nNão nos podiam assustar, \nNem somos derrotados. \nO príncipe do mal, \nCom rosto infernal, \nJá condenado está. \nVencido cairá \nPor uma só palavra.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_254, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1070, position: 4, content: "Que a palavra ficará, \nSabemos com certeza, \nE nada nos assustará. \nCom Cristo por defesa. \nSe temos de perder \nOs filhos, bens, mulher, \nEmbora a vida vá, \nPor nós Jesus está, \nE dar-nos-á Seu reino.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_254, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1071, position: 1, content: "Pelo amor de Deus bendito \nVai tudo bem. \nSeu amor é infinito. \nTudo está bem. \nEsse amor nos tem provado \nEm Seu filho muito amado, \nQue por nós foi imolado. \nSim, sim, está bem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_255, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1072, position: 2, content: "Cristo agora o ceptro empunha \nVai tudo bem. \nQuem morreu é quem governa. \nTudo está bem. \nSeu amor é imutável; \nSeu poder inabalável; \nSeu cuidado é incansável. \nSim, sim, está bem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_255, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1073, position: 3, content: "A fé canta na tristeza, \nVai tudo bem. \nCanta, sim, e com firmeza, \nTudo está bem. \nPois se Deus é quem nos guia, \nTernamente nos vigia, \nCom bondade, noite e dia. \nSim, sim, está bem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_255, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1074, position: 4, content: "Por caminhos escabrosos, \nVai tudo bem. \nOu por mares tormentosos, \nTudo está bem. \nA Jesus tudo obedece, \nSempre o mesmo permanece, \nNem dum só dos Seus esquece. \nSim, sim, está bem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_255, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1075, position: 1, content: "Jerusalém excelsa, \nGloriamo-nos em Ti. \nConsoladora esperança \nDo teu rebanho aqui. \nRadiantes, belos muros, \nQue ao longe já se vê, \nE as preces, ânsias, lutas, \nRedobra pela fé.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_256, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1076, position: 2, content: "Deus é que te alumia, \nE o grande Redentor, \nCordeiro teu Esposo \nTributa-lhe louvor. \nQue gozo tu me inspiras, \nEterna habitação, \nSaber que em ti termino \nA peregrinação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_256, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1077, position: 3, content: "Ó doce Pátria amada \nTeu gozo será meu? \nÓ Pátria desejada, \nQuero ir ao solo teu. \nExulta, tu que gemes \nNa dor que te desfaz. \nCom Deus que te redime, \nFeliz sempre serás.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_256, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1078, position: 1, content: "Para altos montes \nErgo, na aflição \nOs olhos meus; \nDe onde virá socorro e salvação, \nDos altos céus? \nTenho socorro certo \nEm meu Senhor! \nDo céu e terra, o grande Criador.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_257, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1079, position: 2, content: "Eis que teu pé jamais vacilará \nAo caminhar. \nPois o Senhor não tosquenejará, \nIrá velar. \nNunca dormita \nO guarda de Israel, \nVigia sempre o terno Pai fiel.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_257, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1080, position: 3, content: "Sendo o Senhor \nQual astro a refulgir, \nGuardar-te-á. \nE como sombra \nAo lado a te seguir \nEle andará. \nDe dia o sol jamais te ferirá. \nNem lua, à noite, te molestará.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_257, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1081, position: 4, content: "De todo o mal \nTua alma guardará \nEm teu dormir. \nA tua entrada Deus protegerá. \nE o teu sair. \nGuarda segura é nosso protector \nQue nos conserva em seu eterno amor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_257, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1082, position: 1, content: "Os que amam Deus, firmes serão\nComo o monte Sião;\nEles não mudarão jamais.\nPara sempre viverão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_258, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1083, position: 2, content: "Tal como os montes em redor,\nDa cidade de Deus.\nAssim é a força do Senhor,\nEnvolvendo os filhos Seus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_258, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1084, position: 3, content: "No Céu e lar celestial,\nJuntos estaremos nós.\nDescanso eterno vamos ter,\nCom o nosso Deus de amor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_258, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1085, position: 4, content: "Vem dirigir-nos nosso Deus,\nAté chegarmos lá.\nNo Teu ditoso e imenso lar.\nDe glória e compaixão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_258, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1086, position: 1, content: "Não há igual outro nome, não,\nSó Teu, ó Cristo, Salvador.\nPode o pecado perdoar,\nE conceder-me eterna paz.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_259, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1087, position: 2, content: "Não há igual outro nome, não,\nQuando abalado meu coração;\nPois Tu me curas sem pagar,\nDo sofrimento e de toda a dor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_259, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1088, position: 3, content: "Não há igual outro nome, não,\nQuando da vida expirar,\nNa morte me acompanharás,\nE no esplendor contigo entrarei.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_259, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1089, position: 4, content: "Não há igual outro nome, não.\nO louvarei, Eterno é.\nIncomparável, só Jesus:\nO meu Senhor e Salvador.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_259, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1090, position: 1, content: "Não sou meu! Por Cristo salvo,\nQue por mim morreu na cruz,\nEu confesso alegremente\nQue pertenço só a Jesus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_260, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1091, position: 2, content: "Não sou meu. Por Cristo salvo,\nPois Seu Sangue derramou,\nE da pena do pecado\nA minha alma resgatou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_260, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1092, position: 3, content: "Não sou meu! A Ti confio\nTudo quanto chamo meu.\nTudo em Tuas mãos entrego,\nPois Senhor, sou todo Teu.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_260, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1093, position: 4, content: "Não sou meu! Oh! santifica\nTudo quanto sou, Senhor.\nDa vaidade e da soberba\nLivra-me, meu Salvador!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_260, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1094, position: 1, content: "Cristo é tudo para mim:\nViver, gozar, cantar;\nÉ minha força, meu bordão.\nSem Ele, que penar!\nQuando em pesar a Ele vou,\nPois nunca, nunca me olvidou,\nQuando em pesar, faz-me alegrar,\nCristo é meu!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_261, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1095, position: 2, content: "Cristo é tudo para mim:\nAmigo em aflição;\nEu d'Ele bênçãos vou buscar,\nE dá-me em profusão.\nEnvia chuva, sol e luz,\nColheita farta, dons a flux,\nSol, chuva e luz, bênçãos a flux,\nCristo é meu!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_261, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1096, position: 3, content: "Cristo é tudo para mim:\nLeal eu Lhe serei;\nEle é amigo tão fiel.\nComo eu O negarei?!\nQuando ao Seu lado, alegre vou,\nPois no caminho certo estou,\nSim, com Jesus, tudo reluz,\nCristo é meu!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_261, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1097, position: 4, content: "Cristo é tudo para mim:\nSó Ele satisfaz,\nA confiança n'Ele pus,\nNão mais me falta a paz.\nTendo a Jesus ao lado, assim,\nMeu gozo nunca mais tem fim,\nVida eternal, livre do mal,\nCristo é meu!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_261, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1098, position: 1, content: "Jesus nos dirige\n'Té chegar ao fim.\nMesmo que haja embaraços,\nNão nos desanimaremos;\nJesus nos dirige\n'Té chegar ao fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_262, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1099, position: 2, content: "Mesmo com tristezas,\nMesmo que sofrendo.\nConfiemos nosso Mestre\nE com fé nós avancemos.\nJesus nos dirige\n'Té chegar ao fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_262, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1100, position: 3, content: "Tendo mui trabalho,\nSendo mui cansados,\nMesmo assim, prosseguiremos\nPois Jesus nos fortalece.\nEle nos dirige\n'Té chegar ao fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_262, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1101, position: 4, content: "Não nos aflijamos,\nNão enfraqueçamos.\nEm todos nossos caminhos\nPor Jesus somos guiados.\nEle nos dirige\n'Té chegar ao fim.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_262, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1102, position: 1, content: "Grandioso é Jeová,\nN'Ele tenhamos fé.\nHavendo hostes demais,\nPor nós vencidos são.\nQue Satã possa resistir,\nQue Satã possa resistir,\nMelhor que ele é o nosso Deus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_263, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1103, position: 2, content: "Fiel é Jeová.\nIncomparável é.\nPois fez-nos filhos Seus,\nNos fortificará.\nEm vão os inimigos vêm,\nEm vão os inimigos vêm,\nMelhor que eles é o nosso Deus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_263, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1104, position: 3, content: "Jeová é protector\nDe todos os fiéis.\nCuidar-los-á melhor,\nPobreza acabará.\nProssiga o mundo a resistir,\nProssiga o mundo a resistir,\nMelhor que ele é o nosso Deus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_263, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1105, position: 4, content: "Jeová é bom Pastor,\nAs nossas faltas vê,\nÉ o nosso benfeitor,\nSustenta e cuida bem.\nProssiga a morte a resistir,\nProssiga a morte a resistir,\nMelhor que ela é o nosso Deus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_263, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1106, position: 1, content: "O meu coração somente repousa\nEm vivas águas frescas,\nNa frescura dos rios\nQue da nascente brotam,\nDa graça de nosso Deus.\nLá está o meu dador\nDa força do coração,\nCareço tanto lá estar\nNas águas refrescantes.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_264, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1107, content: "Nas águas refrescantes,\nNas águas refrescantes,\nCareço tanto lá estar,\nNas águas refrescantes.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_264, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1108, position: 2, content: "Firmando a fé em meu Senhor,\nMe apreço para o prémio,\nO qual meu Deus bem prometeu,\nA todos os que O crêm.\nConfio no Senhor Jesus\nPois Ele é quem promete,\nNa minha vida até ao fim\nMostrar o meu caminho.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_264, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1109, content: "Mostrar o meu caminho,\nMostrar o meu caminho;\nEm minha vida até ao fim\nMostrar o meu caminho.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_264, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1110, position: 3, content: "Meu guia bem em frente\nCorajoso passarei.\nCom a sua boa direcção.\nProsseguindo para o alvo,\nReceio nenhum eu terei.\nMesmo sofrendo sem cessar,\nDe mim Ele cuidará;\nAlegre eu vou chegar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_264, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1111, content: "Alegre eu vou chegar,\nAlegre eu vou chegar.\nDe mim Ele cuidara\nAlegre eu vou chegar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_264, typeStanza: HymnsContentCode.CHOIR),

    HymnsContent(id: 1112, position: 1, content: "Vinde vós que, na tristeza,\nCaminhais sem luz;\nQuem vos chama com ternura\nÉ Jesus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1113, position: 2, content: "Vida, gozo, paz, descanso\nTudo vos ganhou\nPela cruz, onde o Seu sangue\nDerramou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1114, position: 3, content: "Não somente quer salvar-vos\nQuer-vos para si,\nPara serdes seus amigos,\nMesmo aqui.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_265, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1115, position: 4, content: "Tudo o mais abandonando\nSem mais resistir,\nVinde, Seu amor e graça\nPossuir.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_265, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1116, position: 1, content: "Ó nosso Deus e benfeitor,\nEsperamos só em Ti.\nTu És o Salvador na dor,\nTambém refúgio És.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1117, position: 2, content: "Descanso em Ti encontrarão,\nOs campeões da fé.\nSeu braço é forte, ó nosso Deus\nTu És o protector.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1118, position: 3, content: "Antes da criação Senhor,\nDa terra e do céu,\nJá Eras no Teu esplendor,\nEterno és Senhor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1119, position: 4, content: "Os anos como um rio vão,\nDias levam também.\nDepressa como um sonho, vão,\nQue esquece de manhã.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_266, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1120, position: 5, content: "Ó nosso Deus e benfeitor\nEsperamos só em Ti.\nÉs nosso Salvador na dor,\nÉs nosso protector.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_266, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1121, position: 1, content: "Espero sempre no meu Deus\nPois n'Ele tenho fé.\nDa terra Ele é criador,\nEle é o protector.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_267, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1122, position: 2, content: "Pois Ele fez meus pés firmar\nNo trilho da vida,\nE cuida-me com compaixão,\nNão me abandonará.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_267, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1123, position: 3, content: "Jehová sempre me protege,\nComigo sempre está.\nDe dia como de noite,\nNunca Ele dormirá.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_267, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1124, position: 4, content: "Livra-me do sofrimento,\nE me fortalece.\nSua bondade é p'ra sempre,\nConfio no Seu poder.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_267, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1125, position: 1, content: "Quem tem a chave do além?\nÉ só Deus.\nSe outro tanto liderar,\nCom o destino por saber,\nPerder-me-ia. Perder-me-ia.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_268, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1126, position: 2, content: "Não vejo para onde vou;\nMeu Senhor,\nDeus nunca mudará jamais;\nDe temores me livrará;\nSossego dá. Sossego dá.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_268, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1127, position: 3, content: "Destino meu é o Senhor,\nFirme estou.\nDia a dia, sem temor\nSustentado por Suas mãos\nDescansarei. Descansarei.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_268, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1128, position: 4, content: "Somente a fé e Teu querer,\nAté morrer.\nTambém no fim da vida aqui,\nAquela porta lá do céu\nAbrir-se-á. Abrir-se-á.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_268, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1129, position: 1, content: "Filho de Deus, nosso Pai,\nVerbo que se revelou\nNa justiça e no amor,\nConhecemos-Te ó Bom Deus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_269, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1130, position: 2, content: "Ainda em vida neste mundo,\nSendo homem e Eras Deus;\nNosso ser também transforme,\nMolde-nos como Sua imagem.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_269, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1131, position: 3, content: "As maravilhas deste mundo,\nSabedoria ou riqueza,\nTudo o que existe chega ao fim,\nMas, tu somente duras sempre.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_269, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1132, position: 4, content: "Em nossa própria eloquência,\nSabendo muito deste mundo,\nReconhecemos sem tardar,\nQue tudo vem de Tuas mãos.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_269, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1133, position: 1, content: "Rocha eterna, foi na cruz\nQue morreste Tu, Jesus.\nVem de Ti um sangue tal\nQue me limpa todo o mal;\nTraz as bênçãos do perdão:\nGozo, paz e salvação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_270, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1134, position: 2, content: "Nem trabalho, nem penar\nPode o pecador salvar,\nSó Tu podes, bom Jesus,\nDar-me vida, paz e luz.\nPeço-te perdão, Senhor,\nPois confio em teu amor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_270, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1135, position: 3, content: "Eis que vem a morte atrás\nDesta vida tão fugaz.\nQuando eu ao meu lar subir,\nE Teu rosto em glória vir,\nRocha eterna, que prazer\nEu terei de em Ti viver!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_270, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1136, position: 1, content: "Mais perto quero estar,\nMeu Deus, de Ti.\n'Inda que seja a dor\nQue me una a Ti!\nSempre hei-de suplicar:\nMais perto quero estar, (2x)\nMeu Deus, de Ti!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_271, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1137, position: 2, content: "Andando triste aqui\nNa solidão,\nPaz e descanso a mim\nTeus braços dão.\nSempre hei-de suplicar:\nMais perto quero estar, (2x)\nMeu Deus, de Ti!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_271, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1138, position: 3, content: "Minha alma cantará\nA Ti, Senhor,\nCheia de gratidão\nPor Teu Amor.\nSempre hei-de suplicar:\nMais perto quero estar, (2x)\nMeu Deus, de Ti!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_271, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1139, position: 4, content: "E quando a morte, enfim,\nMe vier chamar,\nCom serafins nos céus\nIrei morar.\nEntão me alegrarei\nPerto de Ti, meu Rei, (2x)\nMeu Deus, de Ti!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_271, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1140, position: 1, content: "Peregrinando por sobre os montes,\nDentro dos vales, sempre na luz,\nCristo promete nunca deixar-me;\nEis-me convosco, disse Jesus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_272, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1141, content: "Brilho celeste! Brilho celeste!\nEnche a minha alma a glória do céu!\nCom aleluias sigo cantando,\nDando louvores, Cristo é meu!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_272, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1142, position: 2, content: "Sombras à roda, sombras em cima,\nO Salvador não hão-de ocultar.\nEle é a luz que nunca se apaga.\nJunto a Seu lado sempre hei-de andar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_272, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1143, position: 3, content: "Raios benditos vão-me cercando;\nPassos avante para a mansão;\nMais e mais perto o Mestre seguindo,\nDando louvores p'la salvação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_272, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1144, position: 1, content: "Mestre! o mar se revolta,\nAs ondas nos dão pavor;\nO céu se reveste de trevas,\nNão temos um Salvador!\nNão se Te dá que morramos?\nPodes assim dormir,\nSe a cada momento nos vemos,\nJá prestes a submergir?", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_273, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1145, content: "As ondas atendem ao meu mandar:\nSossegai!\nSeja o encapelado mar,\nA ira dos homens, o génio do mal,\nTais águas não podem a nau tragar,\nQue leva o Mestre do céu e mar,\nPois todos ouvem o meu mandar:\nSossegai! Sossegai!\nConvosco estou para vos salvar;\nSim, sossegai!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_273, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1146, position: 2, content: "Mestre, na minha tristeza\nEstou quase a sucumbir;\nA dor que perturba minha alma,\nEu peço-Te, vem banir!\nDas ondas do mar que me encobrem,\nQuem me fará sair?\nPereço sem Ti, ó meu Mestre!\nVem logo, vem-me acudir!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_273, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1147, position: 3, content: "Mestre, chegou a bonança,\nEm paz vejo o céu e o mar!\nO meu coração goza calma\nQue não poderá findar.\nFica comigo, ó meu Mestre,\nDono da terra e Céu,\nE assim chegarei bem seguro\nAo porto, destino meu.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_273, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1148, position: 1, content: "Em nada ponho a minha fé,\nSenão na graça de Jesus;\nNo sacrifício remidor,\nNo sangue do meu Redentor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_274, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1149, content: "A minha fé e o meu amor\nEstão firmados no Senhor. (2x)", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_274, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1150, position: 2, content: "Se lhe não posso a face ver\nNa Sua graça vou viver.\nEm cada transe sem falhar,\nSempre hei-de n'Ele confiar.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_274, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1151, position: 3, content: "Seu juramento é mui leal.\nAbriga-me no temporal;\nAo vir cercar-me a tentação,\nÉ Cristo a minha salvação.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_274, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1152, position: 4, content: "Assim que o seu clarim soar,\nIrei com Ele me encontrar;\nE gozarei da redenção\nCom todos que no céu estão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_274, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1153, position: 1, content: "Que vista amável é\nQuando, com santo amor,\nIrmãos unidos pela fé\nAdoram o Senhor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_275, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1154, position: 2, content: "O mundo observará\nAquela santa paz;\nComo um perfume sentirá\nO gozo que ela traz.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_275, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1155, position: 3, content: "Envia-nos, Jesus,\nDo Teu monte Sião,\nO Santo Espírito que produz\nAquela doce união.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_275, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1156, position: 1, content: "Na Terra abençoada estou,\nPor Beulah peregrino vou;\nDelícias abundantes são;\nE só dos céus saudades dão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_276, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1157, content: "Oh! Bela terra de amor,\nDo alto monte encantador;\nOlhando, vejo além do mar\nQue breve hei-de atravessar,\nA praia áurea, eternal,\nQuerido lar Celestial!", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_276, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1158, position: 2, content: "Comigo anda o Salvador,\nConversa em tons de santo amor;\nMe guia sempre pela mão,\nÀ beira-céu os passos vão.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_276, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1159, position: 3, content: "A brisa traz o belo odor,\nDo paraíso ao redor,\nDe flores que não murcharão,\nDe frutos que supernos são.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_276, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1160, position: 4, content: "No zéfiro celestial\nFlutua o canto angelical,\nDe triunfante multidão,\nQue entoa a grande redenção.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_276, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1161, position: 1, content: "De Jesus a doce voz\nOuvi eu, pecador;\nAceitei, de coração,\nJesus, meu Salvador.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_277, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1162, content: "Meu pecado, sim,\nExpiou na cruz,\nE por graça sem igual\nSalvou-me meu Jesus.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_277, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1163, position: 2, content: "Rectidão em mim não há;\nPor graça salvo sou.\nDevo tudo a meu Senhor,\nPois já me resgatou.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_277, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1164, position: 3, content: "Por Jesus eu tenho paz,\nE gozo o seu favor;\nNada aqui me faltará,\nCom Cristo, meu Senhor.", hymnsNumber: HymnsNumberSeeder.FAITH_AND_SECURITY_277, typeStanza: HymnsContentCode.VERSE),

  ];
}