import 'package:ieca_mobile/db/_import.dart';
import 'package:ieca_mobile/enums/HymnsContentCode.dart';
import 'package:ieca_mobile/models/_import.dart';

class HymnsPraiseToWorship{
  static List<HymnsContent> list = [
    HymnsContent(id: 17, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 1, content: "Santo! Santo! Santo! Deus omnipotente! Cedo de manhã Cantaremos teu louvor. Santo! Santo! Santo! Justo e compassivo! És Deus triuno, Excelso criador!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 18, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 2, content: "Santo! Santo! Santo! Todos os remidos Juntos com os anjos, Proclamam teu louvor. Antes de formar-se O firmamento e a terra, Eras e sempre és, E hás-de ser Senhor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 19, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 3, content: "Santo! Santo! Santo! Nós os pecadores Não podemos ver Tua glória sem tremor. Tu somente és Santo, Só Tu és perfeito Deus soberano, Imenso em Teu amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 20, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 4, content: "Santo! Santo! Santo! Deus Omnipotente! Tuas obras louvam Teu nome com fervor. Santo! Santo! Santo! Justo e compassivo, És um só Deus, Supremo Criador.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 21, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 1, content: "Louvai o eterno Deus, O que seu Filho ao mundo enviou; Jesus a oferta nos ofereceu, Louvai o eterno Deus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 22, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 2, content: "Quem nos acusará? Jesus que foi morto e ressuscitou; Agora está à dextra do bom Deus, Quem nos acusará?", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 23, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 3, content: "Jesus nos libertou, Quem nos recusará ter o perdão? Quem nos intentará acusação? Jesus nos libertou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 24, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 4, content: "Havemos de vencer; O Salvador defende todos os seus; Nosso inimigo, Jesus já venceu, Havemos de vencer.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 25, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 1, content: "Louvamos-Te, ó Deus, Pelo Dom de Jesus, Que por nós pecadores Foi morto na cruz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 26, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, content: "Aleluia, toda a glória Te rendemos, sem fim; Aleluia, tua graça Imploramos. Ámen!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 27, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 2, content: "Louvamos-Te, ó Deus E ao teu Filho de amor, Que foi morto, mas vive, Supremo Senhor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 28, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 3, content: "Louvamos-Te, ó Deus, Pelo Espírito, luz Que nos tira das trevas E a Cristo conduz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 29, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 4, content: "Ó vem-nos encher De celeste fervor, E fazer-nos fruir Teu afável amor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 30, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 1, content: "Ao Rei adorai com glória e louvor, E graças rendei por seu grande amor. É Deus o refúgio a defesa eternal, Que em glória recebe louvor triunfal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 31, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 2, content: "Falai do poder, da graça de Deus, Em vestes de luz habita Ele os Céus. Seu carro Ele pode das nuvens formar Nas asas do vento faz Seu caminhar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 32, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 3, content: "Mistérios sem fim a terra contém Nosso inimigo, Jesus já venceu, Havemos de vencer.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 33, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 4, content: "Ó Deus, Teu poder quem pode narrar? Está no fulgor da luz, pelo ar. Nas fontes das rochas, no campo e na flor, Nas gotas de orvalho, na chuva e vapor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 34, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 5, content: "Nós filhos do pó, de frágil viver, Em Ti temos fé, ó Deus do poder. Mil bênçãos eternas quiseste nos dar, Amigo, que o mundo vieste salvar!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 35, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 1, content: "Todos bem-digam com prazer O santo nome do Senhor. Supremo em glória e em poder; É Deus de graça, Deus de amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 36, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 2, content: "Entrai na casa do Senhor Para com júbilo cantar. Somos ovelhas dum Pastor, A quem devemos adorar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 37, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 3, content: "Sejamos servos do Senhor E bem guardemos Sua lei. Cantemos todos o louvor Do nosso Salvador e Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 38, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 4, content: "Tudo Seu nome louvará Porque benigno é o Senhor; O Seu amor sem fim será. É sempre o mesmo o Benfeitor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 39, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 1, content: "A Cristo coroai! Que por nós encarnou. E Deus, o Santo Deus e Pai, Aos homens revelou. Eis Sua compaixão! Eis Sua mansidão! Quem vê a Cristo vê ao Pai, Sim, vê Seu coração!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 40, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 2, content: "A Cristo coroai! De tudo, o Criador! O Filho do Supremo Deus; Do mundo, o Salvador! Jesus, Senhor e Deus O grande Redentor, Em busca dos perdidos vem, O nosso bom Pastor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 41, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 3, content: "A Cristo coroai! Que, sobre a cruz, ganhou Por nós eterna redenção E para os céus voltou! Ele é o Rei dos reis, O príncipe da paz! Jesus, da morte o vencedor, Que a salvação nos traz!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 42, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 4, content: "A Cristo coroai! De todos o Senhor, A quem a multidão dos céus Aclama com fervor! Eis o Cordeiro ali, Que sobre o trono está! Que vive e reina lá por nós E cedo voltará!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 43, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_11, position: 1, content: "Louvores a Deus, mui sinceros louvores, Tributa a minha alma com grande fervor; Só Tu és a fonte de graça e favores, Divina promessa recursos de amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 44, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_11, position: 2, content: "Louvar-Te, Senhor, meu desejo constante, Meus votos ardentes em penhor sem par. Louvar-Te na vida, no lar ou distante, Sozinho ou na Igreja por todo o lugar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 45, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_11, position: 3, content: "Aceita, Senhor, a expressão de minha alma, Tributo de graças, pois tudo me dás: Nos dias de lutas, nas horas de calma, Contigo, Senhor, tenho a bênção da paz!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 46, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_12, position: 1, content: "Ó Deus, bom Pai e Benfeitor, A Ti rendemos com ardor, Louvor, poder, sem fim, Senhor De todos nós, Sustentador.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 47, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_12, position: 2, content: "E Tu, Deus Filho, ó bom Jesus, Por nós sofreste numa cruz. De Ti nos vem a clara luz Que nossos pés aos céus conduz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 48, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_12, position: 3, content: "Tu Deus, Espírito veraz, As nossas almas satisfaz Com gozo e divina paz E as nossas aflições desfaz.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 49, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_13, position: 1, content: "Deus está no templo! Pai Omnipotente: A Seus pés nos humilhamos. Servos consagrados Reverentemente, Ao Santíssimo adoremos. Por favor, com amor, Spiritualmente, Deus está no templo.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 50, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_13, position: 2, content: "Cristo está no templo! Sumo benefício! Recebemos do seu sangue, Ele, o bom Cordeiro, Foi o sacrifício Que o pecado todo extingue. Escolheu e sofreu O cabal suplício; Cristo está no templo.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 51, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_13, position: 3, content: "Vem, ocupa o templo! Espírito divino! Nossos corações habita. Ó paciente Mestre, Dá-nos Teu auxílio, Aclarando a lei bendita. Com prazer e poder E graça infinita; Ele está no templo.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 52, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_14, position: 1, content: "Altamente os céus proclamam, Seu divino Criador; Anuncia o firmamento, Tuas obras, ó Senhor! Incessantes, noite e dia, Dão sinais do Teu poder, Sem palavras proclamando Tua glória, teu saber.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 53, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_14, position: 2, content: "Tua lei, quão preciosa, Brilha mais que a clara luz; Esclarece os ignorantes, Guia as almas a Jesus. Grande e linda recompensa, Ganhará quem Te servir, E Teus santos mandamentos Bem fiel, Senhor, cumprir.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 54, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_14, position: 3, content: "Da soberba vem guardar-nos, Da impureza e transgressão; Nossos passos conduzindo, Em sincera rectidão. Nesta graça meditando, Cantarei, meu bom Senhor, E será, na minha boca Agradável Teu louvor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 55, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 1, content: "A Jesus, o Rei da glória, Hinos de louvor cantai; Aos seus pés, humildemente, Seu poder, pois exaltai. Perdoados, resgatados, Sua glória proclamai!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 56, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 2, content: "Seu perdão e sua graça, Aos perdidos dispensou; Tão paciente e mui bondoso, Aos rebeldes se mostrou; Libertou-os, transformou-os, Dos castigos os salvou!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 57, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 3, content: "Nossas tentações conhece, Pois satã o quis vencer; Triunfante, Cristo agora, Aos tentados quer valer. Poderoso e tão bondoso, Ele pode socorrer!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 58, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 4, content: "Contemplando sua face, Ó remidos, O adorai! Dedicados, consagrados, Sua fama publicai. Oh! Louvai-O, exaltai-O, Seu amor anunciai!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 59, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_16, position: 1, content: "Alegre me senti, Ao convidar-me assim: Vamos a casa do Senhor. De sorte que os meus pés Caminham em direcção A Deus e Sua santa Sião.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 60, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_16, position: 2, content: "A Sua Santa Sião, Bem edificada está: É lá onde as tribos vão. Louvando ao seu Deus E seu grande poder. Abençoados são os que O crêem.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 61, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_16, position: 3, content: "Paz haja em Sião, Cidade de Jehová, Sua casa de adoração. Havemos de encontrar A habitação feliz. Meu coração anseia Ter.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 62, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_17, position: 1, content: "Fonte Tu de toda a bênção, Vem o canto me inspirar; Dons de Deus, que nunca cessam, Oh! Ensina o novo canto Dos remidos lá dos céus. Ao teu servo e ao povo santo, P’ra louvarmos-Te, ó bom Deus!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 63, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_17, position: 2, content: "Cá meu «EBENEZER» ergo, Pois Jesus me socorreu; E, por sua graça, espero Transportar-me para o Céu. Eu, perdido, procurou-me, Longe do meu Deus, sem luz; Maculado e vil, lavou-me, Com seu sangue o bom Jesus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 64, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_17, position: 3, content: "Devedor à Tua graça Cada dia e hora sou; Teu desvelo sempre faça Com que eu ame a Ti, Senhor. Eis minha alma vacilante: Toma-a, prende-a com amor, Sela o coração volante, Para o céu, meu Salvador.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 65, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 1, content: "Jesus, és a Palavra eterna de Deus; Senhor, sim, de graça e de paz. Nós te imploramos, vem pois escutar-nos; Vem dar-nos esperança e alegria.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 66, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 2, content: "Vem, faz-nos perfeitos, p'ra andarmos direitos, Vem já, sim nos tirar a cegueira. Perdoa nossas faltas, vem purificar-nos. Vem dar-nos a vida dos céus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 67, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 3, content: "Fortifica esta casa, de adoração viva; Que seja a entrada dos céus. Os corações fracos encontrem descanso; Os enfermos encontrem a cura.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 68, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 4, content: "Vem fortificar sim, os corações fracos, Enchê-los de paz e propensos a justiça; Que sejam pertença de Cristo.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 69, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 1, content: "Que delícia é crer em Cristo, Em seu nome confiar, Aceitar os seus ensinos E as promessas desfrutar!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 70, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, content: "Cristo! Cristo! Já confio Em Teu nome, em Teu poder; Cristo! Cristo, Bem-amado! Faze minha fé crescer.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 71, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 2, content: "Oh! que bênção crer em Cristo, Crer no sangue que verteu, Pois os meus pecados todos Deus por Ele removeu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 72, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 3, content: "Oh! que gozo é crer em Cristo, Ter certeza de perdão! Receber de Cristo mesmo Vida, paz e salvação.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 73, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 4, content: "Bem feliz eu sou em Cristo, Sempre d'Ele quero ser; Quero agora mui submisso, Sempre a Ele obedecer.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 74, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_20, position: 1, content: "Se eu pudesse celebrar, Com hino digno e voz sem par, A glória de Jesus Com os anjos eu alternaria Em doce e terna melodia, Ao pé da Sua cruz, Ao pé da Sua cruz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 75, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_20, position: 2, content: "Diria o sangue que verteu, As dores que por mim sofreu Maldito pela lei! E cantaria em grato ardor A majestade do Senhor, Meu sacrossanto Rei. Meu sacrossanto Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 76, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_20, position: 3, content: "O dia alegre chegará, Quando meu Pai me levará Remido à Sua luz! Ali, em êxtase de amor, No céu eu cantarei melhor, Salvo por meu Jesus! Salvo por meu Jesus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 77, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 1, content: "Santo, santo, santo é o Senhor; Sempre exaltado seja o Seu nome! Santo, santo, santo é o Senhor; Dai-lhe adoração, toda a terra! Cantai louvores, sim, triunfantes, Ao glorioso Cristo cantai. Santo, santo, santo é o Senhor Exaltado seja o Seu Nome.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 78, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 2, content: "Justo, justo, justo é o Senhor; No Seu governo sempre há justiça! Justo, justo, justo é o Senhor; Equidade vem com o Seu reino! Seu santo trono estabelecido, Garante a glória do Seu poder. Justo, justo, justo é o Senhor Equidade vem com Seu reino.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 79, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 3, content: "Terno, terno, terno é o Senhor; Cheio de compaixão e de graça! Terno, terno, terno é o Senhor Como nós em tudo tentado! Alto refúgio, fonte de graça Para Seu povo, Deus Salvador. Terno, terno, terno é o Senhor; Cheio de ternura e de graça.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 80, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 4, content: "Compassivo sempre é o Senhor; Tudo sabendo, tudo sentindo! Compassivo sempre é o Senhor; Nossas dores todas levando! Mesmo na morte a todos amando, Dando-Se a Si por nós sobre a cruz. Compassivo sempre é o Senhor. Nossas dores todas levando!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 81, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 1, content: "Ó Cristão, tem esperança, Cristo é teu fiel amigo, Tua luz e confiança; Ele é teu amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 82, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 2, content: "Ó Jesus em Ti confio; Fui por tua morte salvo, Salvo enfim além do rio Viverei feliz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 83, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 3, content: "Te verei na glória eterna, Sobre o trono majestoso. Cantarei canção suprema, Dando a Ti louvor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 84, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 4, content: "Glória a Ti, Jesus clemente, Seja dada aqui na terra; Glória a Ti, eternamente Lá nos altos céus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 85, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 1, content: "Vinde louvai ao Senhor; Glória, glória a Jesus; Glória dai ao Santo Espírito, Ao Deus trino nossa luz. Adorai-o com fervor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 86, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, content: "Grande é seu poder e amor; Sempiterno Criador", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 87, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 2, content: "Ele omnipotente Deus Fez as águas, terra e céus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 88, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 3, content: "Sol e lua e estrela são Obra da divina mão", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 89, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 4, content: "Com mão forte ao povo seu Grandiosa herança deu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 90, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 5, content: "Príncipes e reis feriu E Seu povo redimiu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 91, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 6, content: "Sua misericórdia traz Aos humildes gozo e paz.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 92, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 1, content: "Glória a Deus, o Pai Eterno, Cujo trono é os Céus: O universo lhe pertence, Glória sim, ao nosso Deus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 93, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, content: "Eu te louvo! Eu te louvo! Oh! Jesus meu Salvador! Dai-lhe glória ó remidos! Pois seu sangue limpa o pecador.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 94, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 2, content: "Glória ao Filho mui amado, Que merece o louvor, Demos glória ao Seu nome, Ao Cordeiro, ao Redentor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 95, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 3, content: "Demos nós, ao Santo Espírito Mil louvores por Seu dom; Por sua graça tão imensa, Glória, a Ele. Ele é bom!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 96, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 4, content: "Glória, glória ao Pai Bendito, Glória, glória a Jesus; Glória dai ao Santo Espírito, Ao Deus trino nossa luz.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 97, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 1, content: "Teu divinal amor veio-me buscar; Tudo com gratidão quero consagrar. Aceita, meu Senhor, de um grato pecador Tributo de louvor, dado com fervor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 98, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 2, content: "Atende, meu Jesus, essa petição; Tão débil sou, e mau é meu coração. Teu nome a exaltar, a nova a publicar, Teu reino a dilatar, vem-me habilitar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 99, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 3, content: "Oh! Dá-me mais paixão de um amor real, P’ra Te servir e ser muito mais leal! As almas a ganhar, sempre na luz a andar, E os filhos a amar, vem-me habilitar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 100, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 4, content: "Tudo o que sou, Senhor, eu Te votarei; Do mundo vil e mau nunca mais serei; Teu rosto quando vir, amor no Céu luzir, A glória do porvir vou enfim fruir.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 101, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 1, content: "Deus é o Criador; Eternamente é Rei. Ele criou o universo; Eternamente é Rei. Ele criou o mar; Eternamente é Rei. Ele criou o sol; Eternamente é Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 102, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, content: "Adorai, adorai, adorai, adorai, Eternamente é Rei. Cantai, cantai, cantai, cantai, Eternamente é Rei. É Santo, é Santo, é Santo, é Santo, Eternamente é Rei.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 103, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 2, content: "Deus é o Criador; Ele criou a chuva; Ele criou o vento; Ele criou o arvoredo;", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 104, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 3, content: "Deus é o Criador; Ele criou a vida; Ele criou o homem; Ele criou o mantimento;", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 105, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 4, content: "Enviou Jesus Cristo; Ele é o Salvador dos homens; E é Espírito Santo; Limpa o coração;", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 106, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 1, content: "A nosso Pai no Céu Tributa lábio meu, O Teu louvor. Jesus o Filho deu. O qual na cruz morreu, Do mal nos defendeu. A Deus louvai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 107, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 2, content: "A nosso Salvador, A nosso Redentor, Demos louvor. Seu corpo se partiu, E ao pobre pecador Na cruz o céu lhe abriu. A Deus louvai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 108, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 3, content: "A Deus Consolador Mandado por Jesus Demos louvor. De Cristo o grande amor Revela Instruidor. Sê meu renovador A Deus louvai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 109, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 4, content: "Louvemos com ardor, Com gozo e com fervor O trino Deus! Eternamente ali, Em canto abrasador, Trindade santa, a Ti Louvor nos céus!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 110, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 1, content: "Omnipotente Rei, Aqui presente sê No teu poder; O Teu excelso amor, Inspira-nos louvor; Queremos-te, Senhor, Engrandecer.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 111, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 2, content: "Ó encarnado Deus, Nos ouve lá dos céus A petição. Vem-nos abençoar, E vem fazer brotar O que se semear No coração.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 112, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 3, content: "Vem tu, Consolador, Sê testificador Da redenção. No templo vem entrar, A obra completar. Das manchas vem limpar O coração.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 113, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 4, content: "Ó grande trino Deus, Sim, te adoramos nós, E só a Ti! Santificar-nos-ás, Ao céu nos levarás, A glória nos darás, Contigo aí.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 114, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_29, position: 1, content: "Oh! com júbilo cantemos; Aleluia! Oh! com gratidão cantemos; Aleluia! Com os sons harmoniosos, Adoremos nosso Deus. Seu amor é tão imenso. Aleluia!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 115, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_29, position: 2, content: "Alegrem-se os corações; Aleluia! Exaltai o Salvador; Aleluia! Jesus é o nosso Guia, E também o nosso refúgio; Sua compaixão é imensa Aleluia!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 116, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_29, position: 3, content: "O louvor não cesse nunca; Aleluia! Tanto aqui como no céu, Aleluia! Testemunhas da esperança; Somos os da Boa-Nova; Vamos divulgá-la ao mundo; Aleluia!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 117, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 1, content: "Bendize, ó tu, meu coração, Bendize ao Salvador, E tudo quanto houver em mim, Derrame-lhe louvor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 118, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 2, content: "Bendize, ó tu, meu coração, Bendize ao Salvador, Não fiques esquecido, pois, Do Seu divino amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 119, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 3, content: "Ele os delitos, com amor E graça perdoou, E com divina compaixão Jesus te aliviou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 120, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 4, content: "O teu desejo satisfaz Com verdadeiros bens; A vida renovada assim, Tu, como as águias tens.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 121, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, position: 1, content: "A Deus dêmos glória, com grande fervor; Seu Filho bendito por nós todos deu; A graça concede ao mais vil pecador, Abrindo-lhe a porta de entrada no Céu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 122, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, content: "Exultai! Exultai! Vinde todos louvar A Jesus, Salvador: A Jesus Redentor; A Deus demos glória, Porquanto do Céu, Seu Filho bendito por nós todos deu.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 123, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, position: 2, content: "Óh! graça real, foi assim que Jesus, Morrendo, Seu sangue por nós derramou! Herança nos céus, com os santos em luz, Comprou-nos Jesus, pois o preço pagou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 124, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, position: 3, content: "A crer nos convida tal rasgo de amor, Nos merecimentos do Filho de Deus; E quem, pois confia no seu Salvador, Vai vê-lo sentado na glória dos céus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 125, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 1, content: "Saudai o nome de Jesus! Arcanjos, vos prostrai! Ao filho do eterno Deus Com glória coroai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 126, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 2, content: "Ó escolhida geração Do bom eterno Pai: Ao grande Autor da Salvação, Com glória coroai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 127, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 3, content: "Ó perdoados, cujo amor Bem triunfante vai, Ao Deus-Varão, Conquistador, Com glória coroai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 128, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 4, content: "Ó raças, tribos e nações, Ao Rei do mundo honrai; A quem quebrou vossos grilhões Com glória coroai.", typeStanza: HymnsContentCode.VERSE),

  ];
}