import 'package:ieca_mobile/db/_import.dart';
import 'package:ieca_mobile/enums/HymnsContentCode.dart';
import 'package:ieca_mobile/models/_import.dart';

class HymnsBirthOfJesus {
  static List<HymnsContent> list = [

    HymnsContent(id: 129, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 1, content: "Numa estrebaria rude Da cidade de Belém, Onde as gentes não pensavam Encontrar o Sumo Bem, Nela a Virgem deu à luz O Menino, o bom Jesus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 130, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 2, content: "Ainda que o Senhor de tudo, Neste mundo veio nascer, Foi seu berço a manjedoura; Leite humano quis beber; Ele tanto se humilhou No caminho que trilhou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 131, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 3, content: "Para ser o bom modelo, Cristo honrou e obedeceu A Maria, mãe bendita E sujeito à lei cresceu; Agradava em tudo a Deus A seu Pai, o Rei dos céus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 132, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_33, position: 4, content: "Desejamos desde agora, Conhecer o bom Jesus Fome, sede, dor, tristezas, Sofreu tanto e até a cruz, P'ra mostrar-nos compaixão E nos dar a salvação.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 133, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 1, content: "Pequena vila de Belém, Tranquilamente jaz, Cintila o estrelado céu, A gente dorme em paz, Nas tuas ruas brilha A sempiterna luz. De ti espera o mundo O Salvador, Jesus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 134, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 2, content: "Jesus recém-nascido! E lá no céu além, Os anjos velam com amor O Cristo de Belém. Oh! Proclamai, estrelas, A noite de Natal. Louvai a Deus, bondoso Rei. Que dá a paz real.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 135, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 3, content: "Agora em silêncio O Dom celeste veio. Aos corações assim Deus dá As bênçãos lá do céu. Ele vem sem ser ouvido No mundo pecador. Nas meigas almas quer entrar Jesus, o Salvador.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 136, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_34, position: 4, content: "Menino Santo de Belém. Rogamos-te descer; Das nossas almas tira o mal; Em nós vem já nascer. Os anjos nos trouxeram Mensagem tão fiel. Vem, faz em nós habitação, Jesus, Emanuel.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 137, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 1, content: "Tu deixaste, Jesus, O Teu reino de luz E baixaste a este mundo tão vil. Um presépio em Belém, Tu Jesus, Sumo Bem, Escolheste por berço infantil.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 138, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, content: "Vem, Jesus, habitar comigo, Em minha alma há lugar para Ti.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 139, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 2, content: "Alegraram-se os céus Com os Santos de Deus, Sim, por teres nascido, Jesus, Vindo aos filhos de Adão Conceder salvação Pela morte, em resgate na cruz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 140, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 3, content: "Tu vieste, Senhor, Revelar-nos amor E de todo o mal nos salvar; Mas provaste do fel, Do motejo cruel, Morte enfim Te fizeram provar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 141, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_35, position: 4, content: "Outra vez Tu virás, E por mim chamarás, Rodeado dos anjos de Deus. Oh, que gozo p’ra mim, Se disseres assim: «Um lugar te darei Eu nos céus»", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 142, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 1, content: "Ó santa luz brilhante, Tal como aos magos cintilaste Para guiá-los a Belém, Vem conduzir a nós também.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 143, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, content: "Ouçam, ouçam os louvores, Pelos anjos lá na glória. Cantam-nos a Boa Nova De paz e amor de Deus, Dada aos homens, De paz e amor de Deus, Dada aos homens.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 144, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 2, content: "Ó luz tal como brilhaste Lá na estalagem da Judea, Vem brilhar em nossos lares, P’ra que haja a Tua beleza.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 145, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 3, content: "Ó luz se nós brilharmos Tristonhos de corações, A Tua paz venha alegrar-nos, Mitigando todas as dores.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 146, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_36, position: 4, content: "Ó luz brilhante de graça, Iluminaste a manjedoura Iluminaste a rude cruz, P’ra conceder-nos a salvação.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 147, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 1, content: "Oh! Vinde fiéis, triunfantes, alegres, Sim, vinde a Belém, Já movidos de amor. Nasceu vosso Rei, O Cristo prometido.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 148, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, content: "Oh! Vinde, adoremos Oh! Vinde, adoremos Oh! Vinde, adoremos a nosso Senhor!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 149, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 2, content: "Olhai admirados a Sua humilde. Os anjos O louvam Com grande fervor, Pois veio connosco Habitar encarnado.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 150, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 3, content: "Por nós se humilhou Jesus, o adorável, Tornando-se pobre, Sujeito a dor, P'ra dar-nos de graça A vida sempiterna.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 151, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_37, position: 4, content: "Nos céus, adorai-O, vós anjos em coro, E todos na terra Lhe rendam louvor! A Deus honra e glória Contentes rendamos", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 152, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 1, content: "Foi na gruta de Belém, Onde surge a maravilha, No primeiro Natal! A criança foi deitada Numa pobre manjedoura, No primeiro Natal! No primeiro Natal!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 153, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 2, content: "Ali junto desta aldeia, Os pastores pastorearam, No primeiro Natal! Brilhou a fulgente luz, Lá, surgiram alguns anjos, No primeiro Natal! No primeiro Natal!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 154, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 3, content: "Já os anjos divulgaram O nascimento de Jesus, No primeiro Natal! Os pastores foram à aldeia, Adoraram o menino, No primeiro Natal! No primeiro Natal!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 155, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_38, position: 4, content: "A estrela fulgurante É que conduziu os magos, No primeiro Natal! E com viva fé partiram, Lá, chegaram com alegria, No primeiro Natal! No primeiro Natal!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 156, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 1, content: "Os enviados lá do céu Adoraram a Jeová. O seu filho enviou, Vindo à terra com a paz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 157, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 2, content: "Ele é Rei de corações, Ele é purificador, Da vida Ele é o sol, É da glória de Deus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 158, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 3, content: "Deixou o reino celestial, Para aqui se humilhar, E os homens salvar, Perdidos com o mal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 159, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_39, position: 4, content: "Gratos pelo seu Natal, Alegria trouxe a nós. Sua graça adorai, Sempiterno Rei Jesus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 160, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 1, content: "Anjos da mais alta glória, Vossas vozes levantai. Cristo já nasceu! A história, Ao mundo todo proclamai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 161, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, content: "Adoremos, Adoremos. Ao recém-nascido rei.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 162, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 2, content: "Os pastores vigiando, Sobre seu rebanho estão. Deus em Cristo habitando, Entre os homens, adoração.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 163, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 3, content: "Magos, vossas buscas todas, Hoje mesmo abandonai; Das nações o desejado, Em casebre adorai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 164, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_40, position: 4, content: "Os que a Cristo reverente Esperando vê-lo estão, Em seu trono de repente, Contemplá-Lo poderão", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 165, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_41, position: 1, content: "Tocai, ó sininhos. Cantai, ó crianças. Publicai a Boa-Nova Do Salvador que nos nasceu. Alegrai-vos todos, Dessa imensa graça. Adorai com reverência, Cristo, nosso Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 166, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_41, position: 2, content: "Tocai, ó sininhos. Cantai, ó crianças. Para as nações inteiras, Da Boa-Nova alegrar-se E da melodia Que os anjos entoaram. Que anunciam a paz bendita, Vinda à humanidade.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 167, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_41, position: 3, content: "Tocai, ó sininhos. Cantai, ó crianças. Ide juntos com os anjos, Contemplai o milagre. Juntos com os magos, Levai oferendas, Àquele que deixou Sua glória, Salvação nos dá.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 168, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_42, position: 1, content: "Do tronco rude e forte Da estirpe de Jessé; Vem o rebento novo, Que infunde nova fé, E nele Deus se apraz. Nas trevas do Universo Jesus a luz nos traz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 169, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_42, position: 2, content: "Tu eras um anelo Do povo de Israel. Da seiva do Rebento Se nutre agora o fiel. Ó Verbo Divinal! De Deus Tu foste oferta, Perfeita do Natal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 170, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_42, position: 3, content: "Ele é o amigo certo De pobres sem esperança; Conhece suas faltas Curadas pela fé. Jamais a morte atroz. Ele lhes dá conforto Por uma libação.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 171, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 1, content: "Ah! Um anjo proclamou O primeiro Natal, À uns pobres pastores Ao pé de Belém, Lá nos campos a guardar Os rebanhos do mal, Numa noite tão fria E escura também.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 172, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, content: "Natal! Natal! Natal! Natal! É-nos nascido um Rei Divinal!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 173, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 2, content: "E de súbito no céu Linda estrela surgiu, No Oriente brilhou Com estranho fulgor. E a Terra recebeu Essa luz que caiu, Muitas noites ainda Em exímio esplendor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 174, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 3, content: "Tendo visto a clara luz Dessa estrela sem par, Do Oriente alguns Magos A foram seguir. À procura de um Rei Que devia chegar, Aos Judeus e as velhas Promessas cumprir.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 175, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 4, content: "Essa estrela apareceu E os Magos guiou, Na estrada que para Belém os conduz; Afinal, sobre Belém Essa estrela parou, Mesmo acima da casa em que Estava JESUS.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 176, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 5, content: "E os magos com afã, E com grande temor, De joelhos entraram Naquele lugar. Com ofertas liberais E de muito valor; Ouro, mirra e incenso Vieram Lhe dar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 177, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_43, position: 6, content: "E com eles vamos nós, Com sincero fervor; Dar louvores a nosso Sublime Senhor. Que, deixando os altos céus, A este mundo baixou. E, morrendo na cruz, Nossas almas salvou.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 178, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_44, position: 1, content: "Noite de paz! Noite de amor! Dormem todos em redor. Entre os astros que espargem a luz, Proclamando o Menino Jesus; Brilha a estrela de paz! Brilha a estrela de paz!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 179, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_44, position: 2, content: "Noite de paz! Noite de amor! Nas campinas aos pastores, Lindos anjos mandados por Deus, Anunciam a nova dos céus; Nasce o bom Salvador, Nasce o bom Salvador!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 180, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_44, position: 3, content: "Noite de paz! Noite de amor! Oh, que belo esplendor Ilumina o Menino Jesus! No presépio do mundo eis a luz, Sol de eterno fulgor! Sol de eterno fulgor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 181, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_45, position: 1, content: "Em linda noite ao mundo êxul, Em coro angelical; Com harpas de ouro o céu quis dar Um canto divinal. E toda a terra, então, ouviu Promessas imortais, Com bênçãos eternais.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 182, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_45, position: 2, content: "Pairando sobre a terra estão Os anjos a cantar; E sobre o mundo pecador Derramam luz sem par. Acima dos tormentos mil, Angústias do viver, Proclamam vida perenal Pois bênçãos vêm trazer.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 183, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_45, position: 3, content: "E vão-se os dias sem cessar, Segundo a voz de Deus; Mas, sobre a terra as gerações Caminham rumos seus. E, quando enfim, reinar a paz Dos salvos pelo amor, O coro imenso então será, E santo o seu louvor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 184, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 1, content: "Oh! vem; Oh! vem, Emanuel Remir o escravo, Israel, Que no exílio em pranto está. Messias, vem, tira-o de lá.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 185, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, content: "Exulta e folga, ó Israel, Que vem remir-te Emanuel", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 186, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 2, content: "Sabedoria lá dos céus, Das gentes enche os corações; Vem vivifica os filhos teus; Do mal separa as nações.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 187, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 3, content: "Raia o dia da redenção! Do mundo as trevas vem dissipar; Louvando a Deus com grata emoção, Oh! vinde todos O proclamar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 188, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_46, position: 4, content: "Cristo entre homens se encarnou E Deus em Cristo a nós se revelou. Oh! quão gloriosa encarnação, De Deus glorioso Emanuel!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 189, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, position: 1, content: "Mal supõe aquela gente Que a Belém quer ir parar, Que uma luz tão refulgente Vai ali brilhar. E por anjos anunciado, E os pastores logo vêem, Que esse Rei por Deus mandado Nasce em Belém.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 190, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, content: "Vinde, ouvir a doce história, Que do oriente vem: O Messias, Rei da Glória, Nasce em Belém.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 191, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, position: 2, content: "Mundo triste, oh! Desperta! Teus grilhões desfeitos são. Tens a porta franca, aberta, Sai da vil prisão! Não hesites duvidoso; Este dom do céu provém. Cristo, o Todo-Poderoso. Nasce em Belém.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 192, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_47, position: 3, content: "Ouve com feliz espanto. Surge da vergonha e dor. Cesse, cesse todo o pranto; Tens um Salvador. Glória a Deus vem promovendo Mas aos homens só quer bem. Paz, eterna paz, trazendo, Nasce em Belém.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 193, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 1, content: "Há uma estrela no céu; Há canções pelo ar; Luz divina desceu Para o homem guiar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 194, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, content: "E essa estrela brilhando Mostra em seu fulgor Que em Belém é nascido Jesus, o Senhor.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 195, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 2, content: "E os anjos dos céus Descem em multidão, Proclamando de Deus Paz, amor e perdão.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 196, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 3, content: "Pela estrela guiados, Sábios, reis e pastores Dão louvores prostrados Ao Senhor dos senhores.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 197, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_48, position: 4, content: "Glória, glória ao Senhor Que até nós baixou. P’ra mostrar Seu amor Entre nós encarnou.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 198, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 1, content: "Sobre os campos de Belém Descem anjos a cantar; Do Senhor aos homens vêm Boas novas proclamar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 199, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, content: "Glória in excelsis Deo! Glória in excelsis Deo.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 200, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 2, content: "Glória a Deus, na terra paz Eis o canto divinal. Hoje Cristo aos homens traz Luz, amor, vida eternal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 201, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 3, content: "Ledos, os pastores vão Visitar o novo Rei; Tributar-Lhe adoração Como sua humilde grei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 202, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_49, position: 4, content: "Vinde à gruta e contemplai O Menino, o Redentor; De joelhos, lhe prestai Honra, glória e louvor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 203, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_50, position: 1, content: "Povos, cantai! Jesus nasceu! À terra a luz desceu! A graça infinda ao mundo vem, A graça infinda ao mundo vem, Na gruta de Belém, Na gruta de Belém, Jesus humilde ao mundo vem.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 204, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_50, position: 2, content: "Do eterno Deus o Salvador Revela o grande amor! Na manjedoura um leito tem, Na manjedoura um leito tem, Na gruta de Belém, Na gruta de Belém, Jesus Cristo um leito tem.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 205, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_50, position: 3, content: "Vamos, ó crentes, recordar Que foi por nos amar, Que à terra veio o Sumo Bem, Que à terra veio o Sumo Bem, Na gruta de Belém, Na gruta de Belém, Jesus o amado, o Sumo Bem.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 206, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 1, content: "Alerta, ó terra, entoa! O canto já ressoa; O mundo pecador Tem grande sorte e boa. A nova se vos dá, E quão alegre soa: Nasceu o redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 207, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, content: "Nasceu o Redentor! Nasceu o Redentor! O Eterno Pai do céu Seu Filho ao mundo deu. Alerta, ó terra entoa A nova alegre e boa: Nasceu o Redentor!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 208, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 2, content: "A noite já passou, A aurora já raiou; O negro e denso véu De todo se rasgou. Dos montes através O brado ressoou: Nasceu o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 209, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 3, content: "Nasceu o Rei da paz, Num berço humilde jaz; Nas asas desse amor Conforto a todos traz; Dizei em alta voz Que Cristo satisfaz; Nasceu o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 210, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 4, content: "Oh, gozo divinal, Amor celestial, Quem pode te sondar Ou Ter um outro igual. Possa eu, da morte réu, Gozar ventura tal? Nasceu o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 211, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_51, position: 5, content: "Oh, povos, proclamai, Nações, oh, jubilai, Eis finda toda a dor, Jamais se dá um ai; A Virgem deu à luz; A Deus glorificai! Nasceu O Redentor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 212, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, position: 1, content: "Eis dos anjos a harmonia, Cantam glória ao Novo Rei; Paz aos homens e alegria, Paz com Deus e suave Lei. Ouçam povos exultantes, Ergam salmos triunfantes, Aclamando o Seu Senhor, Nasceu Cristo, o Redentor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 213, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, content: "Toda a terra e altos céus Cantem glória ao Homem-Deus!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 214, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, position: 2, content: "Cristo eternamente honrado, Do Seu trono se ausentou. Cristo, entre homens encarnado, Deus connosco nos mostrou. Quão bondosa divindade! Quão gloriosa humanidade! Salve! Glória de Israel, Luz do mundo Emanuel!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 215, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_52, position: 3, content: "Cante o povo resgatado; “Glória ao Príncipe da paz”. Deus em Cristo revelado, Vida e luz ao mundo traz! Nasce p’ra que renasçamos; Vive para que vivamos, Rei, Profeta e Salvador! Todos louvem ao Senhor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 216, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 1, content: "Nós, três reis com dons p'ra ofertar, Do oriente ousamos viajar; Tendo a estrela pura e bela Para nos guiar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 217, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, content: "Oh, estrela, ó astro condutor Como é belo o teu fugor! Para oeste nos conduz, Com tua forte e meiga luz.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 218, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 2, content: "Ouro, eu trago ao Rei que nasceu Em Belém, Senhor lá do céu; Quero honrá-Lo, coroá-Lo, Tê-Lo por Deus meu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 219, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 3, content: "Eu, Insenso venho oferecer, Por tal culto a Deus pertencer; Grato adoro, ledo imploro Tão augusto ser.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 220, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 4, content: "Mirra amargo, símbolo de dor Venho eu dar ao meu Salvador; Odiado, desprezado, Vai ser meu Senhor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 221, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_53, position: 5, content: "Mas glorioso, alfim, se erguerá; Sobre a morte triunfará; Aleluia! Aleluia! Tudo cantará!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 222, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_54, position: 1, content: "Lá na manjedoura Da nobre Belém, Jesus pequenino; Um berço não tem. Mas dorme nas palhas, Seu rosto a brilhar, E os astros se curvam P'ra o virem beijar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 223, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_54, position: 2, content: "O gado fez bulha; Jesus acordou; Olhou meigo em volta, Porém não chorou, Eu amo-te muito, Querido Jesus; Dos Céus p'ra mim olha, Derrama em mim luz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 224, hymnsNumber: HymnsNumberSeeder.BIRTH_OF_JESUS_54, position: 3, content: "Oh! fica comigo, Te rogo Senhor, P'ra ter-Te bem perto, Sentir Teu amor. Oh! toma as crianças Nos bons braços Teus. Prepara-nos todos Para a vida nos céus.", typeStanza: HymnsContentCode.VERSE),
    
  ];

}