import 'package:ieca_mobile/models/_import.dart';
import 'package:ieca_mobile/seeders/_import.dart';

class InvocationContentSeeder{

  static List<InvocationContent> items() {
    return [
      InvocationContent(id: 1, position: 1, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Habacuque 2:20", content: "O Senhor está no seu santo templo: cale-se diante dele toda a terra"),
      InvocationContent(id: 2, position: 2, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 122:1, 29:2; Génesis 28:16-17", content: "Alegrei-me quando me disseram: Vamos à casa do Senhor. Na verdade o Senhor está neste lugar. Esta é a casa de Deus: esta é a porta dos céus. Dai ao Senhor a glória devida ao seu nome, adorai o Senhor na beleza da Sua santidade."),
      InvocationContent(id: 3, position: 3, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 15:1-2", content: "Senhor quem habitará no Teu tabernáculo? Quem morará no Teu santo monte? Aquele que anda em sinceridade e pratica a justiça, e fala verazmente, segundo o seu coração"),
      InvocationContent(id: 4, position: 4, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Isaías 45:22; Salmo 85:9, 84:11; 106:1", content: "Olhai para mim, e sereis salvos, vós, todos os termos da terra; porque eu Sou Deus, e não há outro. Na verdade a sua salvação está perto dos que o temem. O Senhor Deus é um sol e protecção. O Senhor dará graça e glória; não negará bem algum aos que andam na rectidão. Louvai ao Senhor"),
      InvocationContent(id: 5, position: 5, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 92:1-2", content: "Bom é louvar ao Senhor, e cantar louvores ao teu nome, ó Altíssimo; para de manhã anunciar a tua benignidade, e todas as noites, a tua fidelidade"),
      InvocationContent(id: 6, position: 6, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 42:1-2, 62:1, 63:3", content: "Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus! A minha alma tem sede de Deus, do Deus vivo: Quando entrarei e me apresentarei ante a face de Deus? A minha alma espera somente em Deus; dele vem a minha salvação. Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão"),
      InvocationContent(id: 7, position: 7, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 115:11", content: "Vós, os que temeis ao Senhor, confiai no Senhor: ele é seu auxílio e seu escudo"),
      InvocationContent(id: 8, position: 8, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Oseias 6:1, 3", content: "Vinde, e tornemos para o Senhor, porque ele despedaçou e nos sarará; fez a ferida e a ligará. Conheçamos, e prossigamos em conhecer ao Senhor; como a alva será a sua saída, e ele a nós virá como a chuva, como chuva serôdia que rega a terra"),
      InvocationContent(id: 9, position: 9, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Miqueias 6-6, 8", content: "Com que me apresentarei ao Senhor, e me inclinarei ante o Deus Altíssimo? Ele te declarou, ó homem, o que é bom. E que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus?"),
      InvocationContent(id: 10, position: 10, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 99:9", content: "Exaltai ao Senhor, nosso Deus, e adorai-O no Seu santo monte, porque o Senhor, nosso Deus, é santo"),
      InvocationContent(id: 11, position: 11, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 95:1-3, 6-8", content: "Vinde, cantemos ao Senhor: cantemos com júbilo à rocha da nossa salvação. Porque o Senhor é Deus grande, e Rei grande, acima de todos os deuses. Ó, vinde, adoremos e prostremo-nos; ajoelhemos diante do Senhor que nos criou. Porque ele é o nosso Deus, e nós, povo do seu pasto e ovelhas da sua mão. Se hoje ouvirdes a sua voz, não endureçais os vossos corações"),
      InvocationContent(id: 12, position: 12, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 69:32, 106:1", content: "O vosso coração viverá, pois que buscais a Deus. Louvai ao Senhor"),
      InvocationContent(id: 13, position: 13, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 100:3-5", content: "Sabei que o Senhor é Deus: foi ele, e não nós, que nos fez povo seu e ovelhas do seu pasto. Entrai pelas portas dele com louvor, e em seus átrios com hinos: louvai-O e bendizei o seu nome. Porque o Senhor é bom, e eterna a Sua misericórdia; e a sua verdade estende-se de geração em geração"),
      InvocationContent(id: 14, position: 14, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 55:17, 145:1", content: "De tarde e de manhã e ao meio-dia orarei; e clamarei, e Ele ouvirá a minha voz. Eu te exaltarei, ó Deus, rei meu, e bendirei o teu nome pelos séculos dos séculos"),
      InvocationContent(id: 15, position: 15, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Jeremias 29:11-13", content: " Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais. Então me invocareis, e ireis, e orareis a mim, e eu vos ouvirei. E buscar-me-eis, e me achareis, quando me buscardes de todo o vosso coração"),
      InvocationContent(id: 16, position: 16, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 24:3-5, 119:1-2", content: "Quem subirá ao monte do Senhor, ou quem estará no seu lugar Santo? Aquele que é limpo de mãos e puro de coração. Este receberá a bênção do Senhor e a justiça do Deus da sua salvação. Bemaventurados os que trilham caminhos rectos, e andam na lei do Senhor. Bem-aventurados os que guardam os seus testemunhos, e o buscam de todo o coração"),
      InvocationContent(id: 17, position: 17, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 118:24, 29:2, 99:9", content: " Este é o dia que fez o Senhor: regozijemo-nos, e alegremo-nos nele. Dai ao Senhor a glória devida ao seu nome: porque o Senhor nosso Deus é santo"),
      InvocationContent(id: 18, position: 18, invocationTitle: InvocationTitleSeeder.GENERAL, books: "João 4:24; Salmo 19:14", content: "Deus é Espírito, e importa que os que o adoram, o adorem em espírito e em verdade. Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, Rocha minha e Libertador meu!"),
      InvocationContent(id: 19, position: 19, invocationTitle: InvocationTitleSeeder.GENERAL, books: "Salmo 113:3, 100:4", content: "Desde o nascimento do sol até ao ocaso, seja louvado o nome do Senhor. Entrai pelas portas dele com louvor, e em seus átrios com hinos. Louvai-O e bendizei o seu nome"),

      InvocationContent(id: 20, position: 20, invocationTitle: InvocationTitleSeeder.ADVENT, books: "I. Tessalonicenses 4:16; Apolípse 1:7", content: "Porque o mesmo Senhor descerá do céu, com alarido, e com voz de arcanjo, e com a trombeta de Deus, e os que morreram em Cristo ressuscitarão primeiro. Eis que vem com as nuvens, e todo o olho o verá, até os mesmos que o trespassaram; e todas as tribos da terra se lamentarão sobre ele. Sim. Ámen."),
      InvocationContent(id: 21, position: 21, invocationTitle: InvocationTitleSeeder.ADVENT, books: "Isaías 27:13", content: "E será, naquele dia, que se tocará uma grande trombeta, e os que andavam perdidos pela terra da Assíria, e os que foram desterrados para a terra do Egipto tornarão a vir, e adorarão ao Senhor no monte santo, em Jerusalém"),

      InvocationContent(id: 22, position: 22, invocationTitle: InvocationTitleSeeder.CHRISTMAS, books: "Gálatas 4:4-5", content: "Mas, vindo a plenitude dos tempos, Deus enviou seu Filho, nascido de mulher, nascido sob a lei, para remir os que estavam debaixo da lei, a fim de recebermos a adopção de filhos"),

      InvocationContent(id: 23, position: 23, invocationTitle: InvocationTitleSeeder.EPIPHANY, books: "João 1:14", content: "E o verbo se fez carne, e habitou entre nós, e vimos a sua glória, como a glória do unigénito do Pai, cheio de graça e de verdade"),

      InvocationContent(id: 24, position: 24, invocationTitle: InvocationTitleSeeder.LENT, books: "Joel 2:12-13", content: "Ainda assim, agora mesmo, diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto. E rasgai o vosso coração, e não os vossos vestidos, e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em beneficência"),

      InvocationContent(id: 25, position: 25, invocationTitle: InvocationTitleSeeder.PALM_SUNDAY, books: "", content: "Hosana ao Filho de David; bendito o que vem em nome do Senhor! Dizei à folha de Sião: Eis que o teu Rei virá a ti, Justo de Salvador. Bendito o Rei que vem em nome do Senhor! Paz no céu e glória nas alturas! Assim o Senhor seja convosco"),

      InvocationContent(id: 26, position: 26, invocationTitle: InvocationTitleSeeder.EASTER, books: "Lucas 24:34, 1 Tessalonicenses 4:14", content: "Diziam: Ressuscitou verdadeiramente o Senhor, e já apareceu a Simão. Porque, se cremos que Jesus morreu e ressuscitou, assim, também, aos que em Jesus dormem, Deus os tornará a trazer com ele"),
      InvocationContent(id: 27, position: 27, invocationTitle: InvocationTitleSeeder.EASTER, books: "Romanos 8:11", content: "Se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará os vossos corpos mortais, pelo seu Espírito que em vós habita"),

      InvocationContent(id: 28, position: 28, invocationTitle: InvocationTitleSeeder.PENTECOST, books: "Joel 2:28-29", content: "E há-de ser que, depois, derramarei o meu Espírito sobre toda a carne, e vossos filhos e vossas filhas profetizarão, os vossos velhos terão sonhos, os vossos mancebos terão visões. E, também, sobre os servos e sobre as servas, naqueles dias, derramarei o meu Espírito"),
    ];
  }
}