import 'package:ieca_mobile/db/_import.dart';
import 'package:ieca_mobile/enums/PsalmsPerson.dart';
import 'package:ieca_mobile/models/PsalmsContent.dart';
import 'package:ieca_mobile/seeders/_import.dart';
import 'package:ieca_mobile/util/AppLang.dart';

class PsalmsContentSeeder{

  static List<PsalmsContent> items() {
    return [
      PsalmsContent(id: 1, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Os céus manifestam a glória de Deus e o firmamento anuncia a obra das Suas mãos. Um dia faz declaração a outro dia, e uma noite mostra sabedoria a outra noite. Sem linguagem, sem fala, ouvem-se as suas vozes em toda a extensão da terra, e as suas palavras até aos confins do mundo", lang: AppLang.PT),
      PsalmsContent(id: 2, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração, perante a tua face, Senhor, Rocha minha e Libertador meu!", lang: AppLang.PT),
      PsalmsContent(id: 3, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Neles pôs uma tenda para o sol, que qual noivo que sai do seu tálamo, e se alegra como um herói a correr o seu caminho. A sua saída é desde uma extremidade dos céus, e o seu curso até a outra extremidade deles; e nada se furta ao seu calor", lang: AppLang.PT),
      PsalmsContent(id: 4, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração, perante a tua face, Senhor, Rocha minha e Libertador meu!", lang: AppLang.PT),
      PsalmsContent(id: 5, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "A lei do Senhor é perfeita e refrigera a alma; o testemunho do Senhor é fiel, e dá sabedoria aos símplices. Os preceitos do Senhor são rectos, e alegram o coração: o mandamento do Senhor é puro e alumia os olhos", lang: AppLang.PT),
      PsalmsContent(id: 6, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração, perante a tua face, Senhor, Rocha minha e Libertador meu!", lang: AppLang.PT),
      PsalmsContent(id: 7, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "A lei do Senhor é perfeita e refrigera a alma; o testemunho do Senhor é fiel, e dá sabedoria aos símplices. Os preceitos do Senhor são rectos, e alegram o coração: o mandamento do Senhor é puO Temor do Senhor é limpo, e permanece eternamente; os juízos do Senhor são verdadeiros e justos juntamente. Mais desejáveis são do que o ouro, sim, do que muito ouro fino; e mais doces do que o mel e o licor dos favos; Também por eles é admoestado o teu servo; e em os guardar há grande recompensaro e alumia os olhos", lang: AppLang.PT),
      PsalmsContent(id: 8, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração, perante a tua face, Senhor, Rocha minha e Libertador meu!", lang: AppLang.PT),
      PsalmsContent(id: 9, position: 9, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Quem pode entender os próprios erros? Expurga-me tu dos que me são ocultos. Também da soberba guarda o teu servo, para que se não assenhoreie de mim; então serei sincero, e ficarei limpo de grande transgressão", lang: AppLang.PT),
      PsalmsContent(id: 10, position: 10, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_19, content: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração, perante a tua face, Senhor, Rocha minha e Libertador meu!", lang: AppLang.PT),

      PsalmsContent(id: 11, position: 11, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "Do Senhor é a terra e a sua plenitude, o mundo e aqueles que nele habitam. Porque ele a fundou sobre os mares, e a firmou sobre os rios", lang: AppLang.PT),
      PsalmsContent(id: 12, position: 12, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "Quem subirá ao monte do Senhor, ou quem estará no seu lugar santo?", lang: AppLang.PT),
      PsalmsContent(id: 13, position: 13, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "Aquele que é limpo de mãos e puro de coração, que não entrega a sua alma à vaidade, nem jura enganosamente. Este receberá a bênção do Senhor e a justiça do Deus da sua salvação. Esta é a geração daqueles que buscam, daqueles que buscam a tua face, ó Deus de Jacob", lang: AppLang.PT),
      PsalmsContent(id: 14, position: 14, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "Levantai, ó portas, as vossas cabeças; levantai-vos, ó entradas eternas, e entrará o Rei da Glória", lang: AppLang.PT),
      PsalmsContent(id: 15, position: 15, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "Quem é este Rei da Glória?", lang: AppLang.PT),
      PsalmsContent(id: 16, position: 16, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "O Senhor, forte e poderoso, o Senhor poderoso na guerra. Levantai, ó portas, as vossas cabeças, levantai-vos, ó entradas eternas, e entrará o rei da Glória", lang: AppLang.PT),
      PsalmsContent(id: 17, position: 17, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "Quem é este Rei da Glória?", lang: AppLang.PT),
      PsalmsContent(id: 18, position: 18, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_24, content: "O Senhor dos Exércitos; ele é o Rei da Glória", lang: AppLang.PT),

      PsalmsContent(id: 19, position: 19, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Regozijai-vos no Senhor, vós, justos, pois aos rectos convém o louvor. Louvai ao Senhor com harpa, cantai a Ele com saltério de dez cordas. Cantai-lhe um cântico novo: tocai bem e com júbilo. Porque a palavra do Senhor é recta, e todas as suas obras são fiéis. Ele ama a justiça e o juízo; a terra está cheia da bondade do Senhor", lang: AppLang.PT),
      PsalmsContent(id: 20, position: 20, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos", lang: AppLang.PT),
      PsalmsContent(id: 21, position: 21, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Pela palavra do Senhor foram feitos os céus, e todo o exército deles pelo espírito da sua boca. Ele ajunta as águas do mar como num montão; Põe os abismos em tesouros. Tema toda a terra ao Senhor; temam-no todos os moradores do mundo, porque falou, e tudo se fez; mandou, e logo tudo apareceu", lang: AppLang.PT),
      PsalmsContent(id: 22, position: 22, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos", lang: AppLang.PT),
      PsalmsContent(id: 23, position: 23, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "O Senhor desfaz o conselho das nações, quebranta os intentos dos povos. O conselho do Senhor permanece para sempre; os intentos do seu coração de geração em geração. Bem-aventurada é a nação cujo Deus é o Senhor, e o povo que Ele escolheu para sua herança", lang: AppLang.PT),
      PsalmsContent(id: 24, position: 24, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos", lang: AppLang.PT),
      PsalmsContent(id: 25, position: 25, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "O Senhor olha desde os céus e está vendo a todos os filhos dos homens; da sua morada, contempla todos os moradores da terra. Ele é que forma o coração de todos eles, que contempla todas as suas obras", lang: AppLang.PT),
      PsalmsContent(id: 26, position: 26, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos", lang: AppLang.PT),
      PsalmsContent(id: 27, position: 27, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Eis que os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia; para livrar as suas almas da morte, e para os conservar vivos na fome. A nossa alma espera no Senhor: Ele é o nosso auxílio e o nosso escudo, pois nele se alegra o nosso coração, porquanto temos confiado no seu santo nome", lang: AppLang.PT),
      PsalmsContent(id: 28, position: 28, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_33, content: "Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos", lang: AppLang.PT),

      PsalmsContent(id: 29, position: 29, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Louvarei ao Senhor em todo o tempo: o seu louvor estará continuamente na minha boca. A minha alma se gloriará no Senhor: os mansos o ouvirão e se alegrarão", lang: AppLang.PT),
      PsalmsContent(id: 30, position: 30, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Engrandecei ao Senhor comigo, e juntos exaltemos o seu nome. Busquei ao Senhor, e ele me respondeu: livrou-me de todos os meus temores. Olharam para ele, e foram iluminados; e os seus rostos não ficarão confundidos", lang: AppLang.PT),
      PsalmsContent(id: 31, position: 31, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Clamou este pobre, e o Senhor o ouviu, e o salvou de todas as suas angústias. O anjo do Senhor acampa-se ao redor dos que o temem, e os livra. Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia. Temei ao Senhor, vós, os seus santos, pois não têm falta alguma aqueles que o temem", lang: AppLang.PT),
      PsalmsContent(id: 32, position: 32, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Os filhos dos leões necessitam e sofrem fome, mas aqueles que buscam ao Senhor de nada têm falta", lang: AppLang.PT),
      PsalmsContent(id: 33, position: 33, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Vinde, meninos, ouvi-me: eu vos ensinarei o temor do Senhor. Quem é o homem que deseja a vida, que quer largos dias para ver o bem? Guarda a tua língua do mal, e os teus lábios de falarem enganosamente. Aparta-te do mal; e faze o bem; procura a Paz; e segue-a", lang: AppLang.PT),
      PsalmsContent(id: 34, position: 34, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Os olhos do Senhor estão sobre os justos e os seus ouvidos atentos ao seu clamor. A face do Senhor está contra os que fazem o mal, para desarreigar da terra a memória deles", lang: AppLang.PT),
      PsalmsContent(id: 35, position: 35, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Os justos clamam, e o Senhor os ouve, e os livra de todas as suas angústias. Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito", lang: AppLang.PT),
      PsalmsContent(id: 36, position: 36, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "Muitas são as aflições do justo, mas o senhor o livra de todas. Ele lhe guarda todos os seus ossos; nem sequer um deles se quebra", lang: AppLang.PT),
      PsalmsContent(id: 37, position: 37, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "A malícia matará o ímpio, e os que aborrecem o justo serão punidos", lang: AppLang.PT),
      PsalmsContent(id: 38, position: 38, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_34, content: "O senhor resgata a alma dos seus servos, e nenhum dos que nele confiam, será condenado", lang: AppLang.PT),

      PsalmsContent(id: 39, position: 39, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_46, content: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. Pelo que não temeremos, ainda que a terra se mude, e ainda que os montes se transportem para o meio dos mares. Ainda que as águas rujam e se perturbem, ainda que os montes se abalem pela sua braveza", lang: AppLang.PT),
      PsalmsContent(id: 40, position: 40, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_46, content: "O senhor dos Exércitos está connosco; o Deus de Jacob é o nosso refúgio", lang: AppLang.PT),
      PsalmsContent(id: 41, position: 41, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_46, content: "Há um rio cujas correntes alegram a cidade de Deus, o santuário das moradas do Altíssimo. Deus está no meio dela; não será abalada: Deus a ajudará, ao romper da manhã. As nações se embraveceram; os reinos se moveram; Ele levantou a sua voz e a terra se derreteu", lang: AppLang.PT),
      PsalmsContent(id: 42, position: 42, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_46, content: "O senhor dos Exércitos está connosco; o Deus de Jacob é o nosso refúgio", lang: AppLang.PT),
      PsalmsContent(id: 43, position: 43, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_46, content: "Vinde, contemplai as obras do Senhor, que desolações tem feito na terra! Ele faz cessar as guerras até o fim da terra: quebra o arco e corta a lança; queima os carros no fogo. Aquietai-vos, e sabei que eu sou Deus; serei exaltado entre as nações; serei exaltado sobre a terra", lang: AppLang.PT),
      PsalmsContent(id: 44, position: 44, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_46, content: "O senhor dos Exércitos está connosco; o Deus de Jacob é o nosso refúgio", lang: AppLang.PT),

      PsalmsContent(id: 45, position: 45, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_67, content: "Deus tenha misericórdia de nós e nos abençoe; e faça resplandecer o seu rosto sobre nós. Para que se conheça na terra o teu caminho e em todas as nações a tua salvação", lang: AppLang.PT),
      PsalmsContent(id: 46, position: 46, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_67, content: "Louvem-te a ti, ó Deus, os povos; louvem-te os povos todos", lang: AppLang.PT),
      PsalmsContent(id: 47, position: 47, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_67, content: "Alegrem-se e regozijem-se as nações, pois julgarás os povos com equidade, e governarás as nações sobre a terra", lang: AppLang.PT),
      PsalmsContent(id: 48, position: 48, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_67, content: "Louvem-te a ti, ó Deus, os povos; louvem-te os povos todos", lang: AppLang.PT),
      PsalmsContent(id: 49, position: 49, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_67, content: "Então a terra dará o seu fruto; e Deus, o nosso Deus, nos abençoará. Deus nos abençoara, e todas as extremidades da terra o temerão.", lang: AppLang.PT),
      PsalmsContent(id: 50, position: 50, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_67, content: "Louvem-te a ti, ó Deus, os povos; louvem-te os povos todos", lang: AppLang.PT),

      PsalmsContent(id: 51, position: 51, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Senhor, tu tens sido o nosso refúgio, de geração em geração", lang: AppLang.PT),
      PsalmsContent(id: 52, position: 52, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Antes que os montes nascessem, ou que Tu formasses a terra e o mundo; sim, de eternidade à eternidade, Tu és Deus", lang: AppLang.PT),
      PsalmsContent(id: 53, position: 53, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Tu reduzes o homem à destruição, e dizes: Volvei, filhos dos homens", lang: AppLang.PT),
      PsalmsContent(id: 54, position: 54, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Porque mil anos são, aos teus olhos, como o dia de ontem que passou, e como a vigília da noite. Tu os levas como corrente da água: são como um sono: são como a erva que cresce de madrugada. De madrugada cresce e floresce; à tarde corta-se e seca. Pois somos consumidos pela tua ira, e pelo teu furor somos angustiados", lang: AppLang.PT),
      PsalmsContent(id: 55, position: 55, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Diante de Ti puseste as nossas iniquidades; os nossos pecados ocultos à luz do teu rosto", lang: AppLang.PT),
      PsalmsContent(id: 56, position: 56, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Pois todos os nossos dias vão passando na tua indignação; acabam-se os nossos anos como um conto ligeiro. A duração da nossa vida é de setenta anos, e se alguns, pela sua robustez, chegam a oitenta anos, o melhor deles é canseira e enfado, pois passa rapidamente, e nós voamos", lang: AppLang.PT),
      PsalmsContent(id: 57, position: 57, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Quem conhece o poder da tua ira? E a tua cólera segundo o temor que te é devido?", lang: AppLang.PT),
      PsalmsContent(id: 58, position: 58, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Ensina-nos, «Senhor», a contar os nossos dias, de tal maneira que alcancemos corações sábios. Volta-te para nós, Senhor; até quando? Aplaca-te para com os teus servos. Sacia-nos de madrugada com a tua benignidade, para que nos regozijemos, e nos alegremos, todos os nossos dias", lang: AppLang.PT),
      PsalmsContent(id: 59, position: 59, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Alegra-nos pelos dias em que nos afligiste e pelos anos em que vimos o mal", lang: AppLang.PT),
      PsalmsContent(id: 60, position: 60, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_90, content: "Apareça a tua obra aos teus servos, e a tua glória sobre seus filhos. E seja sobre nós a graça do Senhor, nosso Deus; e confirma sobre nós a obra das nossas mãos: sim, confirma a obra das nossas mãos", lang: AppLang.PT),

      PsalmsContent(id: 61, position: 61, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Cantai ao Senhor um cântico novo, cantai ao Senhor todos os moradores da terra. Cantai ao Senhor, bendizei o seu nome; anunciai a sua salvação de dia em dia", lang: AppLang.PT),
      PsalmsContent(id: 62, position: 62, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Anunciai entre as nações a sua glória; entre todos os povos as suas maravilhas.", lang: AppLang.PT),
      PsalmsContent(id: 63, position: 63, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Porque grande é o Senhor, e digno de louvor, mais tremendo do que todos os deuses.", lang: AppLang.PT),
      PsalmsContent(id: 64, position: 64, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Porque todos os deuses dos povos são coisas vãs, mas o Senhor fez os céus. Glória e majestade estão ante a sua face, força e formosura no seu santuário", lang: AppLang.PT),
      PsalmsContent(id: 65, position: 65, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Dai ao Senhor, ó famílias dos povos, dai ao Senhor glória e força. Dai ao Senhor a glória devida ao seu nome; trazei oferendas, entrai nos seus átrios. Adorai ao Senhor na beleza da Sua santidade; tremei diante d’Ele todos os moradores da terra", lang: AppLang.PT),
      PsalmsContent(id: 66, position: 66, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Dizei entre as nações: O Senhor reina; o mundo, também, se firmará, para que se não abale; ele julgará os povos com rectidão", lang: AppLang.PT),
      PsalmsContent(id: 67, position: 67, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Alegre-se o campo, com tudo o que há nele; então se regozijarão todas as árvores do bosque, ante a face do Senhor, porque vem", lang: AppLang.PT),
      PsalmsContent(id: 68, position: 68, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_96, content: "Porque vem a julgar a terra; julgará o mundo com justiça e os povos com a sua verdade", lang: AppLang.PT),

      PsalmsContent(id: 69, position: 69, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_100, content: "Celebrai com júbilo ao Senhor, todos os moradores da terra. Servi ao Senhor com alegria; e apresentai-vos a Ele com cânticos", lang: AppLang.PT),
      PsalmsContent(id: 70, position: 70, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_100, content: "Sabei que o Senhor é Deus: foi Ele, e não nós, que nos fez povo seu e ovelhas do seu pasto", lang: AppLang.PT),
      PsalmsContent(id: 71, position: 71, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_100, content: "Entrai pelas portas dele com louvor, e em seus átrios com hinos; louvai-O, e bendizei o seu nome", lang: AppLang.PT),
      PsalmsContent(id: 72, position: 72, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_100, content: "Porque o Senhor é bom, e eterna a sua misericórdia; e a sua verdade estende-se de geração em geração", lang: AppLang.PT),

      PsalmsContent(id: 73, position: 73, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o Seu santo nome", lang: AppLang.PT),
      PsalmsContent(id: 74, position: 74, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum dos seus benefícios", lang: AppLang.PT),
      PsalmsContent(id: 75, position: 75, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "É Ele que perdoa todas as tuas iniquidades, e sara todas as tuas enfermidades; quem redime a tua vida da perdição, e te coroa de benignidade e de misericórdia; quem enche a tua boca de bens, de sorte que a tua mocidade se renova como a águia", lang: AppLang.PT),
      PsalmsContent(id: 76, position: 76, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "O Senhor faz justiça e juízo a todos os oprimidos. Fez notórios os seus caminhos a Moisés, e os seus feitos aos filhos de Israel", lang: AppLang.PT),
      PsalmsContent(id: 77, position: 77, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Misericordioso e piedoso é o Senhor; longânimo e grande em benignidade. Não repreenderá perpetuamente, nem para sempre conservará a sua ira", lang: AppLang.PT),
      PsalmsContent(id: 78, position: 78, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Não nos tratou segundo os nossos pecados, nem nos retribuiu segundo as nossas iniquidades", lang: AppLang.PT),
      PsalmsContent(id: 79, position: 79, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Pois quanto o céu está elevado acima da terra, assim é grande a sua misericórdia para com os que o temem", lang: AppLang.PT),
      PsalmsContent(id: 80, position: 80, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Quanto está longe o oriente do ocidente, assim afasta de nós as nossas transgressões", lang: AppLang.PT),
      PsalmsContent(id: 81, position: 81, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Como um pai se compadece dos seus filhos, assim o Senhor se compadece daqueles que o temem. Pois Ele conhece a nossa estrutura; lembra-se de que somos pó", lang: AppLang.PT),
      PsalmsContent(id: 82, position: 82, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Porque o homem, são seus dias como a erva; como a flor do campo, assim floresce: pois, passando por ela o vento, logo se vai, e o seu lugar não se conhece mais", lang: AppLang.PT),
      PsalmsContent(id: 83, position: 83, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Mas a misericórdia do Senhor é de eternidade à eternidade, sobre aqueles que o temem, e a sua justiça sobre os filhos dos filhos; sobre aqueles que guardam o seu concerto, e sobre os que se lembram dos seus mandamentos para os cumprirem", lang: AppLang.PT),
      PsalmsContent(id: 84, position: 84, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_103, content: "Bendizei ao Senhor, todos os seus exércitos, vós ministros seus, que executais o seu beneplácito. Bendizei ao Senhor todas as suas obras, em todos os lugares do seu domínio. Bendize, ó minha alma, ao Senhor", lang: AppLang.PT),

      PsalmsContent(id: 85, position: 85, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Não a nós, Senhor, não a nós, mas ao teu nome dá glória, por amor da sua benignidade e da Tua verdade. Por que dirão as nações: Onde está o Seu Deus?", lang: AppLang.PT),
      PsalmsContent(id: 86, position: 86, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Mas o nosso Deus está nos céus; faz tudo o que lhe apraz", lang: AppLang.PT),
      PsalmsContent(id: 87, position: 87, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Os ídolos deles são prata e ouro, obra das mãos dos homens. Têm boca, mas não falam; têm olhos, mas não vêem; têm ouvidos, mas não ouvem; nariz têm, mas não cheiram; têm mãos, mas não apalpam; têm pés, mas não andam; nem som algum sai da sua garganta", lang: AppLang.PT),
      PsalmsContent(id: 88, position: 88, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Tornem-se semelhantes a eles os que os fazem, e todos os que neles confiam", lang: AppLang.PT),
      PsalmsContent(id: 89, position: 89, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Confia, ó Israel, no Senhor:", lang: AppLang.PT),
      PsalmsContent(id: 90, position: 90, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Ele é seu auxílio e seu escudo", lang: AppLang.PT),
      PsalmsContent(id: 91, position: 91, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Casa de Aarão, confia no Senhor:", lang: AppLang.PT),
      PsalmsContent(id: 92, position: 92, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Ele é seu auxilio e seu escudo", lang: AppLang.PT),
      PsalmsContent(id: 93, position: 93, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "O Senhor, que se lembrou de nós, abençoará; abençoará a casa de Aarão", lang: AppLang.PT),
      PsalmsContent(id: 94, position: 94, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Abençoará os que temem ao Senhor, tanto pequenos como grandes", lang: AppLang.PT),
      PsalmsContent(id: 95, position: 95, person: PsalmsPerson.DIRECTOR, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "O Senhor vos aumentará cada vez mais, a vós e a vossos filhos. Sede benditos do Senhor, que fez os céus e a terra. Os céus são os céus do Senhor; Mas a terra deu-a ele aos filhos dos homens", lang: AppLang.PT),
      PsalmsContent(id: 96, position: 96, person: PsalmsPerson.CONGREGATION, psalmsTitle: PsalmsTitleSeeder.PSALMS_115, content: "Nós bendiremos ao Senhor, desde agora e para sempre. Louvai ao Senhor", lang: AppLang.PT),
    ];
  }

  static void run(Database db) {
    for(PsalmsContent it in items() ){
      db.insert(PsalmsContentSql.TABLE_NAME, {
        "id": it.id,
        "content": it.content,
        "position": it.position,
        "person": it.person,
        "lang": it.lang,
        "psalms_title_id": it.psalmsTitle.id,
      });
    }
  }

}