import 'package:ieca_mobile/_import.dart';

class NgHymnsMiasoYaKuSemukaKuaYesu {
  static List<HymnsContent> list =[
    HymnsContent(id: 3480, position: 1, content: "Zoleleni Yesu neza,\nTu Mu tambuleni,\nMu aveleni zimbunge,\nMu vialekeni kalamba,\nMuilu na hantsi, vose tsikameni,\nMuilu na hantsi tsikameni.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_64, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3481, position: 2, content: "Ku viuma viose via tema,\nVi Mu avela vulamba.\nKu viuma viose via tema,\nKu viuma viose via tema\nVi Mu avela vulamba,\nVi Mu avela vulamba,\nVi Mu avela vulamba.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_64, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3482, position: 3, content: "Vulamba vua Yesu vuavuo,\nVua muilu na hantsi.\nVa Mu tsiliela, va Mu tsiliela,\nVa ka kala kasi, va ka kala kasi,\nVa ka kala kasi Nendi muilu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_64, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3483, position: 1, content: "Ha Tungelo va ku imba,\nVa zimbula Muangana;\nNa semuua mu litanga,\nNeza ku tu hambesa:\nZolelenu vakua-mavu,\nMuaso uenu u hete muilu;\nHamo navo tu imba,\nNa semuua Muangana.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_65, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3484, content: "Ha Tungelo va ku imba,\nVa sangala Yehova.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_65, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3485, position: 2, content: "K’listu va lemesa muilu,\nK’listu Muana Kalunga;\nNa tava ku iza hano,\nNa semuua ku mpuevo:\nNa ntsitu tu mona Njambi,\nNa cifua ca muanamuntu;\nNgue muntu na soloka,\nYesu, Muovole uetu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_65, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3486, position: 3, content: "Na tu nehela ciyulo,\nNa tu ceke ha mavu;\nMuono na mutana A neha,\nA kanguisa mivezi:\nNa tava ku seza Vieni;\nMu ku ambata vipi vietu;\nKu tu hana S’pilitu,\nTu semuue luvali.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_65, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3487, position: 4, content: "Tuaya Yesu, tu Ku lania,\nKovela mu mitima;\nPalakana mutue uo uze,\nMukua ku tu vangela;\nZimangana vipi vietu,\nU tu himpuise ngue Yove:\nYove Muovole uetu,\nTu hiluise ku Njambi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_65, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3488, position: 1, content: "U neza vutsiki vumo,\nMuaso ua tumbala\nKuli tungelo va muilu,\nVa suena kuli vantu,\nCiyulo hantsi na ngozi\nKuli Kalunga vi huma.\nHantsi hose ha lendama\nMu ku ivua tungelo.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_66, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3489, position: 2, content: "Kasi na lelo ve ku iza\nNa zimbava za ciyulo.\nKuli vaze va na lemuua,\nMuaso u va huimisa.\nHelu uva huimisa\nHelu lia vakua vusiua\nVa va tengela na ngozi,\nHakati ka malimi a engi", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_66, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3490, position: 3, content: "Taleni, litangua li keza\nLia vamba vakua cimona,\nMuilu na hantsi hose\nVi ka himpuka via viha.\nImba vantu vose valimo\nVa tava kuli Kalamba.\nHamo na tungelo va kemba\nMuaso uze ua muilu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_66, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3491, position: 1, content: "Kuli muaso muilu! \nKuli ntongonosi!\nKuli naye a lomba, \nKakeke a lila!\nNtongonosi i tuila \nMua tunganda vemba\nMu cikasa ca Betlehem \nMuli Muene.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_67, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3492, position: 2, content: "Va zolela muamo\nMomu Muene neza.\nMuana ua muhumbe \nA hua Muanangana.\nNtongonosi i tuila \nMua tunganda vemba.\nMu cikasa ca Betlehem \nMuli Muene.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_67, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3493, position: 3, content: "Ceke ca tumbala \nCi na tu ku miaka.\nMuaso ua ku lahe \nUeza hose hantsi.\nVantu va li na ntuima \nMu vihuti viose\nMua va Mu tumbula \nYesu Muene uavo.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_67, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3494, position: 4, content: "Ceke ca njolela, \nMuaso ua tumbala\nUa tunda vutsiki \nKuli vaka muilu.\nEtu tu tambakana \nZinkanda za ngozi.\nTu Mu cesa mu cikasa \nMuene uetu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_67, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3495, position: 1, content: "Ku lahe kua tu na humu\nTua kavele ntongonosi;\nMu ku uana Muene Yesu\nNa ku Mu lemesa.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_68, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3496, content: "Ntongonosi ya ku komoka\nYa vulamba vua Muene\nTu tuamene tu ka hete\nMuilu ceke ci na tu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_68, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3497, position: 2, content: "Mu Belem va Mu vembela\nOlu nji nehela Muene\nViala netu Muene uetu\nKu miaka ka i hu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_68, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3498, position: 3, content: "Vihemba via ku tsimika\nNji Mu nehela Muangana\nVi lekesa Endi Muene\nNetu tu Mu lemesa.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_68, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3499, position: 4, content: "Vihemba via lemba viange\nVia ku sasa momu lamba\nUe vuile vusiua, kutsa\nMu mbumbo va Mu haka.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_68, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3500, position: 5, content: "Yendi cikasela cetu,\nMuene na Kalunga ketu\nHaleluya Ou na hiana\nA li ku tu lambela.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_68, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3501, position: 1, content: "Tuayenu mu vose, \nTu ka Mu lemese;\nTu yenu na ndzolela ku\nMbetelema:\nTenu mu tanga \nMuangana A kosa;", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_69, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3502, content: "Tuayenu Mu lemese,\nTuayenu Mu lemese,\nTuayenu Mu lemese,\nMuangana Yesu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_69, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3503, position: 2, content: "Tungelo, imbenu \nMiaso ya ku viuka;\nI zumbe vumpahu \nVua Njambi Tatetu:\nTu santselienu \nNgozi Yeni yose;", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_69, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3504, position: 3, content: "Tu ku sangaziala \nMuyoyesi uetu;\nLizina Liove\nTu ka li zumbangeya:\nLizi lia Tata, \nUa himpuka ntsitu;", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_69, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3505, position: 1, content: "Lekenuko vantu vose va ha mavu,\nKuose ku li lamba na vipi via lana;\nMalimi a vose a tambeke lizi,\nMukuasi nezako.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_70, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3506, content: "Mukuasi nezako, Mukuasi nezako,\nS’pilitu ua muilu, Ya tu sikileko;\nAmbululenuko kuli vantu vose,\nMukuasi nezako.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_70, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3507, position: 2, content: "Vutsiki vua piti, litangua li na ce,\nNa lamba ya holo na mavezi ose;\nTu suena ku ola, i ku heta vuasi,\nMukuasi nezako.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_70, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3508, position: 3, content: "Talenu Muangana neza ku ohiela,\nA patula vantu ku vundungo vuavo;\nVose va ku imba miaso ya ndzolela,\nMukuasi nezako.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_70, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3509, position: 4, content: "Cilemo ca Yesu ca nji komouesa,\nVati nji santsela ngozi ya ngecize;\nYange mukua vupi nji ka fua ngue Yesu,\nMukuasi nezako.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_70, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3510, position: 1, content: "Vakua-Yesu, zolelenu\nNa mitima hamo netu!\nVi ivuenu vi tu amba,\nYesu Kilistu Na semuka.\nA li mu tanga kuze\nVose va Mu tsikamena:", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_71, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3511, position: 2, content: "Vakua-Yesu, zolelenu,\nNa mitima hamo netu!\nYesu ha mi yoyesa,\nEvi vi a Na semukila,\nNa sokolola mbelo,\nMuntu a kovela muilu:", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_71, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3512, position: 3, content: "Vakua-Yesu, zolelenu\nNa mitima hamo netu!\nKati mu ivue vuoma,\nYesu a mi ovola vene.\nA sana yenu vose\nMu ka hete kuimbo Lieni.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_71, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3513, position: 1, content: "Halakana! Nji ku leka\nZinkanda za tumbala;\nMuana Kalunga Ua kele Muilu,\nUa vu sezele vulamba vuendi,\nUezile mu ku vovola\nVaze va zimbalele", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_72, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3514, position: 2, content: "Tata Kalunga, Muka-ngozi,\nUa tumine tunganda\nKuli tuniungi vutsiki vuze,\nKu va’mbuluila ngozi Yendi,\nMu va selumuisa K’listu\nYendi Nkuli ya vantu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_72, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3515, position: 3, content: "Ve’tavele ku tazela\nNdivo ya Muana uze;\nVa Mu uanene, Muana Kalunga\nNa semuuine ngue uaku-hutua\nMu ku tu tazela yetu,\nTu lisambuese nendi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_72, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3516, position: 4, content: "Yove lelo, kati u viane\nLuhande lua tumbala;\nTazela Muene na mbunge yose,\nU ka vezika, u ka Mu uana,\nA ka kovela, ku viala,\nMu mbunge yove lelo.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_72, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3517, position: 1, content: "Omo vipange viose vi na hu,\nNange nji mana mu sinia oku;\nNji ka huima mu ku mona\nYesu,\nKaha viose vi ka pua vumpahu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_73, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3518, content: "Nji ka kala na vumpahu,\nNa vumpahu, na vumpahu;\nOmo nji mona cihanga Ceni,\nVumpahu Vueni, vukevuo vuange.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_73, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3519, position: 2, content: "Viose via mavu nji ka vi suva,\nVi ka pua ngue ndzozi ya ku\nlota;\nNtsimbu ize nji ka mona Yesu,\nKaha viose vi ka pua vumpahu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_73, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3520, position: 3, content: "Vakua-cilemo nji ka va uana,\nTu ka viukilila mu ku hiana;\nVuno ku mona cihanga Ceni\nKaha viose vi ka pua vumpahu", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_73, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3521, position: 1, content: "Nji tuamene, A Yehova\nYange ngendzi ha mavu;\nNji na zeye, Mukua Ngolo,\nNji kuate na livoko:\nYove Mbolo, Yove Mbolo,\nNji lise miaka yose.\nNji lise miaka yose.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_74, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3522, position: 2, content: "Ndundzi Yove ivue luoke,\nMema a nji kanguise;\nCeke Cove ci minike\nNjila yose ya hano:\nNgami yange, Ngami yange,\nYove ndzili na ntelo.\nYove ndzili na ntelo.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_74, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3523, position: 3, content: "Omo ku-tsa ci nji suena,\nNji holuese mutima;\nU nji tuale na mu sinia\nNoho nji novoloka:\nVisangala, visangala,\nNji kemba kuli Yove\nNji kemba kuli Yove", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_74, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3524, position: 1, content: "U ka hita ntsimbu ika,\nCo u ka kala kuli? \nU zivuka njila yove, \nU ci tambuka nayo?\nU ka hita, u ka hita, \nU ya muilu, yove ni?", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_75, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3525, position: 2, content: "U ka hita lika liove, \nU ka hetela kuli?\nMuilu ka u hasa yove,\nKanda u tenguluke!\nU ka hita, u ka hita, \nU tenguluka lika.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_75, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3526, position: 3, content: "U ka hungumuka yove, \nKu suenesa ku-tsa, ni?\nKa u livola vene, \nU ka lifuika kuli? \nU ka hita, u ka hita,\nKa u linga lisalu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_75, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3527, position: 4, content: "U hita ntsimbu ya ihi, \nU ka seza vivi, ni?\nLelo litangua lia cili,\nKa u kovoka muze.\nU ka hita, u ka hita,\nKu u kovoka muze.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_75, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3528, position: 1, content: "Iza u tolile ku lijui lia Yesu,\nUze A hasa ku ku ovola;\nNa lingi Nguendi Yange Nji Yesu,\nYange Nji hasa ku ku ovola,", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_76, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3529, content: "Kulahela Yesu,\nKulahela Yesu, \nIkeye A hasa ku ku ovola.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_76, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3530, position: 2, content: "Nambe ku mbunge kuasulu na vivi,\nYesu A hasa ku tokesa to;\nHa ku kulahela muaso ua Yesu,\nTu linonena muono ka hu", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_76, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3531, position: 3, content: "Yesu A li na ngozi na vuana ,\nNa tu lania ku cifuti Cendi;\nNga tu u hianga muono ua cili,\nTu ka tambula ku –ovola kuendi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_76, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3532, position: 1, content: "Halakana! A ku sana,\nHalakana! A ku sana,\nHalakana! A ku sana,\nNguendi u Nji kave mu yehi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_77, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3533, content: "Kuose A tuama nji kava, \nKuose A tuama nji kava, \nKuose A tuama nji kava,\nNji Mu kava-kava mu yehi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_77, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3534, position: 2, content: "Muene Yesu A li nange,\nKa nji seza lika liange,\nNji kevua ku lizi Liendi, \nA ka kala-kala mu yehi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_77, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3535, position: 3, content: "Mu tuyando na vusiua,\nMu tuyando na vusiua,\nMu tuyando na vusiua,\nNji Mu kava-kava mu yehi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_77, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3536, position: 4, content: "Ku mavezi na ku ku-tsa,\nKu mavezi na ku ku-tsa,\nKu mavezi na ku ku-tsa,\nNji Mu kava-kava mu yehi", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_77, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3537, position: 1, content: "Yesu U nji tuamene,\nKa nji zimbala njila;\nNga nji mana ku hiehi\nNa cimo ci nji kuata.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_78, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3538, content: "Tuama, tuama,\nYesu, U nji tuamene, \nTuama, na ngozi Yove,\nNtsimbu yove tuamena.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_78, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3539, position: 2, content: "Yesu U ntelo yange,\nNga Satana a iza;\nNdzili Yove nji lomba, \nKa nji ende vavenia", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_78, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3540, position: 3, content: "Yesu, U nji tuamene,\nCo nomo muono u hua;\nNji ka kovela muilu, \nMisozi yose yahi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_78, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3541, position: 1, content: "Nji li na vivi via lana,\nVi ci nji hana kalua;\nNji Mu hianga Muyoyi, \nA njamena mu mbunge,", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_79, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3542, content: "Yove Yesu Yove Yesu,\nYove U li Mukuasi,", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_79, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3543, position: 2, content: "Ua nji zemene Vavenia,\nUa tsililile vivi;\nYove U ci nji setela,\nKu vutulula yange.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_79, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3544, position: 3, content: "Vusunga vuange vuahiko,\nNji ci vi linga vivi;\nU iza Muyoyesi uange,\nU ecela mbunge yange,", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_79, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3545, position: 4, content: "Nji sevuka ku tapalo,\nNga U nji seza Yove;\nLizi Liove nji na zivi,\nLi nji kolesa honi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_79, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3546, position: 1, content: "Yesu nji ku lema,\nNa U nji lema \nNa cilemo Cove \nU nji hianese.\nMuangana ua kama\nMuovole uange.\nNja kava ku laako \nYesu, nji suenese.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_80, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3547, position: 2, content: "Nji ku lema Yove \nMu muono uange, \nMuomu Ua fuetete \nMulonga uange.\nHa cilindakono\nVa na ku yandesele\nNja kava ku laako \nYesu, nji suenese.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_80, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3548, position: 3, content: "Mu vumpahu muilu \nNji ka zolela\nNa ku sangaziala \nLizina Liove.\nLelo naua nji hianga \nKu ku lemesa vuino.\nNja kava ku laako \nYesu, nji suenese.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_80, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3549, position: 1, content: "Mu mutima nji ku zolela,\nYesu A ci nji zema;\nNa nji nehela muono Uendi\nMuono ka ue ku hua", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_81, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3550, content: "Nji zolela, nji zolela\nOmo muono nji na tambula;\nMu ku mona cihanga Cendi,\nNji zolela manene", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_81, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3551, position: 2, content: "Mu mutima nji li ku imba,\nNa ku sangala Yesu,\nNa ku santsela vuana Vuendi,\nMuono ka ue ku hua.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_81, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3552, position: 3, content: "Mu mutima nji li na ngozi,\nOmo nji li na Yesu;\nNji zema ku leka vakuetu\nMuono ka ue ku hua.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_81, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3553, position: 1, content: "Hano hantsi mu vitanga \nVia Satana, na lamba,\nMuene Yesu A tu lania \nKu Mu kava mu yehi", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_82, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3554, position: 2, content: "Tu lisangala vavena \nNa vulamba vua hantsi;\nMuene Yesu A tu leka\nNguendi, Nji tsilieleni.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_82, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3555, position: 3, content: "Vumoni vua hano hantsi;\nTua vu kunguiya cili,\nMuene Yesu A tazela \nKu pua vumoni vuetu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_82, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3556, position: 4, content: "Tu ka Mu tava, ndi vati?\nTu hanguleni lelo.\nVi hita via hano hantsi,\nA kala Muene Yesu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_82, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3557, position: 5, content: "Hamo Nendi miaka yose\nNa ndzolela ya muilu,\nVose vaka ku lunguka \nVa ka viala na Muene.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_82, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3558, position: 1, content: "A nji zema Yesu ou,\nNguendi mu mukanda ou,\nNji kambututu Kendi,\nKa nji hasa vavenia.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_83, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3559, content: "Eua, Yesu ou, Ua nji zemene, \nUa nji zemene, nji na zivi oco.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_83, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3560, position: 2, content: "A nji zema Yesu ou,\nNa sokolola mbelo,\nNa tundisile vivi,\nNji ka kovela muilu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_83, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3561, position: 3, content: "A nji zema Yesu ou, \nA ka tumbama nange,\nAka nji kuasa vene,\nAka nji yisa muilu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_83, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3562, position: 1, content: "K’Listu Ua hindukila; \nAleluya!\nVantu na tungelo nguavo;  \nAleluya!\nImbeni na nzolela;\nAleluya!\nKuanyeni melu na hantsi;\nAleluya!", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_84, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3563, position: 2, content: "Lumo ha cilindakano;\nAleluya!\nLumo ua tsililile,\nAleluya!\nVuno A li na muono;\nAleluya!\nA ka viala ntsimbu yose;\nAleluya!", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_84, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3564, position: 3, content: "Imbeni na ku sakuila;\nAleluya!\nKuli Yesu Muene uetu;\nAleluya!\nUa hianene ku ku-tsa;\nAleluya!\nLinga a tu ovole;\nAleluya!", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_84, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 3565, position: 1, content: "U tsiliela Muene Yesu,\nA ka ku kuasa, \nA ka ku kuasa;\nImba u tsiliela vuino,\nU zolela ngambu.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_85, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3566, content: "Tsiliela, kuli Muene Yesu,\nTsiliela ku ngozi Yendi;\nTsiliela, tala meso muilu,\nMu tsiliele Endi.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_85, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 3567, position: 2, content: "U tsiliela Muene Yesu,\nYendi u kava, \nYendi u kava;\nMuono uove, Yendi a uizi,\nA ka ku tuamene.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_85, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 3568, position: 3, content: "U tsiliela Muene Yesu,\nNehia citeli, \nNehia citeli;\nU Muavele citeli cove,\nA ka ci tualeko.", hymnsNumber: NgHymnsNumberSeeder.MIASO_YA_KU_SEMUKA_KUA_YESU_85, typeStanza: HymnsContentCode.VERSE),
  ];
}