import 'package:ieca_mobile/enums/_import.dart';
import 'package:ieca_mobile/models/_import.dart';
import 'package:ieca_mobile/seeders/_import.dart';

class NgPsalmsContentSeeder{

  static List<PsalmsContent> items() {
    return [
      PsalmsContent(id: 200, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Melu a ambulula vumpahu vua Njambi; Na lilu li solola vipanga via mavoko eni. Litangua li handeka na litangua, na vutsiki vu muesa mana ku vutsiki. Mezi ahiko cipue lilimi; Lizi liao ka va li ivu. A na i hose ha mavu, na mezi ao kuze kua lenga mavu. Mu akeo na tumbika mbalaka ya litangua."),
      PsalmsContent(id: 201, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Mezi a kanua kange na vi singanieka via mutima wange vi viuke ku meso ove, a Yehova, livue liange, na Nkuli yange."),
      PsalmsContent(id: 202, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Likelio li na pu ngue ivenea ntsombola omo a tuhuka ku hondo yeni, Kaha li viukilila ngue mukua ngolo mu ku tunta njila yeni. Li tuhuka kuze kua lenga melu, kaha li zinguluka na ku ku-hua cao; Kaha na kamo kahi ka na vandela ntuima yalio."),
      PsalmsContent(id: 203, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Mezi a kanua kange na vi singanieka via mutima wange vi viuke ku meso ove, a Yehova, livue liange, na Nkuli yange."),
      PsalmsContent(id: 204, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Lisiko lia Yehova lia tantuluka, li hindula muono: Vukaleho vua Yehova vua kolo ngo, vu hia mangana kuli ciheve. Zinguli zia Yehova zia viuka, zi zolesa mutima: Cizilika ca Yehova ca lela, ci tuila meso ceke."),
      PsalmsContent(id: 205, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Mezi a kanua kange na vi singanieka via mutima wange vi viuke ku meso ove, a Yehova, livue liange, na Nkuli yange."),
      PsalmsContent(id: 206, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Ku vuila Yehova vuoma ca lela, ci kala ku miaka yose: Visika via Yehova vikevio via vusunga, via viuka kuose. Ku vi zanga ca pulakana olu, cili vene, ca hiana olu ya yingi ya ku viuka; Via hiana vuci ku lembuluka na ku-ndueka ca cisila. Hali vikevio ngamba yove a nanguka: Na mu ku vi niunga ku li cilunguiso ca kama."),
      PsalmsContent(id: 207, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Mezi a kanua kange na vi singanieka via mutima wange vi viuke ku meso ove, a Yehova, livue liange, na Nkuli yange."),
      PsalmsContent(id: 208, position: 9, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Iya a hasa ku mona ku-sevuka ceni? Nji lelese ku vize via vande. Tengesa ngamba yove naua ku ovio via vuhumuke; Kati vi nji suane: Kaha nji ka sungama, Nji kovoka ku civulumuna ca kama."),
      PsalmsContent(id: 209, position: 10, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_19, content: "Mezi a kanua kange na vi singanieka via mutima wange vi viuke ku meso ove, a Yehova, livue liange, na Nkuli yange."),

      PsalmsContent(id: 210, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Mavu akeo a Yehova, na ku-sula cao; Vifuti viose, na vose va kalamo. Muomu ikeye na hinda luvula luao ku mema a kalunga, Na a tumbika helu lia vandonga."),
      PsalmsContent(id: 211, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Iya a ka kanduka ku mucinda ua Yehova? Kaha iya a ka mana mu hondo yeni ya ku lela?"),
      PsalmsContent(id: 212, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Uze a li na mavoko a ku lela, na mutima ua ku lela; Uze ke ku haka mutima ueni ku makuli, Kaha ka lisingile na makuli. Ikeye a ka tambula civezikiso kuli Yehova, Na vuviuke kuli Njambi ua vuovoke vueni. Eli likelio lizimo lia vaze vakua ku mu lengeya, Vaze va lengeya cihanga cove, vakevo Yakomba."),
      PsalmsContent(id: 213, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Andulenu mitue yenu, A enu zimbelo; Kaha andukenu, enu mapito a ku myaka yose: Kaha Muangana ua vumpahu a ka kovela."),
      PsalmsContent(id: 214, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Muangana ou ua vumpahu ikeye iya?"),
      PsalmsContent(id: 215, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Yehova mukua zindzili mukua ngolo, Yehova mukua ngolo ku ndzita. Andulenu mitue yenu, A enu zimbelo; Cili i andulienu, enu mapito a ku myaka yose; Kaha Muangana ua vumpahu a ka kovela."),
      PsalmsContent(id: 216, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Muangana ou ua vumpahu ikeye iya?"),
      PsalmsContent(id: 217, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_24, content: "Yehova ua vivunga, Ikeye Muangana ua vumpahu."),

      PsalmsContent(id: 218, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_46, content: "Njambi ikeye vutinino vuetu na ngolo yetu, Ku-kuasa ca mu hiehi mu kayando. Ngoco vene ka tu kevua vuoma, cipue mavu a aluluka, Vutuhu mincinda i ndundumukila mu kati ka mema a kalunga; Vutuhu mema ao a cume na ku hita lusi, Vutuhu mincinda i zaze na ku-seta cao."),
      PsalmsContent(id: 219, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_46, content: "Yehova ua vivunga a li netu; Njambi ya Yakomba ikeye vutinino vuetu."),
      PsalmsContent(id: 220, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_46, content: "Ku a li ndonga, mita yeni i zolesa nganda ya Njambi, Muhela ua ku vikalo vio uze Ua Hiana viose. Njambi a li ha kati kayo; ka i ka taliangela: Njambi a ka i kuasa, na cikeco vuovunovuno. Vakua vifuti va lingile muyoyo, mavuangana a taliangelele: Ikeye ua handekele na lizi lieni, mavu a sangunukile."),
      PsalmsContent(id: 221, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_46, content: "Yehova ua vivunga a li netu; Njambi ya Yakomba ikeye vutinino vuetu."),
      PsalmsContent(id: 222, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_46, content: "Tuayenu, monenu vipanga via Yehova, Vati na pihisa mavu. A lingisa zindzita ku likela na haze ha lenga mavu; A pokola vuta vua lungusa, kaha a vatula ha kati likunga; A tsimika makalu a ndzita mu tuhia. Holokenu, kaha tantekeyenu ngecize ange nji Njambi: Va ka nji halesa ha kati ka vakua vifuti va ka nji halesa ha mavu."),
      PsalmsContent(id: 223, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_46, content: "Yehova ua vivunga a li netu; Njambi ya Yakomba ikeye vutinino vuetu."),

      PsalmsContent(id: 224, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_67, content: "Njambi a tu vuileko cikeketima, na ku tu vezikisa, A lingise cihanga ceni ku tu tuila ceke; Linga njila yove va i tantekeye ha mavu, Vuovole vuove ha kati ka vakua vifuti."),
      PsalmsContent(id: 225, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_67, content: "Vantu va ku sangaziale, a Njambi; Vantu vose va ku sangaziale."),
      PsalmsContent(id: 226, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_67, content: "A! vakua vifuti va zolele kaha vembe omo ndzolela;Muomu ove u ka sompesa vantu na vusunga, Na ku sika vifuti via ha mavu."),
      PsalmsContent(id: 227, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_67, content: "Vantu va ku sangaziale, a Njambi; Vantu vose va ku sangaziale."),
      PsalmsContent(id: 228, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_67, content: "Mavu a nemisa mbuto yao: Njambi, Njambi yetu vene, a ka tu vezikisa. Njambi a ka tu vezikisa; Na hose ha lenga mavu va ka mu vuila vuoma."),
      PsalmsContent(id: 229, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_67, content: "Vantu va ku sangaziale, a Njambi; Vantu vose va ku sangaziale."),

      PsalmsContent(id: 230, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "A! Imbenu kuli Yehova muaso ua uha:Imbenu kuli Yehova, mavu ose. Imbenu kuli Yehova, sangazialenu lizina lieni; Lekesa vuovole vueni ku litangua ku litangua."),
      PsalmsContent(id: 231, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "Ambululenu vumpahu vueni ha kati ka vakua vifuti, Vipanga vieni via ku komuesa ha kati ka vantu."),
      PsalmsContent(id: 232, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "Muomu ua kama Yehova, ua ku sangaziala cikumakuma: Ua ku vuila vuoma mu ku hiana vanjambi vose."),
      PsalmsContent(id: 233, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "Muomu vanjambi vose va vantu vakevo tumponia; Vunoni Yehova ua tangele melu. Kasingimiko na vukama vi li ku meso eni: Ngolo na vuviuke vi li mu ndzivo yeni ya ku lela."),
      PsalmsContent(id: 234, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "Tumbuilenu Yehova, enu vikota via vantu, Tumbuilenu Yehova vumpahu na ngolo. Tumbuilenu Yehova vumpahu vuze vua pande lizina lieni: Nehenu cikombelo, kaha tuayenu mu mapela eni. A! lemesenu Yehova na vuzalo vua ku lela: Zazenu ku meso eni, mavu ose."),
      PsalmsContent(id: 235, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "Handekenu ha kati ka vakua vifuti nguenu, Yehova a suana: Via ku tanga vi na kolo ngecize ka vi hasa ku taliangela."),
      PsalmsContent(id: 236, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "A ka sompela vantu na vusunga. Melu a zolele, na mavu a viukilile; Mema a kalunga a cume, na ku-sula cao; Lihia li lisambe, na viose vi limo; Kaha miti yose ya mu musenge i kemba omo ndzolela ku meso a Yehova; muomu a li ku iza."),
      PsalmsContent(id: 237, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_96, content: "Muomu a li ku iza ku sompesa mavu: A ka sompesa via ku tanga na vuviuke, Na vantu na vusunga vueni."),

      PsalmsContent(id: 238, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_100, content: "Lingenu muyoyo ua ndzolela kuli Yehova, enu vifuti viose. Pangelenu Yehova na ndzolela: Tuayenu ku meso eni na ku imba. Tantekeyenu ngecize Yehova ikeye Njambi."),
      PsalmsContent(id: 239, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_100, content: "Ikeye wa tu tangele, netu tu veni; Yetu tu vantu veni, na vampanga va vulilo vueni."),
      PsalmsContent(id: 240, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: NgPsalmsTitleSeeder.SAMO_100, content: "Kovelenu mu zimbelo zieni na ku santsela, Na mu mapela eni na visangala: Mu santselienu, na ku sangaziala lizina lieni."),
      PsalmsContent(id: 241, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: NgPsalmsTitleSeeder.SAMO_100, content: "Muomu Yehova ikeye ua viuka; ngozi yeni i kala ku miaka yose ya ya-ye, Na vucili vueni ku mazimo ose."),
    ];
  }
}