import 'package:ieca_mobile/enums/_import.dart';
import 'package:ieca_mobile/models/_import.dart';
import 'package:ieca_mobile/seeders/_import.dart';

class FtPsalmsContentSeeder{

  static List<PsalmsContent> items() {
    return [
      PsalmsContent(id: 400, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mazulu masamunanga nzitusu a Nzambi, ye luyalungunu luazulu luzaikisanga mavanga mamoko mandi; Lumbu kimosi kieti bo mokisa kwa kiankaka, ye fuku dimosi dieti bo zaikisa kwa diankaka. Ka i mpovolo vo ndinga yilembolo wakana ko. Bieti lambuka mu ntoto wamvimba, ye mambu mau maluakanga nate ye kwasukila nsi."),
      PsalmsContent(id: 401, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mambu manw’ami bika mazolwa kwa ngeye ye mabanza mantim’ami, Mfumu, i tadi diami diamongo ye nkudi ami."),
      PsalmsContent(id: 402, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Yandi wavangila ntangu nzo mu biau; yifwanane bonso toko diandambisa dieti vaika mu vinga kiadi, yau yeti yangalala bonso kesa dieti yungusa mu nzila yansinsani. Kuna nsuk’azulu i kuna yivaikilanga, ye nzungununu andi yeti luaka kuna nsuka yankaka, ye widi lekwa kimosi nkutu ka kiafukwa mu mbangazi andi ko."),
      PsalmsContent(id: 403, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mambu manw’ami bika mazolwa kwa ngeye ye mabanza mantim’ami, Mfumu, i tadi diami diamongo ye nkudi ami."),
      PsalmsContent(id: 404, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mina mia Mfumu miena mialunga ye mikindisanga ntima; kimbangi kia Mfumu kiena nakekete ye kiluengisanga ukondolo nduka. Ntumunu za Mfumu zisongele ye ziyangidikanga ntima; nsikudukusu a Mfumu yena yawanguka ye yiwangulanga meso."),
      PsalmsContent(id: 405, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mambu manw’ami bika mazolwa kwa ngeye ye mabanza mantim’ami, Mfumu, i tadi diami diamongo ye nkudi ami."),
      PsalmsContent(id: 406, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Vumi kia Mfumu kiena kiavedila ye kisikilanga ntangu yi ka yimani; nsiku mia Mfumu miena kedika, miamionsono miena mialunga. Miau milutidi wola mu ntalu, i wola wawingi wabiza; miau miviokele niosi mu zenza, inga, niosi yilutidi vedila mpe. Sielo kiaku kieti mio lubukila mpe; wonso ukebanga mio una baka nsendo waunene."),
      PsalmsContent(id: 407, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mambu manw’ami biku mazolwa kwa ngeye ye mabanza mantim’ami, Mfumu, i tadi diami diamongo ye nkudi ami."),
      PsalmsContent(id: 408, position: 9, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Nani lenda zaya nkusumukunu zandi zazonsono zikakusumukanga? Ungiambudila nzimbukunu zami zansweki. Bika wakeba sielo kiaku mu masumu maluyanu; kuyambulani mangiala ko, buna ngina kala walunga ye kondwa ntulumunu yangolo."),
      PsalmsContent(id: 409, position: 10, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_19, content: "Mambu manw’ami biku mazolwa kwa ngeye ye mabanza mantim’ami, Mfumu, i tadi diami diamongo ye nkudi ami."),

      PsalmsContent(id: 410, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "Ntoto uvwilu kwa Mfumu ye yayonsono yena mu wau, nza ye bakalanga yo kundu. Kadi yandi watudila wo lufulu wa ntandu amimbu, yandi wasiamisa wo va ntandu amila."),
      PsalmsContent(id: 411, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "Nani una baluka mu mongo wa Mfumu, ye nani una kota mu vinga kiandi kialongo?"),
      PsalmsContent(id: 412, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "Wonso wena moko makondolo bila ye wena ntima wavedila; ulembolo vengumuna mwel’andi mu bungiangia ye ulembolo dia ndefi zaluvunu. Yandi una tambula lusakumuna kwa Mfumu ye lunungu kwa Nzambi ampulusu andi. Bau i mbandu yikunyuvulanga; batombanga zizi kiaku, bau i bana ba Yakobi."),
      PsalmsContent(id: 413, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "Beno lu biavulu, ludongika ntu mieno, ye beno lu bielo bi ka bimani ludongalala, ntinu wanzitusu mpasi kakota."),
      PsalmsContent(id: 414, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "Ntinu wanzitusu i nani?"),
      PsalmsContent(id: 415, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "I Mfumu yangolo ye lulendo, Mfumu yalulenda mu mvita. Beno lu biavulu, lundongika ntu mieno, beno lu bielo bi ka bimani, lundongika mio, ntinu wanzitusu mpasi kakota."),
      PsalmsContent(id: 416, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "Ntinu wanzitusu i nani?"),
      PsalmsContent(id: 417, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_24, content: "I Mfumu Sebaoti; yandi i ntinu wanzitusu."),

      PsalmsContent(id: 418, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_46, content: "Nzambi i swamunu kieto ya ngole zeto, yandi i nsadisi wena lukufi mu ntangu zanzungu. I kuma ka tuna tina ko, vo ntoto una bukama ye miongo mina bukomuka mu nsin’ambu; evo mayo mawau mana kumba ya tulama ye miongo mina zakama mu diambu diakensi zawau."),
      PsalmsContent(id: 419, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_46, content: "Mfumu Sebaoti wena yeto, Nzambi a Yakobi i tinunu kieto kiasiama."),
      PsalmsContent(id: 420, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_46, content: "Nzadi yipasumukanga yena ma miyangidikanga mbanz’a Nzambi kundu kialongo kia Nkwa kayengele. Nzambi ukundanga momo; kiau ka kinikukanga ko; Nzambi usadisanga kio, biwisi bu bukiele. Bapaien babamanga, ye bimfumu bieti zeza; yandi weti wakasa nding’andi, buna ntoto unienganga."),
      PsalmsContent(id: 421, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_46, content: "Mfumu Sebaoti wena yeto, Nzambi a Yakobi i tinunu kieto kiasiama."),
      PsalmsContent(id: 422, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_46, content: "Luiza luatala mavanga ma Mfumu; yandi uvanganga mavanga mangitukulu mu ntoto. Yandi usinganga mvita nate ye kasukila ntoto, yandi weti tabula ntoto ye tolula dionga ye yoka makalu ku tia. Ludingalala luayindula, vo mono Nzambi; mono ngina kala wazangama mu bapaien, wazangama va ntoto."),
      PsalmsContent(id: 423, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_46, content: "Mfumu Sebaoti wena yeto, Nzambi a Yakobi i tinunu kieto kiasiama."),

      PsalmsContent(id: 424, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_67, content: "Bika Nzambi katulemvukila ye katusakumuna, bika katukienzudila zizi kiandi, mpeasi nzil’ku yazayakana va ntoto, ye mpulusu aku mu bapaien babonsono."),
      PsalmsContent(id: 425, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_67, content: "Kwa ngeye Nzambi, bika bantu batonda, bika bantu babonsono batonda kwa ngeye."),
      PsalmsContent(id: 426, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_67, content: "Makanda mabantu bika mayangalala ye makala kiese, kadi ngeye ukongudilanga bantu mu lusongo ye utuadisanga makanda mabantu va ntoto."),
      PsalmsContent(id: 427, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_67, content: "Kwa ngeye Nzambi, bika bantu batonda, bika bantu babonsono batonda kwa ngeye."),
      PsalmsContent(id: 428, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_67, content: "Ntoto umeni vana mbutu miandi, Nzambi, u Nzambi eto, bika watusakumuna. Bika Nzambi katusakumuna, ye bika nsuka zazonsono zantoto zamvumina."),
      PsalmsContent(id: 429, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_67, content: "Kwa ngeye Nzambi, bika bantu batonda, bika bantu babonsono batonda kwa ngeye."),

      PsalmsContent(id: 430, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Lu nsi zazonsono, luyimbila nkunga wamona kwa Mfumu, luyimbila mu nzitusu a Mfumu. Luyimbila mu nzitusu a Mfumu, lusika nkumbu andi, lusamunanga nsamu wakiese mu mpulusu andi lumbu ka lumbu."),
      PsalmsContent(id: 431, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Lusamuna nzitusu andi mu bapaien ye mangu biandi mu bantu babonsono."),
      PsalmsContent(id: 432, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Kadi Mfumu wena waunene ye ufweni mu zituswa ye lutidi nzambi zazonsono mu nsisi."),
      PsalmsContent(id: 433, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Kadi nzambi zazonsono zabantu i biteki kwandi, kansi Mfumu i yandi wavanga dizulu. Kimfumu ye nzitusu biena va luse luandi, lulendo ye nkembo mu kinlongo kiandi."),
      PsalmsContent(id: 434, position: 5, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Beno lu makanda mabantu, luvana kwa Mfumu, luvana nzitusu ye lulendo kwa Mfumu. Nzitusu ufweni kwa nkumbu andi luvana kwa Mfumu, lutuala minkailu ye luiza ku tumbu tuandi. Lusambila Mfumu mu mvwatu mianlongo. Nsi zazonsono bika zazakama va ntadisi andi."),
      PsalmsContent(id: 435, position: 6, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Mu kati diabapaien luvova: Mfumu i ntinu! I diau nza yeti telama nakekete ye ka yinikukanga ko; yandi ukongudilanga bantu bwasonga."),
      PsalmsContent(id: 436, position: 7, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Bika zulu diayangalala ye ntoto vakala kiese; bika mbu wakumba ye biabionsono biena mu wau. Bika mayinza mayangalala ye biabionsono biena mu mau, inga, nti miamionsono miena mu mfinda bika miayangalala va ntadisi a Mfumu."),
      PsalmsContent(id: 437, position: 8, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_96, content: "Kadi weti kwiza, kadi weti kwiza mu kongudila ntoto. Yandi una kongudila nza mulunungu ye bantu mu kinkwikizi kiandi."),

      PsalmsContent(id: 438, position: 1, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_100, content: "Lu nsi zazonsono, lusasula yangalala kwa Mfumu. Lusadila Mfumu mu kiese, luiza va luse luandi mu mbokolo zayangalala."),
      PsalmsContent(id: 439, position: 2, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_100, content: "Luzaya vo Mfumu i Nzambi. Yandi watuvanga, ka beto kibeni ko, mpasi tuakala bantu bandi ye mameme mandi mu kamba diandi."),
      PsalmsContent(id: 440, position: 3, person: PsalmsPerson.DIRECTOR, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_100, content: "Lukota mu mielo miandi mu mvutudulu amatondo ye mu tumbu tuandi mu nsikulu; lutonda kwa yandi, luzitisa nkumbu andi."),
      PsalmsContent(id: 441, position: 4, person: PsalmsPerson.CONGREGATION, psalmsTitle: FtPsalmsTitleSeeder.NKUNGA_100, content: "Kadi Mfumu wena wambote, nlemvo andi usikilanga ntangu yi ka yimani ye kinkwikizi kiandi mu mbandu ka mbandu."),
    ];
  }
}