import 'package:ieca_mobile/_import.dart';

class UmInvocationContentSeeder{

  static List<InvocationContent> items() {
    return [
      InvocationContent(id: 30, position: 1, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Hav.2:20", content: "Yehova o kasi vonembele yaye yikola. Omanu vosi vohile kovaso aye."),
      InvocationContent(id: 31, position: 2, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm.122:1;Eft. 28:16-7; Osm.29:1-2", content: "Nda yolela eci va mañinya vati, tu endi konjo ya Yehova. Ocili Suku o kasi kulo; kulo konjo ya Suku; kulo kombundi yokilu. Muisi Yehova ulamba wa posokela onduko yaye. Fendeli Yehova loku posoka kuesunga."),
      InvocationContent(id: 32, position: 3, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 15:1-2", content: "A Yehova, o tumãla vonembele yove helie? Helie o tunga vomunda yove yi kola? Yu omuenyo waye wa pua eko, haeye o lingainga esunga, vutima waye mu tunda olondaka viocili."),
      InvocationContent(id: 33, position: 4, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Is. 45:22, Osm. 85:9;84:11;106:1", content: "Asukiyo oluali, njimbi ovaso ho popeliwa. Momo ame ndi Suku, ka kuli yikuavo. Ocili, eyovo liaye li kasi ocipepi lava vo sumbila, momo Suku eye ekumbi, haeye ombindikiyo. Yehova ecaeca esumuluho lekemainyo. Lacimue ciwa a limila ava va endaenda lesunguluko. Sivayi Yehova."),
      InvocationContent(id: 34, position: 5, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 92:1-2", content: "Ca posoka oku pandula Yehova, loku imbila onduko yove esivayo, a Tõlo; loku sapula, omele, ocisola cove ka ci pui, locili cove, oñolosi."),
      InvocationContent(id: 35, position: 6, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm.42:2;62:1;63:3", content: "Ndeci osonge yi livela olondui viovava, haico utima wange u ku livela, a Suku. Utima wange u kasi lenyona lia Suku, Suku ukuamuenyo. Eteke lipi njiya, si moli ocipala ca Suku? Utima wange u felevela Suku lika, loku uhã. Kokuaye ku tunda eyovo liange. Omo ocisola Cove ka ci pui, ca velapo, okuti omuenyo u sule."),
      InvocationContent(id: 36, position: 7, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm.115:11", content: "Ene wa sumbili Yehova, koleli Yehova. Eye oñuatisi yene, haeye ombindikiyo yene."),
      InvocationContent(id: 37, position: 8, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Hos.6:1,3", content: "Enjui, tu tiukili ku Yehova; momo eye wa tu velisa okuti o tu sakula; haye wa tu tonyõla okuti o tu itika. Tu kulihisi Yehova. Tu kuati ombili yoku u kuliha. Iya kokuetu ndombela yomandavela yina yi yulisa osi."),
      InvocationContent(id: 38, position: 9, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Mik. 6:6,8.", content: "Ngambata nye, eci njiya ku Yehova? Ngambata nye, eci fendela Suku yovailu? Amunu, Suku wa ku lekisa eci ciwa. Yehova o yongola nye love, hateko oku linga esunga, lo cisola; Ohenda kuenda oku endaenda la Suku yove lesuluviko?"),
      InvocationContent(id: 39, position: 10, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 99:9", content: "Kemainyi Yehova Suku Yetu. Fendeli vomunda yaye yi kola, momo Yehova Suku yetu o kola."),
      InvocationContent(id: 40, position: 11, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 95:1-3,6-8", content: "Kokeli, tu imbili Yehova ovisungo. Tu uluili ewe lieyovo lietu. Tu kokeli kokuaye lolopandu, tu wimbili lonjolela ovisungo viesivayo. Momo eye Suku yinene, haeye Soma yinene ya piãla olosuku viosi. Kokeli, tu fendeli loku petama. Tu kekameli kovaso a Yehova, utungi wetu. Momo eye Suku yetu, letu tumanu vaye, o tu lisalisa, haetu tulomeme vi songuilua leka liaye."),
      InvocationContent(id: 41, position: 12, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 69:32;106:1", content: "Lene wakuakusanda Suku, ovitima viene vi kuate omuenyo. Sivayi Yehova."),
      InvocationContent(id: 42, position: 13, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm.100:3-5", content: "Limbuki Yehova okuti eye Suku. Eye wa tu lulika, kuenje tuvaye. Tumanu vaye, tulomeme o tu lisalisa. Iñili volombundi viaye loku imba, lolopandu; vovitali viaye, lesivayo. U panduli, sivayi onduko yaye. Momo Yehova uwa. Ocisola caye ka ci pui, ci enda ño hu. Ocili caye ci enda ño-o, kovitumbulukila viosi."),
      InvocationContent(id: 43, position: 14, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 55:17;145:1", content: "Loñolosi, lomele, lekumbi pongunji, ndi litetela loku lisiõsiõla, kuenje o yeva ondaka yange. Hu kemainya, a Suku yange, a Soma yange. Manduila onduko yove oloneke viosi."),
      InvocationContent(id: 44, position: 15, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Yer. 29:11-13", content: "Momo nda kũliha ovisimilo nãsi loku vu simila; ovisimilo viaco vioku u kuatisi, havioku u lingako civi, haivio vioku waveli elavoko lioloneke viya. Kotembo yaco vu mbilikiya; wiyi oku likutilila kokuange, kuenje ndu yevi. Vu sanda, kuenje vu sanga. Oco ca popia Yehova."),
      InvocationContent(id: 45, position: 16, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 24:3-5; 119:1-3: 136:1", content: "O lamana komunda ya Yehova helie? Helie o talama kocitali caye ci kola? U o kasi lovaka a yela lutima wa pua eviho. U ka tiamisile utima waye kuhembi. U ka likuminyile lesanda. Eye o mola ku Yehova esumuluho, lesunga ku Suku ukueyovo liaye. Va sumuluha ava va endaenda lovihandeleko via Yehova. Va sumuluha vakuaku linga ovovangi aye, haivo vo vanjalaiya lutima wavo wosi, momo ohenda yaye yalua, ocili ca Yehova ka ci pui."),
      InvocationContent(id: 46, position: 17, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm.118;24;99:9", content: "Lilo olio eteke lia sovola Yehova: tu li yolela, loku li sanjukila. Kemainyi Yehova, Suku yetu; Fendeli vomunda yaye yi kola, momo Yehova Suku yetu o kola."),
      InvocationContent(id: 47, position: 18, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Yoam. 4:24; Osm:19:14", content: "Suku Espiritu, kuenje ca sesamela ava vo fendaila oku u fendela lespiritu, locili. Olondaka viomela wange, lovisimilo viutima wange, vi sunguluke kokuove, a Yehova, wucikolo cange, haive wunjovoli yangu."),
      InvocationContent(id: 48, position: 19, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm. 113;3; 100;4", content: "Tunde pokutunda kuekumbi toke pokuiñila kualio, onduko ya Yehova yi sivayiwe. Iñili volombundi viaye lolupandu, vovitali viaye lesivayo. U panduli, sivayi onduko yaye."),
      InvocationContent(id: 49, position: 20, invocationTitle: UmInvocationTitleSeeder.AKOVONGO, books: "Osm.19", content: "Olondaka viomela wange lovisimilo viutima wange, vi sunguluke kokuove a Yehova, wucikolo cange, haive wunjovoli yangu."),

      InvocationContent(id: 50, position: 21, invocationTitle: UmInvocationTitleSeeder.EPULUVI_LIELAVOKO, books: "1Tes.4;16;Esit.1:7", content: "Momo Ñala, eye muele, wa tunda kilu levilikiyo, londaka yungelo unene, Kuenda lolumbeta lua Suku. Kuenje ava va fa vu Kristu va pinduka tete. Ota, iya. Endela valende, kuenje ovaso osi vo mola, ndãno vava vo toma, lapata osi o kilu lieve o va litetelela, eye muele. Amene."),
      InvocationContent(id: 51, position: 22, invocationTitle: UmInvocationTitleSeeder.EPULUVI_LIELAVOKO, books: "Isy.27:13", content: "Kuenda vali keteke liaco olumbeta lunene lu sika, kuenje ava va nyelela vofeka ya Asuria, lava va takumuhila ve Engito, va tiuka, va fendela Yehova komunda yi kola, yo ko  Yelusalãi."),

      InvocationContent(id: 52, position: 23, invocationTitle: UmInvocationTitleSeeder.UCITO_WA_YESU, books: "", content: "Eci otembo ya telã, oco Suku wa tuma Omõlaye, wa citiwa lukãi, haeye wa citiwa kotembo yovihandeleko. Wo tuma oku yovola ava va tiamela kovihandeleko, ha va moli omangu yo ku linga omalã vaye."),
      InvocationContent(id: 53, position: 24, invocationTitle: UmInvocationTitleSeeder.UCITO_WA_YESU, books: "Yoano.1:14", content: "Oco Ndaka wa linga omunu, kuenje wa tunga pokati ketu, yu we yuka ocali, locili. Tua mola ulamba waye. Ulamba waco, ulamba wa Mõla wongunga wa Isia."),

      InvocationContent(id: 54, position: 25, invocationTitle: UmInvocationTitleSeeder.EPULUVI_LIEPOPELO, books: "Yoel.2:12-13", content: "Puãi, ndãno cilo, lopo Yehova oli loku tu laleka, hati: Pongolokeli kokuange lutima wosi, loku likandangiya okulia, lokulila kuenda okulitetela. Ko ka toli olonanga, toli puãi itima. Pongolokeli ku Yehova, Suku yene, momo eye ukuahenda, haeye ukuacikembe, o livala konyeño, otembo yosi o kasi locisola ka ci pongoloka."),

      InvocationContent(id: 55, position: 26, invocationTitle: UmInvocationTitleSeeder.OVIANJA, books: "", content: "Hosana ku Mola a Ndaviti. U iyilila onduko ya Ñala a sivayiwe! Popi lomola a Siono ukãi hoti, Tala eyovo liove liya: tala, onima yahe yi kasi laye, kuenje upange wahe wenda kovaso aye. Soma iyilila onduko ya Ñala a sivayiwe. Kilu va vilikiye Hosana. Suku a kale lene."),

      InvocationContent(id: 56, position: 27, invocationTitle: UmInvocationTitleSeeder.OPASKUA, books: "Luk.24:34; Tes.4:14", content: "Va popia vati, Nãla wa pinduka muele, yu wa moleha ku Simono. Omo tu kolela okuti Yesu wa fa, kuenje wa pinduka, oco ava va pekela vu Yesu, Suku o va pindula kumuamue laye."),
      InvocationContent(id: 57, position: 28, invocationTitle: UmInvocationTitleSeeder.OPASKUA, books: "Rom.8:11", content: "Puãi, nda Espiritu liu wa pindula Yesu kuava va fa, li tunga vovitima viene, oco, U wa pindula Kristu kuava va fa omuisa omuenyo atimba ene a fafa. O ci linga loku talavaya le Espiritu liaye lina li kasi vovitima viene."),

      InvocationContent(id: 58, position: 29, invocationTitle: UmInvocationTitleSeeder.OPENDEKOSTE, books: "Yoel.2:28-29", content: "Kuenje, noke ci iya okuti, ndi sukumuila Espiritu liange komanu vosi. Omãla vene valume, lomãla vene vakãi va imba owanji; olosekulu viene vi lota olonjoi, lamalehe vene va mola ovinjoinjoi. Koloneke viaco, ndãno kakuenje lokafeko, vakuopange, ndi va sukumuila Espiritu liange."),

    ];
  }
}