import 'package:ieca_mobile/_import.dart';

class HymnsPraiseToWorship{
  static List<HymnsContent> list = [
    HymnsContent(id: 17, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 1, content: "Santo! Santo! Santo!\nDeus omnipotente!\nCedo de manhã\nCantaremos teu louvor.\nSanto! Santo! Santo!\nJusto e compassivo!\nÉs Deus triuno,\nExcelso criador!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 18, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 2, content: "Santo! Santo! Santo!\nTodos os remidos\nJuntos com os anjos,\nProclamam teu louvor.\nAntes de formar-se\nO firmamento e a terra,\nEras e sempre és,\nE hás-de ser Senhor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 19, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 3, content: "Santo! Santo! Santo!\nNós os pecadores\nNão podemos ver\nTua glória sem tremor.\nTu somente és Santo,\nSó Tu és perfeito\nDeus soberano,\nImenso em Teu amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 20, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_5, position: 4, content: "Santo! Santo! Santo!\nDeus Omnipotente!\nTuas obras louvam\nTeu nome com fervor.\nSanto! Santo! Santo!\nJusto e compassivo\n És um só Deus,\nSupremo Criador.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 21, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 1, content: "Louvai o eterno Deus,\nO que seu Filho ao mundo enviou;\nJesus a oferta nos ofereceu,\nLouvai o eterno Deus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 22, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 2, content: "Quem nos acusará?\nJesus que foi morto e ressuscitou;\nAgora está à dextra do bom Deus,\nQuem nos acusará?", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 23, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 3, content: "Jesus nos libertou,\nQuem nos recusará ter o perdão?\nQuem nos intentará acusação?\nJesus nos libertou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 24, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_6, position: 4, content: "Havemos de vencer;\nO Salvador defende todos os seus;\nNosso inimigo,\nJesus já venceu,\nHavemos de vencer.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 25, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 1, content: "Louvamos-Te, ó Deus,\nPelo Dom de Jesus,\nQue por nós pecadores\nFoi morto na cruz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 26, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, content: "Aleluia, toda a glória\nTe rendemos, sem fim;\nAleluia, tua graça\nImploramos. Ámen!", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 27, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 2, content: "Louvamos-Te, ó Deus\nE ao teu Filho de amor,\nQue foi morto, mas vive,\nSupremo Senhor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 28, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 3, content: "Louvamos-Te, ó Deus,\nPelo Espírito, luz\nQue nos tira das trevas\nE a Cristo conduz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 29, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_7, position: 4, content: "Ó vem-nos encher\nDe celeste fervor,\nE fazer-nos fruir\nTeu afável amor!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 30, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 1, content: "Ao Rei adorai com glória e louvor,\nE graças rendei por seu grande amor.\nÉ Deus o refúgio a defesa eternal,\nQue em glória recebe louvor triunfal.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 31, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 2, content: "Falai do poder, da graça de Deus,\nEm vestes de luz habita Ele os Céus.\nSeu carro Ele pode das nuvens formar\nNas asas do vento faz Seu caminhar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 32, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 3, content: "Mistérios sem fim a terra contém\nNosso inimigo, Jesus já venceu,\nHavemos de vencer.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 33, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 4, content: "Ó Deus, Teu poder quem pode narrar?\nEstá no fulgor da luz, pelo ar.\nNas fontes das rochas, no campo e na flor,\nNas gotas de orvalho, na chuva e vapor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 34, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_8, position: 5, content: "Nós filhos do pó, de frágil viver,\nEm Ti temos fé, ó Deus do poder.\nMil bênçãos eternas quiseste nos dar,\nAmigo, que o mundo vieste salvar!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 35, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 1, content: "Todos bem-digam com prazer\nO santo nome do Senhor.\nSupremo em glória e em poder;\nÉ Deus de graça, Deus de amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 36, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 2, content: "Entrai na casa do Senhor\nPara com júbilo cantar.\nSomos ovelhas dum Pastor,\nA quem devemos adorar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 37, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 3, content: "Sejamos servos do Senhor\nE bem guardemos Sua lei.\nCantemos todos o louvor\nDo nosso Salvador e Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 38, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_9, position: 4, content: "Tudo Seu nome louvará\nPorque benigno é o Senhor;\nO Seu amor sem fim será.\nÉ sempre o mesmo o Benfeitor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 39, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 1, content: "A Cristo coroai!\nQue por nós encarnou.\nE Deus, o Santo Deus e Pai,\nAos homens revelou.\nEis Sua compaixão!\nEis Sua mansidão!\nQuem vê a\nCristo vê ao Pai,\nSim, vê Seu coração!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 40, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 2, content: "A Cristo coroai!\nDe tudo, o Criador!\nO Filho do Supremo Deus;\nDo mundo, o Salvador! Jesus,\nSenhor e Deus\nO grande Redentor,\nEm busca dos perdidos vem,\nO nosso bom Pastor!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 41, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 3, content: "A Cristo coroai!\nQue, sobre a cruz, ganhou Por nós eterna redenção\nE para os céus voltou!\nEle é o Rei dos reis,\nO príncipe da paz!\nJesus, da morte o vencedor,\nQue a salvação nos traz!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 42, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_10, position: 4, content: "A Cristo coroai!\nDe todos o Senhor,\nA quem a multidão dos céus\nAclama com fervor!\nEis o Cordeiro ali,\nQue sobre o trono está!\nQue vive e reina lá por nós\nE cedo voltará!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 43, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_11, position: 1, content: "Louvores a Deus,\nmui sinceros louvores,\nTributa a minha alma\ncom grande fervor;\nSó Tu és a fonte\nde graça e favores,\nDivina promessa\nrecursos de amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 44, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_11, position: 2, content: "Louvar-Te, Senhor,\nmeu desejo constante,\nMeus votos ardentes\nem penhor sem par.\nLouvar-Te na vida,\nno lar ou distante,\nSozinho ou na Igreja\npor todo o lugar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 45, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_11, position: 3, content: "Aceita, Senhor,\na expressão de minha alma,\nTributo de graças,\npois tudo me dás:\nNos dias de lutas,\nnas horas de calma,\nContigo, Senhor,\ntenho a bênção da paz!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 46, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_12, position: 1, content: "Ó Deus, bom Pai e Benfeitor,\nA Ti rendemos com ardor,\nLouvor, poder, sem fim,\nSenhor De todos nós, Sustentador.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 47, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_12, position: 2, content: "E Tu, Deus Filho, ó bom Jesus,\nPor nós sofreste numa cruz.\nDe Ti nos vem a clara luz Que nossos pés aos céus conduz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 48, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_12, position: 3, content: "Tu Deus, Espírito veraz,\nAs nossas almas satisfaz\nCom gozo e divina paz\nE as nossas aflições desfaz.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 49, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_13, position: 1, content: "Deus está no templo!\nPai Omnipotente:\nA Seus pés nos humilhamos.\nServos consagrados\nReverentemente,\nAo Santíssimo adoremos.\nPor favor, com amor,\nSpiritualmente,\nDeus está no templo.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 50, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_13, position: 2, content: "Cristo está no templo!\nSumo benefício!\nRecebemos do seu sangue,\nEle, o bom Cordeiro,\nFoi o sacrifício\nQue o pecado todo extingue.\nEscolheu e sofreu\nO cabal suplício;\nCristo está no templo.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 51, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_13, position: 3, content: "Vem, ocupa o templo!\nEspírito divino!\nNossos corações habita.\nÓ paciente Mestre,\nDá-nos Teu auxílio,\nAclarando a lei bendita.\nCom prazer e poder\nE graça infinita;\nEle está no templo.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 52, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_14, position: 1, content: "Altamente os céus proclamam,\nSeu divino Criador;\nAnuncia o firmamento,\nTuas obras, ó Senhor!\nIncessantes, noite e dia,\nDão sinais do Teu poder,\nSem palavras proclamando\nTua glória, teu saber.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 53, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_14, position: 2, content: "Tua lei, quão preciosa,\nBrilha mais que a clara luz;\nEsclarece os ignorantes,\nGuia as almas a Jesus.\nGrande e linda recompensa,\nGanhará quem Te servir,\nE Teus santos mandamentos\nBem fiel, Senhor, cumprir.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 54, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_14, position: 3, content: "Da soberba vem guardar-nos,\nDa impureza e transgressão;\nNossos passos conduzindo,\nEm sincera rectidão.\nNesta graça meditando,\nCantarei, meu bom Senhor,\nE será, na minha boca\nAgradável Teu louvor.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 55, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 1, content: "A Jesus, o Rei da glória,\nHinos de louvor cantai;\nAos seus pés, humildemente,\nSeu poder, pois exaltai.\nPerdoados, resgatados,\nSua glória proclamai!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 56, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 2, content: "Seu perdão e sua graça,\nAos perdidos dispensou;\nTão paciente e mui bondoso,\nAos rebeldes se mostrou;\nLibertou-os, transformou-os,\nDos castigos os salvou!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 57, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 3, content: "Nossas tentações conhece,\nPois satã o quis vencer;\nTriunfante, Cristo agora,\nAos tentados quer valer.\nPoderoso e tão bondoso,\nEle pode socorrer!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 58, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_15, position: 4, content: "Contemplando sua face,\nÓ remidos, O adorai!\nDedicados, consagrados,\nSua fama publicai.\nOh! Louvai-O, exaltai-O,\nSeu amor anunciai!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 59, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_16, position: 1, content: "Alegre me senti,\nAo convidar-me assim:\nVamos a casa do Senhor.\nDe sorte que os meus pés\nCaminham em direcção\nA Deus e Sua santa Sião.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 60, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_16, position: 2, content: "A Sua Santa Sião,\nBem edificada está:\nÉ lá onde as tribos vão.\nLouvando ao seu\nDeus E seu grande poder.\nAbençoados são os que O crêem.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 61, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_16, position: 3, content: "Paz haja em Sião,\nCidade de Jehová,\nSua casa de adoração.\nHavemos de encontrar\nA habitação feliz.\nMeu coração anseia Ter.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 62, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_17, position: 1, content: "Fonte Tu de toda a bênção,\nVem o canto me inspirar;\nDons de Deus, que nunca cessam,\nQuero em alto som louvar,\nOh! Ensina o novo canto\nDos remidos lá dos céus.\nAo teu servo e ao povo santo,\nP’ra louvarmos-Te, ó bom Deus!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 63, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_17, position: 2, content: "Cá meu «EBENEZER» ergo,\nPois Jesus me socorreu;\nE, por sua graça, espero\nTransportar-me para o Céu.\nEu, perdido, procurou-me,\nLonge do meu Deus, sem luz;\nMaculado e vil, lavou-me,\nCom seu sangue o bom Jesus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 64, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_17, position: 3, content: "Devedor à Tua graça\nCada dia e hora sou;\nTeu desvelo sempre faça\nCom que eu ame a Ti, Senhor.\nEis minha alma vacilante:\nToma-a, prende-a com amor,\nSela o coração volante,\nPara o céu, meu Salvador.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 65, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 1, content: "Jesus,  és a Palavra eterna de Deus;\nSenhor, sim, de graça e de paz.\nNós te imploramos, vem pois escutar-nos;\nVem dar-nos esperança e alegria.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 66, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 2, content: "Vem, faz-nos perfeitos, p'ra andarmos direitos,\nVem já, sim nos tirar a cegueira.\nPerdoa nossas faltas, vem purificar-nos.\nVem dar-nos a vida dos céus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 67, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 3, content: "Fortifica esta casa, de adoração viva;\nQue seja a entrada dos céus.\nOs corações fracos encontrem descanso;\nOs enfermos encontrem a cura.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 68, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_18, position: 4, content: "Vem fortificar sim, os corações fracos,\nEnchê-los de paz e propensos a justiça;\nQue sejam pertença de Cristo.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 69, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 1, content: "Que delícia é crer em Cristo,\nEm seu nome confiar,\nAceitar os seus ensinos\nE as promessas desfrutar!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 70, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, content: "Cristo! Cristo!\nJá confio\nEm Teu nome, em Teu poder;\nCristo! Cristo, Bem-amado!\nFaze minha fé crescer.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 71, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 2, content: "Oh! que bênção crer em Cristo,\nCrer no sangue que verteu,\nPois os meus pecados todos\nDeus por Ele removeu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 72, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 3, content: "Oh! que gozo é crer em Cristo,\nTer certeza de perdão!\nReceber de Cristo mesmo\nVida, paz e salvação.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 73, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_19, position: 4, content: "Bem feliz eu sou em Cristo,\nSempre d'Ele quero ser;\nQuero agora mui submisso,\nSempre a Ele obedecer.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 74, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_20, position: 1, content: "Se eu pudesse celebrar,\nCom hino digno e voz sem par,\nA glória de Jesus\nCom os anjos eu alternaria\nEm doce e terna melodia,\nAo pé da Sua cruz,\nAo pé da Sua cruz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 75, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_20, position: 2, content: "Diria o sangue que verteu,\nAs dores que por mim sofreu\nMaldito pela lei!\nE cantaria em grato ardor\nA majestade do Senhor,\nMeu sacrossanto Rei.\nMeu sacrossanto Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 76, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_20, position: 3, content: "O dia alegre chegará,\nQuando meu Pai me levará\nRemido à Sua luz!\nAli, em êxtase de amor,\nNo céu eu cantarei melhor,\nSalvo por meu Jesus!\nSalvo por meu Jesus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 77, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 1, content: "Santo, santo, santo é o Senhor;\nSempre exaltado seja o Seu nome!\nSanto, santo, santo é o Senhor;\nDai-lhe adoração, toda a terra!\nCantai louvores, sim, triunfantes,\nAo glorioso Cristo cantai.\nSanto, santo, santo é o Senhor\nExaltado seja o Seu Nome.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 78, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 2, content: "Justo, justo, justo é o Senhor;\nNo Seu governo sempre há justiça!\nJusto, justo, justo é o Senhor;\nEquidade vem com o Seu reino!\nSeu santo trono estabelecido,\nGarante a glória do Seu poder.\nJusto, justo, justo é o Senhor\nEquidade vem com Seu reino.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 79, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 3, content: "Terno, terno, terno é o Senhor;\nCheio de compaixão e de graça!\nTerno, terno, terno é o\nSenhor Como nós em tudo tentado!\nAlto refúgio, fonte de graça\nPara Seu povo, Deus Salvador.\nTerno, terno, terno é o Senhor;\nCheio de ternura e de graça.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 80, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_21, position: 4, content: "Compassivo sempre é o Senhor;\nTudo sabendo, tudo sentindo!\nCompassivo sempre é o Senhor;\nNossas dores todas levando!\nMesmo na morte a todos amando,\nDando-Se a Si por nós sobre a cruz.\nCompassivo sempre é o Senhor.\nNossas dores todas levando!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 81, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 1, content: "Ó Cristão, tem esperança,\nCristo é teu fiel amigo,\nTua luz e confiança;\nEle é teu amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 82, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 2, content: "Ó Jesus em Ti confio;\nFui por tua morte salvo,\nSalvo enfim além do rio\nViverei feliz.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 83, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 3, content: "Te verei na glória eterna,\nSobre o trono majestoso.\nCantarei canção suprema,\nDando a Ti louvor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 84, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_22, position: 4, content: "Glória a Ti, Jesus clemente,\nSeja dada aqui na terra;\nGlória a Ti, eternamente\nLá nos altos céus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 85, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 1, content: "Vinde louvai ao Senhor;\nGlória, glória a Jesus;\nGlória dai ao Santo Espírito,\nAo Deus trino nossa luz.\nAdorai-o com fervor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 86, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, content: "Grande é seu poder e amor;\nSempiterno Criador", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 87, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 2, content: "Ele omnipotente Deus\nFez as águas, terra e céus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 88, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 3, content: "Sol e lua e estrela são\nObra da divina mão", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 89, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 4, content: "Com mão forte ao povo seu\nGrandiosa herança deu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 90, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 5, content: "Príncipes e reis feriu\nE Seu povo redimiu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 91, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_23, position: 6, content: "Sua misericórdia traz\nAos humildes gozo e paz.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 92, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 1, content: "Glória a Deus, o Pai Eterno,\nCujo trono é os Céus:\nO universo lhe pertence,\nGlória sim, ao nosso Deus.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 93, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, content: "Eu te louvo! Eu te louvo!\nOh! Jesus meu Salvador!\nDai-lhe glória ó remidos!\nPois seu sangue limpa o pecador.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 94, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 2, content: "Glória ao Filho mui amado,\nQue merece o louvor,\nDemos glória ao Seu nome,\nAo Cordeiro, ao Redentor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 95, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 3, content: "Demos nós, ao Santo Espírito\nMil louvores por Seu dom;\nPor sua graça tão imensa,\nGlória, a Ele. Ele é bom!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 96, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_24, position: 4, content: "Glória, glória ao Pai Bendito,\nGlória, glória a Jesus;\nGlória dai ao Santo Espírito,\nAo Deus trino nossa luz.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 97, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 1, content: "Teu divinal amor veio-me buscar;\nTudo com gratidão quero consagrar.\nAceita, meu Senhor, de um grato pecador\nTributo de louvor, dado com fervor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 98, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 2, content: "Atende, meu Jesus, essa petição;\nTão débil sou, e mau é meu coração.\nTeu nome a exaltar, a nova a publicar,\nTeu reino a dilatar, vem-me habilitar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 99, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 3, content: "Oh! Dá-me mais paixão de um amor real,\nP’ra Te servir e ser muito mais leal!\nAs almas a ganhar, sempre na luz a andar,\nE os filhos a amar, vem-me habilitar.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 100, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_25, position: 4, content: "Tudo o que sou, Senhor, eu Te votarei;\nDo mundo vil e mau nunca mais serei;\nTeu rosto quando vir, amor no Céu luzir,\nA glória do porvir vou enfim fruir.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 101, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 1, content: "Deus é o Criador;\nEternamente é Rei.\nEle criou o universo;\nEternamente é Rei.\nEle criou o mar;\nEternamente é Rei.\nEle criou o sol;\nEternamente é Rei.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 102, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, content: "Adorai, adorai, adorai, adorai,\nEternamente é Rei.\nCantai, cantai, cantai, cantai,\nEternamente é Rei.\nÉ Santo, é Santo, é Santo, é Santo,\nEternamente é Rei.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 103, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 2, content: "Deus é o Criador;\nEle criou a chuva;1nEle criou o vento;\nEle criou o arvoredo;", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 104, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 3, content: "Deus é o Criador;\nEle criou a vida;\nEle criou o homem;\nEle criou o mantimento;", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 105, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_26, position: 4, content: "Enviou Jesus Cristo;\nEle é o Salvador dos homens;\nE é Espírito Santo;\nLimpa o coração;", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 106, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 1, content: "A nosso Pai no Céu\nTributa lábio meu,\nO Teu louvor.\nJesus o Filho deu.\nO qual na cruz morreu,\nDo mal nos defendeu.\nA Deus louvai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 107, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 2, content: "A nosso Salvador,\nA nosso Redentor,\nDemos louvor.\nSeu corpo se partiu,\nE ao pobre pecador\nNa cruz o céu lhe abriu.\nA Deus louvai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 108, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 3, content: "A Deus Consolador\nMandado por Jesus\nDemos louvor.\nDe Cristo o grande amor\nRevela Instruidor.\nSê meu renovador\nA Deus louvai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 109, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_27, position: 4, content: "Louvemos com ardor,\nCom gozo e com fervor\nO trino Deus!\nEternamente ali,\nEm canto abrasador, Trindade santa, a\nTi Louvor nos céus!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 110, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 1, content: "Omnipotente Rei,\nAqui presente sê\nNo teu poder;\nO Teu excelso amor,\nInspira-nos louvor;\nQueremos-te, Senhor,\nEngrandecer.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 111, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 2, content: "Ó encarnado Deus,\nNos ouve lá dos céus\nA petição.\nVem-nos abençoar,\nE vem fazer brotar\nO que se semear No coração.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 112, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 3, content: "Vem tu, Consolador,\nSê testificador\nDa redenção.\nNo templo vem entrar,\nA obra completar.\nDas manchas vem limpar\nO coração.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 113, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_28, position: 4, content: "Ó grande trino Deus,\nSim, te adoramos nós,\nE só a Ti!\nSantificar-nos-ás,\nAo céu nos levarás,\nA glória nos darás,\nContigo aí.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 114, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_29, position: 1, content: "Oh! com júbilo cantemos;\nAleluia!\nOh! com gratidão cantemos;\nAleluia!\nCom os sons harmoniosos,\nAdoremos nosso Deus.\nSeu amor é tão imenso.\nAleluia!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 115, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_29, position: 2, content: "Alegrem-se os corações;\nAleluia!\nExaltai o Salvador;\nAleluia!\nJesus é o nosso Guia,\nE também o nosso refúgio;\nSua compaixão é imensa\nAleluia!", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 116, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_29, position: 3, content: "O louvor não cesse nunca;\nAleluia!\nTanto aqui como no céu,\nAleluia!\nTestemunhas da esperança;\nSomos os da Boa-Nova;\nVamos divulgá-la ao mundo;\nAleluia!", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 117, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 1, content: "Bendize, ó tu, meu coração,\nBendize ao Salvador,\nE tudo quanto houver em mim,\nDerrame-lhe louvor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 118, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 2, content: "Bendize, ó tu, meu coração,\nBendize ao Salvador,\nNão fiques esquecido, pois,\nDo Seu divino amor.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 119, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 3, content: "Ele os delitos, com amor\nE graça perdoou,\nE com divina compaixão\nJesus te aliviou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 120, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_30, position: 4, content: "O teu desejo satisfaz\nCom verdadeiros bens;\nA vida renovada assim,\nTu, como as águias tens.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 121, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, position: 1, content: "A Deus dêmos glória, com grande fervor;\nSeu Filho bendito por nós todos deu;\nA graça concede ao mais vil pecador,\nAbrindo-lhe a porta de entrada no Céu.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 122, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, content: "Exultai! Exultai!\nVinde todos louvar\nA Jesus, Salvador:\nA Jesus Redentor;\nA Deus demos glória,\nPorquanto do Céu,\nSeu Filho bendito por nós todos deu.", typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 123, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, position: 2, content: "Óh! graça real, foi assim que Jesus,\nMorrendo, Seu sangue por nós derramou!\nHerança nos céus, com os santos em luz,\nComprou-nos Jesus, pois o preço pagou.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 124, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_31, position: 3, content: "A crer nos convida tal rasgo de amor,\nNos merecimentos do Filho de Deus;\nE quem, pois confia no seu Salvador,\nVai vê-lo sentado na glória dos céus.", typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 125, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 1, content: "Saudai o nome de Jesus!\nArcanjos, vos prostrai!\nAo filho do eterno Deus\nCom glória coroai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 126, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 2, content: "Ó escolhida geração\nDo bom eterno Pai:\nAo grande Autor da Salvação,\nCom glória coroai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 127, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 3, content: "Ó perdoados, cujo amor\nBem triunfante vai,\nAo Deus-Varão, Conquistador,\nCom glória coroai.", typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 128, hymnsNumber: HymnsNumberSeeder.PRAISE_AND_WORSHIP_32, position: 4, content: "Ó raças, tribos e nações,\nAo Rei do mundo honrai;\nA quem quebrou vossos grilhões\nCom glória coroai.", typeStanza: HymnsContentCode.VERSE),

  ];
}