import 'package:ieca_mobile/_import.dart';

class HymnsTestimonyAndWork {
  static List<HymnsContent> list = [
    HymnsContent(id: 1165, position: 1, content: "Mais de Cristo eu quero ser,\nMais do Seu amor obter,\nMais da Sua compaixão,\nMais da Sua mansidão.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_278, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1166, content: "Mais, mais de Cristo!\nMais, mais de Cristo!\nMais do seu puro e santo amor,\nMais de Ti mesmo, ó Salvador!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_278, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1167, position: 2, content: "Mais de Cristo eu quero ouvir,\nMais do Seu grande amor sentir,\nMais fervor eu quero obter,\nMais auxílio receber.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_278, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1168, position: 3, content: "Mais de Cristo eu quero ler.\nMais de Sua graça eu quero ter,\nMais ardente gratidão,\nMais amante coração.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_278, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1169, position: 1, content: "Se quer ser abençoado,\nSiga sempre os pés de Cristo;\nDar-te-á muita alegria,\nSiga sempre os pés de Cristo.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_279, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1170, content: "Seja discípulo Seu,\nCom toda a fé seguindo-O;\nSempre ao pé d'Ele estar;\nSiga sempre os pés de Cristo.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_279, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1171, position: 2, content: "Se queres bom repouso obter,\nSiga sempre os pés de Cristo;\nSe és fraco te fortalece!\nSiga sempre os pés de Cristo.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_279, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1172, position: 3, content: "Se quiser ter a coroa,\nSiga sempre os pés de Cristo;\nVá, e tua cruz levante,\nSiga sempre os pés de Cristo.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_279, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1173, position: 4, content: "Se coisas do céu quer obter,\nSiga sempre os pés de Cristo;\nSomente Ele é o repartidor,\nSiga sempre os pés de Cristo.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_279, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1174, position: 1, content: "Sede mensageiros do reino da graça,\nEspalhai a Palavra da vida.\nVoltem os que estão\nEm desertos, perdidos,\nP'ra entrar na família da vida.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_280, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1175, content: "Sede mensageiros do reino da graça,\nCom perseverança e fé;\nPara os carentes ouvirem alegres,\nA boa mensagem da vida.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_280, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1176, position: 2, content: "Sede mensageiros do reino da graça,\nA luz verdadeira mostrai.\nNas medonhas trevas\nDo mal deste mundo\nBrilhai como vela da vida.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_280, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1177, position: 3, content: "Sede mensageiros do reino da graça\nMostrando a terra do gozo.\nP'ra que os viajantes\nCansados e tristes\nRetomem o caminho da vida.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_280, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1178, position: 4, content: "Sede mensageiros do reino da graça\nPregando as bênçãos de Deus.\nSeja ouvida ao mundo\nA imensa graça,\nQue deu-vos o prémio da vida.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_280, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1179, position: 1, content: "Há trabalho pronto\nPara ti, cristão,\nQue demanda toda\nA tua devoção.\nVem alegremente\nA Cristo obedecer,\nPois, só tu, ó crente,\nO poderás fazer.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_281, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1180, content: "Por Jesus é trabalhar!\nProntamente, fielmente, trabalhar!\nEm servi-lo que prazer!\nE só tu, ó crente, o poderás fazer!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_281, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1181, position: 2, content: "Para cada crente o\nMestre preparou\nUm trabalho certo,\nQuando o resgatou.\nE o trabalho a que\nJesus te chama aqui,\nComo será feito\nSe o não for por ti?", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_281, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1182, position: 3, content: "Pode ser humilde,\nMas, se for p'ra Deus,\nTeu trabalho é visto\nLá dos altos céus!\nE o esforço feito\nNão será em vão,\nSe tiver em Cristo\nPlena aprovação!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_281, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1183, position: 4, content: "Quantos há perdidos,\nSem a salvação!\nQuantos que precisam\nDe consolação!\nComo Cristo os ama,\nFaze-os entender,\nPois só tu, ó crente,\nO poderás fazer!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_281, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1184, position: 1, content: "Nas tormentas desta vida\nPerto está a perdição.\nAos incautos navegantes\nQuem trará a salvação?", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_282, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1185, content: "Resplandeçam nossas luzes\nAtravés do escuro mar.\nPois nas trevas do pecado\nAlmas podem naufragar.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_282, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1186, position: 2, content: "Sempre brilha em graça imensa,\nRico amor do eterno Deus.\nToca a nós mostrar o rumo\nNa viagem para os céus.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_282, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1187, position: 3, content: "Nuvens de paixão mundana\nObscurecem-lhes o sol.\nErgue o grito de perigo,\nAlça as luzes do farol.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_282, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1188, position: 4, content: "Os errantes, insensatos,\nGuia ao porto divinal.\nEm Jesus há vero abrigo\nDo furor do temporal.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_282, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1189, position: 1, content: "Alguém o amor de Cristo mostrou,\nE uma alma triste assim consolou.\nAlguém, com doce e alegre\ncanção,\nTirou as nuvens dum coração.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1190, content: "Foste tu este alguém? (2x)", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_283, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1191, position: 2, content: "Alguém precioso tempo perdeu,\nE a voz divina desobedeceu.\nAlguém, que vendo o pecador,\nNão lhe apontou para o\nSalvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1192, position: 3, content: "Alguém honrou e serviu a Jesus,\nTrazendo almas à Sua luz.\nAlguém mensagem de paz levou,\nAlguém do mal uma alma tirou.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1193, position: 4, content: "Alguém espalha, ao caminhar\nPor este mundo, bênçãos sem\npar.\nAlguém terá o gozo de ouvir:\n«Servo fiel» no doce porvir.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_283, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1194, content: "Serás tu esse alguém? (2x)", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_283, typeStanza: HymnsContentCode.CHOIR),

    HymnsContent(id: 1195, position: 1, content: "Avante, ó camaradas,\nVós que sois filhos da luz.\nAvante! Esforçai-vos\nPor Cristo o Senhor e Sua cruz.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_284, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1196, content: "Avante! Avante!\nPelejai pelo bem.\nAvante! Avante!\nA luz nos brilha além.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_284, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1197, position: 2, content: "Avante, ó camaradas,\nIde às campinas ceifar.\nAvante! Vem a noite\nE a lida em breve vai findar.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_284, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1198, position: 3, content: "Avante, ó camaradas.\nAndai enquanto há luz.\nAvante, consagrados\nÀ causa de Jesus vos dedicai.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_284, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1199, position: 4, content: "Avante, ó camaradas,\nNão haja tréguas com mal\nAvante, combatendo\nNa luta divinal estais sempre firmes.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_284, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1200, position: 1, content: "Eu amo a história\nQue fala no Senhor\nJesus e sua glória,\nJesus e seu amor.\nEu amo a história,\nTão linda quão veraz;\nA todo meu anseio,\nSó ela satisfaz.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_285, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1201, content: "Eu amo a história\nDe tão singela glória,\nA história de meu Mestre,\nJesus e seu amor.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_285, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1202, position: 2, content: "Eu amo a história,\nCantá-la é meu prazer,\nE cada vez que a conto,\nMais doce vem a ser.\nEu amo a história,\nQue a muitos nova é;\nPois traz-nos a mensagem,\nDe paz e salvação.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_285, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1203, position: 3, content: "Eu amo a história,\nPois quem a sabe bem,\nCom grande enlevo busca\nOuvi-la outra vez.\nEu amo a história,\nQue é hino de emoção\nA nova e velha história,\nTão grata ao coração.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_285, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1204, position: 1, content: "Às nações contaremos a história\nQue é capaz de livrá-las do mal;\nRevela a verdade e a vida,\nE dá uma paz real. (2x)", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_286, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1205, content: "Cederão densas trevas à aurora\nDesse dia de Cristo Jesus.\nCom a vinda do reino divino,\nO mundo verá a luz.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_286, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1206, position: 2, content: "Às nações cantaremos um hino,\nP'ra atrair corações ao Senhor;\nDissipa a tristeza e a mágoa.\nDifunde no mundo amor. (2x)", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_286, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1207, position: 3, content: "Às nações mostraremos o Cristo\nPois só ele conduz para os céus;\nQue todos por ele venham\nHumildes servir a Deus. (2x)", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_286, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1208, position: 4, content: "Às nações pregaremos a nova,\nQue Jesus outra vez há de vir;\nE salva por fé aquele\nQue sua palavra ouvir. (2x)", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_286, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1209, position: 1, content: "Levantai agora, gente de Cristo,\nCom alegria a palavra pregai.\nJesus a força da morte venceu,\nRessuscitou para o povo salvar.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_287, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1210, content: "Cantai o coro: jubilosamente\nReina Jesus, reina Jesus.\nProntos p'ra lida do reino de Deus,\nTriunfou Jesus, sempre reinará.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_287, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1211, position: 2, content: "Ide com firmeza, ao mal resisti,\nMensagens de justiça e paz pregai\nE armai-vos com armaduras de Deus.\nNão desisti, ao Capitão confiai.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_287, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1212, position: 3, content: "Na vossa terra e em todo o lugar,\nCom a luz do céu as trevas vencei,\nNo meio dos embaraços do mundo,\nReino de justiça edificai.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_287, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1213, position: 4, content: "A escarnecedora morte na cruz,\nVeio a vida e mui gozo trazer.\nAo grande vencedor todos louvai,\nCom regozijo e alegria O servi.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_287, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1214, position: 1, content: "A mensagem vem de Deus,\nQue Jesus é o Salvador!\nOh, clamai, vós filhos Seus:\nÉ Jesus o Salvador!\nProclamai com grande ardor\nQue Deus ama ao pecador,\nQue Seu Filho amado deu\nPara ser o Salvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_288, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1215, position: 2, content: "Ó vós, povos, eis o dom:\nÉ Jesus o Salvador!\nPor Seu sangue dá perdão;\nÉ Jesus o Salvador!\nIlhas todas, exultai;\nSeu amor considerai,\nE vós anjos, proclamai\nQue Jesus é o Salvador!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_288, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1216, position: 3, content: "Ó vós, santos, já bradai:\nÉ Jesus o Salvador!\nVós, nações, oh! Jubilai!\nÉ Jesus o Salvador.\nSalvação de graça dá\nHoje a todo o pecador.\nGlória! Glória ao Deus de amor,\nPois Jesus é o Salvador!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_288, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1217, position: 1, content: "Real pendão deixai voar,\nNo azul do céu, em terra e mar,\nMostrai, pregar de Cristo a cruz\nPendão real de amor e luz!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_289, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1218, position: 2, content: "Deixai voar real pendão,\nAos que sem Deus, sem luz estão;\nPendão real que ao mundo traz.\nMais fé em Deus, perdão e paz.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_289, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1219, position: 3, content: "Pendão real deixai voar,\nSalvai o mundo sem tardar,\nErguei pendão de amor e luz\nQue abriu o céu e a Deus conduz.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_289, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1220, position: 1, content: "Nosso Rei veio ao mundo,\nE os homens cegos achou,\nCegueira de coração;\nDespertos agora estão.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1221, content: "Felizes e abençoados,\nEm nós cintila a luz da cruz;\nCreiamos com fé na palavra da vida,\nSejamos Suas testemunhas.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_290, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1222, position: 2, content: "Enviados chegados ao país,\nIgnorada era a Palavra,\nPela gente pobre encontrada,\nPobre de coração.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1223, position: 3, content: "Ao povo pregaram a Salvação,\nMostrando o caminho da vida.\nOuviram uns jubilosos,\nOutros porém famintos.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1224, position: 4, content: "Agora crentes somos nós,\nConhecendo a Sã doutrina.\nQue a salvação nos mostra,\nA salvação do mundo.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_290, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1225, position: 5, content: "Levantai e pregai ao mundo,\nAs nações levai a Palavra.\nSedentas da Boa Nova,\nPalavra da salvação.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_290, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1226, position: 1, content: "Há um amigo verdadeiro,\nCristo, o Senhor,\nQue sofreu sobre o madeiro\nA nossa dor.\nEste amigo, moribundo,\nPadecendo pelo mundo,\nPatenteia amor profundo.\nQue grande amor!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_291, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1227, position: 2, content: "Vida eterna é conhecê-Lo,\nCristo, o Senhor.\nQuem quiser depressa venha\nAo Redentor.\nPor nós outros derramava\nO Seu sangue, pois amava\nOs perdidos que chamava;\nQue grande amor.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_291, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1228, position: 3, content: "Ontem, hoje e para sempre,\nCristo, o Senhor,\nÉ o mesmo bom Amigo\nDo pecador.\nÉ maná para o deserto,\nGuia no maior aperto,\nSeu socorro sempre é certo;\nQue grande amor!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_291, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1229, position: 1, content: "Da tentação sempre devemos fugir,\nPois ela ao pecado nos pode induzir;\nSempre combatendo toda a vil paixão,\nA Jesus seguindo como um bom cristão.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_292, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1230, content: "Ao Salvador pedindo força,\nAuxílio e graça,\nEle está-vos ouvindo;\nEle vo-las quer dar.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_292, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1231, position: 2, content: "Das más companhias não queiras saber;\nNão ouvem a Cristo; vos querem perder.\nSede fervorosos, com bom coração.\nA Jesus seguindo como um bom cristão.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_292, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1232, position: 3, content: "Deus dá uma c'roa só a quem vencer,\nAvante! Avante! Nada há que temer.\nVolvei para o Mestre, vosso Capitão.\nA Jesus seguindo, como um bom cristão.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_292, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1233, position: 1, content: "Confiando no Senhor,\nAvançai. Avançai!\nSempre andando em Seu amor,\nAvançai. Avançai!\nPela fé a Jesus honrai.\nSua glória espalhai,\nSua graça proclamai,\nAvançai. Avançai.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_293, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1234, position: 2, content: "P'ra com Cristo, trabalhar,\nAvançai. Avançai!\nSob a cruz p'ra batalhar,\nAvançai. Avançai!\nCom coragem, fé e amor,\nCrendo em Cristo, o Salvador,\nIde avante com ardor,\nAvançai. Avançai.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_293, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1235, position: 3, content: "O caminho aberto está.\nAvançai. Avançai.\nCristo força vos dará.\nAvançai. Avançai.\nLuz do céu p’ra vos guiar,\nGraças p'ra vos sustentar,\nVosso é galardão sem par.\nAvançai. Avançai.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_293, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1236, position: 1, content: "Todos falam dos perigos\nDo caminho em que eu estou,\nMas não vêem a luz que brilha\nAo redor, por onde eu vou.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_294, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1237, content: "Meu Jesus me guia os passos,\nE já veio em mim morar.\nNeste mundo perigoso\nSó por mim não posso andar.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_294, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1238, position: 2, content: "Falam mais de desenganos\nE de dura provação,\nMas Jesus me ampara sempre\nE me dá consolação.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_294, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1239, position: 3, content: "Sei que meu amor é fraco,\nSou propenso p'ra pecar;\nMas com seu divino auxílio\nHei-de sempre triunfar.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_294, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1240, position: 1, content: "Espalhemos todos\nA semente santa,\nDesde a madrugada\nAté o anoitecer,\nCalmos, aguardando\nO tempo da colheita,\nQuando alegremente\nHavemos de colher.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_295, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1241, content: "Havemos de colher! (2x)\nOh! quão jubilosos\nHavemos de colher!\nHavemos de colher! (2x)\nMesses abundantes\nHavemos de trazer!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_295, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1242, position: 2, content: "Semeemos quando\nSeres perniciosos\nA semente boa\nQuerem destruir;\nDeus abençoando,\nAlegres, satisfeitos.\nA colheita santa\nHavemos de fruir.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_295, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1243, position: 3, content: "Eia, pois, obreiros,\nSemeai, ousados,\nA semente viva\nDa verdade e luz,\nProclamando Cristo,\nSeu poder e glória,\nSalvação perfeita\nQue alcançou na cruz!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_295, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1244, position: 1, content: "Livres do medo temos ficado;\nCristo morreu, levando o pecado;\nEis o resgate: o pacto se fez;\nFomos remidos de uma vez!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_296, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1245, position: 2, content: "De uma vez! Oh! sim, acredita!\nÓ pecador, tens sorte bendita!\nTudo Jesus, por nós, satisfez!\nCristo salvou-nos de uma vez!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_296, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1246, position: 3, content: "Ao malfeitor, que a pena merece,\nVida e perdão Jesus oferece;\nClama por graça, com avidez,\nCristo te acolhe de uma vez!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_296, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1247, position: 4, content: "Graça real! Não há mais castigo:\nTemos a paz sem medo e perigo!\nVestes reais, não triste nudez;\nCristo enriquece de uma vez!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_296, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1248, position: 5, content: "«Filhos de Deus!» favor inaudito!\nDeus nos amou em grau infinito!\nNesta clemência não há dobrez;\nHá segurança de uma vez!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_296, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1249, position: 1, content: "Quero estar ao pé da cruz,\nDe onde a rica fonte\nCorre franca, salutar,\nDo Calvário monte.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_297, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1250, content: "Sim, na cruz, sim na cruz,\nSempre me glorio,\n'Té que alfim vá descansar,\nSalvo, além do rio.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_297, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1251, position: 2, content: "A tremer ao pé da cruz,\nGraça eterna achou-me;\nMatutina Estrela ali,\nRaios seus mandou-me.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_297, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1252, position: 3, content: "Sempre a cruz, Jesus, meu Deus,\nQueiras recordar-me;\nDela à sombra, Salvador,\nQueiras abrigar-me.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_297, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1253, position: 4, content: "Junto à cruz, ardendo em fé,\nSem temor vigio;\nPois à terra santa irei,\nSalvo, além do rio.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_297, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1254, position: 1, content: "Vamos nós trabalhar,\nSomos servos de Deus;\nCom o Mestre seguir\nNo caminho dos céus;\nCom o seu bom conselho\nO vigor renovar,\nE fazer prontamente\nO que Cristo mandar!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_298, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1255, content: "No labor, com fervor, a servir a Jesus.\nCom esperança e fé e com oração,\nAté que volte o Senhor.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_298, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1256, position: 2, content: "Vamos nós trabalhar,\nOs famintos fartar,\nPara a fonte os sedentos\nDepressa levar;\nSó na cruz do Senhor\nNossa glória será,\nPois Jesus salvação\nPela graça nos dá!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_298, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1257, position: 3, content: "Vamos nós trabalhar\nPara Cristo, o Senhor;\nContra o reino das trevas\nSerá vencedor;\nEle, então, para sempre\nExaltado será,\nPois real salvação\nPela graça nos dá!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_298, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1258, position: 4, content: "Vamos nós trabalhar,\nAjudados por Deus,\nQue coroa real\nNos dará lá nos céus;\nNa mansão dos fieis\nO descanso será,\nPois Jesus salvação\nPela graça nos dá!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_298, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1259, position: 1, content: "Avançai! Avançai!\nDerramai essa luz\nSobre os povos da terra\nQue não têm Jesus!\nIde, pois, disse o Mestre.\nDe vós quem irá\nObservando o preceito\nQue Cristo nos dá?\nConfiai no Senhor.\nNão tenhais mais temor.\nAvançai com Jesus. Avançai!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_299, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1260, position: 2, content: "Avançai! Avançai!\nCom a Bíblia na mão.\nProclamai às nações\nQue já há remissão.\nEncarai os perigos\nCom fé em Jesus!\nSe sofremos aqui\nReinaremos em luz.\nIde, crentes, lutai.\nNos trabalhos entrai!\nAvançai sem temor. Avançai!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_299, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1261, position: 3, content: "Avançai! Avançai\nA pregar aos milhões\nQue perecem nas trevas\nE sem salvação!\nFoi por eles também\nQue Jesus padeceu.\nQue na terra pobreza\nE desprezo sofreu.\nProclamai redenção!\nEm Jesus há perdão.\nAvançai com amor, Avançai!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_299, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1262, position: 1, content: "Avante! Avante! ó crentes!\nSoldados de Jesus!\nErguei Seu estandarte,\nLutai por Sua cruz!\nContra hostes inimigas,\nAnte essas multidões,\nO Comandante excelso\nDirige os batalhões.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_300, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1263, position: 2, content: "Avante! Avante! ó crentes!\nPor Cristo pelejai;\nVesti Sua armadura,\nEm seu poder marchai!\nNo posto sempre achados,\nVelando em oração;\nPor meio de perigos,\nSeguindo o Capitão!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_300, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1264, position: 3, content: "Avante! Avante! ó crentes!\nCom passo triunfal!\nHoje há combate horrendo!\nMui cedo a paz final!\nEntão, eternamente,\nBendito vencedor,\nPor Deus vitorioso!\nCom Cristo, o Salvador!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_300, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1265, position: 1, content: "Que grande amigo é meu Jesus,\nTão santo, bom e terno!\nSem outro igual o Seu poder\nE o Seu amor superno.\nPara esta ovelha sem vigor\nOlhou com simpatia.\nE Sua tão bondosa mão\nServiu-me então de guia.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_301, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1266, position: 2, content: "Que grande amigo é meu Jesus!\nDe longe quis buscar-me!\nDesceu, chegou, sofreu, penou,\nMorreu p'ra resgatar-me!\nAs glórias do Seu santo lar\nRenovam meu alento,\nPois breve espero receber\nO Seu acolhimento.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_301, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1267, position: 3, content: "Que grande amigo é meu Jesus!\nMeu Guia tão prudente,\nMeu Protector tão ideal,\nMeu Capitão valente.\nSou de Jesus, Jesus é meu\nPor tempos sempiternos,\nE gozarei de Deus no céu\nFavores Seus paternos.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_301, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1268, position: 1, content: "Veio lá dos altos céus\nJesus Salvador.\nEle sobre a cruz morreu\nJesus Salvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_302, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1269, content: "A mensagem anunciai,\nEle trouxe a salvação.\nDeu-nos vida eternal,\nJesus Salvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_302, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1270, position: 2, content: "A Segunda morte em nós,\nJesus Salvador.\nVeio para nos salvar\nJesus Salvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_302, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1271, position: 3, content: "A promessa nos deixou\nJesus Salvador.\nDiz: «quem crer já salvo está»\nJesus Salvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_302, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1272, position: 4, content: "Há-de vir p'ra nos buscar\nJesus Salvador,\nLevar-nos-há ao Senhor:\nJesus Salvador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_302, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1273, position: 1, content: "Eis os milhões,\nQue em trevas tão medonhas,\nJazem perdidos,\nSem o Salvador!\nQuem, lhes irá,\nAs novas proclamando.\nQue Deus em Cristo,\nSalva o pecador.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_303, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1274, content: "Poder supremo o Pai me deu,\nNa terra, como lá no céu!\nIde, pois, anunciai o Evangelho,\nE eis-Me convosco sempre!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_303, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1275, position: 2, content: "Portas abertas,\nEis por todo o mundo!\nCristãos, erguei-vos!\nEia avante andai!\nCrentes em Cristo,\nUni as vossas forças,\nDa escravidão os povos libertai!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_303, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1276, position: 3, content: "«Oh! vinde a Mim»\nA voz divina clama\n«Vinde!» clamai\nNo nome de Jesus.\nP'ra nos salvar\nDa maldição eterna,\nSeu sangue derramou\nPor nós na cruz.", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_303, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1277, position: 4, content: "Ó Deus, apressa o dia glorioso,\nEm que os remidos\nTodos se unirão,\nE em coro excelso,\nSanto, jubiloso,\nP’ra todo o sempre,\nGlória a Ti darão!", hymnsNumber: HymnsNumberSeeder.TESTIMONY_AND_WORK_303, typeStanza: HymnsContentCode.VERSE)
  ];
}