import 'package:ieca_mobile/_import.dart';

class HymnsThanksgivingToGod {
  static List<HymnsContent> list = [
    HymnsContent(id: 1278, position: 1, content: "Com reverente júbilo, nós vimos\nRender-Te muitas graças, Bom Senhor,\nPor esta Igreja em que de Ti haurimos\nEnsinamentos belos, luz e amor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1279, position: 2, content: "A nossa Igreja abriu caminho novo,\nNa direcção de um alto e maior bem\nVeio apontar a todo o nosso povo,\nUm alvo nobre e que áureo prémio tem!", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1280, position: 3, content: "Graças, ó Deus, porque nos concedeste\nQuem semeou, bem como quem regou;\nDepois de Ti nos veio, ó Pai celeste,\nO crescimento e fruto que abundou.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1281, position: 4, content: "Graças te damos pelos fundadores,\nE pelos que os seguiram com amor.\nAjuda agora, ó Deus, os sucessores,\nA prosseguirem com crescente ardor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_304, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1282, position: 5, content: "Também rogamos, Pai, que nos concedas\nO grande ensejo de ir compartilhar,\nCom os irmãos por todas as veredas,\nA bênção destes ricos dons sem par.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_304, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1283, position: 1, content: "Ó Deus do céu, da terra e mar,\nHumildes vimos-Te adorar,\nTua bondade celebrar,\nQue tudo dás.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_305, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1284, position: 2, content: "A luz benigna, o belo ar,\nTão doce e branda e salutar,\nQue vem a tudo renovar,\nSim, tudo dás.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_305, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1285, position: 3, content: "A verde relva, a linda flor,\nDe ricos frutos o penhor,\nProclamam Teu constante amor,\nSim tudo dás.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_305, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1286, position: 4, content: "Tu, por um mundo pecador,\nTeu Filho deste, o Salvador,\nCom Ele tudo dás, Senhor,\nSim, tudo dás.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_305, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1287, position: 1, content: "Gratos estamos à Ti, ó Deus,\nPelos Teus grandes feitos,\nDo imenso amor\nQue aos povos mostrastes;\nSalvação grandiosa,\nRevelada em Cristo,\nPorque tudo, de graça,\nSempre nos dás, Senhor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_306, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1288, position: 2, content: "Gratos estamos a Ti, ó Deus\nPois a sabedoria\nE saúde nos destes,\nPara em tudo pensar,\nP'ra seguir a justiça,\nO Senhor deu-nos fé,\nPorque tudo, de graça,\nSempre nos dás, Senhor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_306, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1289, position: 3, content: "Gratos estamos a Ti, ó Deus;\nPela gente exemplar,\nCorajosa na fé,\nSem temor pela morte,\nMensageiros antigos,\nNos legaram a fé,\nPorque tudo, de graça,\nSempre nos dás, Senhor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_306, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1290, position: 4, content: "Gratos estamos a Ti, ó Deus,\nDas histórias antigas,\nConvencidos estamos\nPelas coisas futuras;\nDê-nos todos, a força,\nP'ra o país construir,\nPorque tudo, de graça,\nSempre nos dás, Senhor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_306, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1291, position: 1, content: "Vendo a história\nNós reconhecemos\nTantos favores\nQue o Senhor nos fez.\nEm nossas lidas,\nBem nos conduziu.\nÓ nosso Deus,\nGrato, grato nós Te somos, (2x)", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_307, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1292, position: 2, content: "Firmes no futuro\nConfiantes estamos,\nSeguindo o Mestre\nCom amor e paz.\nInda que haja muitos embaraços\nNão temeremos,\nPois Tu És o nosso guia. (2x)", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_307, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1293, position: 3, content: "Fitos nos altos,\nOnde Cristo está\nMarchando para\nO nosso fim lograr,\nSempre na via\nQue o Senhor mostrou,\nAli seguimos com a fé e gratidão, (2x)", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_307, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1294, position: 4, content: "Jesus, o Mestre,\nFim de todas as coisas,\nTanto ontem, hoje\nE eternamente,\nÉs Salvador e És o nosso Rei.\nCom Teu poder\nSomos mais que vencedores, (2x)", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_307, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1295, position: 1, content: "Visto conceder-nos Deus\nUma rica oferenda,\nDeste novo e belo dia,\nGraças nós rendemos.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1296, position: 2, content: "Visto ter-nos dado a força\nP'ra fazer nosso trabalho\nE amigos igualmente,\nGraças nós rendemos.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1297, position: 3, content: "Corações nos concedeu\nPara outros sempre amar,\nOdiando sempre o mal,\nGraças nós rendemos.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1298, position: 4, content: "Várias coisas recebemos,\nCoisas boas que não fartam,\nQue nos tornam reverentes,\nGraças nós rendemos.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1299, position: 5, content: "Porque sono merecemos\nPara que bem descansemos,\nE as forças restaurarmos,\nGraças nós rendemos.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_308, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1300, position: 6, content: "Porque o Filho se nos deu,\nE por Ele fomos salvos,\nRedimindo nossas vidas,\nGraças nós rendemos.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_308, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1301, position: 1, content: "Amor, que por amor desceste,\nAmor, que por amor morreste,\nAh! Quanta dor não padeceste,\nMeu coração p'ra conquistar\nE meu amor ganhar!", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_309, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1302, position: 2, content: "Amor, que com amor seguias\nA mim, que sem amor Tu vias,\nOh! quanto amor por mim sentias,\nPois por amor, Senhor Jesus,\nSofreste sobre a cruz!", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_309, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1303, position: 3, content: "Amor, que tudo me perdoas.\nAmor, que até mesmo abençoas\nUm réu de quem Tu te afeiçoas!\nPor Ti vencido, ó Salvador,\nEis-me aos Teus pés, Senhor!", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_309, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1304, position: 4, content: "Amor, que para sempre duras,\nQue nos Teus braços me seguras,\nCercando-me de mil venturas,\nAceita agora, ó Salvador,\nO meu humilde amor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_309, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1305, position: 1, content: "Bem longe de Deus eu andava,\nUm pobre perdido fui eu;\nPensava que fosse impossível\nEntrar a minha alma no Céu.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1306, position: 2, content: "Vaguei tão errante nas trevas,\nNem raio de luz vinha a mim,\nE triste, cansada minha alma,\nNão via perdão para mim.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1307, position: 3, content: "Estando no meio das trevas\nBem clara uma voz eu ouvi\nDizendo-me: «Sou poderoso\nP'ra dar salvação hoje a ti.»", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1308, position: 4, content: "Parei; era a voz do meu Mestre,\nFalando palavras de amor;\nClamei: «Sou um pobre perdido;\nOh! tem compaixão, Salvador!»", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1309, position: 5, content: "Então me entreguei a meu Mestre;\nFeliz Jesus Cristo me fez.\nA todos eu vou proclamando:\nFoi Ele que me satisfez.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_310, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1310, position: 6, content: "E quando, por graça de Cristo,\nO Céu alcançar afinal,\nLouvores darei para sempre\nA quem me deu vida eternal.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_310, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1311, position: 1, content: "A terra semeamos,\nA fim de nos dar pão,\nMas Deus é Quem a nutre\nCom benfazeja mão;\nEle é Quem manda o frio,\nA calma no verão,\nAs chuvas e os orvalhos\nE a doce viração.\nDe todo o bem a fonte\nÉ nosso bom Senhor!\nLouvai a Deus! Louvai a Deus\nPor todo o Seu amor!", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_311, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1312, position: 2, content: "O Criador de tudo\nQue perto ou longe está,\nA flor silvestre pinta\nE aos astros brilho dá!\nOs ventos Lhe obedecem\nE o bravo mar também;\nAs frágeis avezinhas\nAo Seu cuidado tem.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_311, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1313, position: 3, content: "A nós, porém, Seus filhos,\nRevela mais amor,\nMandando-nos Seu Filho,\nJesus, o Salvador,\nDotando-nos em Cristo\nCom tudo quanto tem,\nFazendo-nos herdeiros\nDe Deus, o Sumo-Bem.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_311, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1314, position: 1, content: "Senhor meu Deus\nQuando eu maravilhado,\nParo a pensar no teu grandioso Ser,\nVejo a tormenta o céu estrelado,\nA declarar ao mundo o teu poder.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_312, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1315, content: "Então minh'alma canta a Ti Senhor.\nQuão grande és Tu,\nQuão grande és Tu!\nCanta minh'alma a Ti, oh, meu Senhor.\nQuão grandes és Tu, Senhor o és.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_312, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1316, position: 2, content: "Quando atravesso\nBosques e florestas,\nOuvindo a brisa, pássaros cantar,\nOu vejo além, montanhas altaneiras,\nO teu poder e glórias proclamar!", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_312, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1317, position: 3, content: "Quando percebo\nQue na cruz maldita,\nPor teu amor, Jesus morreu por mim,\nE me livrou do jugo do pecado,\nAli vertendo o sangue carmesim.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_312, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1318, position: 4, content: "E quando enfim eu for ao céu subindo,\nEntão verei a glória do Senhor.\nAdorarei, com meu amor infindo,\nA quem mostrou por mim tão\ngrande amor.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_312, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 1319, position: 1, content: "Alegres estão as nossas almas\nMarchamos no trilho do céu.\nSeu brilho já cintila em nós,\nMarchamos no trilho do céu.\nAs duras provas já vencidas,\nConfiando o nosso Guia,\nPois com Ele chegaremos\nMarchamos no trilho do céu.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_313, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1320, content: "Irmãos, cantemos com alegria;\nPeregrinos da esperança.\nNossa jornada acaba alegremente,\nMarchamos no trilho do céu.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_313, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 1321, position: 2, content: "O nosso guia é o Senhor\nMarchamos no trilho do céu.\nNão temos nada que temer,\nMarchamos no trilho do céu.\nNo vasto campo de pecados\nTransgredindo nos achamos\nMas agora avante vamos;\nMarchamos no trilho do céu.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_313, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1322, position: 3, content: "O nosso protector é Cristo,\nMarchamos no trilho do céu.\nRenunciar, jamais faremos,\nMarchamos no trilho do céu,\nA tempestade tentadora,\nMesmo a nuvem pecadora,\n'Inda que nos atormentem;\nMarchamos no trilho do céu.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_313, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 1323, position: 4, content: "Irmão, também se junte a nós,\nVem e segue o trilho do céu.\nDeixe de vaguear no mundo,\nE siga o trilho do céu.\nNão percas esta salvação,\nVem, aceita o convite,\nNão duvides desta graça\nVem e segue o trilho do céu.", hymnsNumber: HymnsNumberSeeder.THANKSGIVING_TO_GOD_313, typeStanza: HymnsContentCode.VERSE)

  ];
}