import 'package:ieca_mobile/_import.dart';

class HymnsInvitationToTheSinner {
  static List<HymnsContent> list = [
    HymnsContent(id: 615, position: 1, content: "Se desejas paz, ventura,\nNesta vida, ó pecador,\nSe desejas céu e glória,\nCrê em Cristo, o Salvador.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_145, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 616, content: "Desde a cruz ensanguentada\nClama a voz do Redentor.\nVem! Aceita o Seu convite.\nCrê em Cristo, o Salvador.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_145, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 617, position: 2, content: "Não te serve de desculpa\nDe teus anos o verdor.\nSe quiseres a ventura\nCrê em Cristo, o Salvador.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_145, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 618, position: 3, content: "Que receios tem tua alma?\nTem da morte algum pavor?\nOh! Recorre a Deus piedoso,\nCrê em Cristo, o Salvador.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_145, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 619, position: 1, content: "Tão perto do reino, mas sem salvação!\nTão perto, porém sem Jesus, sem perdão!\nDeixai os pecados e o vosso temor!\nChegai-vos agora a Jesus, Salvador!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_146, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 620, content: "Oh! vinde a Jesus! Chegai-vos,\nChegai-vos ao bom Salvador!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_146, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 621, position: 2, content: "Tão perto que ouvis os remidos cantar\nDa graça de Cristo que os veio salvar!\nE ainda quereis no pecado viver,\nEnquanto o perdão Deus vos quer conceder?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_146, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 622, position: 3, content: "Morrer sem ser salvo, sem paz, sem Jesus,\nPerdidos p'ra sempre, em tormentos sem luz!\nOh! considerai! e ao convite atendei!\nE sem mais demora a Jesus rendei!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_146, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 623, position: 1, content: "Tal qual estou, eis-me, Senhor,\nPois o Teu sangue remidor\nVerteste pelo pecador;\nÓ Salvador, me achego a Ti!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_147, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 624, position: 2, content: "Tal qual estou, sem esperar\nQue possa a vida melhorar;\nNa Tua graça a confiar;\nÓ Salvador, me achego a Ti!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_147, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 625, position: 3, content: "Tal qual estou, e sem poder.\nAs faltas podes preencher,\nE tudo quanto me é mister.\nÓ Salvador, me achego a Ti!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_147, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 626, position: 4, content: "Tal qual estou, me aceitarás,\nE Tu minha alma limparás,\nCom teu amor me cobrirás,\nÓ Salvador, me achego a Ti!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_147, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 627, position: 1, content: "P'ra todo perdido nas trevas do mal.\nJesus é a luz do mundo!\nDo sol no esplendor não encontra rival:\nJesus é a luz do mundo.\nVem para a luz, pois brilha por ti;", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_148, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 628, content: "Dentro do peito, alegre a senti;\nVendo-a do mal a Deus eu corri;\nJesus é a luz do mundo!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_148, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 629, position: 2, content: "Do reino das trevas nós vimos Jesus;\nJesus é a luz do mundo!\nAndamos seguros na trilha da cruz;\nJesus é a luz do mundo!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_148, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 630, position: 3, content: "Ó cegos, que a terra do mal habitais,\nJesus é a luz do mundo!\nNa Bíblia se encontra esta luz que buscais;\nJesus é a luz do mundo!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_148, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 631, position: 4, content: "Do brilho do sol não carecem os céus;\nJesus é a luz do mundo!\nPois brilha o Cordeiro no Templo de Deus;\nJesus é a luz do mundo!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_148, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 632, position: 1, content: "Do país distante,\nOnde tu não tens\nPai, nem pão, nem casa\nVem, filho, vem!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_149, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 633, content: "Tu serás benvindo\nNo celeste lar;\nDeus o beijo de perdão\nTe espera dar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_149, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 634, position: 2, content: "Oh! se tal convite\nTratas com desdém,\nTriste a tua sorte!\nVem, Filho, vem!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_149, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 635, position: 3, content: "Eis a porta aberta,\nSabes para quem?\nPara os desviados,\nVem, filho, vem!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_149, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 636, position: 4, content: "Oh! contempla a mesa,\nQue fartura tem!\nTu estás faminto\nVem, filho, vem.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_149, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 637, position: 1, content: "Repeti-mas ainda outra vez,\nBelas palavras de vida.\nAcho nelas consolo e paz.\nBelas palavras de vida,\nElas vêm de cima.\nDão sustento e vida.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_150, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 638, content: "Que belas são!\nQue belas são\nEssas palavras de vida.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_150, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 639, position: 2, content: "Jesus Cristo a todos dá\nBelas palavras de vida.\nDá-lhe ouvidos, ó pecador,\nBelas palavras de vida.\nPor amor te salva.\nEle ao céu te chama.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_150, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 640, position: 3, content: "Jesus, único Salvador!\nBelas palavras de vida!\nJesus terno Consolador!\nBelas palavras de vida!\nEle é luz e vida\nPaz, conforto e guia.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_150, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 641, position: 1, content: "Do pecado resulta agonia;\nTambém dá a segunda morte;\nQuem é que pode salvar?\nSó Jesus a quem confiamos.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_151, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 642, position: 2, content: "Para os que em Jesus confiam,\nÀqueles que confiantes o seguem,\nEle pode dar-lhes amparo,\nJamais serão abandonados.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_151, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 643, position: 3, content: "Aqueles que tanto confiam\nNo juízo que Jesus lhes dá;\nReconhecem a Sua justiça,\nA qual sempre lhes dá conforto.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_151, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 644, position: 4, content: "Aqueles que n'Ele confiam,\nEstão seguros aqui na terra;\nEncontrarão também nos céus\nJesus, como o seu refúgio.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_151, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 645, position: 1, content: "Oh! que mensagem cheia\nDa compaixão de Deus,\nE do Evangelho santo\nQue nos conduz aos céus!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_152, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 646, content: "Eis a nova:\nQuem em Jesus confia,\nD'Ele há-de ter verdadeira luz,\nVida, perdão e alegria!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_152, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 647, position: 2, content: "Incomparável graça,\nCheia de santo amor,\nQue ao pecador perdido\nTrouxe o bom Salvador!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_152, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 648, position: 3, content: "Pois o pecado avilta,\nEnche de escuridão\nA alma rebelde e errada\nSob sua maldição!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_152, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 649, position: 4, content: "Temos na cruz de Cristo\nBênção e salvação;\nPorta da vida aberta,\nÚnica redenção!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_152, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 650, position: 1, content: "Queres tu obter a vida,\nVida eternal?\nCrê somente em Jesus Cristo,\nEle ha de te salvar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_153, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 651, content: "A vida eterna\nSe deseja obter,\nCrê somente em Jesus Cristo,\nEle há de te salvar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_153, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 652, position: 2, content: "Os pecados te desviam\nPara a perdição.\nJesus Cristo te procura\nPara te purificar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_153, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 653, position: 3, content: "Prestes à segunda morte.\nNão terás temor?\nCorre já p'ra o Salvador,\nOnde nunca morrerás.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_153, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 654, position: 4, content: "O Senhor Jesus amou-nos,\nFoi porque morreu,\nPara outorgar-nos vida,\nUma vida eternal.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_153, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 655, position: 1, content: "Deus está chamando.\nPorque não escutar?\nMinh'alegria onde posso achar?\nPode dormir o coração?\nNão procuro a vida?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_154, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 656, position: 2, content: "Deus está chamando.\nPorque não escutar?\nAmou-me, porque O desprezar?\nPorque não aceitar Sua voz?\nPorque não Sua graça receber?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_154, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 657, position: 3, content: "Deus está chamando.\nPorque demorar?\nQuando hesitante tudo hei de perder,\nAs coisas fúteis devo eu deixar.\nE regozijar-me com Sua voz.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_154, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 658, position: 1, content: "A terna voz do bom Jesus,\nCom grande amor nos chama,\nQuerendo dar conforto e luz,\nProvando que nos ama.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_155, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 659, content: "Homens jamais irão cantar,\nMesmo no céu de amor e luz,\nCom tanto ardor mais doce som\nQue o nome de Jesus.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_155, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 660, position: 2, content: "Do cálice de amarga dor\nNão tem Jesus poupado,\nA fim de dar, por seu amor,\nPerdão do vil pecado.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_155, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 661, position: 3, content: "Oh, graças pois, ao nosso Deus\nPor este amor supremo;\nTambém nos Céus, os santos Seus\nDarão louvor eterno.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_155, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 662, position: 1, content: "Tens achado em Cristo\nPlena, salvação,\nPelo sangue vertido na cruz?\nToda mancha lava\nDe teu coração,\nEste sangue eficaz de Jesus.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_156, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 663, content: "Salvo estás, limpo estás,\nPelo sangue de Cristo Jesus?\nTens teu coração mais alvo que a luz,\nFostes limpo no sangue eficaz?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_156, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 664, position: 2, content: "Vives sempre ao lado\nDo teu Salvador,\nPelo sangue que mana da cruz?\nDo pecado foste\nSempre vencedor,\nComo foi teu bendito Jesus?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_156, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 665, position: 3, content: "Terás roupa branca\nQuando vier Jesus?\nFoste limpo na fonte do amor?\nEstás pronto p'ra\nSeguir ao Céu de luz\nPelo sangue purificador?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_156, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 666, position: 4, content: "Cristo hoje dá pureza\nE mui poder.\nFita os olhos na cruz do Senhor.\nDela fonte sai que\nTe enche de prazer,\nQue te farta de vida e vigor.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_156, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 667, position: 1, content: "Ouvi a doce voz\nDe Cristo, o Redentor,\nQue chama para a salvação,\nO pobre pecador.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_157, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 668, content: "Venho meu Senhor!\nVenho, como estou!\nBem nenhum existe em mim,\nTua voz me convidou.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_157, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 669, position: 2, content: "Outrora andei sem fé,\nIndigno e sem saber;\nPorém agora, meu Senhor,\nEu vivo em teu poder.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_157, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 670, position: 3, content: "A Deus eu louvarei,\nPor esta redenção!\nPois tenho Cristo, o Salvador,\nEu tenho a salvação.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_157, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 671, position: 1, content: "A Jesus Cristo contarei tudo\nQue haja em meu peito a me perturbar;\nOs meus cuidados, meus sofrimentos,\nSó Ele os pode suavizar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_158, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 672, content: "A Jesus Cristo, meu Bem-Amado,\nNarrarei sempre minha aflição;\nAos meus cuidados, aos meus tormentos,\nSó Ele pode dar solução.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_158, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 673, position: 2, content: "A Jesus Cristo contarei tudo:\nEle é Amigo firme e leal.\nBasta pedir-Lhe, que, sem demora,\nAos meus pesares dá fim cabal.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_158, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 674, position: 3, content: "Sempre tentado, sei que preciso\nDe um protector que possa valer;\nSó meu Amado, que é invencível,\nPode, portanto, me proteger.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_158, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 675, position: 4, content: "Deste caminho os maus me desejam,\nPois, desviar e me demover;\nMas Jesus Cristo, forte e zeloso,\nSempre me ajuda a permanecer.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_158, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 676, position: 1, content: "Vamos cantar desse amor eternal,\nVindo de Deus, vindo de Deus;\nFonte de bênção e paz divinal\nHá nas alturas dos céus.\nGraça e amor, graça e amor,\nVêm-nos por nosso bendito Senhor!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_159, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 677, position: 2, content: "Cristo Jesus, para os homens salvar,\nVeio dos céus, veio dos céus,\nCheio de graça, querendo mostrar\nSeu grande amor pelos réus.\nLá sobre a cruz, lá sobre a cruz,\nVê-se brilhando o amor de Jesus!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_159, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 678, position: 3, content: "Cristo exaltado na glória está,\nNos altos céus, nos altos céus,\nIntercedendo por nós sempre lá,\nSim, na presença de Deus.\nQue grande amor, que grande amor,\nVem-nos do Teu coração, ó Senhor!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_159, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 679, position: 1, content: "Ouço o Salvador chamando,\nCom ternura convidando,\nSua voz solicitando:\nVem e segue, sempre segue-Me.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_160, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 680, content: "Minha cruz eu tomo e sigo;\nA Jesus eu sempre sigo,\nAonde me levar eu sigo.\nMeu Jesus, eu sempre seguirei.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_160, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 681, position: 2, content: "Se o caminho for custoso,\nE o trabalho mui penoso,\nInda assim fico animoso.\nQuando sigo, sigo a meu Jesus.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_160, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 682, position: 3, content: "Pelo vale Cristo guia;\nSempre, sempre, me auxilia;\nMinhas dores alivia,\nQuando sigo, sigo a meu Jesus.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_160, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 683, position: 1, content: "Leva tu contigo o nome\nDe Jesus, o Salvador;\nEste nome dá consolo,\nSeja no lugar que for.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_161, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 684, content: "Nome bom, doce à fé,\nA esperança do porvir. (2x)", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_161, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 685, position: 2, content: "Este nome leva sempre,\nPara bem te defender;\nEle é arma ao teu alcance,\nQuando o mal te aparecer.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_161, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 686, position: 3, content: "Oh! que nome tão precioso!\nGozo traz ao coração;\nSendo por Jesus aceite,\nTu terás o seu perdão.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_161, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 687, position: 4, content: "Nome santo e venerável\nÉ Jesus, o amado teu;\nRei dos reis, Senhor eterno,\nTu O aclamarás no Céu.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_161, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 688, position: 1, content: "Quem ouvir as novas,\nVá proclamar:\nSalvação de graça\nVinde desfrutar!\nOh! que o mundo inteiro\nOuça anunciar:\nTodo que quiser, é vir!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_162, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 689, content: "Todo que quiser, venha receber!\nPossam todos essa boa nova ouvir!\nÉ o Pai celeste que convida assim:\nTodo que quiser, é vir!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_162, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 690, position: 2, content: "Quem quiser agora,\nVenha aceitar;\nEis a porta aberta,\nJá podeis entrar;\nÉ Jesus caminho\nPara ao Céu chegar;\nTodo que quiser, é vir!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_162, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 691, position: 3, content: "Que fiel promessa tens, pecador!\nQueres tu a vida?\nVem ao Salvador!\nEle a todos fala\nCom mui terno amor:\nTodo que quiser, é vir!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_162, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 692, position: 1, content: "Franqueada a porta a nós está\nDa perenal morada.\nE Cristo nos concederá\nA triunfal entrada.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_163, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 693, content: "Oh! Quanto amor Jesus sentiu!\nPois Ele a porta já me abriu\nA mim, a mim;\nA porta já me abriu.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_163, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 694, position: 2, content: "Se queres, pecador, entrar,\nA porta está aberta!\nAlí no Céu terá lugar\nQue Cristo a ti oferta.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_163, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 695, position: 3, content: "Oh! vinde pecadores, já,\nSim, vinde sem demora!\nO tempo próprio passará,\nOh! vinde entrar agora!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_163, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 696, position: 1, content: "Não te demores, amigo!\nPor que te delongas assim?\nJesus está pronto a salvar-te:\nNão ouves o seu «Vinde a mim»?", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_164, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 697, content: "Vem já, vem já,\nVem, perdido, a Jesus!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_164, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 698, position: 2, content: "Que lucrarás, meu amigo,\nDeixando isto para amanhã?\nAs coisas do mundo perecem;\nSem Cristo terás vida vã.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_164, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 699, position: 3, content: "Não te demores, amigo!\nO dia da morte já vem!\nDepois que deixares o mundo\nTerás de prestar conta além.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_164, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 700, position: 4, content: "Ó meu amigo, decide:\nVem logo a Jesus aceitar!\nDespreza teus muitos pecados;\nJesus dá-te graça sem-par.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_164, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 701, position: 1, content: "Oiça a chamada\nDo teu Salvador;\nAceita o Amor\nQue está a te chamar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_165, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 702, position: 2, content: "O Seu terno amor\nQue de tudo dá,\nQue te alivia sempre,\nToda a tua carga.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_165, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 703, position: 3, content: "Quando preocupado\nEle te consola;\nTambém te oferece\nGrande alegria.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_165, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 704, position: 4, content: "Jesus tudo limpa.\nTodos os teus caminhos\nEle também guarda,\nSempre e todos os dias.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_165, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 705, position: 5, content: "Oh! não desperdices!\nAceita O compassivo;\nEle esta esperando,\nCom Seu imenso amor.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_165, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 706, position: 1, content: "Cristo salva o pecador,\nLava o negro coração;\nAo contrito, com amor,\nOferece salvação.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_166, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 707, content: "Confiai em seu poder;\nConfiai em seu amor;\nCrede, pois, que Cristo quer\nLibertar o pecador.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_166, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 708, position: 2, content: "Cristo salva o pecador\nE concede-lhe perdão.\nAceitai o bom Senhor;\nAceitai de coração.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_166, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 709, position: 3, content: "Vinde todos, e achareis\nPaz e luz no Redentor;\nVinde, e então recebereis\nVida eterna do Senhor.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_166, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 710, position: 1, content: "Cristo, meu Salvador, veio a Belém,\nPara sofrer zombaria e desdém;\nVeio por causa do amor que me tem,\nA procurar-me a mim!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_167, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 711, position: 2, content: "Cristo, meu Salvador, morto na cruz,\nDeu-me a alegria do reino de luz,\nE no caminho do Céu me conduz;\nTudo Ele faz por mim!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_167, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 712, position: 3, content: "Cristo, meu Salvador, chama por ti,\nEle te diz: «Com amor te remi».\nVem, pois Jesus já fez tanto por ti:\nNão te demores mais!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_167, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 713, position: 4, content: "Cristo, meu Salvador, inda virá\nCom os remidos; que glória será!\nEu face a face verei a Jeová,\nQuando me vier buscar!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_167, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 714, position: 1, content: "Alma, que aflita estás,\nDeus, Pai bondoso,\nEm compaixão e amor,\nTem o poder\nDe te livrar do mal e dar-te gozo,\nE sem demora\nEm Jesus te esconder.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_168, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 715, position: 2, content: "Ó meu irmão, se tens\nGrandes tormentos,\nLembra-te, então, de Deus,\nTeu Protector;\nEle te livrará desses lamentos;\nSó Ele pode sarar tua dor.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_168, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 716, position: 3, content: "Se pesaroso estás em tua vida,\nBusca o teu Salvador\nCristo Jesus,\nEle com muito amor\nJá te convida,\nCristo te ajuda a levar tua cruz.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_168, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 717, position: 4, content: "Oh! Que consolação\nTemos em Cristo,\nPois da tristeza Deus nos livrará!\nSempre sustenta os seus;\nSomos benquistos,\nEle nos ama e nos protegerá.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_168, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 718, position: 1, content: "Quase achegado ao bom\nSalvador?\nChega mais perto, sim pecador!\nNão penses em dizer:\n«Hoje, não pode ser;\nVou amanhã fazer a decisão»", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_169, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 719, position: 2, content: "Se resolveste a Cristo seguir\nHoje é o tempo de decidir\nOuve essa voz de amor\nQue diz, ó pecador\n«Tempo não há melhor\nP'ra salvação.»", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_169, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 720, position: 3, content: "«Quase», não basta; faz perigar\nTua esperança de ao Céu chegar.\n«Quase» não valerá,\nNunca te salvará,\nMas, sim, te levará à perdição.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_169, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 721, position: 1, content: "Escuta a voz do bom Jesus:\n«Segue-Me, vem segue-Me.\nGuiar-te-ei à eterna luz;\nSegue-Me, vem, segue-Me.\nPor ti Eu toda a lei cumpri;\nPor ti o amargo fel bebi;\nPor ti a morte já sofri;\nSegue-Me, vem segue-Me».", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_170, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 722, position: 2, content: "«Liberto dos pecados teus,\nSegue-Me, vem, segue-Me.\nGuiar-te-ei aos altos céus;\nSegue-Me, vem, segue-Me.\nOh! Quantas vezes te chamei,\nE tu quebraste a minha lei;\nMas fiador teu Eu fiquei;\nSegue-Me, vem, segue-Me».", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_170, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 723, position: 3, content: "«Em Mim tu podes descansar;\nSegue-Me, vem, segue-Me.\nVem teus cuidados Me entregar;\nSegue-Me, vem, segue-Me.\nEu sou teu Deus, teu Salvador;\nEu te amo muito, ó pecador;\nOh! Deixa todo o teu temor;\nSegue-Me, vem, segue-Me».", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_170, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 724, position: 4, content: "«Sim, meu Jesus, Te seguirei;\nSeguirei, sim, seguirei;\nPor Ti eu tudo deixarei;\nDeixarei, sim, deixarei.\nMui débil sou, e sem valor;\nSem Ti não posso andar, Senhor;\nMas enche-me do teu vigor!\nSeguirei, sim, seguirei».", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_170, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 725, position: 1, content: "Manso e suave\nJesus, convidando,\nChama por ti e por mim.\nEis que Ele à porta\nTe espera velando:\nVela por ti e por mim.\n«Vem já, vem já!\nAlma cansada, vem já»!\nManso e suave Jesus, convidando,\nChama: «Ó pecador, vem»!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_171, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 726, position: 2, content: "Pois que esperamos?\nJesus convidando,\nConvida a ti, sim, e a mim.\nOh! Não desprezes\nMercê que está dando,\nSim, dando a ti, dando a mim.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_171, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 727, position: 3, content: "Correm os dias,\nAs horas se passam,\nPassam por ti e por mim;\nTranses de morte\nPor fim nos esperam,\nVêm tanto a ti quanto a mim.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_171, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 728, position: 4, content: "Oh! Grande amor\nQue Jesus nos tem dado,\nTem dado a ti, dado a mim!\nVeio salvar-nos\nDo tão vil pecado,\nVeio por ti e por mim.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_171, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 729, position: 1, content: "Quão admirável é a história\nDo Cordeiro do Bom Deus.\nPronto deixou a Sua glória\nPara resgatar os Seus.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_172, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 730, content: "Quem nos salvou da perdição?\n- Jesus que trouxe a salvação.\nComo sofreu?\n- Por nós morreu.\nOnde Ele está?\n— Está junto a Deus.\nPor nós intercedendo.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_172, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 731, position: 2, content: "Anjo nenhum jamais tentou,\nMesmo ali na eterna luz.\nO que Jesus assim mostrou,\nPela morte aqui na cruz.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_172, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 732, position: 3, content: "Estás pronto a crer no Salvador?\nA tua alma Lhe entregar?\nPode, também fruir o amor,\nPois Jesus te quer salvar!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_172, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 733, position: 1, content: "Jesus misericordioso,\nPerdoou-me tudo sim;\nEu perdido me achou,\nQuando Ele por mim morreu.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_173, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 734, position: 2, content: "Ante meu coração duro,\nNem sua voz eu acatei;\nEle elucidou-me bem,\nNão mais hesitei, sim, não.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_173, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 735, position: 3, content: "Antes duvidoso andei,\nNunca me prontifiquei;\nA seguir meu Salvador\nHoje não duvido, não.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_173, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 736, position: 4, content: "Ante a morte duvidei;\nEncorajou-me o coração;\nDa tua morte no calvário\nJamais duvidoso serei.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_173, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 737, position: 5, content: "Seu amor me comoveu,\nNão tem outro similar,\nSantificarei Teu nome,\nMil compensações terei.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_173, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 738, position: 1, content: "O chorar não salva!\nMesmo o prantear sem fim\nJamais mancha carmesim\nPoderá lavar-me a mim;\nO chorar não salva!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_174, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 739, content: "Foi Jesus que padeceu;\nSobre a cruz por mim morreu;\nPor seu sangue que verteu\nPôde assim salvar-me!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_174, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 740, position: 2, content: "Obras não me salvam!\nMeus esforços sem cessar\nNão me podem transformar\nNem meus males expiar,\nObras não me salvam!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_174, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 741, position: 3, content: "Orações não salvam!\nApesar do seu fervor,\nPetições não têm valor\nP’ra salvar o pecador;\nOrações não salvam!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_174, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 742, position: 4, content: "É Jesus quem salva!\nEle a obra consumou\nMeus pecados expiou,\nCom seu sangue me lavou;\nÉ Jesus quem salva.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_174, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 743, position: 1, content: "A mensagem do Senhor; aleluia!\nÉ cheia de perdão e amor!\nCristo salva o pecador; aleluia!\nSalva até por meio de um olhar!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_175, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 744, content: "Oh! Olhai, pois, e vivei!\nConfiai só em Jesus!\nEle salva o pecador! Aleluia!\nSalva-O até por meio de um olhar!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_175, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 745, position: 2, content: "Vossa culpa já levou; aleluia!\nJesus a satisfez na cruz;\nSua vida já entregou, aleluia!\nPara vos apresentar a Deus.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_175, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 746, position: 3, content: "Sua graça nos legou; aleluia!\nEterna vida lá nos céus;\nConfiai só em Jesus, aleluia!\nConvertei-vos hoje mesmo a Deus!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_175, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 747, position: 4, content: "Aceitai a salvação; aleluia!\nSegui os passos do Senhor;\nProclamai o seu perdão; aleluia!\nExaltai o grande Redentor!", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_175, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 748, position: 1, content: "Quero o Salvador comigo;\nSó com Ele eu posso andar;\nQuero conhecê-Lo perto,\nNo seu braço descansar.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_176, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 749, content: "Confiado no Senhor,\nConsolado em seu amor,\nSeguirei no meu caminho,\nSem tristeza e sem temor.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_176, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 750, position: 2, content: "Quero o Salvador comigo,\nPois tão fraca é minha fé;\nSua voz me dá conforto,\nQuando me vacila o pé.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_176, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 751, position: 3, content: "Quero o Salvador comigo,\nDia a dia em meu viver,\nNa tristeza, no trabalho,\nNo conflito e no prazer.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_176, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 752, position: 4, content: "Quero o Salvador comigo,\nSábio Guia e bom Pastor,\n' Te passar além da morte,\nLonge do perigo e dor.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_176, typeStanza: HymnsContentCode.VERSE),

    HymnsContent(id: 753, position: 1, content: "Companheiros, convidados,\nA dedicarmo-nos a sério\nA Cristo nosso Rei,\nDecidamos, firmes, hoje.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_177, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 754, content: "Decidamos, firmes, hoje, (2x)\nCom persistência e fé,\nDecidamos, firmes, hoje.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_177, typeStanza: HymnsContentCode.CHOIR),
    HymnsContent(id: 755, position: 2, content: "Companheiros, convidados,\nA transportar a cruz!\nCom fé a levantemos,\nDecidamos, firmes, hoje.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_177, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 756, position: 3, content: "Companheiros, convidados,\nA sermos testemunhas\nDa lei da liberdade,\nDecidamos, firmes, hoje.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_177, typeStanza: HymnsContentCode.VERSE),
    HymnsContent(id: 757, position: 4, content: "Companheiros, convidados,\nÀ alegria, sendo salvos!\nQue cesse toda a dor.\nDecidamos, firmes, hoje.", hymnsNumber: HymnsNumberSeeder.INVITATION_TO_THE_SINNER_177, typeStanza: HymnsContentCode.VERSE),

  ];
}